<?php 	$orders = $this->orders;?>
<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo I18N::T('food', '订餐统计记录报表'); ?></title>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	table .time {
		font-size: 16px;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>

	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('food', '打印'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('food', '订餐统计记录报表'); ?></caption>
	<thead id="stat">
		<tr>
			<td colspan="8" class="time">
			<?php echo I18N::T('food', '预订时间:'); ?>
			&nbsp;
			<?php
				if ($form['dtstart_check'] && $form['dtend_check']) {
					if ($form['dtstart'] == $form['dtend']) {
						$time = H(date('Y/m/d', $form['dtstart']));
					}
					else {
						$time = H(date('Y/m/d', $form['dtstart'])).'~'.H(date('Y/m/d', $form['dtend']));
					}
				}
				elseif ($form['dtstart_check']) {
					
					$time = H(date('Y/m/d', $form['dtstart']));
				}
				elseif ($form['dtend_check']) {
					$time = H(date('Y/m/d', $form['dtend']));
				}
				else {
					$time = I18N::T('food', '全部');
				}
				echo $time; 
			?>
			</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<th class="left nowrap"><?php echo I18N::T('food', '预订人员'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('food', '菜式名称'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('food', '菜式价格'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('food', '订单备注'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($orders as $order): ; ?>
				<?php if ($supplier != $order->supplier) :
					$supplier = $order->supplier;
					$temp_orders = $orders->filter("[supplier=$supplier]");
				?>
					<tr>
						<td colspan="8" class="left nowrap" >
							<b><?php echo $order->supplier ? : V('order_table/data/supplier', ['order'=>$order]);?></b>
							<?php echo I18N::T('food', $temp_orders->length().'份');?>
							<?php echo V('order_table/data/count', ['orders'=>$temp_orders]); ?>
						</td>
					</tr>
				<?php endif; ?>
				<tr>
					<td class="left nowrap"><?php echo H($order->user->name); ?></td>
					<td class="left nowrap"><?php echo V('order_table/data/foods', ['order'=>$order]); ?></td>
					<td class="left nowrap">
						<?php 
							echo I18N::T('food', Number::currency($order->price));
						?>
					</td>
					<td class="left nowrap"><?php echo H($order->remarks); ?></td>
				</tr>
		<?php endforeach; ?>
		<tr>
			<td colspan="8" class="right nowrap" >
				<?php echo I18N::T('food', '共计：%length份', ['%length'=>$orders->length()]);?>
				<?php echo V('order_table/data/count', ['orders'=>$orders]); ?>
			</td>
		</tr>
	</tbody>
	</table>
</body>
</html>
