<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo I18N::T('food', '订餐统计记录汇总报表'); ?></title>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	table .time {
		font-size: 16px;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>

	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('food', '打印'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('food', '订餐统计记录汇总报表'); ?></caption>
	<thead id="stat">
		<tr>
			<td colspan="8" class="time">
			</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<th class="left nowrap"><?php echo I18N::T('food', '订餐年费及月份'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('food', '菜式份数总和（份）'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('food', '菜式价格（元）'); ?></th>
		</tr>
	</thead>
	<tbody>
			<?php
				//初始化时间为第一条记录
				$time = $start_time;
			
				$count_length = 0;
				$count_price = 0;
				while($time <= $end_time) {
					//获取记录当月的第一秒
					$first_second = mktime('0', '0', '0', date('m', $time), '1', date('Y', $time));
				
					//获取记录当月的最后一秒
					
					$last_second = mktime('0', '0', '0', date('m', $time) + 1, '1', date('Y', $time)) - 1;
					
					$selector = 'fd_order';
					$selector .= "[ctime>$first_second][ctime<$last_second]";
					//设置时间为下月的第一秒
					$time = $last_second + 1;
					
					$price = Q($selector)->SUM('price');
					$length = count(Q($selector));
					$count_length += $length;
					$count_price += $price; 
			?>
				<tr>
					<td class="left nowrap"><?php echo H(date('Y-m', $first_second));?></td>
					<td class="left nowrap"><?php echo I18N::T('food', $length);?></td>
					<td class="left nowrap"><?php echo H($price);?></td>
				</tr>	
			<?php
				}
			?>
				<tr>
					<td class="right nowrap" colspan="3">
						<?php 
							echo I18N::T('food', '合计 %length 份， %price 元', ['%length'=>$count_length,'%price'=>$count_price]);
						?>
					</td>
				</tr>
	</tbody>
	</table>
</body>
</html>
