<?php $unique_billing_department = $GLOBALS['preload']['billing.single_department'];?>
<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('billing', '实验室明细统计报表'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {

		font-size: 14px;
		margin:auto;
	}
	table .time {
		font-size: 16px;
	}

	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}

	tbody{
		border-bottom:2px solid #000;
	}

	thead#stat{
		font-size: 10px;
		border:none;
	}

	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>

  <div class="buttons">
	<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('billing', '打印'); ?></a>
    <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('billing', '关闭'); ?></a>
  </div>
  <table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('billing', '实验室财务明细统计报表'); ?></caption>
	<thead id="stat">
	  <tr>
		<td colspan="7" class="time">
			<?php
				$dtstart = $form['dtstart_check'] ? Date::format($form['dtstart'], T('Y/m/d')) : I18N::T('billing','最初');
				$dtend = $form['dtend_check'] ? Date::format($form['dtend'], T('Y/m/d')) : I18N::T('billing','最末');
				echo $dtstart . ' - ' . $dtend;
			?>
		</td>
	  </tr>
	</thead>
	<thead>
	  <tr>
	  	<?php foreach($properties_can_print as $key=>$value) :?>	
		<td class="left nowrap"><?php echo $value; ?></td>
		<?php endforeach; ?>
	  </tr>
	</thead>
	<tbody>
	  <?php
	  	$me = L('ME');
	  	foreach($transactions as $transaction): ; ?>
	  <?php if ($me->is_allowed_to('查看', $transaction)) : ?>
	  <?php
	  	$data = [];
	  	foreach ($properties_can_print as $key => $value) {
	  		switch ($key) {
			case 'ref_no':
  				$data[] = Number::fill($transaction->id, 6);
  				break;
  			case 'date':
  				$data[] = Date::format($transaction->ctime);
  				break;
  			case 'department':
  				$data[] = H($transaction->account->department->name);
  				break;
  			case 'income':
  				$data[] = $transaction->income ? Number::currency($transaction->income) : '' ;
  				break;
  			case 'outcome':
  				$data[] = $transaction->outcome ? Number::currency($transaction->outcome) : '';
  				break;
  			case 'description':
  				$data[] = preg_replace('/\<[\/]?a[^\>]*\>/', '', $transaction->description());
  				break;
  			case 'certificate':
  				$data[] = H($transaction->certificate);
  				break;		
	  		}
	  	}
	  ?>
	  <tr>
		<?php foreach ($data as $key => $value) : ?>
			<td class="left nowrap"><?php echo $value?></td>
		<?php endforeach; ?>
	  </tr>
	<?php endif; ?>
	  <?php endforeach; ?>
	</tbody>
  </table>
</body>
</html>
