<div class="interval_20"></div>
<table class="form">
<tr>
	<td class="left nowrap middle" width="126"><?php echo I18N::T('application','有效时间') ?></td>
	<td class="left nowrap middle">
		<input name="dtfrom[<?php echo $flexform_index ?>]" class="text date" date_type="date" value="<?php echo H($dtfrom ) ?>" />
		-
		<input name="dtto[<?php echo $flexform_index ?>]" class="text date" date_type="date" value="<?php echo H($dtto) ?>" />
	</td>
</tr>
</table>
