<div class="form">
    <form action="<?php echo H(URI::url('!eq_evaluate/export', ['type'=>$type, 'form_token'=>$form_token])) ?>" target="<?= $type == 'csv' ? '_self' : '_blank';?>" class="prevent_default" method="post">
        <ul class="ep_triple">
            <?php
            foreach ($columns as $p => $p_name) :?>
            <?php if ($p < 0): ?>
            <div class="clear">&#160;</div>
            <h4><?php echo I18N::HT('equipments', $p_name) ?></h4>
            <?php  else:?>
                <li class="nowrap">
                    <?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('equipments', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>
                </li>
            <?php endif; ?>
            <?php endforeach;?>
        </ul>

        <div class="button_container">
		<div class="float_right">
		<input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('equipments', '取消');?>" />
		<input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('equipments', '提交');?>" />
		</div>
        <span class="lpadding_2 red"><?php echo $description?></span>
    </form>
</div>