<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></title>
    <base href="<?php echo H(Config::get('system.base_url') ) ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
    <style>
    a {
        color:blue;
        text-decoration:underline;
    }
    table.report {
        
        font-size: 14px;
        margin:auto;
    }
    
    thead{
        border-top:2px solid  #000;
        border-bottom:1px solid #000;
    }
    
    tbody{
        border-bottom:2px solid #000;
    }
    
    thead#stat{
        font-size: 10px;
        border:none;
    }
    
    table.report caption {
        font-size: 150%;
        margin-bottom: 10px;
    }

    table.report tbody td {
        vertical-align: top;
        border-bottom: 1px dotted #CCC;
    }
    table.report .referred_charge {
        background-color: #eee;
        border:1px dotted #CCC;
    }
    p {
        margin: 0;
    }
    .quote {
        margin-left: 1em;
    }
    </style>
    <style media="print">
    .buttons{
        display:none;
    }
    </style>
</head>

<body>
    <div class="buttons">
        <a href="#" onclick="window.print(); return false;"><?php echo I18N::T('equipments', '打印'); ?></a>
        <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('equipments', '关闭|:print'); ?></a>
    </div>
    <?php 
    $form['@columns'] = $valid_columns;
    $form['selector'] = $selector;
    $_SESSION[$form_token] = $form;

    $print_limit = Config::get('eq_evaluate.print_max', 500);
    if ($evaluates->total_count() >= $print_limit) :

    $csv_link = I18N::T('equipments', '导出Excel');
    
    $return_url = I18N::T('equipments', '搜索条件');
    ?>
    <div class="center">
        <strong>
            <?php echo I18N::T('equipments',
                '您选择数据超过%print_limit条, 不适合打印, 请选择%csv_link或调整您的%return_url', [
                '%print_limit' => $print_limit,
                '%csv_link' => $csv_link,
                '%return_url' => $return_url,
            ]); ?> 
        </strong>
    </div>
    <?php else : ?>
    <table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
    <caption><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></caption>
    <thead id="stat">
        <tr>
        <td colspan="8">
        <?php echo I18N::T('equipments', '时间范围:'); ?>
        &#160;
        <?php
            $dtstart = isset($form['dtstart_check']) ? H(date('Y/m/d',$form['dtstart'])) : I18N::T('equipments','最初');
            $dtend = isset($form['dtend_check']) ? H(date('Y/m/d',$form['dtend'])) : I18N::T('equipments','最末');
            echo $dtstart . ' - ' . $dtend;
        ?>
        </td>
        </tr>
    </thead>
    <thead>
        <tr>
            <?php foreach ($valid_columns as $key => $value) :?>
                <th class="left nowrap"><?php echo I18N::T('equipments',$value); ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $sum_dtstart = 0;
        $sum_dtend = 0;
        foreach($evaluates as $evaluate): ?>
        <tr>
        <?php if(array_key_exists('equipment', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($evaluate->equipment->name); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_ref_no', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($evaluate->equipment->ref_no); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_cf_id', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($evaluate->equipment->id); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_group', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($evaluate->equipment->group->name); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('user', $valid_columns)): ?>
        <td class="left nowrap"><?php echo H($evaluate->user->name); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('lab', $valid_columns)): ?>
        <?php $labs = Q("{$evaluate->user} lab")->to_assoc('id', 'name'); ?>
        <td class="left nowrap"><?php echo H(join(',', $labs)); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('user_group', $valid_columns)): ?>
        <td class="left nowrap"><?php echo H($evaluate->user->group->name); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('evaluate_ref_no', $valid_columns)): ?>
        <td class="left nowrap"><?php echo Number::fill(H($evaluate->id), 6); ?></td>
        <?php endif;?>
        <?php if(array_key_exists('score', $valid_columns)): ?>
        <td class="left nowrap"><?php echo Config::get('eq_evaluate')['rate.tip'][$evaluate->score - 1];?></td>
        <?php endif; ?>
        <?php if(array_key_exists('content', $valid_columns)): ?>
        <td class="left nowrap"><?php echo $evaluate->content;?></td>
        <?php endif; ?>
        <?php if (array_key_exists('duty_teacher', $valid_columns)) : ?>
            <?php $record = O('eq_record', ['evaluate' => $evaluate]); ?>
            <td class="left nowrap"><?php echo H($record->duty_teacher->id ? $record->duty_teacher->name : '--'); ?></td>
        <?php endif; ?>
        <?php echo Event::trigger('extra.print.columns', $valid_columns, $evaluate); ?>
        </tr>
        <?php endforeach; ?>
        <tr>
        <td colspan="<?php echo H(count($valid_columns)) ?>" class="right nowrap">
            <?php echo I18N::T('equipments', '总计评价: %count 次', ['%count'=>$records->total_count()]); ?>
        </td>
        </tr>
    </tbody>
    </table>
    <?php endif; ?>
</body>
</html>
