<div class="short_container">
    <div class="img_icon" style="position: relative;">
        <?php echo $user->icon('104', 'class="icon_none_border"');?>
        <div class="icon_cover" style="display: none;">
            <div class="modify_icon">+</div>
            <div class="interval_12"></div>
            <div class="modify_font">修改图标</div>
        </div>
    </div>
    <input class="upload_icon" name="file" type="file" class="file" style="display: none;" />
    <div class="interval_24"></div>
    <?php
    $items = Event::trigger('people.info.short.picture', $user) ?: [];
    if (count($items)):
        ?>
        <div class="short_info">
            <?php foreach ($items as $key => $item){
                echo $item;
            }?>
        </div>
    <?php endif; ?>
</div>

<script>
    $.upload_icon(<?php echo '"'.URI::url().'"'; ?>);
</script>
