<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title><?php echo I18N::T('credit', '成员信用列表'); ?></title>
    <base href="<?php echo H(Config::get('system.base_url') ) ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
    <style>
    a {
        color:blue;
        text-decoration:underline;
    }
    table.report {

        font-size: 14px;
        margin:auto;
    }

    thead{
        border-top:2px solid  #000;
        border-bottom:1px solid #000;
    }

    tbody{
        border-bottom:2px solid #000;
    }

    thead#stat{
        font-size: 10px;
        border:none;
    }

    table.report caption {
        font-size: 150%;
        margin-bottom: 10px;
    }

    table.report tbody td {
        vertical-align: top;
        border-bottom: 1px dotted #CCC;
    }
    table.report .referred_charge {
        background-color: #eee;
        border:1px dotted #CCC;
    }
    p {
        margin: 0;
    }
    .quote {
        margin-left: 1em;
    }
    </style>
    <style media="print">
    .buttons{
        display:none;
    }
    </style>
</head>

<body>
    <div class="buttons">
        <a href="#" onclick="window.print(); return false;"><?php echo I18N::T('equipments', '打印'); ?></a>
        <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('equipments', '关闭|:print'); ?></a>
    </div>
    <?php
    $form['@columns'] = $valid_columns;
    $form['selector'] = $selector;

    $_SESSION[$form_token] = $form;

    $print_limit = 500;
    if ($credits->total_count() >= $print_limit) :

    $csv_link = I18N::T('equipments', '导出Excel');

    $return_url = I18N::T('equipments', '搜索条件');
    ?>
    <div class="center">
        <strong>
            <?php echo I18N::T( 'equipments', '您选择数据超过%print_limit条, 不适合打印, 请选择%csv_link或调整您的%return_url',
            ['%print_limit' => $print_limit,
                '%csv_link' => $csv_link,
                '%return_url' => $return_url,
             ] ); ?>
        </strong>
    </div>
    <?php else : ?>
    <table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
    <caption><?php echo I18N::T('equipments', '成员信用列表'); ?></caption>
    <thead>
        <tr>
            <?php foreach ($valid_columns as $key => $value) :?>
                <th class="left nowrap"><?php echo I18N::T('credit',$value); ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($credits as $credit): ?>
        <tr>
            <?php if(array_key_exists('name', $valid_columns)) : ?>
                <td class="left nowrap"><?php echo H($credit->user->name); ?></td>
            <?php endif; ?>
            <?php if(array_key_exists('lab', $valid_columns)) : ?>
                <?php $lab = Q("{$credit->user} lab")->current() ?>
                <td class="left nowrap"><?php echo H($lab->id ? $lab->name : ''); ?></td>
            <?php endif; ?>
            <?php if(array_key_exists('group', $valid_columns)) : ?>
                <td class="left nowrap"><?php echo H($credit->user->group_id ? $credit->user->group->name : ''); ?></td>
            <?php endif; ?>
            <?php if(array_key_exists('level', $valid_columns)) : ?>
                <td class="left nowrap"><?php echo H(str_repeat('A', $credit->credit_level->level)); ?></td>
            <?php endif; ?>
            <?php if(array_key_exists('credit_score', $valid_columns)) : ?>
                <td class="left nowrap"><?php echo H($credit->total); ?></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
    <?php endif; ?>
</body>
</html>
