<div class="form padding_2">
    <?php if ($type == 'csv'): ?>
        <form method="POST" q-object="credit_records_export" q-src="<?= URI::url('!credit/export/credit_records') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" q-event="submit" autocomplete="off" class="prevent_default">
    <?php else: ?>
    <form action="<?php echo H(URI::url('!credit/export/credit_records', ['type'=>$type, 'form_token'=>$form_token])) ?>" target="<?= $type == 'csv' ? '_self' : '_blank';?>" class="prevent_default" method="post">
    <?php endif; ?>
        <ul class="ep_triple triple">
            <?php
            foreach ($columns as $p => $p_name) :?>
            <?php if ($p < 0): ?>
            <div class="clear">&#160;</div>
            <h4><?php echo I18N::HT('credit', $p_name) ?></h4>
            <?php  else:?>
                <li class="nowrap">
                    <?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('credit', $p_name), 'class="middle checkbox"', 'class="middle"');?>
                </li>
            <?php endif; ?>
            <?php endforeach;?>
        </ul>
        <div class="hr_2"></div>
        <input type="submit" name="submit" class="font-button-save float_right middle" value="<?php echo H(I18N::T('credit', '提交')) ?>" />
        <span class="lpadding_2 red"><?php echo $description?></span>
    </form>
</div>
