<?php
echo CSS::load_async('orders:order');
$me = L('ME');
$no_error = (!is_object($form) || !!$form->no_error);
$form_id = 'order_order_form_'. uniqid();
$portion_name = 'grant_portion';
$table_id = 'table_' . uniqid();
?>
<div class="hr_1">&#160;</div>
<div class="order_form">
<form q-src="<?php echo $order->url(); ?>" q-object="mall_confirm" q-event="submit" id="<?php echo H($form_id) ?>" autocomplete="off">
<?php echo V('form_error', ['form'=>$form]);?>
<div class="form padding_1 clearfix">
	<div class="clear">&#160;</div>
    <table class="form" id="<?php echo $table_id; ?>">
        <tbody>
            <tr>
                <td class="label top nowrap right">
                    <span class="title"><?php echo I18N::T('orders', '货品信息');?></span>
                </td>
                <td colspan="3">&#160;</td>
            </tr>

            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('product_name'); echo I18N::T('orders', '产品名称') ?>
                </td>
                <td class="left nowrap" colspan="3">

                    <input class="text remote" type="text" size='60' disabled="disabled" name="product_name" value="<?php echo H($order->product_name)?>"/>
                    <input name="source" class="hidden" type="text" value="<?php echo H($order->source);?>" />
                    <input name="order_id" class="hidden" type="text" value="<?php echo $order->id; ?>" />
                    <input name="order_status" class="hidden" type="text" value="<?php echo $order->status; ?>" />
                </td>
            </tr>

            <tr class="nowrap">
                <td class="label top nowrap right">
                    <?php echo $order->get_require('manufacturer'); echo I18N::T('orders', '生产商') ?>
                </td>
                <td class="left top nowrap">
                    <input class="text remote" type="text" name="manufacturer" disabled="disabled" value="<?php echo H($order->manufacturer)?>"/>
                </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('model'); echo I18N::T('orders', '型号') ?>
                </td>
                <td class="left">
                    <input class="text remote" type="text" name="model" disabled="disabled" value="<?php echo H($order->model)?>"/>
                </td>
            </tr>

            <tr class="nowrap">
                <td class="label top nowrap right">
                    <?php echo $order->get_require('catalog_no'); echo I18N::T('orders', '目录号') ?>
                </td>
                <td class="left">
		            <input class="text remote" type="text" name="catalog_no" disabled="disabled" value="<?php echo H($order->catalog_no)?>"/>
                </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('spec'); echo I18N::T('orders', '规格')?>
                </td>
                <td class="left">
		            <input class="text remote" type="text" name="spec" disabled="disabled" value="<?php echo H($order->spec)?>" />
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('order_no'); echo I18N::T('orders', '订单编号') ?>
                </td>
                <td class="left">
		            <input class="text remote" type="text" name="order_no" disabled="disabled" value="<?php echo H($order->order_no)?>" />
               </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('quantity'); echo I18N::T('orders', '数量') ?>
                </td>
                <td class="left">
                <input class="text number" type="text" name="quantity" id="quantity" disabled="disabled" value="<?php echo H($order->quantity)?>"/>
                </td>
            </tr>
            <tr class="nowrap">
            	<td class="label top nowrap right">
                    <?php echo $order->get_require('unit_price'); echo I18N::T('orders', '单价') ?>
                </td>
                <td class="left">
		            <input class="text currency remote" type="text" name="unit_price" disabled="disabled" value="<?php echo H($order->unit_price)?>"/>
                </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('fare'); echo I18N::T('orders', '运费') ?>
                </td>
                <td class="left">
                    <input class="text currency" type="text" name="fare" disabled="disabled" value="<?php echo H($order->fare)?>" />
               </td>
            </tr>
            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('price'); echo I18N::T('orders', '总价') ?>
                </td>
                <td class="left" colspan="3">
                <input class="text currency middle remote" type="text" name="price" disabled="disabled" value="<?php echo H($order->price)?>" />
                    <a href="#" class="button button_calculate middle prevent_default" name="calculate_price"><?php echo I18N::T('orders', '计算')?></a>
                </td>
            </tr>
	        <?php if ($me->is_allowed_to('编辑订单标签', 'order')) : ?>
            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('tags'); echo I18N::T('orders','标签') ?>
                </td>
                <td class="left" colspan="3">
                    <?php
                    /* xiaopei.li@2011.02.23 */
                    $root = Tag_Model::root('inventory');
                    $tags = (array) Q("$order tag[root=$root]")->to_assoc('name','name');
                    $tags_str = '';
                    if (count($tags)) {
                        $tags_str =  implode(',', $tags);
                    }
                    ?>
                    <input size="60" name="tag" class="text"  disabled="disabled" value="<?php echo H($tags_str)?>" />
                </td>
            </tr>
            <?php endif;?>

            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('link'); echo I18N::T('orders', '链接地址') ?>
                </td>
                <td class="left" colspan="3">
                    <input size="60" name="link" class="text" disabled="disabled" value="<?php echo H($order->link)?>" />
                </td>
            </tr>
            <tr>
                <td colspan="4">&#160;</td>
            </tr>
            <?php
                $view = Event::trigger('get_extra_order_order_view', $form, $order);
                echo $view;
            ?>
            <tr>
                <td colspan="4">
                    <span class="title"><?php echo I18N::T('orders', '订单信息')?></span>
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '配送地址');?>
                </td>
                <td>
                    <input name="address" type="text" disabled="disabled" class="text" value="<?php echo H($order->receive_address);?>" size="30"/>
                </td>
                <td class="label top nowrap right">
                    &#160;&#160;&#160;
                    <?php echo I18N::T('orders', '邮政编码');?>
                </td>
                <td>
                    <input name="postcode" type="text" disabled="disabled" class="text" value="<?php echo H($order->receive_postcode);?>"/>
                </td>
            </tr>

            <tr>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '联系电话');?>
                </td>
                <td>
                    <input name="phone" type="text" disabled="disabled" class="text" value="<?php echo H($order->receive_phone);?>" />
                </td>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '电子邮箱');?>
                </td>
                <td>
                    <input name="email" type="text" disabled="disabled" class="text" value="<?php echo H($order->receive_email);?>" />
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right"><?php echo I18N::T('orders', '确认备注') ?></td>
                <td class="left" colspan="3">
                    <textarea cols="60" name="approve_note" id="approve_note" class="text" ><?php echo H($no_error ? $order->approve_note : $form['approve_note'])?></textarea>
                </td>
            </tr>


            <tr>
                <td colspan="4">&#160;</td>
            </tr>
            <tr>
                <td class="label top nowrap right">&nbsp;</td>
                <td class="left" colspan="3">
		            <input type="submit" name="submit" value="<?php echo H(I18N::T('orders', '确认')) ?>" class="button button_save"/>
                </td>
            </tr>
        </tbody>
    </table>
</div>
</form>
</div>

<script type="text/javascript">
	jQuery(function($){

        var $form = $('#<?php echo $form_id;?>');

		$form.find("a[name=calculate_price]").bind('click', function(e) {
            var n = parseInt($('input[name=quantity]', $form).val()) || 0;
            var up = parseFloat($('input[name=unit_price]', $form).val()) || 0;
            var fare = parseFloat($('input[name=fare]', $form).val()) || 0;
            var total = (n * up + fare).toFixed(2);
            $('input[name=price]', $form).prev().val(total).blur();
            $('input[name=price]', $form).val(total).blur();
            $('input[name=quantity]').val(n);
            e.preventDefault();
            return false;
		});

	});
</script>

