<?php
echo CSS::load_async('orders:order');
$me = L('ME');
$no_error = (!is_object($form) || !!$form->no_error);
$form_id = 'order_request_form_'. uniqid();
?>
<div class="hr_1">&#160;</div>
<div class="order_form">
<form q-src="<?php echo $order->url(); ?>" q-object="request" q-event="submit" id="<?php echo H($form_id) ?>" autocomplete="off">
<?php echo V('form_error', ['form'=>$form]);?>
<div class="form padding_1 clearfix">
	<div class="clear">&#160;</div>
    <table class="form">
        <tbody>
            <tr>
                <td class="label top nowrap right">
                    <span class="title"><?php echo I18N::T('orders', '货品信息');?></span>
                </td>
                <td colspan="3">&#160;</td>
            </tr>

            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('product_name'); echo I18N::T('orders', '产品名称') ?>
                </td>
                <td class="left nowrap" colspan="3">
                    <?php
                        echo Widget::factory('orders:order_autofill', [
                                                'autocomplete'=>URI::url('!orders/autocomplete/order'),
                                                'name'=>'product_name',
                                                'order'=>$order,
                                                'form'=>$form,
                                            ]);
                    ?>
                    <input name="source" class="hidden" type="text" value="<?php echo H($order->source);?>" />
                    <input name="order_id" class="hidden" type="text" value="<?php echo $order->id; ?>" />
                    <input name="order_status" class="hidden" type="text" value="<?php echo $order->status; ?>" />
                </td>
            </tr>

            <tr class="nowrap">
                <td class="label top nowrap right">
                    <?php echo $order->get_require('manufacturer'); echo I18N::T('orders', '生产商') ?>
                </td>
                <td class="left top nowrap">
                    <input class="text remote" type="text" name="manufacturer" value="<?php echo H($no_error?$order->manufacturer:$form['manufacturer'])?>"/>
                </td>
                <?php /*
                <td class="label top nowrap right"><?php echo I18N::T('orders', '供应商') ?></td>
                <td class="left">
                   <?php
                        echo Widget::factory('orders:vendor_selector', array(
                            'name' => 'vendor',
                            'autocomplete' => URI::url('!orders/autocomplete/vendor'),
                            'vendor'=> $form['vendor'] ? O('vendor', $form['vendor']) : O('vendor', $order->vendor_id),
                            'size' => 19
                        ));
                    ?>
                </td>
                */ ?>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('model'); echo I18N::T('orders', '型号') ?>
                </td>
                <td class="left">
                    <input class="text remote" type="text" name="model" value="<?php echo H($no_error?$order->model:$form['model'])?>"/>
                </td>
            </tr>

            <tr class="nowrap">
                <td class="label top nowrap right">
                    <?php echo $order->get_require('catalog_no'); echo I18N::T('orders', '目录号') ?>
                </td>
                <td class="left">
		            <input class="text remote" type="text" name="catalog_no" value="<?php echo H($no_error?$order->catalog_no:$form['catalog_no'])?>"/>
                </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('quantity'); echo I18N::T('orders', '数量') ?>
                </td>
                <td class="left">
                <input class="text number" type="text" name="quantity" id="quantity" value="<?php echo H($no_error?$order->quantity:$form['quantity'])?>"/>
                </td>
            </tr>

            <tr class="nowrap">
                <td class="label top nowrap right">
                    <?php echo $order->get_require('spec'); echo I18N::T('orders', '规格')?>
                </td>
                <td class="left">
		            <input class="text remote" type="text" name="spec" value="<?php echo H($no_error?$order->spec:$form['spec'])?>" />
                </td>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('fare'); echo I18N::T('orders', '运费') ?>
                </td>
                <td class="left">
                    <input class="text currency remote" type="text" name="fare" value="<?php echo H($no_error ? $order->fare : $form['fare'])?>"/>
                </td>
            </tr>

            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('unit_price'); echo I18N::T('orders', '单价') ?>
                </td>
                <td class="left" colspan="3">
                    <?php if($order->source && $order->unit_price<0):?>
                        <input class="text" value="<?= I18N::T('orders', '待询价');?>" disabled/>
                    <?php else:?>
		            <input class="text currency remote" type="text" name="unit_price" value="<?php echo H($no_error ? $order->unit_price : $form['unit_price'])?>"/>
                    <?php endif;?>
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('price'); echo I18N::T('orders', '总价') ?>
                </td>
                <td class="left" colspan="3">
                <?php if($order->source && $order->price<0):?>
                    <input class="text" value="<?= I18N::T('orders', '待询价');?>" disabled/>
                <?php else:?>
                <input class="text currency middle remote" type="text" name="price" value="<?php echo H($no_error ? $order->price : $form['price'])?>" />
                    <a href="#" class="button button_calculate middle prevent_default" name="calculate_price"><?php echo I18N::T('orders', '计算')?></a>
                <?php endif;?>
                </td>
            </tr>
            <?php
                $view = Event::trigger('get_extra_order_request_view', $form, $order);
                echo $view;
            ?>
	        <?php if ($me->is_allowed_to('编辑订单标签', 'order')) : ?>
            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('tags'); echo I18N::T('orders','标签') ?>
                </td>
                <td class="left" colspan="3">
                    <?php
                    /* xiaopei.li@2011.02.23 */
                    $root = Tag_Model::root('inventory');
                    if ($order->id) {
                        $tags = (array) Q("$order tag[root=$root]")->to_assoc('name','name');
                        if(count($tags)) {
                            $tags = json_encode($tags,TRUE);
                        }
                    }
                    else{
                        $tags = '';
                    }
                    if ($showTags) {
                        $tags = (array) Q("$stock tag[root=$root]")->to_assoc('name','name');
                        if(count($tags)) {
                            $tags = json_encode($tags,TRUE);
                        }
                    }                
                    echo Widget::factory('application:multi_tag_selector',
                        [
                            'autocomplete'=> URI::url("!inventory/autocomplete/tags.$root->id"),
                            'name'=>'tags',
                            'value'=> $no_error ? $tags : $form['tags'],
                            'size'=>'68',
                            'allow_creating'=>TRUE,
                            'token_tip' => I18N::T('orders', '您可选择标签或按回车键输入新的标签'),
                        ]);
                    ?>
                </td>
            </tr>
            <?php endif;?>

            <tr>
                <td class="label top nowrap right">
                    <?php echo $order->get_require('link'); echo I18N::T('orders', '链接地址') ?>
                </td>
                <td class="left" colspan="3">
                    <input size="60" name="link" class="text remote" value="<?php echo H($no_error ? $order->link : $form['link'])?>" />
                </td>
            </tr>
            <tr>
                <td colspan="4">&#160;</td>
            </tr>
            <tr>
                <td colspan="4">
                    <span class="title"><?php echo I18N::T('orders', '订单信息')?></span>
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '配送地址');?>
                </td>
                <td>
                    <input name="address" type="text" class="text" value="<?php echo H(!$no_error ? $form['address'] : ($order->receive_address ? : Lab::get('orders.receive_address')));?>" size="30"/>
                </td>
                <td class="label top nowrap right">
                    &#160;&#160;&#160;
                    <?php echo I18N::T('orders', '邮政编码');?>
                </td>
                <td>
                    <input name="postcode" type="text" class="text" value="<?php echo H(!$no_error ? $form['postcode'] : ($order->receive_postcode ? : Lab::get('orders.receive_postcode')));?>"/>
                </td>
            </tr>

            <tr>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '联系电话');?>
                </td>
                <td>
                    <input name="phone" type="text" class="text" value="<?php echo H(!$no_error ? $form['phone'] : ($order->receive_phone ? : Lab::get('orders.receive_phone')));?>" />
                </td>
                <td class="label top nowrap right">
                    <?php echo I18N::T('orders', '电子邮箱');?>
                </td>
                <td>
                    <input name="email" type="text" class="text" value="<?php echo H(!$no_error ? $form['email'] : ($order->receive_email ? : Lab::get('orders.receive_email')));?>" />
                </td>
            </tr>

            <tr>
                <td class="label top nowrap right"><?php echo I18N::T('orders', '申购备注') ?></td>
                <td class="left" colspan="3">
			        <textarea cols="60" name="request_note" id="request_note" class="text" ><?php echo H($form['request_note'])?></textarea>
                </td>
            </tr>
            <tr>
                <td class="label top nowrap right"><?php echo I18N::T('orders', '通知负责人');?></td>
                <td class="left" colspan="3">
                    <?php
                        if ($form['incharges']) {
                            $incharger = $form['incharges'];
                        }
                        elseif (count(json_decode($order->incharges, TRUE))) {
                            $incharger = $order->incharges;
                        }
                        else {
                            $incharger = Lab::get('orders.incharges');
                        }

                     ?>
                    <?php echo Widget::factory('multi_user_selector', [
                        'name' => 'incharges',
                        'autocomplete'=> URI::url('!orders/autocomplete/incharge'),
                        'value' => $incharger,
                        'extra'=> 'token_verify',
                        'size'=> '68'
                    ]); ?>
                </td>
            </tr>

            <tr>
                <td colspan="4">&#160;</td>
            </tr>
            <tr>
                <td class="label top nowrap right">&nbsp;</td>
                <td class="left" colspan="3">
		            <input type="submit" name="submit" value="<?php echo H(I18N::T('orders', '提交')) ?>" class="button button_save"/>
                </td>
            </tr>
        </tbody>
    </table>
</div>
</form>
</div>

<script type="text/javascript">
	jQuery(function($){
        var source = '<?php echo $order->source ?>';
        var disable = '<?php echo $disable ?>';
        var $form = $('#<?php echo $form_id;?>');

        if (source.length > 0) {
            $form.find('.remote').prop('disabled', 'TRUE');
            $form.find('[name=product_name]').prop('disabled', true);
        }

		$form.find("a[name=calculate_price]").bind('click', function(e) {
            var n = parseInt($('input[name=quantity]', $form).val()) || 0;
            var up = parseFloat($('input[name=unit_price]', $form).val()) || 0;
            var fare = parseFloat($('input[name=fare]', $form).val()) || 0;
            var total = (n * up + fare).toFixed(2);
            $('input[name=price]', $form).prev().val(total).blur();
            $('input[name=price]', $form).val(total).blur();
            $('input[name=quantity]').val(n);
            e.preventDefault();
			return false;
		});
	});
</script>
