<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('eq_stat', '%name 报表', ['%name'=>$perf->name]); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
		<caption><?php echo I18N::T('eq_stat', '%name 报表', ['%name'=>H($perf->name)]); ?></caption>
	<thead id="stat">
		<tr>
			<td colspan="8">
			<?php echo I18N::T('eq_stat', '评估范围:'); ?>
			&#160;
			<?php
				$tag = $perf->collection;
				echo $tag->root->id ? $tag->name : T('所有');
			?>
			</td>
		</tr>
		<tr>
			<td colspan="8">
			<?php echo I18N::T('eq_stat', '评估时间:'); ?>
			&#160;
			<?php
				echo Date::format($perf->dfrom, 'Y/m/d').' - '.Date::format($perf->dto, 'Y/m/d');
			?>
			</td>
		</tr>
		<tr>
			<td colspan="8">
			<?php echo I18N::T('eq_stat', '评分时间:'); ?>
			&#160;
			<?php
				echo Date::format($perf->rating_from, 'Y/m/d').' - '.Date::format($perf->rating_to, 'Y/m/d');
			?>
			</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<?php foreach ($valid_columns as $key => $value) :?>
			<th class="left nowrap"><?php echo I18N::T('eq_stat', $value); ?></th>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php
		$valid_columns = array_flip($valid_columns);
		foreach($equipments as $equipment): 
			$scores = Perf::owner_score($equipment, $perf);
			$total = Perf::perf_score($equipment, $perf);
		?>
		<tr>
			<?php if (in_array('equipment', $valid_columns)): ?>
			<td class="left nowrap"><?php echo H($equipment->name); ?></td>
			<?php endif; ?>
			<?php if (in_array('score', $valid_columns)): ?>
			<td class="center nowrap"><?php echo H($scores['score'])?></td>
			<?php endif; ?>
			<?php if (in_array('num', $valid_columns)): ?>
			<td class="center nowrap"><?php echo H($scores['num'])?></td>
			<?php endif; ?>
			<?php if (in_array('average', $valid_columns)): ?>
			<td class="center nowrap"><?php echo H($scores['average'])?></td>
			<?php endif; ?>
			<?php if (in_array('extra', $valid_columns)): ?>
			<td class="center nowrap"><?php echo H($total['total'] - $total['user_score'])?></td>
			<?php endif; ?>
			<?php if (in_array('total', $valid_columns)): ?>
			<td class="center nowrap"><?php echo H($total['total'])?></td>
			<?php endif; ?>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td colspan="8" class="right nowrap">
				<?php echo I18N::T('eq_stat', '总台数:') . $equipments->total_count(); ?>
			</td>
		</tr>
	</tbody>
	</table>
</body>
</html>
