<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('eq_stat', '仪器统计列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('eq_stat', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('eq_stat', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                	echo I18N::HT('eq_stat', '仪器统计列表');			
                ?>
              
            </caption>
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('eq_stat', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
			$special_list = (array)Config::get('eq_stat.special_list', []);
			
			foreach($equipments as $equipment): ?>
				<?php $project_values = Event::trigger('stat.equipment.project_statistic_values', $equipment, $form['dtstart'], $form['dtend']); ?> 
				<tr>
					<?php foreach ($valid_columns as $p => $p_name) : ?>
				<?php 
					$align = 'center';
					if (array_key_exists($p, $special_list) && $special_list[$p]['currency']) {
						$align = 'right';
					}
				?>
						<td class="nowrap <?php echo $align;?>">
						<?php
							if ( strpos($p, 'project') !== false ) {
								echo trim(V("eq_stat/export_value/$p", ['value' => $project_values[$p], 'type' => 'print' ]));
								continue;
							}
		                    $stat_opts = Config::get('eq_stat.stat_opts');
		                    if (array_key_exists($p, $stat_opts)) {
		                        echo trim(V("eq_stat/export_value/$p", ['value'=> EQ_Stat::data_point($p, $equipment, $dtstart, $dtend), 'type'=> 'print']));
		                    }
		                    else {
		                        echo trim(V("eq_stat/export_value/$p", ['value'=> $equipment, 'type'=> 'print']));
		                    }
						?>
					</td>
					<?php endforeach; ?>
				</tr>
		<?php endforeach; ?>
				<tr>
					<td colspan="<?php echo count($valid_columns) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('eq_stat', '总计:') . $equipments->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
