<div class="form padding_2">
    <?php if ($type == 'csv'): ?>
        <form id="list_form" method="POST" q-object="list_export" q-src="<?= URI::url('!eq_stat/export') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" q-event="submit" autocomplete="off" class="prevent_default">
    <?php else: ?>
        <form action="<?php echo H(URI::url('!eq_stat/export', ['type'=>$type,'form_token'=>$form_token])) ?>" target="<?= $type == 'csv' ? '_self' : '_blank'?>" class="prevent_default" method="post">
    <?php endif; ?>
	<ul class="eq_stat_triple">
	  <?php
	 		foreach ($columns as $p => $p_name) :?>
		 		<?php if ( $p<0 ) :?>
		 		<div class="clear">&#160;</div>
				<h4><?php echo I18N::HT('eq_stat', $p_name) ?></h4>
		 		<?php else: ?>
				  <li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('eq_stat', $p_name), 'class="middle monitor"', 'class="middle"');?>
				  </li>
				  <?php endif; ?>
			 <?php endforeach;?>
	</ul>
	<input type="submit" name="submit" class="button button_edit" value="<?php echo H(I18N::T('eq_stat', '提交')) ?>" />
  </form>
</div>
