<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title><?php echo I18N::T('equipments', '仪器维修记录报表'); ?></title>
    <base href="<?php echo H(Config::get('system.base_url') ) ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
    <style>
    a {
        color:blue;
        text-decoration:underline;
    }
    table.report {
        
        font-size: 14px;
        margin:auto;
    }
    
    thead{
        border-top:2px solid  #000;
        border-bottom:1px solid #000;
    }
    
    tbody{
        border-bottom:2px solid #000;
    }
    
    thead#stat{
        font-size: 10px;
        border:none;
    }
    
    table.report caption {
        font-size: 150%;
        margin-bottom: 10px;
    }

    table.report tbody td {
        vertical-align: top;
        border-bottom: 1px dotted #CCC;
    }
    table.report .referred_charge {
        background-color: #eee;
        border:1px dotted #CCC;
    }
    p {
        margin: 0;
    }
    .quote {
        margin-left: 1em;
    }
    </style>
    <style media="print">
    .buttons{
        display:none;
    }
    </style>
</head>

<body>
    <div class="buttons">
        <a href="#" onclick="window.print(); return false;"><?php echo I18N::T('equipments', '打印'); ?></a>
        <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('equipments', '关闭|:print'); ?></a>
    </div>
    <?php 
    $form['@columns'] = $valid_columns;
    $form['selector'] = $selector;
    $_SESSION[$form_token] = $form;

    $print_limit = Config::get('eq_maintain.print_max', 500);
    if ($keeps->total_count() >= $print_limit) :

    $csv_link = I18N::T('equipments', '导出Excel');
    ?>
    <div class="center">
        <strong>
            <?php echo I18N::T('equipments',
                '您选择数据超过%print_limit条, 不适合打印, 请选择%csv_link或调整您的搜索条件', [
                '%print_limit' => $print_limit,
                '%csv_link' => $csv_link,
            ]); ?> 
        </strong>
    </div>
    <?php else : ?>
    <table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
    <caption><?php echo I18N::T('equipments', '仪器维修记录报表'); ?></caption>
    <thead id="stat">
        <tr>
        <td colspan="8">
        <?php echo I18N::T('equipments', '时间范围:'); ?>
        &#160;
        <?php
            $dtstart = isset($form['dtstart_check']) ? H(date('Y/m/d',$form['dtstart'])) : I18N::T('equipments','最初');
            $dtend = isset($form['dtend_check']) ? H(date('Y/m/d',$form['dtend'])) : I18N::T('equipments','最末');
            echo $dtstart . ' - ' . $dtend;
        ?>
        </td>
        </tr>
    </thead>
    <thead>
        <tr>
            <?php 
                $col = 0;
                $already = FALSE;
                foreach ($config as $key => $value) {
                    if (array_key_exists($key, $valid_columns)) {
                        $col ++;
                    }
                }
            ?>
            <?php foreach ($valid_columns as $key => $value) :?>
                <?php if (array_key_exists($key, $config ? : []) && !$already): ?>
                <th colspan="<?php echo H($col ) ?>" class="center nowrap" 
                    style="border-left:1px solid #000;border-bottom:1px solid #000;">
                    <?php echo I18N::T('equipments', '费用来源'); ?>
                </th>
                <?php 
                $already = TRUE;
                elseif (!$already || $key == 'description'): 
                ?>
                <th rowspan="2" class="left nowrap" 
                style="border-left:1px solid #000;border-right:1px solid #000;">
                    <?php echo I18N::T('equipments', $value); ?></th>
                <?php endif ?>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $amount = 0;
        $i = [];
        foreach($keeps as $keep): ?>
        <tr>
        <?php if(array_key_exists('equipment', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($keep->equipment->name);$i['equipment'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_ref_no', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($keep->equipment->ref_no);$i['eq_ref_no'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_cf_id', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($keep->equipment->id);$i['eq_cf_id'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_group', $valid_columns)) : ?>
        <td class="left nowrap"><?php echo H($keep->equipment->group->name);$i['eq_group'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('maintain_ref_no', $valid_columns)): ?>
        <td class="left nowrap"><?php echo Number::fill(H($keep->id), 6);$i['maintain_ref_no'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('time', $valid_columns)): ?>
        <td class="left nowrap"><?php echo Date('Y-m-d H:i:s', $keep->time);$i['time'] = 1; ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('amount', $valid_columns)): ?>
        <td class="left nowrap"><?php echo Number::currency($keep->amount);?></td>
        <?php endif; ?>
        <?php if(array_key_exists('rate', $valid_columns)): ?>
        <td class="left nowrap"><?= $keep->rate . H('%'); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('description', $valid_columns)): ?>
        <td class="left nowrap"><?php echo $keep->description;?></td>
        <?php endif; ?>
        </tr>
        <?php             
            $amount += $keep->amount;
            endforeach; ?>
        <tr>
            <td class="left nowrap">
            <?php echo H('总计'); ?>
            </td>
            <td colspan="<?php echo count($i) - 1; ?>"></td>
            <?php if(array_key_exists('amount', $valid_columns)): ?>
            <td class="left nowrap"><?php echo Number::currency($amount);?></td>
            <?php endif; ?>
        </tr>
        <tr>
        <td colspan="<?php echo H(count($valid_columns)) ?>" class="right nowrap">
            <?php echo I18N::T('equipments', '总计维修: %count 次', ['%count'=>$keeps->total_count()]); ?>
        </td>
        </tr>
    </tbody>
    </table>
    <?php endif; ?>
</body>
</html>
