<table class="mini_form">
	<tr>
		<td class="middle icon"><?php echo $user->icon('58') ?></td>
		<td class="middle">
			<span class="name"><?php echo H($user->friendly_name());?></span>
			<div>
				<?php echo $user->status_tags();?>
			</div>
			<div>
				<?php
					$token = explode('|', $user->token);
					if (is_array($token) && !empty($token)) {
						echo $token[0];
					}
				?>
			</div>
			<?php if ($user->group->id): ?>
			<div class="description" style="padding-top:2px"><?php echo H($user->group->name); ?></div>
			<?php endif; ?>
		</td>
	</tr>
</table>
