<?php $object = $reject ? 'batch_reject' : 'batch_approve';?>
<div class="form padding_1">
<?php if (isset($message)): ?>
    <div class="message message_error clearfix nowrap"><?php echo H($message);?></div>
<?php endif;?>
<form q-object="<?= $object?>" q-event="submit" q-src="<?php echo H(URI::url('!reserv_approve/index')) ?>" q-static="<?= H(['selected_ids' => $selected_ids]) ?> "autocomplete="off" method="post">
    <?php echo V('form_error', ['form'=>$form]);?>
    <table class="form">
        <tr>
            <td class="label left top nowrap">
                <div class="lpadding_3">
                    <span><?php echo I18N::HT('reserv_approve', '原因描述');?></span>
                </div>
            </td>
        </tr>
        <tr>
            <td class="left top nowrap">
                <div class="lpadding_3 rpadding_3">
                <textarea class="top" name="description" rows="3" cols="50" class="autogrow"><?php echo $form['description'] ?></textarea>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="label left top nowrap">
                <div class="lpadding_3 padding_2"><input name="submit" type='submit' class="button button_add middle" value="<?php echo I18N::HT('reserv_approve', '保存');?>"></div>
            </td>
        </tr>
    </table>
</form>
</div>
