<script>
jQuery(function($){
       var $center = $('#center');
       $center.css('vertical-align', 'middle');
       $center.find('.center_content').css({width: '0px', margin: 'auto', paddingBottom: '10em'});
});
</script>
<div class="form padding_1 clearfix">
<h3 class="section_title margin_1 lmargin_2"><?php echo I18N::T('people', '重置您的登录密码')?></h3>
<div class="hr_1">&#160;</div>
<table class="form margin_1">
	<tbody>
	<tr>
		<td class="top icon" style="padding: 10px;">
			<img src="<?php echo H(O('user')->icon_url('64')) ?>" />
		</td>
		<td class="top">
			<form method="post" autocomplete="off">
			<?php echo V('form_error', ['form'=>$form]);?>
			<input class="hidden" name="key" value="<?php echo H($key) ?>" />
			<table class="form">
				<tbody>
                    <tr>
						<td class="label left nowrap middle"><label><?php echo I18N::T('people', '新密码')?></label></td>
                    </tr>
					<tr>
						<td class="middle">
							<input type="password" autocomplete="off" size="30" class="text" name="new_pass" value="<?php echo H($form['new_pass'])?>" />
						</td>
					</tr>
                    <tr>
                    </tr>
						<td class="label left nowrap middle"><label><?php echo I18N::T('people', '确认新密码')?></label></td>
					<tr>
						<td class="middle">
							<input type="password" autocomplete="off" size="30" class="text" name="confirm_pass" value="<?php echo H($form['confirm_pass'])?>" />
						</td>
					</tr>
                    <tr class="description">
                        <td colspan="3"><?= H(T('8-24个字符，必须包含数字和大小写字母')) ?></td>
                    </tr>
					<tr>
						<td>
							<input type="submit" name="submit" class="button button_save middle" value="<?php echo H(I18N::T('people', '重置')) ?>" />
						</td>
					</tr>
				</tbody>
			</table>
			</form>
		</td>
	</tr>
	</tbody>
</table>
</div>
