<?php
$template = Config::get('eq_charge.template')['service_count'];
$charge_title = $template['title'];
$disabled = L('ME')->is_allowed_to('修改计费设置', $equipment) ? '' : 'disabled="disabled"';
$readonly = L('ME')->is_allowed_to('修改计费设置', $equipment) ? '' : '_readonly';
$charge_setting = EQ_Charge::get_charge_setting($equipment);
$service_setting = $charge_setting['service'] ?: [];
$common_settings = $service_setting['*'];
?>
<form method="post" autocomplete="off" action="<?php echo H(URI::url()) ?>">
    <div class="interval_30"></div>
    <div class="form">
        <table class="form flexible">
            <tbody>
            <tr>
                <td class="top lpadding_30">
                    <h2 class="section_title"><?php echo I18N::T('eq_charge', '计费参数设置') ?> (<?php echo $charge_title ?>)</h2>
                    <div class="interval_30"></div>
                    <div class="lmaigin_1e5">
                        <table class="form">
                            <tbody>
                            <?php foreach ($projects as $id => $project): ?>
                                <tr>
                                    <td class="right nowrap middle rpadding_label"><?php echo I18N::T('eq_charge', $project->name) ?></td>
                                    <td class="">
                                        <input name="<?= 'price[project_price_' . $id . ']' ?>" class="text currency" size="10"
                                               sign="<?php echo H(Config::get('lab.currency_sign')) ?>"
                                               value="<?= H($common_settings['project_price_'.$project->id]) ?>" <?= $disabled ?>/>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <div class="interval_12"></div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="interval_30"></div>
    <?php
    unset($service_setting['*']);
    $tags = $service_setting;
    if ($tags) foreach ($tags as $k => $tag) {
        if ($tag) {
            $key = serialize($tag);
            if (!isset($specific[$key])) {
                $specific[$key] = [];
            }
            $specific[$key]['special_tags'][] = $k;
            $specific[$key]['special_tags_price'] = $tag;
        }
    }
    $specific = (array)$specific;
    if ($specific || !$disabled) :?>
        <div class="form" style="padding-left: 30px;">
            <?php
            echo Widget::factory('flexform' . $readonly, [
                'title' => I18N::T('eq_charge', '个别收费标准'),
                'title_class' => "section_title_span",
                'template_data' => ['disabled' => TRUE],
                'existing_data' => array_values($specific),
                'item_view' => 'technical_service:charge/setup/service_count_item' . $readonly,
                'extra_vars' => [
                    'equipment' => $equipment,
                    'projects' => $projects,
                ],
            ]);
            ?>
        </div>
    <?php endif; ?>
    <div class="interval_60"></div>
    <?php if (!$disabled): ?>
        <div class="form float_right">
            <input type="reset" name="cancel" class="font-button-default rmargin_16" value="<?php echo H(T('取消')) ?>"/>
            <input type="submit" name="submit" class="font-button-save" value="<?php echo H(T('保存修改')) ?>"/>
        </div>
    <?php endif; ?>
</form>