<?php
$me = L('ME');
$show_privacy = $me->is_allowed_to('查看相关人员联系方式', $training->equipment) || $me->is_allowed_to('查看联系方式', $user);
if ($show_privacy) :
?>
    <?php if ($user->phone) :?>
        <div class="phone"><?php echo H($user->phone)?></div>
    <?php endif;?>
    <?php if ($user->email) :?>
        <div class="email"><a href="mailto:<?php echo H($user->email)?>"><?php echo H($user->email) ?></a></div>
    <?php endif;?>
<?php else:?>
    <p class="privacy"><?php echo I18N::T('eq_ban', '您没有权限查看')?></p>
<?php endif;?>
