<?php 
if (isset($specific_add_earliest_limit)) list($specific_add_earliest_time, $specific_add_earliest_format) = Date::format_interval($specific_add_earliest_limit, 'hid');
if (isset($specific_add_latest_limit)) list($specific_add_latest_time, $specific_add_latest_format) = Date::format_interval($specific_add_latest_limit, 'hid');
if (isset($specific_modify_latest_limit)) list($specific_modify_latest_time, $specific_modify_latest_format) = Date::format_interval($specific_modify_latest_limit, 'hid');
if (isset($specific_delete_latest_limit)) list($specific_delete_latest_time, $specific_delete_latest_format) = Date::format_interval($specific_modify_latest_limit, 'hid');

$system_default_add_earliest_limit = Lab::get('equipment.add_reserv_earliest_limit');
$system_default_add_latest_limit = Lab::get('equipment.add_reserv_latest_limit');
$system_default_modify_latest_limit = Lab::get('equipment.modify_reserv_latest_limit');
$system_default_delete_latest_limit = Lab::get('equipment.delete_reserv_latest_limit');

list($system_default_add_earliest_time, $system_default_add_earliest_format) = Date::format_interval($system_default_add_earliest_limit, 'ihd');
list($system_default_add_latest_time, $system_default_add_latest_format) = Date::format_interval($system_default_add_latest_limit, 'ihd');
list($system_default_modify_latest_time, $system_default_modify_latest_format) = Date::format_interval($system_default_modify_latest_limit, 'ihd');
list($system_default_delete_latest_time, $system_default_delete_latest_format) = Date::format_interval($system_default_delete_latest_limit, 'ihd');

?>
<table class="form">
	<tbody>
		<tr>
			<td class="right nowrap middle label">
				<?php echo I18N::T('eq_reserv', '用户标签')?>
            </td>
            <td>
				<?php
					echo $tags ? join($tags,',') : '';
				?>
			</td>
		</tr>
		<tr>
			<td class="right nowrap middle label"><?php echo I18N::T('eq_reserv', '添加预约最早可提前')?></td>
			<td class="nowrap middle">
				<?php 
					echo Form::radio('specific_add_earliest_limit['.$flexform_index.']', 'customize', 
						is_null($specific_add_earliest_limit) ? 
							'default' : 'customize',
							'','class="middle monitor" disabled="disabled"'); 
				?>
				<span class="middle toggle_status:specific_add_earliest_limit[<?= $flexform_index ?>] enable_on:customize">
				<input class="text number middle" name="specific_add_earliest_time[<?= $flexform_index?>]" size="10" 
				value="<?php 
					echo isset($specific_add_earliest_time) ?  $specific_add_earliest_time : (isset($add_reserv_earliest_time) ? $add_reserv_earliest_time : $system_default_add_earliest_time)?>" disabled="disabled"/>&#160;
				<?php 
					echo Form::dropdown('specific_add_earliest_format['.$flexform_index.']', Date::units('ihd'), 
						$specific_add_earliest_format 
						? : $add_reserv_earliest_format ? : $system_default_add_earliest_format ? : Config::get('eq_reserv.default_add_limit_format', 'd'),
						'class="middle" disabled="disabled"');
						?>
				</span>&#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
				<?php
					echo Form::radio('specific_add_earliest_limit['.$flexform_index.']', 'default', 
						is_null($specific_add_earliest_limit) ? 
							'default' : 'customize',
							I18N::T('eq_reserv', '系统默认值'),
							'class="middle monitor" disabled="disabled"','class="middle"'); 
				?>

			</td>
		</tr>
		<tr>
			<td class="right nowrap middle label"><?php echo I18N::T('eq_reserv', '添加预约最晚可提前')?></td>
			<td class="nowrap middle">
				<?php 
					echo Form::radio('specific_add_latest_limit['.$flexform_index.']', 'customize', 
						is_null($specific_add_latest_limit) ? 
							'default' : 'customize',
							'','class="middle monitor" disabled="disabled"'); 
				?>
				<span class="middle toggle_status:specific_add_latest_limit[<?= $flexform_index ?>] enable_on:customize">
				<input class="text number middle" name="specific_add_latest_time[<?= $flexform_index ?>] " size="10" value="<?php echo H(isset($specific_add_latest_time) ?  $specific_add_latest_time : (isset($add_reserv_latest_time) ? $add_reserv_latest_time : $system_default_add_latest_time) ) ?>" disabled="disabled"/>&#160;
				<?php 
					echo Form::dropdown('specific_add_latest_format['.$flexform_index.']', Date::units('ihd'), 
						$specific_add_latest_format 
						? : $add_reserv_latest_format? : $system_default_add_latest_format ? : Config::get('eq_reserv.default_add_limit_format', 'd'),
						'class="middle" disabled="disabled"');
				?>
				</span>&#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
				<?php
					echo Form::radio('specific_add_latest_limit['.$flexform_index.']', 'default', 
						is_null($specific_add_latest_limit) ? 
							'default' : 'customize',I18N::T('eq_reserv', '系统默认值'),
							'class="middle monitor" disabled="disabled"','class="middle"'); 
				?>
			</td>
		</tr>
		<tr>
			<td class="right nowrap middle label"><?php echo I18N::T('eq_reserv', '修改预约最晚可提前')?></td>
			<td class="nowrap middle">
				<?php 
					echo Form::radio('specific_modify_latest_limit['.$flexform_index.']', 'customize', 
						is_null($specific_modify_latest_limit) ? 
							'default' : 'customize',
							'','class="middle monitor" disabled="disabled"'); 
				?>
				<span class="middle toggle_status:specific_modify_latest_limit[<?= $flexform_index ?>] enable_on:customize">
				<input class="text number middle" name="specific_modify_latest_time[<?= $flexform_index ?>]" size="10" value="<?php echo H(isset($specific_modify_latest_time) ?  $specific_modify_latest_time : (isset($modify_reserv_latest_time) ? $modify_reserv_latest_time :$system_default_modify_latest_time)) ?>" disabled="disabled"/>&#160;
				<?php 
					echo Form::dropdown('specific_modify_latest_format['.$flexform_index.']', Date::units('ihd'), 
						$specific_modify_latest_format 
						? : $modify_reserv_latest_format ? : $system_default_modify_latest_format ? : Config::get('eq_reserv.default_modify_reserv_limit_format', 'd'),
						'class="middle" disabled="disabled"');
				?>
				</span>&#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
				<?php
					echo Form::radio('specific_modify_latest_limit['.$flexform_index.']', 'default', 
						is_null($specific_modify_latest_limit) ? 
							'default' : 'customize',I18N::T('eq_reserv', '系统默认值'),
							'class="middle monitor" disabled="disabled"','class="middle"'); 
				?>
			</td>
		</tr>

        <tr>
            <td class="right nowrap middle label"><?php echo I18N::T('eq_reserv', '删除预约最晚可提前')?></td>
            <td class="nowrap middle">
                <?php
                echo Form::radio('specific_delete_latest_limit['.$flexform_index.']', 'customize',
                    is_null($specific_delete_latest_limit) ?
                        'default' : 'customize',
                    '','class="middle monitor" disabled="disabled"');
                ?>
                <span class="middle toggle_status:specific_delete_latest_limit[<?= $flexform_index ?>] enable_on:customize">
				<input class="text number middle" name="specific_delete_latest_time[<?= $flexform_index ?>]" size="10" value="<?php echo H(isset($specific_delete_latest_time) ?  $specific_delete_latest_time : (isset($delete_reserv_latest_time) ? $delete_reserv_latest_time :$system_default_delete_latest_time)) ?>" disabled="disabled"/>&#160;
				<?php
                echo Form::dropdown('specific_delete_latest_format['.$flexform_index.']', Date::units('ihd'),
                    $specific_delete_latest_format
                        ? : $delete_reserv_latest_format ? : $system_default_delete_latest_format ? : Config::get('eq_reserv.default_delete_reserv_limit_format', 'd'),
                    'class="middle" disabled="disabled"');
                ?>
				</span>&#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
                <?php
                echo Form::radio('specific_delete_latest_limit['.$flexform_index.']', 'default',
                    is_null($specific_modify_latest_limit) ?
                        'default' : 'customize',I18N::T('eq_reserv', '系统默认值'),
                    'class="middle monitor" disabled="disabled"','class="middle"');
                ?>
            </td>
        </tr>

	</tbody>
</table>
