<?php $this->dtstart = $this->dtstart ? date('Y-m-d', $this->dtstart) : ''; ?>
<?php $this->dtend = $this->dtend ? date('Y-m-d', $this->dtend) : ''; ?>

<input id="dtstart" name="dtstart" class="text date small_search_text" date_type="date" value="<?php echo H($this->dtstart) ?>" /><span class="middle date_interval description">-</span><input id="dtend" name="dtend" class="text date small_search_text" date_type="date" value="<?php echo H($this->dtend) ?>" />
