<?php $me = L('ME');?>
<div class="form padding_1">
<form method="post" action="<?php echo URI::url(); ?>" autocomplete="off">
<?php echo V('form_error', array('form'=>$form));?>
<table class="form">
	<tr>
		<td>
			<div class="padding_1">
			<h4><?php echo I18N::T('wechat', 'AppID')?></h4>
			<div class="lpadding_3">
				<p>
					<input name="appID" value="<?php echo H(Lab::get('Wechat.AppID')) ?>" class="text<?php if(strlen(Lab::get('Wechat.AppID'))) echo ' readonly'?>"/>
				</p>
			</div>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="padding_1">
			<h4><?php echo I18N::T('wechat', 'Secret')?></h4>
			<div class="lpadding_3">
				<p>
					<input name="Secret" value="<?php echo H(Lab::get('Wechat.Secret')) ?>" class="text<?php if(strlen(Lab::get('Wechat.Secret'))) echo ' readonly'?>" size="30"/>
				</p>
			</div>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="padding_1">
			<?php
				if(!strlen(Lab::get('Wechat.AppID')) && !strlen(Lab::get('Wechat.Secret'))) {
			?>
				<input type="submit" name="submit" class="button button_save" value="<?php echo H(I18N::T('wechat', '注册')) ?>" />
			<?php
				} else  {
			?>
				<input type="submit" name="unregister" class="button button_save" value="<?php echo H(I18N::T('wechat', '注销')) ?>" />
			<?php
				}
			?>
			</div>
		</td>
	</tr>
</table>
</form>
</div>
