<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo I18N::T('billing', '人事列表'); ?></title>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {

		font-size: 14px;
		margin:auto;
	}
	table .time {
		font-size: 16px;
	}

	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}

	tbody{
		border-bottom:2px solid #000;
	}

	thead#stat{
		font-size: 10px;
		border:none;
	}

	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>

  <div class="buttons">
	<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('staff', '打印'); ?></a>
  </div>
  <table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('staff', '人事列表'); ?></caption>
	<thead>
	  <tr>
		<th class="left nowrap"><?php echo I18N::T('staff', '工号'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '姓名'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '性别'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '年龄'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '籍贯'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '省份证号'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '学历'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '学校'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '专业'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '联系电话'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '角色'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '部门'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '职位'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '合同开始时间'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '合同结束时间'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('staff', '有效期'); ?></th>
	  </tr>
	</thead>
	<tbody>
	  <?php foreach($staffs as $staff){ ?>
	  <tr>
		<td class="left nowrap"><?php echo $staff->user->ref_no?H($staff->user->ref_no):'--'; ?></td>
		<td class="left nowrap"><?php echo H($staff->user->name); ?></td>
		<td class="left nowrap"><?php echo I18N::T('staff', User_Model::$genders[$staff->user->gender] ); ?></td>
		<td class="left nowrap"><?php echo V('staff:staffs_table/data/age', ['staff'=>$staff]); ?></td>
		<td class="left nowrap"><?php echo H($staff->birthplace); ?></td>
		<td class="left nowrap"><?php echo H($staff->IDnumber); ?></td>
		<td class="left nowrap"><?php echo I18N::T('staff', $staff->get_education()); ?></td>
		<td class="left nowrap"><?php echo H($staff->school); ?></td>
		<td class="left nowrap"><?php echo H($staff->professional); ?></td>
		<td class="left nowrap"><?php echo V('people:users_table/data/phone', ['user'=>$staff->user]); ?></td>
		<td class="left nowrap"><?php echo I18N::T('staff', Staff_Model::$roles[ $staff->role ] ); ?></td>
		<td class="left nowrap"><?php echo H($staff->user->group->name); ?></td>
		<td class="left nowrap"><?php echo V('staff:staffs_table/data/position', ['staff'=>$staff]); ?></td>
		<td class="left nowrap"><?php echo $staff->start_time ? Date::format($staff->start_time, 'Y/m/d') : null; ?></td>
		<td class="left nowrap"><?php echo $staff->contract_time ? Date::format($staff->contract_time, 'Y/m/d'):null; ?></td>
		<td class="left nowrap"><?php echo V('staff:staffs_table/data/effective_time', ['staff'=>$staff]); ?></td>
	</tr>
	<?php } ?>
	</tbody>
  </table>
</body>
</html>
