<div class="form padding_1">
<form method="post" action="<?php echo H(URI::url() ) ?>" autocomplete="off">
<?php 
	echo V('form_error', ['form'=>$form]);
	$no_error = ($form->no_error!==FALSE);
?>
<?php $require = (string) V('form_require'); ?>
<?php
	$tag = $perf->collection;
	$check_group = $tag->id == $group_root->id || $tag->root->id == $group_root->id;
	$tag_type = $no_error ? ($check_group ? 'group' : 'cat') : $form['tag'];
	$cat_selector = V('eq_stat:eq_stat_table/filters/tag', [
				'name'=>'cat_id',
				'tag'=>$no_error ? $tag : O('tag', $form['cat_id']),
				'root'=>$cat_root,
			]);

	$group_selector = V('eq_stat:eq_stat_table/filters/tag', [
				'name'=>'group_id',
				'tag'=>$no_error ? $tag : O('tag', $form['group_id']),
				'root'=>$group_root,
			]);
?>
	<table class="form">
		<tr>
			<td class="label right nowrap"><?php echo I18N::T('eq_stat', '评估名称')?></td>
			<td class="middle">
				<input name="name" class="text" value="<?php echo H($no_error?$perf->name:$form['name']) ?>" /><?php echo $require;?>
			</td>
		</tr>
		<tr>
			<td class="label right nowrap top"><?php echo I18N::T('eq_stat', '仪器范围')?></td>
			<td class="middle">
				<?php if($perf->can_grade):?>
				<?php 
					if($perf->collection->root->id) {
						echo V('application:tag/path', ['tag'=>$perf->collection]);
					}
					else {
						echo I18N::T('eq_stat', '所有');
					}
				?>
				<?php else:?>
				<div>
					<?php 
						echo Form::radio('tag', 'cat',	$tag_type=='cat' ?: FALSE, I18N::T('eq_stat', '按仪器分类'), 'class="monitor middle"', 'class="middle"');
					?>
					&#160;
					<div class="inline_block hidden toggle:tag show_on:cat">
						<?php echo $cat_selector ?>
					</div>
				</div>
				<div>
					<?php
						 echo Form::radio('tag', 'group', $tag_type, I18N::T('eq_stat', '按组织机构'), 'class="monitor middle"', 'class="middle"'); 
					?>
					&#160;
					<div class="inline_block hidden toggle:tag show_on:group">
						<?php echo $group_selector ?>
					</div>
				</div>
				<?php endif;?>
			</td>
		</tr>
		<tr>
			<td class="label right nowrap"><?php echo I18N::T('eq_stat', '评估时段')?></td>
			<td class="middle">
				<input class="text date" name="dfrom" value="<?php echo H($no_error?$perf->dfrom:$form['dfrom']);?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>
				-
				<input class="text date" name="dto" value="<?php echo H($no_error?$perf->dto:$form['dto']);?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input class="button button_save" type="submit" name="submit" value="<?php echo H(I18N::T('eq_stat', '更新')) ?>" />
				<?php if (L('ME')->is_allowed_to('删除', $perf)):?>
				&#160;&#160;&#160;
				<a class="font-button-delete" confirm="<?php echo H(I18N::T('eq_stat', '您确定删除该评估吗?')) ?>" href="<?php echo H($perf->url(NULL, NULL, NULL, 'delete') ) ?>"><?php echo I18N::T('eq_stat', '删除评估')?></a>
				<?php endif;?>
			</td>
		</tr>
	</table>
</form>
</div>
