<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('billing', '评价列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
			.align_right {
				text-align:right;
			}

		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>

	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('billing', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('billing', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                	echo I18N::HT('billing', '评价列表');
                ?>

            </caption>
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('eq_comment', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($comments as $comment): ?>
				<tr>
					<?php if(array_key_exists('equipment', $valid_columns)):?>
						<td>
							<?php echo H($comment->equipment->name); ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('user', $valid_columns)):?>
						<td>
							<?php echo H($comment->user->name); ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('service_attitude', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->service_attitude - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('service_quality', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->service_quality - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('technical_ability', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->technical_ability - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('emergency_capability', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->emergency_capability - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('detection_performance', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->detection_performance - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('accuracy', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->accuracy - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('compliance', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->compliance - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('timeliness', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->timeliness - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('sample_processing', $valid_columns)):?>
						<td>
							<?php echo H($tip[$comment->sample_processing - 1]) ?>
						</td>
					<?php endif; ?>
          <?php if(array_key_exists('sample_processing', $valid_columns)):?>
						<td>
							<?php echo $comment->comment_suggestion ?>
						</td>
					<?php endif; ?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</body>
</html>