<style type="text/css">
ul{
	margin:0px;
	list-style:none;
	font-size:14px;
}

.top_text {
	font-size:14px;
	margin-left:42px;
	padding:4px;
}

li {
	padding: 4px;
}
</style>
<span style="font-size:14px"><?php echo date('F d, Y');?><span>
<div class="hr_1">&#160;</div>
<p style="font-size:18px"><b>Dear <?php echo H($user->name);  ?>: </b></p>
<?php
	$base_url = Config::get('system.base_url');
	$str = URI::anchor($base_url, 'LabScout LIMS');
?>
<div>
	<div class="top_text">The LabScout LIMS secretary is honored to present you all updates from your lab: <?php echo $str; ?></div>
<div style="height:30px">&#160;</div>
<?php echo $body; ?>
</div>
<div class="hr_1">&#160;</div>
<div align='left' style="font-size:14px;">
	<div style="padding:5px">
		<b>Genee Support</b>
	</div>
	<div style="padding:5px">
		<!-- <b>E: support@geneegroup.com</b> -->
	</div>
	<div style="padding:5px">
		<b>T: <?= Config::get('system.customer_service_tel_text'); ?>（<?= Config::get('system.customer_service_tel'); ?>）</b>
	</div>
	<div style="padding:5px">
		<b>W: <a href='www.geneegroup.com'>www.geneegroup.com</a></b>
	</div>
	<div style="padding:5px">
		<b>LabScout LIMS: Research Gets Easier!</b>
	</div>
</div>