<div class="pages"><?= $pagination ?></div>
<?php

$me = L('ME');
$table = Widget::factory('table');
$table->name = 'approval_reserv';
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;
$table->form = $form;

$table->add_columns((array) $columns);

$table->empty_message = I18N::T('approval', '没有查询到相应的项目!');

if (count($approval) > 0) {

    foreach($approval as $ap) {
        $stime = $stime_title ? O('approved', ['source' => $ap, 'flag' => $flag])->ctime : '';

        $links = $ap->links();
        if ($me->is_allowed_to('删除', $ap->source->component) && $ap->flag != 'done') {
            $links['delete'] = [
                'url' => NULL,
                'text' => I18N::T('eq_sample', '删除'),
                'extra' => 'class="blue" q-object="delete_component" q-event="click" q-static="'
                    . H(['component_id' => $ap->source->component->id,])
                    . '" q-src="' . URI::url('!calendars/calendar') . '"',
            ];
        }
        $table->add_row([
            'equipment' => V('approval_flow:approval_table/data/equipment', ['equipment'=>$ap->equipment]),
            'reserv_time' => date('Y/m/d H:i:s', $ap->dtstart).' - '.date('Y/m/d H:i:s', $ap->dtend),
            'amount' => V('approval_flow:approval_table/data/amount', ['source'=>$ap->source]),
            'ctime' => date('Y/m/d H:i:s', $ap->ctime),
            'stime' => $stime_title ? date('Y/m/d H:i:s', $stime) : '',
            'description' => $ap->source->component->description ? H($ap->source->component->description) : H($ap->reserv_desc),
            'rest' => Widget::factory('application:links', ['links' => $links])
        ]);
    }
}
echo $table;
?>
<div class="pages"><?= $pagination ?></div>