<?php
	$size = L('ME')->locale == 'en_US' ? 49 : 46;
?>
<div class="<?php echo $class;?> nowrap radio_container bpadding_1">
    <span class="holder">
        <input name="field[<?php echo $prefix?>][radio][default_value]" type="radio" disabled="disabled" 
        value="<?php echo H($subprefix ? : 0) ?>" <?php echo $subprefix == $default ? 'checked' : '' ?>/>
    </span>
    <input type="text" name="field[<?php echo $prefix?>][radio][<?php echo $subprefix ? : 0;?>]" class="text" size="<?php echo $size; ?>" value="<?php echo H($item) ?>" disabled="disabled" />
</div>
