<div class="interval_20"></div>
<table class="form">
    <tr><td><div class="interval_20"></div></td></tr>
    <tr>
        <td class="left nowrap middle"><?php echo I18N::T('eq_time_counts', '单次预约时长限制阈值') ?></td>
        <td class="left nowrap middle" colspan="3">
            <input name="per_reserv_time[<?php echo $flexform_index ?>]" class="text number"
                   value="<?= $per_reserv_time ?>" disabled="disabled"/>
            <span class="description"><?= I18N::T('eq_time_counts', '单位(小时)') ?></span>
        </td>
    </tr>
    <tr style="display: none">
        <td class="left nowrap middle"><?php echo I18N::T('eq_time_counts', '预约总时长限制阈值') ?></td>
        <td class="left nowrap middle" colspan="3">
            <input name="total_reserv_time[<?php echo $flexform_index ?>]" class="text number"
                   value="<?= $total_reserv_time ?>" disabled="disabled"/>
            <span class="description"><?= I18N::T('eq_time_counts', '单位(小时)') ?></span>
        </td>
    </tr>
    <tr><td><div class="interval_20"></div></td></tr>
    <tr>
        <td class="left nowrap middle"><?php echo I18N::T('eq_time_counts', '预约总次数限制阈值') ?></td>
        <td class="left nowrap middle" colspan="3">
            <input name="total_reserv_counts[<?php echo $flexform_index ?>]" class="text number"
                   value="<?= $total_reserv_counts ?>" disabled="disabled"/>
            <span class="description"><?= I18N::T('eq_time_counts', '单位(次)') ?></span>
        </td>
    </tr>
    <tr><td><div class="interval_30"></div></td></tr>
</table>


<h4><?php echo I18N::T('eq_time_counts', '设置受限用户'); ?></h4>
<div class="interval_10"></div>
<div class="toggle:time_counts_controlall[<?= $flexform_index ?>] show_on:0">
    <table class="form" style="width: 100%">
        <tr><td><div class="interval_12"></div></td></tr>
        <tr>
            <td class="left nowrap top" style="width:100px">
                <?= Form::checkbox("time_counts_select_user_mode_user[{$flexform_index}]", !!$controluser,
                I18N::T('eq_time_counts', '个别用户'), 'class="middle monitor checkbox" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
            </td>
            <td>
                <?= implode(',', json_decode($controluser, true) ?: []); ?>
            </td>
        </tr>
        <tr><td><div class="interval_12"></div></td></tr>
        <?php if (!$GLOBALS['preload']['people.multi_lab'] && Module::is_installed('labs')): ?>
            <tr>
                <td class="left nowrap top">
                    <?= Form::checkbox("time_counts_select_user_mode_lab[{$flexform_index}]", $controllab,
                        I18N::T('eq_time_counts', '课题组'), 'class="middle monitor checkbox" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
                </td>
                <td>
                    <?= implode(',', json_decode($controllab, true) ?: []); ?>
                </td>
            </tr>
        <?php endif ?>
        <tr><td><div class="interval_12"></div></td></tr>
        <tr>
            <td class="left nowrap top">
                <?= Form::checkbox("time_counts_select_user_mode_group[{$flexform_index}]", $controlgroup,
                    I18N::T('eq_time_counts', '组织机构'), 'class="middle monitor checkbox" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
            </td>
            <td>
                <?= implode(',', json_decode($controlgroup, true) ?: []); ?>
            </td>
        </tr>
    </table>
<!-- </div> -->
<div class="interval_24"></div>
