<span>
    <input name="field[<?php echo $prefix?>][range][default_value][0]" type="text" class="text" value="<?php echo H($min ) ?>" style="width: 60px;" <?php echo $readonly ? 'disabled="disabled"' : ''?>/>
    &nbsp;-&nbsp;
    <input name="field[<?php echo $prefix?>][range][default_value][1]" type="text" class="text" value="<?php echo H($max ) ?>" style="width: 60px;" <?php echo $readonly ? 'disabled="disabled"' : ''?>/>
</span>