<?php /* BUG #1052::财务明细页面中，实验室搜索和其他不同，可能导致由于实验室过多，无法选定需要搜索的实验室(kai.wu@2011.08.22) */ ?>
<?php
$uniqid = 'labsel_'.uniqid();
$autocomplete = $this->autocomplete ?: URI::url('!billing/autocomplete/lab');
$lab = $this->lab;
?>

<input id="<?php echo $uniqid?>_lab" name="<?php echo H($this->name ) ?>" type="hidden" value="<?php echo H($lab->id) ?>" />
<input id="<?php echo $uniqid?>_lab_name" class="text middle select_on_focus autocomplete:<?php echo H($autocomplete) ?> autocomplete_alt:#<?php echo $uniqid?>_lab" value="<?php echo H($lab->name) ?>" q-tooltip="<?php echo H(I18N::T('billing', '请输入关键字并选择') ) ?>" />
