<?php 
$uniqid = 'rechargersel_'.uniqid();
$autocomplete = $this->autocomplete ?: URI::url('!billing/autocomplete/recharger');
$recharger = $this->recharger;
?>

<input id="<?php echo $uniqid?>_recharger" name="<?php echo H($this->name ) ?>" type="hidden" value="<?php echo H($recharger->id) ?>" />
<input id="<?php echo $uniqid?>_recharger_name" class="text middle select_on_focus autocomplete:<?php echo H($autocomplete) ?> autocomplete_alt:#<?php echo $uniqid?>_recharger" value="<?php echo H($recharger->name) ?>" q-tooltip="<?php echo H(I18N::T('billing', '请输入关键字并选择') ) ?>" />
