<div class="description">
	<p>This is list of equipment currently in service.</p>
	<p>Click the equipment name and enter the equipment page For more detailed information.</p>
	<p>You may sign up for equipment, and report problems to the person in charge.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may edit equipment information, status, charging standard and more.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
