<div class="form">
<table class="form flexible">
	<tbody>
	<tr>
		<td class="icon top" width="130">
			<!-- <img src="<?php // echo H($meeting->icon_url('100')) ?>" width="100" /> -->
            <div class="short_container">
                <div class="icon-radius img_icon" style="position: relative;">
                        <?php echo $meeting->icon('104'); ?>
                    <div class="icon_cover" style="display: none;">
                        <div class="modify_icon">+</div>
                        <div class="interval_12"></div>
                        <div class="modify_font">修改图标</div>
                    </div>
                </div>

                <input class="upload_icon" name="file" type="file" class="file" style="display: none;" />
            </div>

            <script>
                $.upload_icon(<?php echo '"'.URI::url().'"'; ?>);
            </script>
		</td>
		<td class="top">
		<form method="post" class="edit" autocomplete="off" action="<?php echo H(URI::url() ) ?>">
		<?php echo V('form_error', ['form'=>$form]);?>
		<?php $require = (string) V('form_require', ['extra_class' => 'top']); ?>
            <div class="interval_60"></div>
            <h2 class="section_title">
                <span class="border"></span>
                <span class="black_title"><?= I18N::T('meeting', '基本信息')?></span>
                <span class="float_right red" style="font-size: 14px;font-weight: normal;color: #666;margin-right: 140px;"><span class="required" style="vertical-align: text-top;">*</span>必填</span>
            </h2>
            <div class="interval_12"></div>
		<table class="form">
			<tbody>
             
            <tr>
                <td class="padding_2  rpadding_4" colspan="2">
                    <div class="bpadding_2">
                        <span class="rpadding_1"><?php echo I18N::T('meeting', '会议室名称')?></span><?php echo $require; ?>
                    </div>
                    <div>
                        <input name="name" class="text"  size="54" value="<?php echo H($meeting->name); ?>" />
                    </div>
                </td>
                <td  class="padding_2  lpadding_4" colspan="2">
                    <div class="bpadding_2">
                        <?php echo I18N::T('meeting', '坐席数')?>
                    </div>
                    <div>
                        <input name="seats" class="text"  size="54" value="<?= $meeting->seats ?>" />
                    </div>
                </td>
            </tr>
             
            <tr>
                <td class="padding_2  rpadding_4" colspan="2">
                    <div class="bpadding_2">
                        <span class="rpadding_1"><?php echo I18N::T('meeting', '地点')?></span><?php echo $require; ?>
                    </div>
                    <div>
                        <?php 
                            echo Widget::factory('application:tag_selector', [
                                    'tag' => $form['location']?O('tag_location', $form['location']):$meeting->location,
                                    'root' => Tag_Model::root('location'),
                                    'name' => 'location',
                                    'class' => 'tag_selector_full',
                                    'ajax' => true,
                                ]);
                        ?>
                    </div>
                </td>
            </tr>

             
            <tr>
                <td class="padding_2" colspan="4">
                    <div class="bpadding_2">
                        <span class="rpadding_1"><?php echo I18N::T('meeting', '负责人')?></span><?php echo $require; ?>
                    </div>
                    <div>
                        <?php
                        $users = Q("{$meeting} user.incharge");
                        $incharges = [];
                        foreach ($users as $incharge) {
                            $incharges[$incharge->id] = $incharge->name;
                            if (!$GLOBALS['preload']['people.multi_lab']) {
                                $incharges[$incharge->id] .= '('.Q("$incharge lab")->current()->name.')';
                            }
                        }
                        echo Widget::factory('multi_user_selector',
                            [
                                'name'=>'incharges',
                                'autocomplete'=>URI::url('autocomplete/user'),
                                'value'=> json_encode($incharges),
                                'extra'=>'token_verify'

                            ]);
                        ?>
                    </div>
                </td>
            </tr>
             
            <tr>
                <td class="padding_2" colspan="4">
                    <div class="bpadding_2">
                        <span class="rpadding_1"><?php echo I18N::T('meeting', '联系人')?></span><?php echo $require; ?>
                    </div>
                    <div>
                        <?php
                        $us = Q("{$meeting} user.contact");
                        $contacts = [];
                        foreach ($us as $contact) {
                            $contacts[$contact->id] = $contact->name;
                            if (!$GLOBALS['preload']['people.multi_lab']) {
                                $contacts[$contact->id] .= '('.Q("$contact lab")->current()->name.')';
                            }
                        }
                        echo Widget::factory('multi_user_selector',
                            [
                                'name'=>'contacts',
                                'autocomplete'=>URI::url('autocomplete/user'),
                                'value'=> json_encode($contacts, TRUE),
                                'extra'=>'token_verify'
                            ]);
                        ?>
                    </div>
                </td>
            </tr>
             
            <tr>
                <td class="padding_2" colspan="4">
                    <div class="bpadding_2">
                        <span class="rpadding_1"><?php echo I18N::T('meeting', '备注')?></span>
                    </div>
                    <div>
                        <textarea class="text autogrow" name="description"><?php echo H($meeting->description);?></textarea>
                    </div>
                </td>
            </tr>
             
            <tr>
                <td class="padding_2  rpadding_4" colspan="2">
                    <div class="bpadding_2">
                        <?php echo Form::checkbox('require_auth', $meeting->require_auth, I18N::T('meeting', '需要授权才能使用'), 'class="middle checkbox"', 'class="middle"'); ?>
                    </div>
                </td>
            </tr>


            <tr>
                <td class="padding_2" colspan="4">
                    <div class="button_container">
                        <div class="float_right">
                            <input type="submit" name="submit" class="font-button-save rmargin_16" value="<?php echo H(I18N::T('meeting', '保存修改')) ?>" />
                            <?php
                            if (L('ME')->is_allowed_to('删除', $meeting)) : ?>
                                <?php
                                $cal_component_counts = Q("calendar[parent={$meeting}] cal_component")->total_count();
                                $lab_meeting_component_counts = Q("cal_component[me_room={$meeting}]")->total_count();
                                $counts = $cal_component_counts + $lab_meeting_component_counts;
                                if ($counts == 0) : ?>
                                    <a class="font-button-delete" confirm="<?php echo H(I18N::T('meeting', '您确定删除该会议室吗?')) ?>" href="<?php echo H($meeting->url(NULL, NULL, NULL, 'delete') ) ?>"><?php echo I18N::T('meeting', '删除会议室')?></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </td>
            </tr>
			</tbody>
		</table>
		</form>
		</td>
	</tr>
	</tbody>
</table>
</div>
