<div class="form">
<form class="view object:tag_edit event:submit static:<?php echo H(['id'=>$tag->id, 'parent'=>$parent, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'is_root'=>$is_root, 'collapsed'=>$collapsed, 'tag_name'=>$tag_name ? : $tag->name()]) ?>">
	<?php echo V('form_error', ['form'=>$form]);?>
    <input type="hidden" name="title" value="<?php echo isset($title)? $title : $form['title'] ?>" />
    <div class="interval_24"></div>
	<table class="form">
		<tbody>
			<tr>
				<td class="right nowrap middle">
                   <span><?php echo T('名称')?></span>
                    <?php echo V('form_filter', ['error'=>$form->errors["name"][0]]); ?>
					<input  style="margin-left: 20px;" type="text" class="text" name="name" value="<?php echo H($tag->name) ?>" />
				</td>
			</tr>

		</tbody>
	</table>
    <div class="button_container">
        <div class="float_right">
            <input type="button" name="cancel" id="cancel" class="font-button-default  sm rmargin_2e4" value="<?php echo H(I18N::T('', '取消')) ?>" />
            <input type="submit" name="submit" class="font-button-save sm" value="<?php echo H(I18N::T('', '确定')) ?>" />
        </div>
    </div>
</form>

</div>
