<div class="tag_title check_hover form padding_1 clearfix" style="padding-left:5px">
  <div class="tag_drag_handle middle tag_id:<?php echo $tag->id?>" style="margin: 6px;
    height: 16px;
    width: 16px;
    text-align: center;
    margin-right: 5px;">&#160;</div>
    <div class="hidden">
        <div class="tag_drag_helper center"><?php echo HT($tag->name); ?></div>
    </div>
    
    <?php if (!$collapsed || ($tag->id && Q("{$tag->name()}[parent=$tag]")->length()>0)): ?>
        <span class="toggle_button <?php echo $collapsed ?' toggle_collapse':'toggle_expand'?> middle view event:click object:tag_view static:<?php echo H(['collapse'=>!$collapsed, 'tag'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'tag_name'=>$tag->name(), 'title'=>$title]); ?> src:<?php echo URI::url('tags') ?> ">&nbsp&nbsp&nbsp</span>
    <?php else: ?>
        <span class="toggle_button middle"></span>
    <?php endif; ?>
    <span class="middle tag_name">
		<?php echo H($tag->name); ?>
        &#160;&#160;&#160;&#160;
		<span class="show_on_hover float_right">
			<?php if (!$tag->readonly): ?>
                <?php
                if ($GLOBALS['preload']['tag.group_limit']):
                    #if (tag.group_limit >= 1)
                    $root = $tag->root;
                    $current_levels = $root->current_levels($tag);
                    if ($current_levels <= $GLOBALS['preload']['tag.group_limit']):
                        ?>
                        <a style="color: var(--basiccolor)" class="icon-edit middle view event:click object:tag_edit src:<?php echo URI::url('tags') ?> static:<?php echo H(['id'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'collapsed'=>$collapsed, 'tag_name'=>$tag->name(), 'title'=>$title]); ?>"><?php echo T(''); ?></a>
                    <?php
                    endif;
                #endif
                else:
                    #ifndef (tag.group_limit)
                    ?>
                    <a style="color: var(--basiccolor)" class="icon-edit middle view event:click object:tag_edit src:<?php echo URI::url('tags') ?> static:<?php echo H(['id'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'collapsed'=>$collapsed, 'tag_name'=>$tag->name(), 'title'=>$title]); ?>"><?php echo T(''); ?></a>
                <?php
                    #endif
                endif;
                ?>

			<a  style="color: var(--basiccolor)" class="icon-trash middle view event:click object:tag_delete src:<?php echo URI::url('tags') ?> static:<?php echo H(['id'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'tag_name'=>$tag->name()]); ?>"><?php echo T(''); ?></a>
            <?php endif; ?>
            <?php
            /*
            guoping.zhang@2011.01.17
            组织机构最大层数（上限）
                默认为3层
            */
            if ($GLOBALS['preload']['tag.group_limit']):
                #if (tag.group_limit >= 1)
                if ($current_levels < $GLOBALS['preload']['tag.group_limit']):
                    ?>
                    <a  style="color: var(--basiccolor)" class="icon-add middle view event:click object:tag_edit src:<?php echo URI::url('tags') ?> static:<?php echo H(['parent'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'tag_name'=>$tag->name(), 'title'=>$title]); ?>"><?php echo T(''); ?></a>
                <?php
                endif;
            #endif
            else:
                #ifndef (tag.group_limit)
                ?>
                <a  style="color: var(--basiccolor)" class="icon-add middle view event:click object:tag_edit src:<?php echo URI::url('tags') ?> static:<?php echo H(['parent'=>$tag->id, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'tag_name'=>$tag->name(), 'title'=>$title]); ?>"><?php echo T(''); ?></a>
            <?php
                #endif
            endif;?>
		</span>
	</span>
</div>
