<?php 
	$calendar = O('calendar', $form['calendar_id']);
    $title = I18N::HT('schedule', '%schedule日程安排列表', [
                        '%schedule'=> $calendar->parent->name
                    ]);
?>
<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('schedule', '日程预约记录打印') . $title; ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('schedule', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('schedule', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                    echo $title;
                ?>
            </caption>
			<thead id="stat">
                <tr>
                    <td colspan="<?php echo H(count($columns)) ?>" class="small">
                        <?php echo I18N::HT('schedule', '时间: %dtstart - %dtend', [
                            '%dtstart' => $form['dtstart'] ? Date::format($form['dtstart']) : '最初',
                            '%dtend'=> $form['dtend'] ? Date::format($form['dtend']) : '最末'
                        ])?>
                    </td>
                </tr>
            </thead>
            <thead>
				<tr>
					<?php foreach($columns as $name) : ?>
						<th class="left nowrap"><?php echo I18N::T('schedule', $name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
			foreach($components as $component): ?>
				<tr>
					<?php if (array_key_exists('name', $columns)) : ?>
					<td class="left nowrap">
						<?php echo H($component->name); ?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('reserv_type', $columns)) : ?>
					<td class="left nowrap">
					<?php
						switch($component->subtype) {
						    case 0:
						        echo I18N::T('schedule', '组会');
						        break;
						    case 1:
						        echo I18N::T('schedule', '文献讨论');
						        break;
						    case 2:
						        echo I18N::T('schedule', '其他');
						        break;
						    case 3:
						        echo I18N::T('schedule', '学术报告');
						        break;
						}
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('speakers', $columns)) : ?>
					<td class="left nowrap">
					<?php echo H(join(', ', json_decode($component->speakers, TRUE))); ?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('attendee', $columns)) : ?>
					<td class="left nowrap">
					<?php
						$return = '';
						if ($component->attendee_type == 'all') {
						    $return = I18N::T('schedule', '全部成员');
						}
						else {
						    if ($component->attendee_groups) {
						        $return .= ' '. I18N::T('schedule', '组织机构: ');
						        $return .= join(',', json_decode($component->attendee_groups, TRUE));
						    }

						    if ($component->attendee_roles) {
						        $return .= ' '. I18N::T('schedule', '角色: ');
						        $return .= join(',', json_decode($component->attendee_roles, TRUE));
						    }

						    if ($component->attendee_users) {
						        $return .= ' '. I18N::T('schedule', '个别用户: ');
						        $return .= join(',', json_decode($component->attendee_users, TRUE));
						    }
						}
						echo $return;
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('organizer', $columns)) : ?>
					<td class="left nowrap">
					<?php echo H($component->organizer->name); ?>	
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('meeting', $columns)) : ?>
					<td class="left nowrap">
					<?php echo H($component->me_room->name);?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('time', $columns)) : ?>
					<td class="left nowrap">
					<?php echo Date::format($component->dtstart, 'Y/m/d H:i:s').  ' - '.  Date::format($component->dtend, 'Y/m/d H:i:s');?>						
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('duration', $columns)) : ?>
					<td class="left nowrap">
					<?php echo I18N::T('schedule', '%duration小时', [ '%duration'=> round(($component->dtend - $component->dtstart) / 3600, 2)]); ?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('description', $columns)) : ?>
					<td class="left nowrap">
					<?php echo H($component->description); ?>	
					</td>
					<?php endif; ?>
				</tr>
			<?php
			endforeach;
			?>
			</tbody>
		</table>
	</body>
</html>
