<div class="form padding_1">
  <form class="prevent_default" method="post" autocomplete="off" q-object="add_position" q-event="submit">
	<?php echo V('form_error', ['form' => $form]); ?>
	<?php $require = (string)V('form_require'); ?>
	<table class="form">
	  <tbody>
		<tr>
		  <td class="nowrap label"><?php echo I18N::T('resume', '职位名称'); ?></td>
		  <td colspan="3"><input name="name" class="text" value="<?php echo H($form['name']); ?>" /></td>
		</tr>
		<tr>
		  <td class="nowrap label"><?php echo I18N::T('resume', '所属部门'); ?></td>
		  <td colspan="3"><input name="department" class="text" value="<?php echo H($form['department']); ?>" /></td>
		</tr>
		<tr>
		  <td class="nowrap label"><?php echo I18N::T('resume', '薪酬范围'); ?></td>
		  <td><input name="minsalary" class="text" value="<?php echo H($form['minsalary']); ?>" /></td>
		  <td><?php echo '~';?></td>
		  <td><input name="maxsalary" class="text" value="<?php echo H($form['maxsalary']); ?>" /></td>
		</tr>
		<tr>
		  <td />
		  <td>
			<input class="button button_save" name="submit" type="submit" value="<?php echo I18N::T('resume', '添加'); ?>" />
			&#160;&#160;
			<input class="button button_cancel" name="reset" type="reset" value="<?php echo I18N::T('resume', '重置'); ?>" />
			&#160;&#160;
		  </td>
		</tr>
	  </tbody>
	</table>
  </form>
</div>
