
<div class="toggle:accept_reserv show_on:on hidden">
    <?php echo Form::checkbox('need_approval', $equipment->need_approval, I18N::HT('eq_reserv', '预约需要审核'), 'class="middle checkbox monitor"' . $disabled, 'class="middle"'); ?>
    <?php 
        /*
        $role = [];
        $flows = Config::get('flow.eq_reserv');
        foreach ($flows as $key => $flow) {
            if (isset($flow['action'])) {
                $role[] = $flow['title'];
            }
        }
        $user = join('-', $role);
        echo T('（勾选后用户预约申请将执行' . $user . '审核流程）');
        */
    ?>
</div>
