<?php
$me = L('ME');
$require = (string)V('form_require');
if (Module::is_installed('labs')):
  if ($me->access('添加/修改所有实验室成果')) $autocomplete = '';
  elseif ($me->access('添加/修改负责实验室成果')) $autocomplete =  URI::url("!labs/autocomplete/lab.{$me->id}.pi");
  else $autocomplete = URI::url("!labs/autocomplete/lab.{$me->id}");
?>
  <tr>
    <td class="label left nowrap top label_width">
        <?php echo $require;?><?php echo I18N::T('achievements', '实验室'); ?>
        <br>
        <?php echo V('form_filter',['error'=>$form->errors['lab'][0]]); ?>
    </td>
    <td class="middle" colspan="5">
    <?php
      $selected_lab = !$form->no_error ?
        json_decode($form['lab'],true) :
        ($award->id ? Q("{$award} lab")->to_assoc('id', 'name') : []);
      echo Widget::factory('labs:multi_lab_selector', [
        'name'=>'lab',
        'form'=>$form,
        'labs'=>$selected_lab,
        'autocomplete' => $autocomplete
      ]);
    ?>
    </td>
  </tr>

<?php endif;?>
