<div class="description">
	<p>* Set default settings to prevent users with violation records from operating equipment.</p>
	<p>* Default settings apply to all users, unless users with specific tags are added to the exception list.</p>
	<p>* In order to add users with specific tags to the exception list, you have to add user tags first and then select from the list. (System Preference -> Group)</p>
	<p>* Administrators only.</p>
</div>