<?php 
	$params = Config::get('system.controller_params');
	$user = O('user', $params[0]);	
?>
<div class="description">
	<p>You are viewing the general information of <?= H($user->name) ?></p>
	<?php if ( Module::is_installed('labs') ) :  ?>
	<p>Follow this user.</p>
	<?php endif; ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit or delete user information.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View daily schedule, assigned tasks, equipment sign-up schedule and equipment usage history of the current user.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>

