<div class="group_prevent_default clearfix">
	<div class="check_hover">
	<?php $note->user->render(); ?> @ 
	<span class="description small"><?php echo Date::format($note->mtime) ?></span>
<?php if ($note->actual_time): ?>
	<span class="description"><?php echo I18N::HT('treenote', '耗时')?></span>
	<strong><big><?php echo round($note->actual_time/3600, 1) ?></big></strong> hr
<?php endif; ?>
	&#160;&#160;
	<span class="nowrap show_on_hover">
		<a class="button button_view" href="<?php echo $note->url(); ?>"><?php echo I18N::HT('treenote', '详细'); ?></a>
		<?php echo Widget::factory('application:links', ['links'=>$note->links('view'), 'separator'=>' ']); ?>
	</span>
	</div>
	<?php if ($note->content): ?>
	<?php echo H($note->content, TRUE); ?>
	<?php endif; ?>
	</div>
	<div class="hr_1">&#160;</div>
	<?php if (Module::is_installed('nfs')) : ?>
	<?php echo V('nfs:nfs_lite/downloads', ['object'=>$note, 'path_type'=>'attachments']); ?>
	<div class="hr_1">&#160;</div>
	<?php endif;?>
	<?php echo Widget::factory('application:comments', ['object'=>$note]); ?>
	<div class="hr_1">&#160;</div>
</div>
