<div class="interval_6"></div>
<div>
<table class="form">
<tr>
    <td class="right nowrap middle">
        <input type="checkbox" name="time_counts_repeat[<?php echo $flexform_index?>]" class="monitor checkbox" <?php if($rtype) echo 'checked';?>/>
    </td>
    <td>
       <span class="rpadding_1"> <?php echo I18N::T('application','每'); ?></span>
    </td>
    <td class="left nowrap middle" style="display: none">
        <input type="text" name="time_counts_rnum[<?php echo $flexform_index ?>]" size="5" value="<?php echo H($rnum ?: 1 ) ?>" class="text number toggle_status:time_counts_repeat[<?php echo $flexform_index?>] disable_on:off" disable/>
    </td>
    <td class="right nowrap middle">
        <?php
            $uniqid = uniqid();
            $rrule_uniqid = 'rrule_'.$uniqid;
            $rtypes = WT_RRule::$rtype;
            unset($rtypes[WT_RRule::RRULE_WEEKDAY]);
            unset($rtypes[WT_RRule::RRULE_WEEKEND_DAY]);
            unset($rtypes[WT_RRule::RRULE_YEARLY]);
            $static = H(['rrule_uniqid'=>$rrule_uniqid, 'flexform_index'=>$flexform_index]);
            echo Form::dropdown('time_counts_rtype['.$flexform_index.']', T($rtypes), $rtype, 'class="middle view event:change object:time_counts_rtype src:'.URI::url('!eq_time_counts/rrule').' static:'.$static.' toggle_status:time_counts_repeat['.$flexform_index.'] disable_on:off" disable', 'class="middle"');
        ?>
    </td>
    <td class="left nowrap middle flexible">
        &nbsp;
        <?php echo I18N::T('application','重复一次'); ?>
        &nbsp;&nbsp;<?= $rtype ? '' : '<span class="description">('.I18N::T('eq_time_counts','不重复').')</span>'?>
    </td>
</tr>
</table>
</div>
<div id="<?php echo H($rrule_uniqid ) ?>">
<?php
    switch ($rtype) {
        case WT_RRule::RRULE_DAILY:   //按照日计算
            break;
        case WT_RRule::RRULE_WEEKDAY:   //每工作日
            echo V('application:widgets/rule_date/weekly/wt_weekday', ['flexform_index'=>$flexform_index,
                                                  'week_day'=>$week_day,
                                            ]);
            break;
        case WT_RRule::RRULE_WEEKEND_DAY:       //每周末
            echo V('application:widgets/rule_date/weekly/wt_weekend', ['flexform_index'=>$flexform_index,
                                                  'week_day'=>$week_day,
                                            ]);
            break;
        case WT_RRule::RRULE_WEEKLY:  //按照周计算
            echo V('application:widgets/rule_date/weekly/wt_week', ['flexform_index'=>$flexform_index,
                                                  'week_day'=>$week_day,
                                            ]);
            break;
        case WT_RRule::RRULE_MONTHLY: //按照月计算
            echo V('application:widgets/rule_date/monthly/wt_month', ['flexform_index'=>$flexform_index,
                                                    'month_day'=>$month_day,
                                            ]);
            break;
        case WT_RRule::RRULE_YEARLY:  //按照年计算
            echo V('application:widgets/rule_date/yearly/wt_year', ['flexform_index'=>$flexform_index,
                                                  'year_month'=>$year_month,
                                            ]);
            break;
        default:
            break;
    }
?>
</div>
