<div class="padding_1 clearfix">
	<table class="form" align="center" width="100%">
		<tbody>
			<tr>
				<td class="description" align="right"><?php echo I18N::T('meeting', '主题'); ?></td>
				<td> <?php echo H($component->name); ?></td>		
			</tr>
			
			<tr>
				<td class="description" align="right"><?php echo I18N::T('meeting', '预约者'); ?></td>
				<td>
					<?php
						echo H($component->organizer->name);
					 ?>
				</td>
			</tr>
			
			<tr>
				<td class="description" align="right"><?php echo I18N::T('meeting', '会议室'); ?></td>
				<td>
					<?php 
					if ( $component->calendar->parent_name=='meeting' ) {
						$parent = $component->calendar->parent;
						echo H($parent->name);
					}

					?>
				</td>
			</tr>
			
			<tr>
				<td class="description" align="right"><?php echo I18N::T('meeting', '起始时间'); ?></td>
				<td><?php echo Date::format($component->dtstart, T('Y/m/d H:i:s')); ?></td>
			</tr>

			<tr>
				<td class="description" align="right"><span class="description"><?php echo I18N::T('meeting', '结束时间'); ?></span></td>
				<td><?php echo Date::format($component->dtend, T('Y/m/d H:i:s')); ?></td>
			</tr>
		</tbody>
	</table>
</div>