<table class="form" style="width: 100%">
    <tr>
        <td class="left nowrap middle" width="126"><?php echo I18N::T('entrance','适用人群') ?></td>
        <td class="left nowrap top" style="width:100px">
            <?= Form::checkbox("select_user_mode_user[{$flexform_index}]", !!$controluser,
          I18N::T('entrance','个别用户'), 'class="middle checkbox monitor"', 'class="middle monitor"') ?>
        </td>
        <td>
            <div class="toggle:select_user_mode_user[<?= $flexform_index ?>] show_on:on" style="display:none">
                <?= Widget::factory('entrance:rule_selector', [
          			'name' => "user[{$flexform_index}]",
          			'autocomplete'=>URI::url('autocomplete/user'),
          			'value'=> $controluser ? $controluser : null,
        		]); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="interval_6"></div>
        </td>
    </tr>
    <?php if (!$GLOBALS['preload']['people.multi_lab'] && Module::is_installed('labs')): ?>
    <tr>
        <td class="left nowrap middle" width="126"></td>
        <td class="left nowrap top">
            <?= Form::checkbox("select_user_mode_lab[{$flexform_index}]", $controllab,
          I18N::T('entrance','实验室'),'class="middle checkbox monitor"', 'class="middle monitor"') ?>
        </td>
        <td>
            <div class="toggle:select_user_mode_lab[<?= $flexform_index ?>] show_on:on" style="display:none">
                <?= Widget::factory('entrance:rule_selector', [
          'name' => "lab[{$flexform_index}]",
          'autocomplete'=>URI::url('!entrance/autocomplete/labs'),
          'value'=> $controllab ? $controllab : null,
        ]); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="interval_6"></div>
        </td>
    </tr>
    <?php endif ?>
    <tr>
        <td class="left nowrap middle" width="126"></td>
        <td class="left nowrap top">
            <?= Form::checkbox("select_user_mode_group[{$flexform_index}]", $controlgroup,
          I18N::T('entrance','组织机构'),'class="middle checkbox monitor"', 'class="middle monitor"') ?>
        </td>
        <td>
            <div class="toggle:select_user_mode_group[<?= $flexform_index ?>] show_on:on" style="display:none">
                <?= Widget::factory('entrance:tag_selector',  [
          'name' => "group[{$flexform_index}]",
          'autocomplete'=>URI::url('autocomplete/groups'),
          'value'=> $controlgroup ? $controlgroup : null,
        ]); ?>
            </div>
        </td>
    </tr>
</table>