<div class="description">
	<?php if ( Module::is_installed('labs') ) : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Fill in the new user’s information.</span>
	</p>
	<?php else : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Please provide required information in order to add a new member.</span>
	</p>
	<?php endif; ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>


