<style type="text/css">ul{margin:0px;list-style:none;font-size:14px;}.top_text {font-size:14px;margin-left:42px;padding:4px;}li {list-style:none;padding: 4px;}</style>
<span style="font-size:14px"><?php echo date('F d, Y');?><span>
<div class="hr_1">&#160;</div>
<p style="font-size:18px"><b>尊敬的 <?php echo H($user->name);  ?>: </b></p>
<?php
	$base_url = Config::get('system.base_url');
	$str = URI::anchor($base_url, '实验室管理系统');
?>
<div>
	<div class="top_text">您好!</div>
	<div class="top_text">您的<?php echo $str; ?>更新如下:</div>
<div style="height:30px">&#160;</div>
<?php echo $body; ?>
</div>
<div class="hr_1">&#160;</div>
<div align='left' style="font-size:14px;">
	<div style="padding:5px">
		<b>基理科技</b>
	</div>
	<div style="padding:5px">
		<b>T: <?= Config::get('system.customer_service_tel_text'); ?>（<?= Config::get('system.customer_service_tel'); ?>）</b>
	</div>
	<div style="padding:5px">
		<b>W: <a href='www.geneegroup.com'>www.geneegroup.com</a></b>
	</div>
	<div style="padding:5px">
		<b>LabScout LIMS: Research Gets Easier!</b>
	</div>
</div>
