<?php
$me = L('ME');
$grantSelect = $form['fund_card_no'] ? : ($record->fund_card_no ? : 0 );
// 如果该使用记录关联了预约
if(!$grantSelect && $record->reserv->id) {
    $grantSelect = $record->reserv->fund_card_no ? : 0;
}
$user = $record->user->id ? $record->user : $me;
$grants = (array)Billing_Standard::get_grants($user);
$must_select_fund = Config::get('billing_standard.must_select_fund', 0) && !Event::trigger('billing_standard.not_must_select_fund', $user);
?>
<div>
    <table style="width: 370px">
        <tr>
            <td style="white-space: nowrap;">
                <?php if ($must_select_fund) echo "*";?><span><?= I18N::T('billing_standard', '经费卡号')?></span>
            </td>
            <td class="right">
                <?php echo Form::dropdown('fund_card_no', ['--'] + $grants, $grantSelect,
                'style="min-width: 294px;"'
                ); ?>
            </td>
        </tr>
    </table>
</div>