<div class="message_content clearfix relative">
	<table class="form flexible">
	<?php
	$me = L('ME');
	echo V('form_error', ['form'=>$form])
	?>
		<tr>

			<td width="130">
				<div class="icon-radius"><img src="<?php echo H($meeting->icon_url('100')) ?>" width="100"></div>
                <div class="interval_12"><div>
			</td>
			<td class="top">
				<h2>
					<a href="<?php echo H( URI::url('')) ?>"><?php echo H($meeting->name);?></a>
				</h2>
                <div class="interval_12">

                </div>
				<p>
					<?php echo I18N::T('meeting', '联系人')?>:
					<?php echo V('meeting:meeting_table/data/contacts', ['meeting' => $meeting]);?>
				</p>
				<?php
				if(!$me->is_allowed_to('修改', $meeting)
				&& $meeting->require_auth
				&& !ME_Reserv_Access::check_authorized($me, $meeting, false)) : ?>
					<p><?php echo V('auths/status', ['meeting'=>$meeting]); ?></p>
				<?php
				endif;
				?>
			</td>
            <td class="top right">
                <?php if ($me->is_allowed_to('修改', $meeting)) : ?>
                <div class="float_right">
        			<a class="button button_edit" href="<?php echo H( URI::url('!meeting/index/edit.'.$meeting->id)) ?>" title="<?php echo I18N::T('meeting', '修改');?>"><?php // echo I18N::T('meeting', '修改');?></a>
        		</div>
                <?php endif;?>
            </td>
		</tr>
	</table>
    <div class="interval_24_fixed interval_gray"></div>
    <div class="interval_24"></div>

    <div class='search_panel'>
    <?php
        echo $secondary_tabs->panel_buttons;
    	echo $secondary_tabs->search_box;
        
        echo $secondary_tabs->content->tertiary_tabs->panel_buttons;
        echo $secondary_tabs->content->tertiary_tabs->search_box;
        
        echo $search_box ?: $panel_buttons;
    ?>
    </div>
    <div class="tab_pagination">
    	<?php echo $secondary_tabs;?>
    </div>
<?php echo $secondary_tabs->content ?>
