<?php $me = L('ME');?>
<form class="edit" enctype="multipart/form-data" method="post" autocomplete="off" q-object="add_meterial" action="<?php echo H(URI::url('!notice/index') ) ?>">
    <?php echo V('form_error', ['form'=>$form]);?>
    <?php $require = (string) V('form_require', ['extra_class' => 'top']); ?>
    <?php $requires = Config::get('form.equipment_add')['requires']; ?>
    <table class="form">
        <tbody>
            <tr>
                <td class="label right nowrap middle"><span class="required">*</span><?= I18N::T('notice', '素材名称')?></td>
                <td class="top nowrap">
                    <input placeholder="请输入仪器名称" name="name" class="text" value="<?php echo H($form['name'])?>" />
                </td>
            </tr>
            <tr>
                <td class="label left nowrap middle"><span class="required">*</span><?php echo I18N::T('notice', '素材类型')?></td>
                <td class="top nowrap">
                    <?php 
                        $types = Material_Model::$TYPES;
                        foreach ($types as $key => $value) {
                            echo Form::radio('type', $key, (int)$form['type'], I18N::T('notice', $value), 'class="monitor radio"');
                            echo "&#160;&#160;";
                        }
                    ?>
                </td>
            </tr>
            <tr class="toggle:type show_on:0 hidden">
                <td class="label left nowrap top">&#160;&#160;&#160;&#160;<?php echo I18N::T('notice', '文本内容')?></td>
                <td class="top nowrap">
                   <textarea class="text autogrow autoselect" rows="6" cols="80" name="description"></textarea>
                </td>
            </tr>
            <tr class="toggle:type show_on:1 hidden">
                <td class="label left nowrap middle">&#160;&#160;&#160;&#160;<?php echo I18N::T('notice', '上传图片')?></td>
                <td class="top nowrap">
                    <input type="file" id="imageUpload" name="image" accept="image/*" />
                </td>
            </tr>
            <tr class="toggle:type show_on:2 hidden">
                <td class="label left nowrap middle">&#160;&#160;&#160;&#160;<?php echo I18N::T('notice', '上传视频')?></td>
                <td class="top nowrap">
                    <input type="file" id="video" name="video" accept="video/*" />
                </td>
            </tr>
        </tbody>
    </table>
    <div class="button_container">
        <div class="float_right">
            <input type="button" name="cancel" id="cancel" class="font-button-default sm rmargin_2e4" value="取消">
            <input type="submit" class="font-button-save sm" value="<?= I18N::HT('notice', '添加') ?>">
        </div>
    </div>
</form>
