<?php

$panel_buttons[] = [
    'url' => URI::url('!notice/index/add'),
    'tip'   => I18N::T('notice', '添加素材'),
    'text' => I18N::T('notice', '添加素材'),
    'extra' => 'q-object="add_meterial" q-event="click" class="button button_add" q-src="' . URI::url('!notice/index') . '"',
];

$table           = Widget::factory('table');
$table->name     = 'meterial';
$table->sort_asc = $sort_asc;
$table->sort_by  = $sort_by;

$columns = [
    'img'        => [
        'extra_class' => 'w80'
    ],
    'name'     => [
        'weight'   => 20,
        'title'    => I18N::T('notice', '素材名称'),
        'sortable' => true,
        'align'    => 'left',
        'nowrap'   => true,
        'filter'   => [
            'form'  => V('notice:search_filter/name', ['name' => $form['name']]),
            'value' => $form['name'] ? H($form['name']) : null,
            'field' => 'name',
        ],
    ],
    'type'   => [
        'weight' => 20,
        'title'  => I18N::T('notice', '素材类型'),
        'align'  => 'left',
        'nowrap' => true,
    ],
    'broadcast'   => [
        'weight' => 21,
        'align' => 'left',
        'title'  => I18N::T('notice', '素材播单')
    ],
    'user' => [
        'weight' => 30,
        'title'  => I18N::T('notice', '上传人'),
        'align'  => 'left',
        'nowrap' => true,
    ],
    'ctime'   => [
        'weight' => 25,
        'title'  => I18N::T('notice', '上传时间'),
        'align'  => 'left',
        'nowrap' => true
    ],
    'rest'     => [
        'title'  => I18N::T('notice', '操作'),
        'align'  => 'right',
        'weight' => 30,
    ]

];

foreach ($materials as $material) {
    $links = $material->links();
    $row = [
        'img'   => V('material/table/data/cover', ['material' => $material]),
        'name'  => H($material->name),
        'type'  => Material_Model::$TYPES[$material->type],
        'broadcast' => V('material/table/data/broadcast', ['material' => $material]),
        'user' => $material->user->id ? $material->user->name : '--',
        'ctime' => Date::format($material->ctime),
        'rest' => Widget::factory('application:links', ['links' => $links])
    ];
    $table->add_row($row);
}

$table->add_columns($columns);
$table->empty_message = I18N::T('meeting', '没有素材信息');

$param = [
    'panel_buttons'     => $panel_buttons,
    'top_input_arr' => ['name', 'ref_no'],
    'columns'       => $table->columns,
    'extra_view'    => '<div class="adj statistics middle">'.$pagination.'</div>'
];
echo V('application:search_box', $param);

echo $table;

?>
<div class="pages"><?= $pagination; ?></div>