<?php 
switch($status) {
case Stock_Model::INADEQUATE:
	$class='warning';
	break;
case Stock_Model::EXHAUSTED:
	$class='error';
	break;
case Stock_Model::ADEQUATE:
	$class='normal';
	break;
default:
	$class='disable';
}
?>
<a href="<?php echo H(URI::url('!inventory/index?status='.$status)) ?>" class="status_tag status_tag_<?php echo $class?>" style="min-width: 30px;">
<?php echo I18N::HT('inventory', Stock_Model::$stock_status[$status]); ?>
</a>
