<tr>
    <td colspan="2" class="left nowrap category">
        <b><?php echo I18N::T('eq_sample', '测样要求');?></b>
    </tr>
</tr>
<?php if ($results) foreach ($results as $result) :?>
<tr>
    <td class="left nowrap">
        <div class="holder">&#160;</div>
        <?php echo I18N::T('eq_sample', '样品编码');?>
    </td>
    <td class="left nowrap">
        <?php echo $result->subname; ?>
    </td>
</tr>
<tr>
    <td class="left nowrap">
        <div class="holder">&#160;</div>
        <?php echo I18N::T('eq_sample', '检测参数');?>
    </td>
    <td class="left nowrap">
        <?php echo $result->parameter; ?>
    </td>
</tr>
<tr>
    <td class="left nowrap">
        <div class="holder">&#160;</div>
        <?php echo I18N::T('eq_sample', '浓度范围');?>
    </td>
    <td class="left nowrap">
        <?php echo $result->concentration; ?>
    </td>
</tr>
<tr>
    <td class="left nowrap">
        <div class="holder">&#160;</div>
        <?php echo I18N::T('eq_sample', '结果要求等级');?>
    </td>
    <td class="left nowrap">
        <?php echo $result->level; ?>
    </td>
</tr>
<tr>
    <td class="left nowrap">
        <div class="holder">&#160;</div>
        <?php echo I18N::T('eq_sample', '测样结果');?>
    </td>
    <td class="left nowrap">
        <?php echo $result->result; ?>
    </td>
</tr>
<tr>
    <td colspan="2" class="left nowrap category">
    </tr>
</tr>
<?php endforeach; ?>