<?php
$code_id = 'access_code_'.uniqid();
$auth_code = str_pad(mt_rand(0, 999999), 6, STR_PAD_LEFT);
$cache = Cache::factory('redis');
$cache->set('equipment_auth_code_' . $auth_code, $equipment->id, 15 * 60);
?>
<span id="<?php echo H($code_id) ?>">
	<span id="auth_code" style="color: #666;" class="float_left label middle"><?php echo H($auth_code);?></span>
    <a style="margin-left:4px" class="font-button-icon button_refresh float_right middle view object:auth_code_refresh event:click static:<?php echo H(['equipment_id'=>$equipment->id, 'code_id'=>$code_id]);?>" style="text-decoration: none;margin-left: 10px;">
        <span class="fa fa-refresh"></span>
		<?php echo I18N::HT('equipments', '重新生成授权码');?>
	</a>
</span>

<script type="text/javascript">
    $().ready(function() {
        setTimeout(() => {
            $("#<?= $code_id?> #auth_code").addClass("access_code_expired");
        }, 1000 * 15 * 60);
    });
</script>
