<?php
	$control_uniqid = 'control_id_'. uniqid();
?>
<div class="equipment_detail clearfix" id="<?php echo $control_uniqid; ?>" style="position: relative;">
<table class="form flexible">
<tbody>
<tr>
	<td class="top icon interval" rowspan="2" style="position: relative;">
		<?= V('equipment/view/icon', ['equipment' => $equipment, 'id' => $control_uniqid]); ?>

		<div class="clearfix"></div>

		<?php if($equipment->status != EQ_Status_Model::NO_LONGER_IN_SERVICE):?>
			<?php echo V('equipment/control', ['equipment'=>$equipment]); ?>
		<?php endif ?>
	</td>

	<?php $is_admin = L('ME')->is_allowed_to('管理培训', $equipment); ?>
	<td class="top nowrap info flexible" rowspan="2">
		<?php if (!$equipment->is_mirror): ?>
		<h2>
		<a href="<?php echo H($equipment->url() ) ?>" style="padding-right: 30px;">
			<?php echo H($equipment->name . ' ' . $equipment->en_name); ?>
		</a>
        <div class="equipment-status-inservice">
		<?php if ($equipment->status == 0) : ?>
			<span style="font-size: 12px" class="right icon-selected"></span>
		<?php endif; ?>
		<small class="<?php if ($equipment->status == 0): ?>right<?php endif; ?>"><?php echo I18N::T('equipments', EQ_Status_Model::$status[$equipment->status]); ?></small>
        </div>
        </h2>
		<div style="height: 20px;"></div>
		<p><?php if($equipment->status != EQ_Status_Model::NO_LONGER_IN_SERVICE): ?>
			<span style="display: inline-block; width: 50%;"><?php echo I18N::T('equipments', '联系人')?>
				<?php echo V('equipments:equipments_table/data/contacts', ['equipment'=>$equipment]);?>
			</span>
			<?php if ($equipment->phone) :?>
			<span class="rpadding_1"><?php echo I18N::T('equipments', '联系电话')?></span><span class="adjust_font"><?php echo H($equipment->phone);?></span>
			<?php endif;?>
		</p>
		<?php if ($equipment->require_training && !$is_admin) : ?>
			<p><?php echo V('training/status', ['equipment'=>$equipment]); ?></p>
			<?php endif; ?>
        <?php endif; ?>

		<p>
        <?php if ($equipment->email) :?>
            <span style="display: inline-block; width: 50%;" ><?php echo I18N::T('equipments', '邮箱')?><span class="lpadding_1"><?php echo URI::mailto($equipment->email)?></span></span>
        <?php endif;?>
		<?php if ($GLOBALS['preload']['tag.group_limit'] >= 0 && $equipment->group->id): ?>
            <span class="rpadding_1"><?php echo I18N::T('equipments', '所属单位')?></span>
			<?php echo V('application:tag/path', ['tag'=>$equipment->group, 'tag_root'=>$equipment->group->root, 'url_template'=>URI::url('!equipments/index','group_id=%tag_id')]) ?>
		<?php endif ?>
        <?php if (Module::is_installed('db_sync') && DB_SYNC::is_module_unify_manage()) : ?>
            <div class="hr_1">&#160;</div>
            <span><?php echo H('所属站点') ?></span>: <?php echo H(Config::get('site.map')[$equipment->site]); ?>
        <?php endif; ?>
		<?php
			// 此处视图由于会做聚合运算 影响性能 故做一部分缓存
			$cache = Cache::factory();
			$brief = $cache->get("equipment.brief.view.{$equipment->id}");
			if (!$brief) {
				$brief = (string)V('equipments:equipment/brief', ['equipment'=> $equipment]);
				$cache->set("equipment.brief.view.{$equipment->id}", $brief, 3600);
			}
			echo $brief;
		?>
		<?php else: ?>
		<?php echo V('equipments:equipment/mirror.info', ['equipment'=>$equipment])?>
		<?php endif;?>
		<div style="height: 12px;"></div>
	</td>
    <td class="top right">
        <?php
        $links = $equipment->links('view') + L('ME')->follow_links($equipment,'view');
        ?>
        <div class="float_right" style="width: 300px">
			<?php
            echo Widget::factory('application:links', ['links' => $links, 'separator'=>' ']) ?>
		</div>
    </td>
</tr>
<tr>
    <td class="right bottom">
        <div class="float_right" style="position: relative;width: 100px;height: 100px;margin-bottom: 12px;">
        <?php echo Event::trigger('equipment.profile.extra_view', $equipment);?>
        </div>
    </td>
</tr>

</tbody>
</table>
    <div class="tab_pagination" style="height: auto;border-bottom: 0px;">
        <?php echo $secondary_tabs;?>
    </div>
</div>


<div class="interval_24_fixed interval_gray"></div>
<div class="interval_24"></div>

<div class='search_panel' <?php if (!$secondary_tabs->search_box && !$secondary_tabs->panel_buttons) echo 'style="display:none"';?>>
    <div class="interval_16"></div>
    <?= $secondary_tabs->search_box ?>
    <?= $secondary_tabs->panel_buttons ?>
</div>
<?php
	echo $secondary_tabs->content;
?>
<?php // echo $secondary_tabs ?>
<?php // echo $secondary_tabs->content ?>
<?php
$me = L('ME');
$aid = $_SESSION['force_read_'.$equipment->id.'_'.$me->id];
if($aid):?>
<script type="text/javascript">
  $(function () {
    Q.trigger({
      object:'view_announce',
      event:'click',
      data:{
        a_id:<?= $aid?>,
      },
      url:'<?php echo URI::url("!equipments/announce")?>'
    });
  })
</script>
<?php endif;?>
