<?php
/**
* edit_title.phtml
* 模块修改页面中的修改标题(例：仪器1 > 修改)
*
* @author: Clh  lianhui.cao@geneegroup.com
* @time: 2018-09-17 17:43:37
**/
?>

<div class="edit_title">
    <div class="name">
        <a class="float_left" href="<?php echo $url; ?>"><?php echo $name; ?></a>
        <span class="angle-right float_left icon-right"></span>
        <span class="modify">修改</span>

        <a href="<?php echo $url; ?>" title="关闭修改" class="close float_right fa fa-close angle-right"></a>
    </div>
</div>
