<div class="login-content" style="height: 490px;
    max-width: 1066px;
    margin-right: auto;
    margin-left: auto;
    margin-top: calc((100vh - 470px) / 3);
	box-shadow: 0 5px 5px -3px rgba(0, 0, 0, 0.15), 0 8px 10px 1px rgba(0, 0, 0, 0.14), 0 3px 14px 2px rgba(0, 0, 0, 0.12);">
	<div class="right-image-box" style="height: 100%;
    width: 50%;
    float: right;">
		<img src="<?= _C('images/loginbg.jpeg') ?>" style="height: 100%; width: 100%">
	</div>
	<div class="left-form-box  no-captcha-challenge" style="text-align: center;
	background-color: var(--basiccolor);
	height: 100%;
	width: 50%;">
		<div style="background-color: var(--basiccolor);">
            <?php echo V('application:login_form', $this->vars); ?>
		</div>
	</div>
</div>

