<div class="top_sidebar_shortcuts">
    <!-- 先加载原先sidebar中的快捷方式 -->
    <?php
        $allshortcuts = Config::get('lab.shortcuts');
        if (count($allshortcuts) > 0) {
            ksort($allshortcuts);
            foreach ($allshortcuts as $key => $shortcuts) {
                foreach ((array) $shortcuts as $key => $shortcut) {
                    $items = [];
                    foreach ((array)$shortcut as $item) {
                        $output1 = (string)(V($item));
                        if ($output1) $items[] = $output1;
                    }
                    if (count($items)) {
                        $output = (string)V("sidebar/shortcuts_menu",[
                                "key" => $key, 
                                "shortcuts" => $items
                        ]);
                        $outputs[] =  $output;
                    }
                }
            }
        }
        if (Switchrole::user_select_role() == '普通用户' && !in_array(L('ME')->token, Config::get('lab.admin', []))) $outputs = [];
        if (count($outputs) > 0):
    ?>
        <div class="shortcut_extra_title">快捷链接</div>
        <div class="shortcut_fields">
            <?php foreach ($outputs as $output): ?>
                <div class="shortcut_menu"><?= $output ?></div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<div class="vertical_separator"></div>

<?php
	$me = L('ME');
	if ($me->id):
		$uniqid = 'sbmenu_'.uniqid(); 
?>
<div id="<?php echo H($uniqid) ?>" class="top_sidebar_menu">
<?php
    $ct_items = SBMenu_Widget::categorized_items($me);
    $hidden_count = 0;

    $view_name = 'application:sidebar/menu/list';
    $show_hidden_class = 'list_item_show_hidden';
    foreach ((array) $ct_items as $name => $items):
        $content = '';
        $count = 0;
        $subMods = [];
        $moreMods = [];
        foreach ((array) $items as $id => $item) {
            $userlistSwitch = Lab::get('people.userlistswitch.token');
            $lablistSwitch = Lab::get('people.lablistswitch.token');
            if ($id == 'people') {
                if ($userlistSwitch === '0' && !$me->access('管理所有内容')) {
                    continue;
                }
                if (!$me->access('查看成员列表')) {
                    continue;
                }
            }
            if ($id == 'labs') {
                if ($lablistSwitch === '0' && !$me->access('管理所有内容')) {
                    continue;
                }
                if (!$me->access('查看所有实验室')) {
                    continue;
                }
            }
            $subMods[] = $id;
            $mid = $item['#module'] ?: $id;
            if ($mid != $id) $moreMods[] = $id;
            if (!Module::is_accessible($mid)) continue;
            if ($mid != $id && !Module::is_accessible($mid, $id))  continue;
            $checked = $item['#checked'];
            $class = '';
            if (!$checked) {
                $class .= ' item_hidden';
                if ($_SESSION['sbmenu_show_hidden'] == TRUE) {
                    $class .= ' '.$show_hidden_class;
                }
                $hidden_count ++;
            }
            $item = $item['list'];
            if (!$item['i18n']) $item['i18n'] = $mid;
            $content .= trim((string) V($view_name, ['item'=>$item, 'class'=>$class, 'id'=>$id]));
            $count ++;
        }
        if ($count == 0) {
            continue;
        }

        if ($name == '@others') {
            if (count($ct_items) == 1) $hide_category_title = TRUE;
            $name = T('其他');
        }
        echo V('application:sidebar/menu/category', [
            'name' => $name, 
            'content' => $content, 
            'hide_category_title' => $hide_category_title,
            'subMods' => $subMods, 
            'moreMods' => $moreMods,
            'items' => $items
        ]);
        
    ?>
    <?php endforeach; ?>
        <?php echo JS::load('application:sbmenu', ['menu_id'=> $uniqid, 'ajax_url'=>URI::url('admin'), 'mode'=>$mode]); ?>
    </div>
<?php endif;?>