<?php echo V('application:top_menu/gohome'); ?>
<div class="sidebar_shortcuts float_left">
    <!-- 先加载原先sidebar中的快捷方式 -->
    <?php
    $allshortcuts = Config::get('lab.shortcuts');
    if (count($allshortcuts) > 0) {
        ksort($allshortcuts);
        foreach ($allshortcuts as $key => $shortcuts) {
            foreach ((array) $shortcuts as $key => $shortcut) {
                $items = [];
                foreach ((array)$shortcut as $item) {
                    $output1 = (string)(V($item));
                    if ($output1) $items[] = $output1;
                }
                if (count($items)) {
                    $output = (string)V("sidebar/shortcuts_menu",
                        ["key" => $key, "shortcuts" => $items]);
                    $outputs[] =  $output;
                }
            }
        }
    }
    if (Switchrole::user_select_role() == '普通用户' && !in_array(L('ME')->token, Config::get('lab.admin', []))) $outputs = [];

    // if (count($outputs) > 0) echo '<div class="shortcut shortcut_first">' . $outputs[0] . '</div>';
    // if ($outputs) array_shift($outputs);

    if (count($outputs) > 0) {
        echo '<div class="shortcut_extra right_content">';
        echo '<div class="shortcut shortcut_extra_title right_content_title">快捷</br>链接</div>';
        echo '<div class="shortcut_extra_fields right_content_menu">';
        foreach ($outputs as $output) {
            echo '<div class="shortcut_menu right_shortcut">' . $output . '</div>';
        }
        echo '</div>';
        echo '</div>';
    }
    ?>

</div>


<?php echo V('application:top_menu/contact'); ?>

<div class="top_menu_item" style="height:auto;line-height:inherit">
    <a class="link"><?php echo I18N::T('people', '语言')?></a>
    <?php echo Form::dropdown('top_locale', Config::get('system.locales'), $me->locale ?: Config::get('system.locale'), 'class="middle"', 'class="middle"');?>
</div>

<?php $tip = V('tip');
$me = L('ME');
$token = Auth::token();
if ((string) $tip):
	$tip_id = 'tips_'.uniqid();
?>
<!-- 行级元素后面不加换行 Clh -->
<div class="top_menu_item">
    <?php if ($me->id && false): ?>
        <a class="fa icon-user" href="<?php echo H($me->url('', NULL, NULL, 'edit') ) ?>" title="<?php echo I18N::HT('people', '个人中心'); ?>"></a>
    <?php endif; ?>
    <a class="fa icon-tips <?php echo $tip->is_hidden ?'':'link_fade'?>" href="#" onclick="(function($,t){$(t).toggle();$(this).toggleClass('link_fade');}).apply(this, [jQuery, '#<?php echo $tip_id?>']); return false;" title="<?php echo HT('提示')?>"></a>
	<div id="<?php echo H($tip_id)?>" class="tip <?php echo $tip->is_hidden ?'hidden':''?>">
		<?php echo $tip ?>
	</div>
</div>
<?php endif; ?>

<?php if (Config::get('layout.public_url')): ?>
    <div class="top_menu_item">
	    <a href="<?php echo 'http://' . $_SERVER['HTTP_HOST'].Config::get('layout.public_url') ?>" class="link"><?php echo T('返回前台');?></a>
    </div>
<?php endif;?>

<div class="top_menu_item">
<?php
if ($me->id || $token): ?>
<?php if ($me->id): ?>
    <a class="fa icon-setting" href="<?php echo H(URI::url('admin')) ?>" title="<?php echo HT('系统设置')?>"></a>
<?php endif; ?>
    <!-- <a class="fa icon-power" href="<?php // echo H(URI::url(Config::get('system.logout_path', 'logout')) ) ?>" title="<?php // echo HT('退出')?>"></a> -->
    <a class="fa icon-avatar"><?php echo $me->icon('24.5') ?>
        <span style="height:24px;line-height:24px;text-align:center;padding-left:5px;font-size:14px;font-family:PingFangSC-Regular,PingFang SC;font-weight:400;color:#B8B8B8;"><?=HT(Switchrole::user_select_role())?></span>
        <span style="color: #B8B8B8; padding-left: 5px;" class="icon icon-drop_down"><span>
    </a>
    <ul class="extra-list">
        <li><a href="<?= H($me->url('', NULL, NULL, 'edit') ) ?>">个人信息</a></li>
        <li><a id="switch_role" q-object="switch_role" q-event="click" q-src="<?=URI::url('!people/switchrole') ?>">切换角色</a></li>
        <li class="switch_default_role_ul"><a id="switch_default_role">默认角色</a></li>
        <li><a href="<?php echo H(URI::url(Config::get('system.logout_path', 'logout')) ) ?>">退出登录</a></li>
    </ul>
    <?php $role_list = $me->get_switch_role(); ?>
    <ul class="switch_default_role_ul">
        <?php foreach ($role_list as $role_name => $role_id) : ?>
        <li>
            <a q-object="switch_default_role" q-event="click" q-src="<?= URI::url('!people/switchrole') ?>" q-static="role_name=<?= $role_name ?>" >
                <?php echo Form::radio('default_role', $role_name, $me->input_user_select_role,  H($role_name), 'class="monitor radio middle"', 'class="middle"'); ?>
                <!-- <?= H($role_name) ?> -->
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <a class="fa link link_login" href="<?php echo H(URI::url('login')) ?>"><?php echo HT('登录')?></a>
<?php endif; ?>
</div>

<script>
jQuery(function($){
	var selector = $("select[name=top_locale]");
	selector.change(function() {
		save_language_change($(this).val());
	})

	function save_language_change(val) {
		Q.trigger({
			object: 'save_language',
			event: 'change',
			url: '<?php echo URI::url($slave_host.'index')?>',
			global: false,
			data: {
				language: val
			},
			success : function(data, status, xhr) {
                window.location.reload();      
            }
        });
	}
})
</script>
