<?php echo V('application:top_menu/gohome'); ?>

<?php // echo V('application:top_menu/contact'); ?>

<div class="top_menu_item" style="height:auto;line-height:inherit">
    <?php echo Form::dropdown('top_locale', Config::get('system.locales'), $me->locale ?: Config::get('system.locale'), 'class="middle"', '');?>
</div>
<style>
.dropdown_container {
    width: auto;
}
</style>

<?php $tip = V('tip');
$me = L('ME');
$token = Auth::token();
if ((string) $tip):
	$tip_id = 'tips_'.uniqid();
?>
<!-- 行级元素后面不加换行 Clh -->
<div class="top_menu_item">
    <?php if ($me->id && false): ?>
    <a class="fa icon-user" href="<?php echo H($me->url('', NULL, NULL, 'edit') ) ?>"
        title="<?php echo I18N::HT('people', '个人中心'); ?>"></a>
    <?php endif; ?>
    <a class="fa icon-tips <?php echo $tip->is_hidden ?'':'link_fade'?>" href="#"
        onclick="(function($,t){$(t).toggle();$(this).toggleClass('link_fade');}).apply(this, [jQuery, '#<?php echo $tip_id?>']); return false;"
        title="<?php echo HT('提示')?>"></a>
    <div id="<?php echo H($tip_id)?>" class="tip <?php echo $tip->is_hidden ?'hidden':''?>">
        <?php echo $tip ?>
    </div>
</div>
<?php endif; ?>

<?php if (Config::get('layout.public_url')): ?>
<div class="top_menu_item">
    <a href="<?php echo 'http://' . $_SERVER['HTTP_HOST'].Config::get('layout.public_url') ?>"
        class="link"><?php echo T('返回前台');?></a>
</div>
<?php endif;?>

<div class="top_menu_item">
    <?php if ($me->id || $token): ?>
        <?php if ($me->id): ?>
            <a class="fa icon-setting" href="<?php echo H(URI::url('admin')) ?>" title="<?php echo HT('系统设置')?>"></a>
        <?php endif; ?>
        <!-- <a class="fa icon-power" href="<?php // echo H(URI::url(Config::get('system.logout_path', 'logout')) ) ?>" title="<?php // echo HT('退出')?>"></a> -->
        <a class="fa icon-avatar">
            <?php echo $me->icon('24.5') ?>
            <span
                style="height:24px;line-height:24px;text-align:center;padding-left:5px;font-size:14px;font-family:PingFangSC-Regular,PingFang SC;font-weight:400;color:#FFF;"><?=HT(Switchrole::user_select_role())?></span>
            <span style="color: #FFF; padding-left: 5px;" class="icon icon-drop_down"><span>
        </a>
        <ul class="extra-list">
            <li><a href="<?= H($me->url('', NULL, NULL, 'edit') ) ?>">个人信息</a></li>
            <li><a id="switch_role" q-object="switch_role" q-event="click"
                    q-src="<?=URI::url('!people/switchrole') ?>">切换角色</a></li>
            <li class="switch_default_role_li">
                <a id="switch_default_role">默认角色</a>
                <?php $role_list = $me->get_switch_role(); ?>
                <ul class="switch_default_role_ul">
                    <?php foreach ($role_list as $role_name => $role_id) : ?>
                    <li>
                        <a q-object="switch_default_role" q-event="click"
                            q-src="<?= URI::url('!people/switchrole') ?>"
                            q-static="role_name=<?= $role_name ?>">
                            <?php echo Form::radio('default_role', $role_name, $me->input_user_select_role,  H($role_name), 'class="monitor radio middle"', 'class="middle"'); ?>
                            <!-- <?= H($role_name) ?> -->
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li><a href="<?php echo H(URI::url(Config::get('system.logout_path', 'logout')) ) ?>">退出登录</a></li>
        </ul>
    <?php else: ?>
        <a class="fa link link_login" href="<?php echo H(URI::url('login')) ?>"><?php echo HT('登录')?></a>
    <?php endif; ?>
</div>

<script>
jQuery(function($) {
    var selector = $("select[name=top_locale]");
    selector.change(function() {
        save_language_change($(this).val());
    })

    function save_language_change(val) {
        Q.trigger({
            object: 'save_language',
            event: 'change',
            url: '<?php echo URI::url($slave_host.'index')?>',
            global: false,
            data: {
                language: val
            },
            success: function(data, status, xhr) {
                window.location.reload();
            }
        });
    }
})
</script>