<?php if ($charge->confirm != EQ_Charge_Confirm_Model::CONFIRM_INCHARGE): ?>
<?php 
    $arr = $_SESSION['check_confirm_select'] ? : []; 
    if (isset($arr[$charge->id]) ) {
        $checked = 'checked';
    } else {
        $checked = '';
    }
?>
<input name="select[]" class="<?php echo H($select_all_id) ?>" type="checkbox" <?php echo $checked;?> value="<?php echo $charge->id; ?>" style="padding:0; margin:0"/>
<?php endif;?>
