<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('eq_reserv', '预约情况报表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
			color:blue;
			text-decoration:underline;
			}
			table.report {

			font-size: 14px;
			margin:auto;
			}
			table .time {
			font-size: 16px;
			}

			thead{
			border-top:2px solid  #000;
			border-bottom:1px solid #000;
			}

			tbody{
			border-bottom:2px solid #000;
			}

			thead#stat{
			font-size: 10px;
			border:none;
			}

			table.report caption {
			font-size: 150%;
			margin-bottom: 10px;
			}

			table.report tbody td {
			vertical-align: top;
			border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
			background-color: #eee;
			border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
			display:none;
			}
		</style>
	</head>

	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('eq_reserv', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::T('eq_reserv', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption><?php echo I18N::T('eq_reserv', '预约情况报表'); ?></caption>
			<thead>
				<tr>
					<?php foreach ($valid_columns as $key => $value) :?>
                        <th class="left nowrap"><?php echo I18N::T('eq_reserv', $value); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
				<?php
                    foreach ($components as $component) :
                        if ($component->name() == 'eq_reserv') {
                            $component = $component->component;    
                        }
                        $calendar = $component->calendar;
                        $equipment = NULL;
                        if ($calendar->parent->name() == 'equipment') {
                            $equipment = $calendar->parent;
                        }
						$eq_reserv = O('eq_reserv', ['component' => $component]);
                ?>
				<tr>
					<?php if (array_key_exists('equipment', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($equipment->name).Event::trigger('extra.equipment.name', $equipment); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('eq_ref_no', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($equipment->ref_no); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('eq_cf_id', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($equipment->id); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('eq_group', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($equipment->group->name); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('organizer', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($component->organizer->name); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('email', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($component->organizer->email); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('phone', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($component->organizer->phone); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('group', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($component->organizer->group->name); ?></td>
					<?php endif; ?>
					<?php if (array_key_exists('lab', $valid_columns)): ?>
					<td class="left nowrap"><?php 
						$lab = $eq_reserv->project->lab->id ?
								$eq_reserv->project->lab :
								Q("{$component->organizer} lab")->current();
						echo H($lab->name);
					?></td>
					<?php endif; ?>
					<?php if (array_key_exists('time', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H(Date::format($component->dtstart, 'Y/m/d H:i:s'). ' - '. Date::format($component->dtend, 'Y/m/d H:i:s'));?></td>
					<?php endif; ?>
					<?php if (array_key_exists('duration', $valid_columns)): ?>
					<td class="left nowrap"><?php echo I18N::T('eq_reserv', '%duration小时', [
                        '%duration'=> round(($component->dtend - $component->dtstart) / 3600, 2)]);?></td>
					<?php endif; ?>
					<?php if (array_key_exists('reserv_type', $valid_columns)){  
                        $ctype = $component->type;
                        if ($ctype == Cal_Component_Model::TYPE_VEVENT) {
                    ?>
                    <td class="left nowrap"><?php echo I18N::T('eq_reserv', '预约');?></td>
                    <?php } elseif ($ctype == Cal_Component_Model::TYPE_VFREEBUSY) { ?>
                    <td class="left nowrap"><?php echo I18N::T('eq_reserv', '非预约时段');?></td>
                    <?php } ?>
					<?php } ?>
                    <?php if (array_key_exists('count', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($eq_reserv->count);?></td>
					<?php endif; ?>
					<?php if (array_key_exists('description', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H($component->description);?></td>
					<?php endif; ?>
					<?php if (array_key_exists('status', $valid_columns)): ?>
					<td class="left nowrap"><?php echo H(EQ_Reserv_Model::$reserv_status[$eq_reserv->get_status()]);?></td>
					<?php endif; ?>
                    <?php if(array_key_exists('university', $valid_columns)): ?>
                    <td class="right nowrap">
                        <?php echo Config::get('university.list')[$eq_reserv->source_name];?>
                    </td>
                    <?php endif; ?>
                    <?php if (array_key_exists('site', $valid_columns)): ?>
					    <td class="left nowrap"><?php echo H(Config::get('site.map')[$eq_reserv->equipment->site]); ?>></td>
					<?php endif; ?>
                    <?php
                    //自定义的输出项
                    $data_custom = Event::trigger('calendar.export_list_csv', $eq_reserv, $data, $valid_columns);
                    if(is_array($data_custom)) foreach ($data_custom as $key => $value) :?>
                    <td class="left nowrap">
                        <?php echo $value;?>
                    </td>
                    <?php endforeach;?>
				</tr> 
				<?php endforeach; ?>
			</tbody>
		</table>
	</body>
</html>
