<?php
$type = $project ? $project->type : (int) $type;
$PREFIX = "project[$type][$flexform_index]";
$form = $form[$flexform_index];
?>
<table class="form">
<tbody>
	<tr>
		<td class="label middle nowrap" width="70">
			<?php echo I18N::T('labs', '名称'); ?>
		</td>
		<td class="middle nowrap">
			<input type="hidden" name="<?php echo $PREFIX ?>[id]" value="<?php echo H($project->id) ?>" />
			<input type="text" class="text"
				value="<?php echo H($form['name'] ? : $project->name);?>"
				name="<?php echo $PREFIX ?>[name]"
			/>
		</td>
        <td colspan="3"></td>
    </tr>
    <tr><td colspan="5"><div class="interval_20"></div></td></tr>
    <tr>
        <td class="label middle nowrap" width="70">
            <?php echo I18N::T('labs', '教材'); ?>
        </td>
		<td class="middle nowrap">
            <?php echo Form::radio("{$PREFIX}[book_type]", 1, $form['book_type']? : $project->book_type,
                I18N::T('labs','自编'), ' class="middle radio"', 'class="middle rmargin_152_i"'); ?>
            <?php echo Form::radio("{$PREFIX}[book_type]", 0, $form['book_type']? : $project->book_type,
                I18N::T('labs','购买'), ' class="middle radio"', 'class="middle"'); ?>
		</td>
        <td class="table_interval"></td>
        <td class="label middle nowrap" width="126">
            <?php echo I18N::T('labs', '教材名称'); ?>
        </td>
		<td class="middle nowrap">
			<input type="text" class="text hint:<?php echo I18N::T('labs','教材名称');?>"
				value="<?php echo H($form['textbook'] ? : $project->textbook);?>"
				name="<?php echo $PREFIX?>[textbook]"/>
		</td>
	<tr>
    <tr><td colspan="5"><div class="interval_20"></div></td></tr>
    <tr>
        <td class="label middle nowrap">
            <?php echo I18N::T('labs', '负责人');?>
        </td>
        <td class="middle nowrap">
            <input type="text" class="text"
                value="<?php echo H($form['incharge'] ? : $project->incharge);?>"
                name="<?php echo $PREFIX?>[incharge]" />
        </td>
        <td class="table_interval"></td>
        <td class="label middle nowrap">
            <?php echo I18N::T('labs', '类别');?>
        </td>
        <td class="middle nowrap">
            <input type="text" class="text"
                value="<?php echo H($form['ptype'] ? : $project->ptype);?>"
                name="<?php echo $PREFIX?>[ptype]" />
        </td>
    </tr>
    <tr><td colspan="5"><div class="interval_20"></div></td></tr>

    <tr>
        <td class="label middle nowrap">
            <?php echo I18N::T('labs', '经费');?>
        </td>
        <td class="middle nowrap">
            <input type="text" class="text"
                value="<?php echo H($form['grant'] ? : $project->grant);?>"
                name="<?php echo $PREFIX?>[grant]" />
        </td>
        <td class="table_interval"></td>
		<td class="label middle nowrap">
			<?php echo I18N::T('labs', '人数'); ?>
		</td>
		<td class="middle nowrap">
			<input type="text" class="text"
				value="<?php echo H($form['student_count'] ? : $project->student_count); ?>"
				name="<?php echo $PREFIX?>[student_count]"/>
		</td>
	<tr>
    <tr><td colspan="5"><div class="interval_20"></div></td></tr>

	<tr>
		<td class="label middle nowrap">
			<?php echo I18N::T('labs', '起始时间'); ?>
		</td>
		<td class="middle nowrap">
            <?php
                $dtstart = $form['dtstart'] ? : $project->dtstart;
                $dtstart = $dtstart ? date('Y-m', $dtstart) : '';
            ?>
			<input class="text date" date_type="month"
				value="<?php echo $dtstart; ?>"
				name="<?php echo $PREFIX?>[dtstart]" />
		</td>
        <td class="table_interval"></td>
        <td class="label middle nowrap">
			<?php echo I18N::T('labs', '结束时间'); ?>
		</td>
        <td class="middle nowrap">
            <?php
                $dtend = $form['dtend'] ? : $project->dtend;
                $dtend = $dtend ? date('Y-m', $dtend) : '';
            ?>
			<input class="text date" date_type="month"
				value="<?php echo $dtend; ?>"
				name="<?php echo $PREFIX?>[dtend]" />
		</td>
	<tr>
    <tr><td colspan="5"><div class="interval_30"></div><hr><div class="interval_30"></div></td></tr>

</tbody>
</table>
<input type="hidden" value="<?php echo $project->id; ?>"/>
