<div class="todo_task_view check_hover">
<div>
<?php
$me = L('ME');
$editable = $task->is_editable();
?>
	<span class="panel panel_uniqid"><?php echo Number::fill($task->id, 6)?></span>
<a class="task_link task_link_editable" href="<?php echo H($task->url()) ?>"><?php echo H($task->title) ?></a>
<?php if ($task->status): ?>
<span class="job_status job_status_<?php echo $task->status; ?>">
	<?php echo H(TN_Task_Model::$status_short_options[$task->status]) ?>
</span>
<?php endif; ?>

<span class="description small"><?php echo Date::fuzzy($task->mtime, TRUE); ?></span>

<?php if ($task->expected_time): ?>
&#160;&#160;
<span class="description"><?php echo I18N::HT('treenote', '预计耗时'); ?></span>
<strong><big><?php echo round($task->expected_time / 3600, 1); ?></big></strong> hr
<?php endif; ?>

<?php	
$progress = $task->progress();
if ($progress['all'] > 0):
$percent = round(100 * $progress['complete'] / $progress['all']);
?>
&#160;&#160;
<span class="description"><?php echo I18N::HT('treenote', '完成度'); ?></span>
<strong><big><?php echo H($percent.'%'); ?></big></strong>
<span> ( <?php echo $progress['complete'] . ' / ' . $progress['all'];?> )</span>
<?php endif; ?>

&#160;&#160;
<span class="nowrap show_on_hover">
	<?php echo Widget::factory('application:links', ['links'=>$task->links('index'), 'separator'=>' ']); ?>
</span>
</div>

<?php if ($task->reviewer->id): ?>
<div class="hr_1">&#160;</div>
<span class="description"><?php echo I18N::HT('treenote', '评审人') ?></span>
<strong><?php $task->reviewer->render(); ?></strong>
<?php endif;?>
<div class="hr_1">&#160;</div>
<?php if($task->is_locked) : ?>
<?php if ($me->is_allowed_to('清除锁定', $task) && !$task->is_complete) :?>
	<a class="button button_unlocked" q-object="clean_lock" q-event="click" q-static="<?php echo H(['id' => $task->id, 'type' => $task->name()]) ?>" q-src="<?php echo H(URI::url('!treenote/index') ) ?>"><?php echo I18N::T('meeting', '清除锁定')?></a>
<?php endif; ?>
<div>
<div class="hr_1">&#160;</div>
<?php
	$tn_lockers = Q("tn_locker[task={$task}]");
	foreach ($tn_lockers as $tn_locker) : ?>
<div>
<?php 
		echo I18N::T('treenote', '%user 于 %date 锁定了该任务', [
		'%user' => URI::anchor($tn_locker->user->url(), H($tn_locker->user->name),
		'class="blue label"'),
		'%date' => '<strong>' . Date::fuzzy($tn_locker->ctime, TRUE) . '</strong>',
		]);
		echo "&#160";
		if ($tn_locker->user->id == $me->id && $me->is_allowed_to('解锁', $task)) : ?>
			<a class="blue" q-object="task_unlock" q-event="click" q-static="<?php echo H(['id' => $task->id, 'type' => $task->name(),'locker_id'=>$me->id]) ?>"  q-src="<?php echo H(URI::url('!treenote/index') ) ?>"> <?php echo I18N::T('treenote', '解锁') ?></a>
		<?php endif; ?>
</div>
<?php 
	endforeach;
?>
</div>
<?php endif; ?>
<?php if ($task->description): ?>
<div class="hr_1">&#160;</div>
<div class="description padding_1">
<?php echo H($task->description, TRUE); ?>
</div>
<?php endif; ?>
<?php if (Module::is_installed('nfs')) : ?>
<div class="hr_1">&#160;</div>
<?php echo V('nfs:nfs_lite/downloads', ['object'=>$task, 'path_type'=>'attachments']); ?>
</div>
<?php endif;?>
<?php echo V('treenote:note/quick_notes', ['task'=>$task]); ?>
<div class="hr_1">&#160;</div>
<?php echo Widget::factory('application:comments', ['object'=>$task]); ?>
<div class="hr_1">&#160;</div>
