<?php
$base_url = Config::get('system.base_url');
foreach ($results as $result) {
	$eq = O('equipment', $result->id);
	$url = $base_url.'!equipments/equipment/index.'.$eq->id;
	$arr[] = URI::anchor($url, $eq->name);
}
?>
<?php if (count($arr)): ?>
<li>➡ &#160;&#160;&#160;<?php echo I18N::T( 'equipments', $template ) .implode(', ', $arr); ?></li>
<?php else: ?>
<li>➡ &#160;&#160;&#160;<?php echo I18N::T('equipments','所有仪器都已恢复正常工作') ?></li>
<?php endif; ?>