<div class="form">

<?php if ($type == 'excel'): ?>
    <form action="<?php echo H(URI::url('!labs/list', ['type' => $type, 'form_token' => $form_token])) ?>" q-object="export" q-src="<?= URI::url('!labs/list') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" target="_self" q-event="submit" class="prevent_default" method="post">
<?php else: ?>
	<form action="<?php echo H(URI::url('!labs/list', ['type' => $type, 'form_token' => $form_token])) ?>" target="_blank" class="prevent_default" method="post">
<?php endif; ?>

        <div class="interval_30"></div>

		<ul class="ep_triple">
			<?php
			foreach ($columns as $p => $p_name) :?>
				<li>
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('labs', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>

				</li>

			<?php endforeach;?>
		</ul>
		<div class="button_container">
		    <div class="float_right">
                <input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('eq_sample', '取消');?>" />
                <input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('equipment', '保存');?>" />
            </div>
		</div>
	</form>
</div>
