<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('labs', '实验室列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('labs', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('labs', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php echo I18N::HT('labs', '实验室列表');?>
              
            </caption>
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('labs', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
			$me = L('ME');
			foreach($labs as $lab): ?>
				<tr>
					<?php if (array_key_exists('lab_name', $valid_columns)) :?>
					<td class="left nowrap">
						<?php echo H($lab->name)?:'-'; ?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('owner', $valid_columns)) :?>
					<td class="left nowrap">
						<?php
							$owner = O('user',$lab->owner_id);
							echo $owner->id ? H($owner->name) : '-';
						 ?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('lab_contact', $valid_columns)) :?>
					<td class="left nowrap">
						<?php echo H($lab->contact)?:'-'; ?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('group', $valid_columns)) :?>
					<td class="left nowrap">
						<?php
							$anchors = [];
							if ( Config::get('tag.group_limit')>=0 && $lab->group->id ) {
								$tag = $lab->group;
								$tag_root = $lab->group->root;

								if (!$tag || !$tag->id) {
									echo '-';
									continue;
								}

								if (!isset($tag_root)) $tag_root = $tag->root;

								if ($tag->id == Tag_Model::root('group')->id) {
									echo '-';
									continue;
								} 

								$found_root =  ($tag_root->id == $tag->root->id);

								foreach ((array) $tag->path as $unit) {
									list($tag_id, $tag_name) = $unit;
									if (!$found_root) {
										if ($tag_id != $tag_root->id) {
											echo '-';
											continue;
										} 
										$found_root = TRUE;
									}
									$anchors[] =  HT($tag_name);
								}
								if ( $anchors ) echo implode(' &#187; ', $anchors);

							}
							if ( !$anchors ) {

								echo '-';
							}
						?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('description', $valid_columns)) :?>
					<td class="left nowrap">
						<?php echo H($lab->description)?:'-'; ?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('creator', $valid_columns)) :?>
					<td class="left nowrap">
						<?php echo $lab->creator->id ? H($lab->creator->name) : '-'; ?>
					</td>
					<?php endif;  ?>
					<?php if (array_key_exists('auditor', $valid_columns)) :?>
					<td class="left nowrap">
						<?php echo $lab->auditor->id ? H($lab->auditor->name) : '-'; ?>
					</td>
					<?php endif;  ?>
				</tr>
			<?php endforeach; ?>
				<tr>
					<td colspan="<?php echo count($valid_columns); ?>" class="right nowrap">
						<?php echo I18N::T('labs', '总计: ') . $labs->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
