<div class="clearfix">
<?php 

    $equipment = $record->equipment;
	$amount = $charge->amount;
	$auto_amount = $charge->auto_amount;
	$description = $charge->description;
	
	if ($reserv_charge->id) {
		$amount += $reserv_charge->amount;
		$auto_amount += $reserv_charge->auto_amount;
		$description = $reserv_charge->description . $description;
	}

	echo I18N::T('eq_charge', '收费 %fee', ['%fee'=>'<strong>'.Number::currency($amount).'</strong>']);

    ?>

    <p>
        <?php
        //TODO 需要修改href, 可进行搜索
        $tid = [];
        if ($reserv_charge->id && $reserv_charge->amount) {
            if (!is_array($reserv_charge->transaction) && $reserv_charge->transaction->id) {
                $tid[] = $reserv_charge->transaction->id;
            }
            else {
                $tid[] = $reserv_charge->id;
            }
        }

        if ($charge->id && $charge->amount) {
            if (!is_array($charge->transaction) && $charge->transaction->id) {
                $tid[] = $charge->transaction->id;
            }
            else {
                $tid[] = $charge->id;
            }
        }

        if (count($tid)) { 

            $_t = [];
            foreach($tid as $t) {
                $_t[] = URI::anchor($equipment->url('charge', ['charge_id'=> $t], NULL, 'view'), '<strong>#'. Number::fill($t). '</strong>', 'class="blue prevent_default"');
            }

            $_t = join(', ', $_t);

            echo I18N::T('eq_charge', '计费编号 %tid', ['%tid'=> $_t]);
        }
        ?>
    </p>
    <?php

    /*
	if ($charge->id) {
		echo '<p>';
		echo I18N::T('eq_charge', '使用收费 %fee', array('%fee'=>'<strong>'.Number::currency($charge->amount).'</strong>'));
		if($charge->transaction->id) echo ' (<strong>#'.Number::fill($charge->transaction->id, 6).'</strong>)';
	}
	if ($reserv_charge->id && $reserv_charge->amount) {
		echo '<p>';
		echo I18N::T('eq_charge', '预约收费 %fee', array('%fee'=>'<strong>'.Number::currency($reserv_charge->amount).'</strong>'));
		if($reserv_charge->transaction->id) echo ' (<strong>#'.Number::fill($reserv_charge->transaction->id, 6).'</strong>)';
	}
    */
	$me = L('ME');
    if (!L('ME')->id) {
        $me = O('user', $current_user);
    }
    if (($charge->custom || $reserv_charge->custom) && $me->is_allowed_to('查看估计收费', $charge->equipment)) {
        $description = I18N::T('eq_charge', '估计收费 %fee', [
            '%fee'=>'<strong>'.Number::currency($auto_amount).'</strong>'
        ]) . $description;
    }
	
    $description .= Event::trigger('extra_charge_description', $charge);

	if($description) {
		echo '<div class="quote">'.$description.'</div>';
	}
?>
<?php if (Config::get('eq_record.charge_desc')) :?>
    <div class="content_wrap"><?php echo  $record->charge_desc;?></div>
<?php endif; ?>
</div>
