<?php

$links = (array)$links;
if (count($links)>0) {
	//根据weight排序
	
	usort($links, function($a, $b) {
		$aw = (int) $a['weight'];
		$bw = (int) $b['weight'];
		if ($aw == $bw) {
			return 0;
		}
		elseif ($aw < $bw) {
			return 1;
		}
		else
			return -1;
	});

	$links = array_reverse($links);
	
	$separator = isset($separator) ? $separator : ' <span class="separator">&nbsp;</span> ';
	
	$str_links = [];
	foreach($links as $link) {
		if ($link['html']) {
			$str_link = $link['html'];
		}
		else {
			$str_link = '';
			if ($link['prefix']) $str_link .= $link['prefix'];
			$extra = $link['extra'];
			if ($link['tip']) $extra .= 'title="'.H($link['tip']).'"';
			$str_link .= URI::anchor($link['url'], $link['text'], $extra);
			if ($link['suffix']) $str_link .= $link['suffix'];
			if($link['extra_class'])$extra='class='.$link['extra_class'].' '.$extra;
		}
		
		$str_links[] = $str_link;
	}	

	echo '<span id='.$ajax_id.'>'.implode($separator, $str_links).'</span>';		

}
