<?= CSS::load_async('calendars:common') ?>

<script>
    Q.globals.cal_week_rel = 'edit_week';
    Q.globals.mode = 'list';
</script>

<?= $pagination ?>
<?php

$me = L('ME');
$table = Widget::factory('table');
$table->name = 'approval';
$table->form = $form;

if($form['dtstart_check'] && $form['dtend_check']) {
    $form['date'] = H(date('Y/m/d', $form['dtstart'])).'~'.H(date('Y/m/d', $form['dtend']));
} elseif($form['dtstart_check']) {
    $form['date'] = H(date('Y/m/d', $form['dtstart'])).'~'.I18N::T('yiqikong_approval', '最末');
} elseif($form['dtend_check']) {
    $form['date'] = I18N::T('yiqikong_approval', '最初').'~'.H(date('Y/m/d', $form['dtend']));
}

$columns = [
    'equipment'=> [
        'title' => I18N::T('yiqikong_approval', '仪器名称'),
        'filter' => [
            'form' => V('yiqikong_approval:approval_table/filters/equipment', ['equipment' => $form['equipment']]),
            'value' => $form['equipment'] ? H($form['equipment']) : NULL
        ],
        'weight' => 10,
        'nowrap' => TRUE
    ],
    'user'=> [
        'title' => I18N::T('yiqikong_approval', '申请人'),
        'filter' => [
            'form' => V('yiqikong_approval:approval_table/filters/user', ['user' => $form['user']]),
            'value' => $form['user'] ? O('user', H($form['user']))->name : NULL
        ],
        'weight' => 30,
        'nowrap' => TRUE
    ],
    'flag'=> [
        'title' => I18N::T('yiqikong_approval', '审核状态'),
        'weight' => 40,
        'nowrap' => TRUE
    ],
    'date' => [
        'title' => I18N::T('yiqikong_approval', '预约起止时间'),
        'align' => 'left',
        'nowrap' =>TRUE,
        'filter' => [
            'form' => V('yiqikong_approval:approval_table/filters/date', ['form' => $form]),
            'value' => $form['date'] ? H($form['date']) : NULL,
            'field' => 'dtstart_check,dtend_check,dtstart,dtend'
        ],
        'weight' => 50,
    ],
    'ctime' => [
        'title' => I18N::T('yiqikong_approval', '申请时间'),
        'align' => 'left',
        'nowrap' =>TRUE,
        'weight' => 60,
    ],
    'description'=> [
        'title' => I18N::T('yiqikong_approval', '备注'),
        'align' => 'left',
        'weight' => 70,
        'nowrap' => TRUE
    ],
    'rest'=>[
        'title' => I18N::T('yiqikong_approval', '操作'),
		'align'=>'left',
        'weight' => 80,
		'nowrap'=>TRUE,
	]
];

$columns = new ArrayIterator($columns);
Event::trigger('approval.table_list.columns', $form, $columns);

if ($type == 'equipment') {
    unset($columns['equipment']);
}

$incharge = Q("{$me} equipment.incharge");
if (!$incharge->total_count()) {
    if ($type == 'people') {
        unset($columns['user']);
    }
}

$table->add_columns((array) $columns);

$table->empty_message = I18N::T('yiqikong_approval', '没有查询到相应的项目!');

if (count($approval) > 0) {

    foreach($approval as $ap) {
        $rows = [
            'equipment' => V('yiqikong_approval:approval_table/data/equipment', ['ap' => $ap]),
            'user' => V('yiqikong_approval:approval_table/data/user', ['ap' => $ap]),
            'flag' => V('yiqikong_approval:approval_table/data/flag', ['ap' => $ap]),
            'date' => V('yiqikong_approval:approval_table/data/date', ['ap' => $ap]),
            'ctime' => V('yiqikong_approval:approval_table/data/ctime', ['ap' => $ap]),
            'description' => V('yiqikong_approval:approval_table/data/description', ['ap' => $ap]),
            'rest' => Widget::factory('application:links', ['links' => Approval_Help::links($ap)])
        ];

        if ($type == 'equipment') {
            unset($columns['equipment']);
        }

        $rows = new ArrayIterator($rows);
        Event::trigger('approval.table_list.row', $rows, $ap);

        $table->add_row((array) $rows);
    }
}
echo $table;
?>

<?= $pagination ?>