<div class="description">
	<p>This is a list of registered labs.</p>
	<p>Click the lab name and view lab information and list of lab members.</p>
	<p>Search labs with corresponding criteria.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Add new labs.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit or delete lab information.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>

