<div class="form lpadding_2 rpadding_2 tpadding_2">
  <form method="post" autocomplete="off" q-event="submit" q-object="add_ban_group" >
    <?php echo V('form_error', ['form'=>$form]);?>
    <?php $require = (string) V('form_require'); ?>
    <table class="form flexible">
      <tbody>
      <tr>
        <td class="middle label left nowrap">
        <?php
          $selected = $form['type'] ? : 'user';
          echo Form::radio('type', 'user', $selected, I18N::T('eq_ban', '用户'), 'class="monitor radio middle"', 'class="middle"');
        ?>
        <br>
        <?php echo V('form_filter',['error'=>$form->errors['user_id'][0]])?>
        </td>
        <td class="top toggle_status:type enable_on:user">
          <?php
            echo Widget::factory('user_selector', [
              'autocomplete'=>URI::url('!eq_ban/autocomplete/user.group'),
              'name'=> 'user_id',
              'user'=> O('user', $form['user_id']),
            ]);
          ?>
        </td>
      </tr>
      <?php if (Module::is_installed('labs') ): ?>
        <tr>
          <td class="middle label left nowrap">
          <?php
            echo Form::radio('type', 'lab', $selected, I18N::T('eq_ban', '实验室'), 'class="monitor radio middle"', 'class="middle"');
          ?>
          <br>
          <?php echo V('form_filter',['error'=>$form->errors['lab_id'][0]])?>
      </td>
          <td class="top toggle_status:type enable_on:lab">
          <?php
            echo Widget::factory('labs:lab_selector', [
              'name'=>'lab_id',
              'selected_lab'=> $form['lab_id'] ? : 0,
              'all_labs'=>TRUE,
            ]);
          ?>
          </td>
        </tr>
      <?php endif;?>
      <tr>
        <td class="middle  left "><?=$require?><?php echo I18N::T('eq_ban', '组织机构')?>
              <br>
              <?php echo V('form_filter',['error'=>$form->errors['group_id'][0]])?>

        </td>
        <td>
        <?php
        $root = Tag_Model::root('group');
        if (L('ME')->is_allowed_to('添加全局', 'eq_banned')) :?>
          <div class="gray_tag_container middle">
            <?php
            echo Widget::factory('application:multi_tag_selector', [
              'autocomplete'=> URI::url('autocomplete/groups'),
              'name'=>"group_id",
              'value'=>$form['group_id'],
            ]);
            ?>
          </div>
        <?php else: ?>
          <?php
            $groups = [];
            $g = L('ME')->group;
            while ($g->id != $root->id) {
              array_unshift($groups, $g->name);
              $g = $g->parent;
            }
          ?>
          <div><?= H(join(' >> ', $groups))?></div>
        <?php endif;?>
        </td>
      </tr>
      <tr><td><br><br></td></tr>
      <tr>
        <td class="middle label left nowrap"><?php echo $require; ?><?php echo I18N::T('eq_ban', '封禁原因')?>
            <br>
        <?php echo V('form_filter',['error'=>$form->errors['reason'][0]])?>
</td>
        <td class="top">
          <textarea style="line-height: normal; padding: 4px 10px; width: 240px;" class="top autogrow reason" name="reason" ><?php echo $form['reason'] ?></textarea>
        </td>
      </tr>
      <tr>
        <td class="middle label left nowrap"> <?php echo $require; ?><?php echo I18N::T('eq_ban', '到期时间')?>
                <br>
                <?php echo V('form_filter',['error'=>$form->errors['atime'][0]])?>
</td>
        <td class="top nowrap">
          <input name="atime" class="text date" date_type="date" value="<?php echo H($form['atime'] ?: Date::time()) ?>" />
        </td>
      </tr>
    </table>
    <div class="button_container">
  <div class="float_right">
  <input name="cancel" id="cancel" type='reset' class="font-button-default rmargin_2e4" value="<?php echo I18N::HT('eq_ban', '取消');?>" />
  <input name="submit" type='submit' class="font-button-save" value="<?php echo I18N::HT('eq_ban', '添加封禁');?>" />
  </div>
  </div>
  </form>

</div>
