<script>
jQuery(function($){
       var $center = $('#center');
       $center.css('vertical-align', 'middle');
       $center.find('.center_content').css({width: '70%', margin: 'auto', paddingBottom: '2em'});

		var height = $('.signup_body').offset().top - $center.offset().top ;
        height = height/2;
		$center.css('vertical-align', 'baseline');
		$center.css('padding-top', height +'px');
        $center.css('background-color', "#ffffff");
});
</script>
<?php 
	$form_config = Config::get('form.user_signup');
	$requires = (array)$form_config['requires'];

	$requires = new ArrayIterator($requires);
    Event::trigger('signup.validate_requires', $requires, $form);

	$_require = function($key) use ($requires) {
		echo $requires[$key] ? V('form_require') : "<span class='lpadding_20'></span>";
	}
?>
<?php if(!L('ME')->is_active()): ?>
	<div style="height: 30px; line-height:30px;border: 1px solid #E5E5E5;padding: 0 2%; text-align: center;width: 66%;margin-left: 15%;"
         class="message_error">
		<span class="error"><strong><?= Config::get('labs.sign_edit.tips') ?></strong></span>
	</div>
    <div class="interval_24"></div>
<?php endif; ?>
<?php echo V('form_error', ['form'=>$form]);?>
<div class="form signup_body" style="margin:0 0 50px 15%;">
	<form method="post" autocomplete="off" action="<?php echo H(URI::url()) ?>">
	 		<table style="width:100%">
				<tbody>
					<tr>
					  <td colspan="2" class="legend">
					  	<h2 class="section_title"><?php echo I18N::T('labs', '1. 登录信息')?></h2>
					  </td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php 
                    list($token, $backend) = explode('|', $user->token, 2);
                    $backends = (array) Config::get('auth.backends');
                    $backend_title = $backends[$backend]['title']?:$backend;
					?>
					<tr>
						<td class="label right nowrap middle rpadding_label"><?php echo I18N::T('labs', '登录帐号') ?></td>
						<td class="middle">
							<div class="text_like" style="padding-left: 10px;width: 290px;background-color:#E7E7E7;color:#999999">
							<?php echo H($token); ?>
							<span class="separator">@</span>
							<?php echo H($backend_title) ?>
							</div>
							<?php echo Form::hidden('token', $user->token); ?>
						</td>
					</tr>
					<?php if ($backends[$backend]['allow_create']) :?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['password'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('passwd'); ?><?php echo I18N::T('labs', '密　　码')?></td>
						<td class="middle"><input name="passwd" type="password" class="text"  value="" />
							
						</td>
					</tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['confirm_password'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('confirm_passwd'); ?><?php echo I18N::T('labs', '确认密码')?></td>
						<td class="middle"><input name="confirm_passwd" type="password" class="text"  value="" />
							
						</td>
					</tr>
					<?php endif;?>
					<?php 
						$backends = (array) Config::get('auth.backends');
						$scope = $backends[$backend]['rpc.scope'];
						if (in_array('people', (array)$scope)) :?>
					<tr>
						<td></td>
						<td>
							<input name="info_sync" type="button" class="button button_remote info_sync" value="<?php echo H(I18N::T('labs', '同步远程信息')) ?>" />
						</td>
					</tr>
                    <?php endif;?>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr>
						<td colspan="2" class="legend">
					  		<h2 class="section_title"><?php echo I18N::T('labs', '2. 个人信息')?></h2>
					  	</td>	
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['name'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('name'); ?><?php echo I18N::T('labs', '姓　　名')?></td>
						<td class="middle"><input name="name" class="text name"  value="<?php echo H($form['name'] ? : $user->name) ?>" /></td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['gender'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('gender'); ?>  <?php echo I18N::T('labs', '性　　别')?></td>
						<td class="middle">
							<span class="gender">
                            <?php echo Form::dropdown('gender', I18N::T('labs', User_Model::$genders), isset($form['gender']) ? $form['gender'] : (is_null($user->gender) ? -1 : $user->gender), 'class="middle dropdown"'); ?>
                       		</span>
							                          
                        </td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['member_type'][0]])?></td></tr>
					<tr>
						<td class="label middle right nowrap rpadding_label"><?php $_require('member_type'); ?> <?php echo I18N::T('labs', '人员类型')?></td>
						<?php
						$members_type = [];
						foreach(User_Model::get_members() as $key => $value){
							$members_type[I18N::T('labs', $key)] = $value;
                            $other_member_type = 22;
                            if ($value == '其他') {
                                $other_member_type = $key;
                            }
						}
						?>
						<td class="middle">
							<span class="member_type">
                            <?php if ($user->signup_type == 'other'): ?>
                                <?php echo Form::dropdown('member_type', [$other_member_type=>'其他'], $other_member_type, 'class="dropdown"'); ?>
                            <?php else: ?>
                                <?php echo Form::dropdown('member_type', [''=>'--'] + I18N::T('labs', $members_type), $form['member_type'] ? : $user->member_type, 'class="dropdown"'); ?>
                            <?php endif; ?>
							</span>
							  
						</td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php if($form['local_remote_group']):?>
						<?php 
							//如果有form按钮的值，说明用户同步过信息，如果表单出错，则显示
							echo V('labs:signup/remote_info/user_group', ['group'=>$_SESSION['remote_user_group'], 'form'=>$form, 'user_group'=>$user->group->id]);
						?>
					<?php else:?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['group_id'][0]])?></td></tr>
					<tr class="group">
						<td class="right nowrap middle rpadding_label"><?php $_require('group_id'); ?><?php echo I18N::T('people', '组织机构')?></td>
						<td class="top">
							<?php
                                if ($user->signup_type == 'other') {
                            ?>
                            <input type="hidden" name="group_id" value="<?php echo H(Wmu_Extra_Labs::other_labs()->id ) ?>">
                            <?php
                                    echo V('application:tag/path', ['tag' => Wmu_Extra_Labs::other_labs()]);
                                } else {
                                    echo Widget::factory('application:tag_selector', [
                                        'tag'=> $form['group_id'] ? O('tag_group', $form['group_id']) : $user->group, 
                                        'root'=>$group_root,
                                        'name'=>'group_id',
                                        'ajax'=>true,
                                    ]);
                                }
							?>
							
						</td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php endif;?>
					<?php if ($user->signup_type != 'other'): ?>
						<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['ref_no'][0]])?></td></tr>
                        <tr>
                            <td class="label middle right nowrap rpadding_label"><?php $_require('ref_no'); ?><?php echo I18N::T('labs', '学号/工号')?></td>
                            <td class="middle"><input name="ref_no" class="text ref_no"  value="<?php echo H($form['ref_no'] ? : $user->ref_no)?>" /> </td>
						</tr>
						<tr><td><div class="interval_12"></div></td></tr>
                    <?php endif; ?>
					<?php if (Config::get('people.show_mentor_name', FALSE)) : ?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['mentor_name'][0]])?></td></tr>
					<tr>
                    	<td class="label middle right nowrap rpadding_label"><?php $_require('mentor_name'); ?><?php echo I18N::T('labs', '导师姓名'); ?></td>
                        <td class="middle">
                           <input name="mentor_name" class="text"  value="<?php echo H($form['mentor_name'] ? : $user->mentor_name) ?>" />   
                        </td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php endif;?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['major'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('major'); ?><?php echo I18N::T('labs', '专　　业')?></td>
						<td class="middle"><input name="major" class="text major"  value="<?php echo H($form['major'] ? : $user->major) ?>" /></td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['organization'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('organization'); ?><?php echo I18N::T('labs', '单位名称')?></td>
						<td class="middle"><input name="organization" class="text organization"  value="<?php echo H($form['organization'] ? : $user->organization)?>" /></td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
                    <?= V('labs:signup/signup_extra_field', ['form' => $form, 'user' => $user, 'type' => 'edit']);?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['lab_id'][0]])?></td></tr>
					<tr>
						<td class="right nowrap rpadding_label"><?php $_require('lab_id'); ?> <?php echo I18N::T('labs', '实验室|:signup')?></td>
						<td class="top">
							<?php echo Widget::factory('labs:lab_selector', [
								'name' => 'lab_id',
								'selected_lab' => Q("$user lab")->current(),
                                'extra' => $user->signup_type == 'other' ? 'disabled="disabled"' : ''
								]); ?>
							
						</td>
					</tr>
                    <tr><td><div class="interval_12"></div></td></tr>
                    <tr>
                        <td class="right nowrap middle rpadding_label"><?php echo I18N::T('labs', '所在时间');?></td>
                        <td class="middle">
                        <?php //echo Form::checkbox('has_dfrom', $form['has_dfrom'], NULL, 'class="middle monitor"'); ?>
                        <input style="width: 26.5%" name="dfrom" class="text toggle_status:has_dfrom enable_on:on date middle" value="<?php echo $user->dfrom ?: H($form['dfrom'])?>" date_type="date"/>
                        <?php //echo Form::checkbox('has_dto', $form['has_dto'], NULL, 'class="middle monitor"'); ?>
                        <span>-</span>
                        <input style="width: 26.5%" name="dto" class="text toggle_status:has_dto enable_on:on date middle" value="<?php echo $user->dto ?: H($form['dto']);?>" date_type="date" />
                        <?php $_require('time');?>
                        </td>
                    </tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr>
						<td colspan="2" class="legend">
					  		<h2 class="section_title"><?php echo I18N::T('labs', '3. 联系方式')?></h2>
					  	</td>	
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['email'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap rpadding_label"><?php $_require('email'); ?>   <?php echo I18N::T('labs', '电子邮箱')?></td>
							<?php if (Config::get('people.link_gapper_system')) { ?>
								<td class="middle"><input disabled class="text email" size="40" value="<?php echo H($form['email'] ? : $user->email) ?>" /></td>
							<?php } else { ?>
								<td class="middle"><input name="email" class="text email" size="40" value="<?php echo H($form['email'] ? : $user->email) ?>" />
									<?php $_require('email'); ?>
								</td>
							<?php } ?>
						</td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['phone'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap middle rpadding_label"><?php $_require('phone'); ?><?php echo I18N::T('labs', '联系电话')?></td>
						<td class="middle"><input name="phone" class="text phone"  value="<?php echo H($form['phone'] ? : $user->phone)?>" />
							
						</td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php if (Config::get('people.show_personal_phone', FALSE)) :?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['personal_phone'][0]])?></td></tr>
					<tr>
                        <td class="label right nowrap middle rpadding_label"><?php $_require('personal_phone'); ?><?php echo I18N::T('labs', '个人手机')?></td>
                        <td class="middle">
                             <input name="personal_phone" class="text"  value="<?php echo H($form['personal_phone'] ? : $user->personal_phone); ?>" />
                             
                        </td>
					</tr>
					<tr><td><div class="interval_12"></div></td></tr>
					<?php endif;?>
					<tr><td></td><td><?php echo V('form_filter',['error'=>$form->errors['address'][0]])?></td></tr>
					<tr>
						<td class="label right nowrap middle rpadding_label"><?php $_require('address'); ?> <?php echo I18N::T('labs', '地　　址')?></td>
						<td class="middle"><input name="address" class="text address"  value="<?php echo H($form['address'] ? : $user->address)?>" />
							  
						</td>
					</tr>
					<tr><td><div class="interval_30"></div></td></tr>
					<tr>
						<td></td>
						<td>
							<input type="submit" name="submit" class="font-button-save" value="<?php echo H(I18N::T('labs', '保存')) ?>" />
						</td>
					</tr>
				</tbody>
			</table>
			</form>
</div>
<script>
	jQuery(function($){
		var $user_group_id = "<?php echo H($user->group->id) ?>";
		//获取远程信息
		function get_remote_info(){
			Q.trigger({
				object: 'get_remote_user',
				event: 'click',
				data: {'user_group_id': $user_group_id},
				success: function(data){
					var  $user_info = data.user_info;
					if($user_info){
						$('input.name').val($user_info.name);
						$('input.ref_no').val($user_info.ref_no);
						$('input.organization').val($user_info.organization);
						$('input.major').val($user_info.major);
						$('input.email').val($user_info.email);
						$('input.phone').val($user_info.phone);
						$('input.address').val($user_info.address);
					}
					$('input.text').removeAttr('disabled');
					$('span.signup_button').show();
				}	
			});
		}

		$('input.info_sync').click(function(){
			get_remote_info();
		});		
	});
</script>
