<?php
foreach($updates as $update):
	if ($update->ctime < $time):
		$time = strtotime(date('y-m-d', $update->ctime));
	?>
	<div class="update_date">
		<?php echo H(Date::fuzzy($update->ctime))?>
	</div>
<?php endif;

	echo V('desktop/item', ['update' => $update]);
endforeach;
$more_id = 'update_more_'.uniqid();
?>
<?php
$count = count( Update::fetch($next_start, 1, $tmp, $model_name) );
if ( $count ) {
?>
<div class="interval_12"></div>
<a id="<?php echo H($more_id) ?>" href="#" class="more_link font-button-default"
		q-event="click"
		q-object="more_updates" 
		q-static="<?php echo H([
			'more_id'=>$more_id, 'start'=>$next_start, 
			'stime'=>$time, 'model_name'=>$model_name])?>"
		q-src="<?php echo H(URI::url('!update/update')) ?>"
	>
	<?php echo I18N::HT('update', '更多更新...')?>
</a>
<?php
}
?>
