<div class="description">
	<p>You are viewing the general information and list of lab members of this lab.</p>
	<p>Search lab members.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may edit or delete lab information.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may follow, edit, delete, activate or block members associated with this lab.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
