<?php
	echo CSS::load_async('equipments:relate_list');
	$uniqid = 'relate_tags_'.uniqid();
    $root = Tag_Model::root('equipment_user_tags');
    $tags = Q("tag_equipment_user_tags[root={$root}]:sort(weight A)")->to_assoc('id', 'id');
	$keys = array_keys($tags);
	$tid = $keys[0];
?>

<div class="relate_list" id="<?php echo H($uniqid) ?>">
<div class="relate_left">
<div class="padding_1 panel clearfix add_tags center tmargin_3 bmargin_3">
	<a
	class="font-button-default border_gray gray"
		q-object="admin_create_tag"
		q-event="click"
		q-src="<?php echo H(URI::url('!equipments/equipment')) ?>">
		<span class='icon-color-g icon-add rmargin_1'></span>
		<?php echo T('添加标签')?></a>
</div>
	<div class="equipment_tags">
		<?php
			foreach($tags as $key => $tag) {
                if ($is_slave) {
                    echo V('equipments:admin/user_tags/tag_slave', ['id'=>$key, 'tid'=>$tid, 'relate_uniqid'=>$uniqid, 'tag_name'=>'tag_equipment_user_tags']);
                } else {
                    echo V('equipments:admin/user_tags/tag', ['id'=>$key, 'tid'=>$tid, 'relate_uniqid'=>$uniqid, 'tag_name'=>'tag_equipment_user_tags']);
                }
			}
		?>
	</div>
		</div>
		<div class="relate_right" id="<?php echo H($uniqid) ?>">
		<?php echo V('equipments:admin/user_tags/relate_view',['tid'=>$tid, 'tag_name'=>'tag_equipment_user_tags', 'is_slave' => $is_slave, 'relate_uniqid'=>$uniqid]); ?>
</div>

<script type="text/javascript">
jQuery(function($) {
    Q.equipment_tag_sortable("<?php echo $uniqid; ?>", "<?php echo URI::url('!equipments/equipment/'); ?>", 'tag_equipment_user_tags');
});
</script>
