<div class="form ">
    <?php if ($type == 'csv'): ?>
        <form id="report_form" method="POST" q-object="charge_export" q-src="<?= URI::url('!eq_charge/report') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" q-event="submit" autocomplete="off" class="prevent_default">
    <?php else: ?>
	    <form id="report_form" name="report_form" action="<?php echo H(URI::url('!eq_charge/report', ['type'=>$type, 'form_token'=>$form_token, 'oname' => $oname, 'oid' => $oid])) ?>" target="<?= $type == 'csv' ? '_self' : '_blank' ?>" class="prevent_default" method='post'>
    <?php endif; ?>
		<?php echo V('form_error', ['form'=>$form]);?>
		<ul class="ep_triple">
			<?php
			foreach ($columns as $p => $p_name) :?>
			<?php  if ($p < 0): ?>
			<div class="clear">&#160;</div>
			<h4><?php echo I18N::HT('eq_charge', $p_name) ?></h4>
			<?php else: ?>
				<li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('eq_charge', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>
				</li>
			<?php endif; ?>
			<?php endforeach;?>
		</ul>
		<div class="hr_2"></div>
        <?php if($type == 'csv') :
				echo Widget::factory('flexform', [
					'template_data' => ['disabled'=>TRUE],
					'item_view' => 'eq_charge:rule/item',
					'add_button_text' => I18N::T('eq_charge', '添加导出项'),
				]);
		?>
		<div class="hr_2"></div>
        <?php endif;?>
		<div class="label right top description">
                <?php if($type == 'csv') echo '<span id="span_haveto" style="display:none">* '.I18N::T('eq_sample', '必填项').'</span>';?>
		</div>
		<div class="button_container">
		<div class="float_right">
		<input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('eq_charge', '取消');?>" />
		<input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('eq_charge', '提交');?>" />
		</div>
		</div>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(".flexform_button_add").bind('click', function(e) {
		$("#span_haveto").show();
	});

// 	$("input=[name=btn_check]").bind('click', function(e) {
// 		var form_data = [];

// 		var extraitems = $('input[name^=export_item_name]');
// 		var extraitem_array = [];
// 		for(var i=0;i<extraitems.length;i++) {
// 			extraitem_array.push(extraitems[i].value);
// 		}
// 		form_data['extraitems'] = extraitem_array;

// 		var searchtypes = $('select[name^=searchtype]');
// 		var type_array = [];
// 		for(var i=0;i<searchtypes.length;i++) {
// 			type_array.push(searchtypes[i].value);
// 		}
// 		form_data['searchtypes'] = type_array;

// 		var extraitem_values = $('input[name^=export_item_value]');
// 		var value_array = [];
// 		for(var i=0;i<extraitem_values.length;i++) {
// 			value_array.push(extraitem_values[i].value);
// 		}
// 		form_data['extravalues'] = value_array;

// 		Q.trigger({
// 			object: 'charge_export',
// 			event: 'click',
// 			url: '<?php echo URI::url('!eq_charge/report')?>',
// 			data: form_data,
// 			success: function(data) {
// 				if(data.result == '1') {
// 					document.forms['report_form'].submit();
// 				}
// 			},
// 		});
// 		return false;
// 	});
});
</script>
