<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php $title = I18N::T('eq_charge', '%name费用汇总表%data', [
	'%name' => H($obj->name),
	'%data' => $data
]);?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?= $title ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			p {
				margin: 0;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo T('关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption><?= $title ?></caption>
			<thead id="stat">
				<tr>
				<td colspan="8">
				<?php echo I18N::T('eq_charge', '时间范围'); ?>:
				&#160;
				<?php
					$dtstart = isset($dtstart) ? H(date('Y/m/d',$dtstart)) : I18N::T('equipments','最初');
					$dtend = isset($dtend) ? H(date('Y/m/d',$dtend)) : I18N::T('equipments','现在');
					echo $dtstart . ' - ' . $dtend;
				?>
				</td>
				</tr>
			</thead>
			<thead>
				<tr>
					<?php foreach($columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('eq_charge', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach($charges as $c): ?>
				<tr>
					<?php foreach ($columns as $p => $p_name) : ?>
						<td class="left nowrap">
						<?php echo V('eq_charge:print_charges_table/data/' . $p, ['c' => $c]);?>
						</td>
					<?php endforeach;?>
				</tr>
			<?php endforeach;?>
				<tr>
					<td class="right nowrap" colspan="<?php echo H(count($columns)) ?>">
						<?php echo I18N::T('eq_charge', '收费总和');?>:
						&#160;
						<?php echo Number::currency($charges->sum('amount'));?>
						<?php
							echo '&#160';
						?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
