<div class="form padding_1">
	<form method="post" autocomplete="off" q-event="submit" q-object="reserv_fail_wait_join_user" q-static="<?php echo H(['id'=>$equipment->id,'user_id'=>$user->id])?>">
		<?php echo V('form_error', ['form'=>$form]);?>
		<?php $require = (string) V('form_require'); ?>
		<table class="form flexible">
			<tbody>
                <tr>
    				<td class="top label right nowrap"><?php echo I18N::T('eq_wait_join', '测样样品数')?></td>
    				<td class="top nowrap">
    					<input class="text number" value="<?= H($form['sample']) ?>" name="sample" />
    					<?php echo $require; ?>
    				</td>
    			</tr>
    			<tr>
    				<td class="top label right nowrap"><?php echo I18N::T('eq_wait_join', '测样要求')?></td>
    				<td class="top nowrap">
    					<textarea class="top" name="description" rows="3" cols="50" class="autogrow"><?php echo $form['description'] ?></textarea>
    				</td>
    			</tr>
    			<tr>
    				<td class="top label right nowrap"><?php echo I18N::T('eq_wait_join', '预计时长')?></td>
    				<td class="top nowrap">
                        <input class="text number middle" name="time" size="10" value="<?php echo H($form['time']) ?>" />&#160;
                        <?php echo Form::dropdown('time_format', Date::units('ihd'), H($form['time_format'] ?: 'h'), 'class="middle"');?>
                        <?php echo $require;?>
    				</td>
    			</tr>
    			<tr>
    				<td></td>
    				<td>
    					<input type="submit" name="submit" class="button button_add" value="<?php echo H(I18N::T('eq_wait_join', '保存')) ?>" />
    				</td>
    			</tr>
		</table>
	</form>
</div>
