<?php

$links = array_filter((array)$links);

if (count($links)>0) {
	//根据weight排序
	usort($links, function($a, $b) {
		$aw = (int) $a['weight'];
		$bw = (int) $b['weight'];
		if ($aw == $bw) {
			return 0;
		}
		elseif ($aw < $bw) {
			return 1;
		}
		else
			return -1;
	});

	$version = substr(PHP_VERSION, 0, 1);
	if ($version < 7) $links = array_reverse($links);

	$separator = isset($separator) ? $separator : ' <span class="separator">&nbsp</span> ';


	$str_links = [];
	foreach($links as $link) {
		if ($link['html']) {
			$str_link = $link['html'];
		}
		else {
			$str_link = '';
			if ($link['prefix']) $str_link .= $link['prefix'];
			$extra = $link['extra'];
			if ($link['tip']) $extra .= '  title="'.H($link['tip']).'"';
			$str_link .= URI::anchor($link['url'], $link['text'], $extra);

			//	echo $extra;
			if ($link['suffix']) $str_link .= $link['suffix'];
		}

		$str_links[] = $str_link;
	}
	echo implode($separator, $str_links);

} else {
}
