<?php 
$autocomplete = $this->autocomplete ?: URI::url('autocomplete/equipment');
?>
<input 
    type="text" 
    name="<?php echo $name; ?>"
    class="text token <?php echo $extra;?> token_autocomplete:<?php echo $autocomplete; ?>" 
    <?php if ($tooltip) : ?>
    q-tooltip="<?php echo H($tooltip) ?>"
    <?php endif;?>
    size="<?php echo H($size ?: '40') ?>" 
    value="<?php echo H($value); ?>"
/>