
<?php
$uniqid = 'user_'.uniqid();

$user = is_object($this->user) ? $this->user : O('user', $this->user);
$autocomplete = $this->autocomplete ?: URI::url('autocomplete/user');

if ($this->labs) {

	$extra = 'id="'.$uniqid.'_lab" class="lab_change middle" onchange="jQuery(\'#'.$uniqid.'_user, #'.$uniqid.'_user\').val(\'\');"';
	echo Form::dropdown($this->lab_name, $this->labs, '', $extra);
}

$size = $this->size ?: '';

if ($user->id) {
	if (Module::is_installed('labs') && !$GLOBALS['preload']['people.multi_lab']) {
		$name = T('%name (%lab)', ['%lab'=>Q("$user lab")->current()->name, '%name'=>$user->name]);
	}
	else {
		$name = $user->name;
	}
}
else {
	$name = '';
}

if( $cardread ) {
	$cardread_str = 'q-cardread="'.$cardread.'" ';
	$cardread_str.= 'q-cardreadNormalMsg="'.T('请刷卡').'" ';
	$cardread_str.= 'q-cardreadErrorMsg="'.T('没找到相应成员').'" ';
}

if ($disabled) {
    $disabled = 'disabled="disabled"';
}
?>
<input id="<?php echo $uniqid?>_user" name="<?php echo H($this->name ) ?>" type="hidden" value="<?php echo H($user->id) ?>" />
<input id="<?php echo $uniqid?>_user_name" <?php echo $cardread_str;?> <?php echo $disabled;?> class="text middle select_on_focus autocomplete:<?php echo H($autocomplete) ?> autocomplete_alt:#<?php echo $uniqid?>_user<?php echo $this->labs ? ' dynamic:'.$this->lab_name.'=#'.$uniqid . '_lab':'' ?>" size="<?php echo H($size) ?>" autocomplete="off"
 value="<?php echo H($name) ?>" q-tooltip="<?php echo H(T('请输入关键字并选择') ) ?>" style="<?php echo H($style); ?>" />
