<?php 
$tag = O('tag_meeting_user_tags', $id);
$uniqid = 'tag_'.uniqid();
// 9行因没有做拖拽所以禁用了特殊鼠标样式
?>
<div class="item:<?= $tag->id; ?> equipment_tag tag_weight:<?= $tag->weight; ?> <?= $tid == $id ? 'active' : '';?>"
id="<?= H($uniqid) ?>">
<div class="tag_title item:<?= $tag->id ?>">
    <div class="tag_drag_handle" style="margin: 6px;height: 16px;width: 16px;text-align: center;margin-right: -8px;">&nbsp;</div>
	<input class="text hidden" value="<?= H($id) ?>" />
	<span class="tag_name lmargin_2" title="<?= H($tag->name)?>" style="width: 6.5rem;text-overflow: ellipsis;white-space: nowrap;"><?= H($tag->name)?></span>
	<a class="icon-trash float_right color-grey" style="cursor: pointer;line-height: 30px"
    q-object="delete_tag"
    q-event="click"
    q-static="<?= H(['tid'=>$id])?>"
    q-src="<?= H(URI::url('!meeting/meeting')) ?>">&#160;</a>
	<script type="text/javascript">
		$("#<?= $uniqid?>").bind('click', function(e){
			var $item = $(this);
			if ($item.hasClass('active')) {
				var $span = $item.find('span:eq(0)');
                $span.next().hide();
				var html = $span.html();
				html = html.replace(/\"/g, '&quot;');
				if ($span.find('input').length) {
					return false;
				}
				var input = '<input size="12" value="'+html+'" /'+'>';
				$span.html($(input));
				$span.find('input:eq(0)').focus().one('blur', function(){
					var $input = $span.prev('input:eq(0)');
					Q.trigger({
						object: 'edit_tag',
						event: 'blur',
						data: {
							tname: $(this).val(),
							tid: $input.val(),
							uniqid: '<?= $uniqid?>',
							relate_uniqid: '<?= $relate_uniqid?>'
						},
						url: '<?= URI::url("!meeting/meeting")?>'
					});
				});
				e.preventDefault();
				return false;
			}

			var $input = $item.find('input:text:eq(0)');
			Q.trigger({
				object: 'admin_replace_tag',
				event: 'click',
				data: {
					tid: $input.val(),
					uniqid: '<?= $relate_uniqid?>'
				},
				url: '<?= URI::url("!meeting/meeting")?>',
				complete: function () {
                    $box = $(".relate_left .equipment_tags .active");
					$box.removeClass('active');
					$item.addClass('active');
				}
			});
			return false;
		});
	</script>
</div>
</div>
