<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以更改此台仪器设备的当前状态。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">出现故障或需要报废时请详细描述原因。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">注意:一旦选择报废,此台仪器设备的状态将不能再更改。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>
