<?php
$list = (array) Config::get('lab.home_list');
$me = L('ME');
?>
<div class="form margin-left-half">
	<form method="post" class="edit" action="" autocomplete="off">
        <div class="interval_6"></div>
        <h2 class="section_title"><?php echo I18N::T('people', '自定义首页')?></h2>
        <div class="interval_10"></div>
        <?php echo Form::dropdown('home', $list, $me->home, 'class="middle margin-left-1"', 'class="middle"'); ?>
		<div class="interval_36"></div>
        <div>
		<input type="submit" name="submit" class="font-button-save" value="<?php echo H(I18N::T('people', '保存修改')) ?>" />
        </div>
        <div class="interval_60"></div>
	</form>
</div>
