<?php if ( Module::is_installed('labs') ) :  ?>
<div class="description">
	<p>View member information here.</p>
	<p>Search by users of laboratories.</p>
	<p>You may edit part of your information.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Add, edit, delete, activate or inactivate users here.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may view a user's sign-up schedule or equipment usage history here by clicking the user's name.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
<?php else : ?>
<div class="description">
	<p>View member information here.</p>
	<p>Search users.</p>
	<p>You may edit part of your information.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit, delete, activate or inactivate users here.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may view a user's sign-up schedule or equipment usage history here by clicking the user's name.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
<?php endif; ?>