<?php
$me = L('ME');
$isGenee = in_array($me->token, (array) Config::get('lab.admin')) ? true : false;
$isAdmin = $me->access('管理所有内容');
if($customType == 'eq_reserv'){
    $isGroup = $me->access('修改所有仪器的预约设置') || $me->access('修改下属机构仪器的预约设置');
}else{
    $isGroup = $me->access('修改所有仪器的计费设置') || $me->access('修改下属机构仪器的计费设置');
}
$isIncharge = Equipments::user_is_eq_incharge($me, $equipment) || $isGenee || $isAdmin || $isGroup;
?>
<input type="text" class="text middle" size="9" name="<?=$name?>" value="<?=$visualVars[$name]?>" <?php if (!$isIncharge):?> disabled <?php endif;?> />