<?php
	if (Input::route() != $_SESSION['system.current_layout_url']) {
		$_SESSION['system.last_layout_url'] = $_SESSION['system.current_layout_url'];
	}
	$_SESSION['system.current_layout_url'] = Input::route();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>
<?php echo H(Config::get('page.title_default')) ?>
</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="renderer" content="webkit" />
<meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<?php /*web app中去除浏览器上地址栏选项的设置*/ ?>
<meta name="apple-mobile-web-app-capable" content="yes" />
<?php /*web app中去除iphone对连串数字拨号映射设置*/ ?>
<meta name="format-detection" content="telephone=no" />
<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
<?php /*web app 中定义app图片的方式*/ ?>
<?php echo $this->controller->load_css(); ?>
<?php echo $this->controller->load_js(TRUE); ?>
</head>
<body>
	<table width="100%" height="100%">
	<tr>
		<td class="top" height="32" colspan="2">
			<div id="header">
				<div class="header_content">
				<img class="middle" src="<?php echo _C("images/logo.png")?>"/>
				</div>
			</div>
		</td>
	</tr>
	<tr>
		<td id="center" class="top" width="100%" style="vertical-align: middle;">
			<div class="center_content" style="max-width:500px;margin:auto">
				<?php echo V('message'); ?>
				<?php echo V('oauth:provider/login_form', $this->vars); ?>
			</div>
		</td>
	</tr>
	</table>
	<?php echo $this->controller->load_js(FALSE); ?>
</body>
</html>
