<div class="float_left gapper_img" style="position:absolute">
	<div style="margin:40px">
		<img src="!gapper/images/gapper.png">
	</div>
</div>
<div class="gapper_content">
    <p class="title">
		<?php echo I18N::T('gapper','什么是Gapper?')?>
	</p>
    <div class="description">
		<p>Gapper = <strong>G</strong>roup-<strong>App</strong>-<strong>er</strong></p>
		<br />
		<p><?php echo I18N::T('gapper','Gapper是基理科技提供的一个便于用户对自己的分组和应用进行统一管理的平台, 能够在一个账号下面绑定自己的多个身份, 用于完成多个系统或软件间的无缝交互.'); ?></p>
    </div>
</div>