<div>
    <div style="width: 126px;line-height: 30px;" class="nowrap float_left">
        <?= H(T($item['name']))?>
    </div>
    <div style="height: 30px; line-height: 30px;">
        <input name="<?= $prekey.'_'.$key?>" type="file" class="file" />
        <?php if ($item['tip']):?>
        <span class="description">
                * <?= H(T($item['tip']))?>
        </span>
        <?php endif;?>
    </div>
</div>
