<style>

    .export_wait {
        width: 400px;
        height: 300px;
        background-color: #FFF;
        padding-top: 44px;

    }

    .export_wait .title {
        color: #7498E0;
        font-size: 36px;
    }

    .export_wait p.content {
        color: gray;
        font-size: 18px;
    }

    .export_wait a.select {
        background-color: #7498E0;
        color: #FFF;
        font-size: 18px;
        padding: 4px 8px;
        text-decoration: none;
        cursor: pointer;
    }

    .loading_box {
        display: none !important;
    }

</style>

<div style="margin:auto" class=" middle center export_wait">
    <img src="<?php echo H(_C('images/wait.png')) ?>"></img>
    <div class="hr_2"></div>
    <h1 class="middle center title"><?= I18N::T('application', '请 稍 后') ?></h1>
    <p class="content center"><?= I18N::T('application', '文件正在生成中, 请勿关闭此页面') ?></p>
    <p class="content center"><?= I18N::T('application', '生成完毕后会自动开始下载') ?></p>
    <h1 class="middle center title">. . .</h1>
    <script>
        (function ($) {
            download = function () {
                Q.trigger({
                    object: 'download',
                    event: 'click',
                    data: {
                        'file_name': '<?= $file_name?>',
                        'ext': 'zip'
                    },
                    url: '<?= URI::url('!technical_service/index') ?>',
                    success: function (data) {
                        if (data.res != '' && data.res != 'not found') {
                            window.location.href = '<?= URI::url('!technical_service/index/download.' . $file_name . '.') ?>' + data.res;
                            clearInterval(download_file);
                        }
                    }
                })
            }
            download_file = setInterval(download, 1000);

            $('.dialog_close').click(function () {
                Q.trigger({
                    object: 'export_wait',
                    event: 'click',
                    data: {
                        'pid': '<?= $pid ?>'
                    },
                    url: '<?= URI::url('index') ?>',
                    success: function (data) {
                        window.location.replace(window.location.href);
                    }
                })
            })

        })(jQuery)
    </script>
</div>
