<?php 
$uniqid = 'door_'.uniqid();

$autocomplete = $this->autocomplete ?: URI::url('!iot_gdoor/autocomplete/doors');

$size = $this->size ?: 40;
$name = $door->id ? $door->doorName() : '';

?>
<input id="<?php echo $uniqid?>_door" name="<?php echo H($this->name ) ?>" type="hidden" value="<?php echo H($door->gdoor_id) ?>" />
<input placeholder="<?= I18N::T('entrance', '请输入关键字并选择')?>" id="<?php echo $uniqid?>_door_name" class="text middle select_on_focus autocomplete:<?php echo H($autocomplete) ?> autocomplete_alt:#<?php echo $uniqid?>_door" size="<?php echo H($size) ?>" value="<?php echo H($name) ?>" />
