<div class="building_detail clearfix">
<table class="form">
<tbody>
<tr>
	<td class="top icon" style="padding-right: 30px;">
		<?php echo $building->icon('104'); ?>
	</td>
	<td class="top flexible">
	<?php if (L('ME')->is_allowed_to('修改', 'gis_building')): ?>
		<div class="float_right">
			<?php echo Widget::factory('application:links', ['links' => $building->links('view'), 'separator'=>' ']) ?>
		</div>
		<?php endif; ?>
		<h2>
			<a href="<?php echo H($building->url() ) ?>"><?php echo H($building->name); ?></a>
		</h2>
		<p class="description">
			<?php echo V('application:tag/path', ['tag'=>$building->group, 'tag_root'=>$group_root]); ?>
		</p>
	</td>
</tr>
</tbody>
</table>
</div>


<div class="interval_24_fixed interval_gray"></div>
<div class="interval_24"></div>
<!--<div class='search_panel'>
    <?php
/*    echo $secondary_tabs->panel_buttons;
    echo $secondary_tabs->search_box;
    echo $search_box ?: $panel_buttons;
    */?>
</div>-->
<div class="tab_pagination">
    <?php echo $secondary_tabs ?>
</div>
<?php echo $secondary_tabs->content ?>
