<?php
$me = L('ME');
$show_privacy = $me->is_allowed_to('查看联系方式', $user);
if ($show_privacy) :
?>
    <?php if ($user->phone) :?>
        <i class="icon-mobile middle"></i>
        <span class="phone middle" style="display: inline-block;min-width: 120px;"><?php echo H($user->phone)?></span>
    <?php endif;?>
    <?php if ($user->email) :?>
        <i class="icon-mail middle"></i>
        <span class="email middle"><a href="mailto:<?php echo H($user->email)?>"><?php echo H($user->email) ?></a></span>
    <?php endif;?>
<?php else:?>
    <p class="privacy"><?php echo I18N::T('people', '您没有权限查看')?></p>
<?php endif;?>
