<?php
    $me = L('ME');
    $show_privacy = $me->is_allowed_to('查看联系方式', $user);

    if ($user->email):
?>
    <?php 
        if ($show_privacy): ?>
            <a class="small" href="mailto:<?php echo H($user->email)?>"><?php echo H($user->email) ?></a>
    <?php else:?>
    <?php
        echo I18N::T('people', '您没有权限查看');
        endif;
    ?>
    <?php else:
        echo '&#160;';
    endif;
?>
