<div class="hr_1">&#160;</div>
<?php
$me = L('ME');
?>
<div class="form padding_1">
	<form method="post" autocomplete="off">
	<?php echo V('form_error', ['form'=>$form]);?>
	<?php $require = (string) V('form_require'); ?>
	<table class="form">
		<tbody>
			<tr>
				<td class="right nowrap middle"><?php echo I18N::T('projects', '任务名称')?></td>
				<td class="middle"><input name="name" class="text" size="40" value="<?php echo H($task->name) ?>" /></td>
			</tr>
			<tr>
				<td class="right nowrap top"><?php echo I18N::T('projects', '任务摘要')?></td>
				<td class="top">
					<textarea name="description" cols="40" class="text autogrow"><?php echo H($task->description) ?></textarea>
				</td>
			</tr>

			<tr>
				<td class="right nowrap top"><?php echo I18N::T('projects', '父节点')?></td>
				<td class="top">
					<?php echo V('task/parent',[
									'project'=>$project, 
									'task'=>$task, 
									'parent_task'=>$parent_task,
									'prev_task_id'=>$prev_task_id,
									'form' => $form
									]
								);
					?>&#160;&#160;&#160;
				</td>
			</tr>
			<tr>
				<td class="right nowrap top"><?php echo I18N::T('projects', '起止时间')?></td>
				<td class="middle">
					<?php
					if ($form->no_error) {
						if ($task->id) {
							$dtstart = $task->dtstart;
							$dtend = $task->dtend;
						}
						else{
							$dtstart = $parent_task->id ? $parent_task->dtstart : $project->task->dtstart;
							$dtend = $parent_task->id ? $parent_task->dtend : $project->task->dtend;
						}
					}
					else{
						$dtstart = $form['dtstart'];
						$dtend = $form['dtend'];
					}
					?>
					<input name="dtstart" class="text middle date" size="40" value="<?php echo $dtstart; ?>" />
					~
					<input name="dtend" class="text middle date" size="40" value="<?php echo $dtend; ?>" />
					<?php echo Form::checkbox('locked', $task->locked, '锁定', 'class="middle"', 'class="middle"'); ?>
				</td>			
			</tr>
			<tr>
				<td class="right nowrap middle"><?php echo I18N::T('projects', '操作')?></td>
				<td class="middle">
					<?php 
					if($task->type == Task_Model::TYPE_CONTAINER || $form['t'] == 'container'): 
						$checked = TRUE;
					endif; 
					$show = TRUE;
					if ($task->id) {
						if	($task->type==Task_Model::TYPE_CONTAINER) {
							$children = Q("task[parent={$task}]");
							if (count($children)>0) {
								$show = FALSE;
							}
						}
					}
					if ($show) {
						echo Form::checkbox('task_container', $checked, '任务目录', 'class="middle"', 'class="middle"');
					}
					else {
						echo Form::checkbox('', $checked, '任务目录', 'class="middle" disabled="true"', 'class="middle"');
					}
					?>
					<?php echo Form::checkbox('task_milestone', $task->milestone, '里程碑', 'class="middle"', 'class="middle"'); ?>
				</td>
			</tr>
			<tr>
				<td class="right nowrap middle"><?php echo I18N::T('projects', '参与者')?></td>
				<td class="top">
					<?php
						echo Widget::factory('projects:multi_user_selector', [
							'name'=>'attendees',
							'users'=>Q("{$task} user.attendee")
						]);
					?>
				</td>
			</tr>
			<tr>
				<td class="right nowrap middle"><?php echo I18N::T('projects', '开发人员')?></td>
				<td class="top">
					<?php
						echo Widget::factory('projects:multi_user_selector', [
							'name'=>'workers',
							'users'=>Q("{$task} user.worker")
						]);
					?>
				</td>
			</tr>
			<?php
			$roles = $task->user_roles($me);
			if($me->access('添加/修改任务', $task)):
				if(!in_array('parent_supervisor ', $roles)):
			?>
			<tr>
				<td class="right nowrap middle"><?php echo I18N::T('projects', '管理人员')?></td>
				<td class="top">
					<?php
						echo Widget::factory('projects:multi_user_selector', [
							'name'=>'supervisors',
							'users'=>Q("{$task} user.supervisor")
						]);
					?>
				</td>
			</tr>
			<?php 
				endif;
			endif;
			?>
		</tbody>
		<tfoot>
			<tr><td colspan="2" class="hr_1">&#160;</td></tr>
			<tr>
				<td>&#160;</td>
				<?php if($task->id): ?>
				<td>
					<input type="submit" name="submit" class="button button_save" value="<?php echo H(T('保存')) ?>" />
					<input type="reset" class="button button_cancel" value="<?php echo H(I18N::T('people', '取消')) ?>" />
					<?php 
					if(1):
					?>
					&#160;&#160;&#160;&#160;
					<a class="font-button-delete" confirm="<?php echo I18N::T('projects', '你确定要删除吗? 删除后不可恢复!'); ?>" href="<?php echo $task->url(NULL, NULL, NULL, 'delete'); ?>"><?php echo I18N::T('inventory', '删除')?></a>
					<?php endif;?>
				</td>
				<?php else: ?>
				<td>
					<input type="submit" name="submit" class="button button_add" value="<?php echo H(T('添加')) ?>" />
				</td>
				<?php endif; ?>
			</tr>
		</tfoot>
	</table>
	</form>
</div>

