<?php $me = L('ME');?>
<div class="hr_1">&#160;</div>
<div class="panel padding_1 clearfix">
	<?php
		$roles = $task->user_roles($me);
		$is_admin = L('ME')->access('添加/修改任务', $task) || L('ME')->access('添加/修改项目', $project);
		if ($task->type == Task_Model::TYPE_CONTAINER) :
			if (count($roles)>0 || $is_admin):
	?>
	<div class="float_left">
		<a href="<?php echo $task->url('timeline'); ?>" class="button"><?php echo I18N::T('projects', '时间线视图')?></a>
	</div>
	<?php 
			endif; 
		endif;
		if (in_array('worker', $roles) || in_array('supervisor', $roles) || in_array('parent_supervisor', $roles) || $is_admin):
	?>
	<div class="float_right">
		<a href="<?php echo $task->parent->id ? $task->url(NULL, NULL, NULL, 'edit') : $project->url(NULL, NULL, NULL, 'edit'); ?>" class="button button_edit"><?php echo I18N::T('projects', '编辑')?></a>
		<a href="<?php echo $task->url(NULL, NULL, NULL, 'add'); ?>" class="button button_add"><?php echo I18N::T('projects', '添加任务')?></a>
		<a href="<?php echo $task->url(NULL, 't=container', NULL, 'add'); ?>" class="button button_add"><?php echo I18N::T('projects', '添加任务集')?></a>
	</div>
	<?php
		endif;
	?>
</div>
<div class="hr_1">&#160;</div>

<div class="padding_1">
	<h1><?php echo I18N::T('projects', '基本信息') ?></h1>
	<hr/>
	
	<!-- 图示开始 -->
	<div class="container clearfix padding_1">
		<?php if ($task->prev->id): ?>
		<div class="box left clearfix">
			<div class="block prev"><a href="<?php echo H($task->prev->url() ) ?>"><?php echo H($task->prev->name) ?></a></div>
			<div class="line"></div>
		</div>
		<?php endif; ?>
		<div class="box middle">
			<?php if ($task->parent->id): ?>
			<div class="block parent"><a href="<?php echo H($task->parent->url() ) ?>"><?php echo H($task->parent->name) ?></a></div>
			<div class="line"></div>
			<?php endif; ?>
			<div class="block current">
				<?php echo Date::format($task->dtstart, 'Y/m/d').' - '.Date::format($task->dtend, 'Y/m/d') ?>
				<h3><a href="<?php echo H($task->url() ) ?>"><?php echo H($task->name) ?></a></h3>
				<p>
					<?php echo $task->locked ? I18N::T('projects', '(锁定)') : '' ?>
					&#160;&#160;
					<?php echo $task->approved ? I18N::T('projects', '结束') : I18N::T('projects', '未结束') ?>
					&#160;&#160;
					<?php 
					if($task->milestone): 
						if($task->dtrealend):
					?>
						<span>灰旗</span>
					<?php
						else:
					?>
						<span>红旗</span>
					<?php
						endif;
					endif;
					?>
				</p>
			</div>
		</div>
		<?php if ($task->next->id): ?>
		<div class="box right clearfix">
			<div class="line"></div>
			<div class="block next"><a href="<?php echo H($task->next->url() ) ?>"><?php echo H($task->next->name) ?></a></div>
		</div>
		<?php endif; ?>
	</div>
	
	<?php if ($task->type == Task_Model::TYPE_CONTAINER): ?>
		<div class="branches">
		<?php foreach($task->branches() as $branch): ?>
			<div class="branch clearfix">
				<?php foreach($branch as $obj): ?>
					<div class="block float_left"><a href="<?php echo H($obj->url() ) ?>"><?php echo H($obj->name) ?></a></div>
				<?php endforeach; ?>
			</div>
		<?php endforeach; ?>		
		</div>
	<?php endif; ?>
	
	<!-- 图示结束 -->
	<?php
		$supervisors = Q("$task user.supervisor");
		$workers = Q("$task user.worker");
		$attendees = Q("$task user.attendee");
	?>
	<?php if ($supervisors->total_count() > 0 || $workers->total_count() > 0 || $attendees->total_count() > 0): ?>
	<h1><?php echo I18N::T('projects', '人员分配') ?></h1>
	<hr/>
	<?php endif; ?>
	<?php if ($supervisors->total_count() > 0): ?>
	<div class="hr_2">&#160;</div>
	<?php echo V('projects:task/users', [
				'users' => $supervisors, 
				'task' => $task, 
				'title' => I18N::T('projects', '管理者'),
				'alert_url' => $task->url('supervisor', NULL, NULL, 'alert'),
			]); 
	?>
	<?php endif; ?>
	<?php if ($workers->total_count() > 0): ?>
	<div class="hr_2">&#160;</div>
	<?php echo V('projects:task/users', [
				'users' => $workers, 
				'task' => $task, 
				'title' => I18N::T('projects', '执行者'),
				'alert_url' => $task->url('worker', NULL, NULL, 'alert'),
			]); 
	?>
	<?php endif; ?>
	<?php if ($attendees->total_count() > 0): ?>
	<div class="hr_2">&#160;</div>
	<?php echo V('projects:task/users', [
				'users' => $attendees, 
				'task' => $task, 
				'title' => I18N::T('projects', '参与者'),
				'alert_url' => $task->url('attendee', NULL, NULL, 'alert'),
			]); 
	?>
	<?php endif; ?>
</div>
