<?php
foreach ($modules as $module) :
    if ($module->mid == 'eq_ban' && Module::is_installed('credit')) {
        continue;
    }

    $url = Config::get('eq_stat.url');
    if (($module->mid == 'eq_stat') && $url || !$module->name) {
        continue;
    }
    ?>
    <div class="perms_container" style="display: table;">

        <div class="perms_has_sub">
            <?php if ($module->name): ?>
                <div class="perm_module_title">
                    <?= I18N::HT($module->mid, $module->name) ?>
                </div>
            <?php endif; ?>
            <?php
            $sub_modules = Q("sub_module[module={$module}]");
            if ($sub_modules->total_count()):
                foreach ($sub_modules as $sub):
                    ?>
                    <div class="perm_submodule_title">
                        <span></span>
                        <?= I18N::HT($module->mid, $sub->name) ?>
                    </div>
                    <?php
                    $perms = Q("perm[sub_module={$sub}]:sort(weight A)");
                    if ($perms->total_count()):?>
                        <div class="perm_submodule_list">
                        <ul style="width: 100%">

                            <?php foreach ($perms as $perm):
                                if ($perm->name == '管理所有内容' || $perm->name == '管理组织机构') continue;
                                ?>

                                <li>
                                    <?= Form::checkbox("perms[{$role->id}][{$perm->id}]",
                                        in_array($perm->id, $select_perms) || in_array($perm->name, $default_perms),
                                        I18N::T($module->mid, $perm->name), ' data-rid=' . $role->id . ' class="rlist middle checkbox"'); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        </div>
                    <?php endif; ?>
                    <div class="clearfix"></div>

                <?php endforeach; ?>
            <?php else: ?>
                <?php
                $perms = Q("perm[module={$module}]:sort(weight A)");
                $select_perms = isset($select_perms) ? $select_perms : [];
                $default_perms = isset($default_perms) ? $default_perms : [];
                if ($perms->total_count()):?>
                    <div class="perm_submodule_list">
                        <ul style="width: 100%">
                            <?php foreach ($perms as $perm):
                                // if ($perm->name == '管理所有内容' && !L('ME')->access('管理所有内容')) continue;
                                if ($perm->name == '管理所有内容' || $perm->name == '管理组织机构') continue;
                                ?>
                                <li>
                                    <?= Form::checkbox("perms[{$role->id}][{$perm->id}]",
                                        in_array($perm->id, $select_perms) || in_array($perm->name, $default_perms),
                                        I18N::T($module->mid, $perm->name), ' data-rid=' . $role->id . ' class="rlist middle checkbox"'); ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>

<div class="interval_20"></div>
<div class="float_right">
    <input name="submit" type="submit" class="font-button-save" value="<?php echo H(I18N::T('roles', '保存')) ?>"/>
</div>
