<graph 
	baseFont="Arial" baseFontSize="13"  formatNumberScale='0' decimalPrecision='0' showColumnShadow='1' 
	animation='1' divlinedecimalPrecision='0' limitsdecimalPrecision='0' baseFontsize="11" hoverCapSepChar=" " yAxisMaxValue="5">
	<?php 
		$categories = (array)$lines[0]['points'];
		if (count($categories)): 
	?>
	<categories>
		<?php 
			foreach ($categories as $category): 
			$name = $category['label'];
		?>
		<category name="<?php echo H($name)?>" />
		<?php endforeach ?>
	</categories>
	<?php 
		foreach($lines as $key => $label) :
		$name = $label['label'];
		$color = $this->colors[$key%10];
		$sets = $label['points'];
	?>
	<dataset seriesName="<?php echo H($name)?>" color="<?php echo H($color)?>">	
		<?php 
			foreach($sets as $set):
			$val = $set['value'];
		?>
		<set value="<?php echo H($val)?>" />
		<?php endforeach ?>
	</dataset>
	<?php endforeach ?>
	<?php endif ?>
</graph>
