<div class="hr_1">&#160;</div>

<div class="panel padding_1 clearfix">
	<?php $me = L('ME'); ?>
	<div class="float_right">
	</div>
	<div class="nowrap">
	<a class="button button_add"><?php echo I18N::HT('workflows', '创建流程')?></a>
		&#160;&#160;
	</div>
</div>
<?php echo $pagination; ?>
<?php 

$table = Widget::factory('table');

$table->name = 'workflows';
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;

$table->add_columns([
	'@'=>[
		'extra_class'=>'tight',
	],
	'name'=>[
		'title'=>I18N::T('workflows', '流程名称'),
		'sortable'=>TRUE,
		'align'=>'left',
		'nowrap'=>TRUE,
		'filter'=> [
			'form' => V('workflows:workflows_table/filters/name.form', ['form'=>$form]),
			'value' => $form['name'] ? H($form['name']) : NULL
		],
		'extra_class' => 'tight',
	],
	'rest'=>[
		'extra_class' => 'flexible',
	],
]);

$table->empty_message = I18N::T('workflows', '无相关工作流程');

echo $table;

