<div class="description">
	<p>您可以查看所有成员基本信息。</p>
	<?php if ( Module::is_installed('labs') ) : ?>
	<p>您可以按照组织机构、姓名、地址、邮箱、电话、登录账号、实验室进行搜索。</p>
	<?php else : ?>
	<p>您可以按照组织机构、姓名、邮箱、电话、地址、登录账号进行搜索。</p>
	<?php endif; ?>
	<p>您可以修改您的部分个人信息。</p>
	<p>您可以关注其他用户成员，也可以对他们取消关注。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以添加新用户。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">点击姓名，可以查看其关注的成员、仪器、仪器预约、使用记录情况。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以点击 “修改” 激活该用户帐号或修改用户其他信息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>