<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo I18N::T('happy', '历史记录'); ?></title>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('happy', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('happy', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap"><?php echo I18N::T('happy', '选购单'); ?></caption>
			<thead id="stat">
				<tr>
					<td colspan='3' class="center">
						<?php echo $happyhour->title;?>
					</td>
				</tr>
			</thead>
			
			<thead>
				
				<tr>
					<?php foreach($properties_to_print as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('happy', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>

			<?php
			$num = 1;
			foreach($replys as $reply): ?>
				<tr>
					<?php foreach ($properties_to_print as $p => $p_name) : ?>
						<td class="left nowrap">
						<?php
							switch ($p) {
							case 'number':
								echo $num++;
								break;
							case 'content':
								echo  $reply->content ? : '--';
								break;
							case 'stock':
								echo $reply->stock ? : '--';
								break;
							default:
								break;
							}
						?>
					</td>
					<?php
					endforeach;
			endforeach;
			?>
				<tr>
					<td colspan="<?php echo count($properties_to_print) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('happy', '总计:') . $replys->length(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
