<div style="padding: 10px">
  <table class="table table-hover">
    <thead>
      <th align="left" width="30%"><?= I18N::T('equipments', '仪器名称') ?></th>
      <th align="left" width="40%"><?= I18N::T('equipments', '使用时间') ?></th>
      <th align="left" width="30%"><?= I18N::T('equipments', '收费') ?></th>
      <th>
        <span style="white-space: nowrap;"><?= I18N::T('eq_charge', '操作') ?></span>
      </th>
    </thead>
    <tbody>
      <?php 
      foreach ($records as $record) : 
      $charge = O('eq_charge', ['source' => $record]);
      ?>
      <tr>
        <td width="30%">
          <h5>
            <?= H($record->equipment->name) ?><br />
          </h5>
        </td>
        <td width="40%">
          <h4>
            <small>
              <?= Date::relative($record->dtstart); ?> - 
              <?= Date::relative($record->dtend, $record->dtstart); ?>
            </small>
          </h4>
        </td>
        <td width="30%">
          <h4>
            <?php $amount = $charge->id ? $charge->amount : 0 ?>
            <small><?= H('￥' . $amount) ?></small>
          </h4>
        </td>
        <td style="width: 50px">
          <a class="btn btn-primary btn-xs" target="_blank"
          href="<?= URI::url("!equipments/equipment/index.{$record->equipment->id}.feedback") ?>">
            <?= I18N::T('equipments', '反馈') ?>
          </a>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
