<?php $require = (string) V('form_require', ['extra_class' => 'top vidcam_require'])?>
<div class="form ">
    <form class="prevent_default vidcam" method="post" autocomplete="off" q-object="vidcam_edit" q-event="submit"
        q-static="<?php echo H(['vidcam_id' => $vidcam->id]) ?>">
        <?php echo V('form_error', ['form' => $form]); ?>
        <table class="form">
            <tbody>
                <tr>
                    <td class="nowrap label top" colspan=2>
                        <div class="title">
                            <?php echo $require; ?>
                            <?php echo I18N::T('vidmon', '名称'); ?>
                            <?php echo V('form_filter', ['error' => $form->errors['name'][0]]) ?>
                        </div>

                        <input name="name" class="text vidcam_input" value="<?php echo H($vidcam->name); ?>" />
                    </td>
                </tr>
                <?php if (Config::get('stream')['use_stream']): ?>
                    <tr>
                        <td class="nowrap label top"><?php echo I18N::T('vidmon', '标识'); ?></td>
                        <td class="nowrap top">
                            <input name="uuid" class="text vidcam_input" value="<?php echo H($vidcam->uuid); ?>" />
                            <?php echo $require;?></td>
                        </tr>
                        <tr>
                        <td class="nowrap label top"><?php echo I18N::T('vidmon', '类型');?></td>
                        <td class="nowrap">
                            <?= Form::dropdown('type', I18N::T('vidmon', Vidcam_Model::$type), $vidcam->type, 'class="dropdown"'); ?><?php echo $require?>
                        </td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td class="nowrap label top" colspan=2>
                        <div class="title">
                            <?php echo $require; ?>
                            <?php echo I18N::T('vidmon', '负责人'); ?>
                            <?php echo V('form_filter', ['error' => $form->errors['incharge'][0]]) ?>
                        </div>
                        <?php
                            $incharges = Q("{$vidcam} user.incharge")->to_assoc('id', 'name');
                            echo Widget::factory('multi_user_selector', [
                                'autocomplete'=>URI::url('autocomplete/user'),
                                'name'=>'incharge',
                                'value'=>$form['incharge'] ? : json_encode($incharges, TRUE),
                                'extra'=>'token_verify vidcam_incharge_input',
                            ]);
                        ?>
                    </td>

                </tr>
                <tr>
                    <td class="nowrap label top" colspan=2>
                        <?php echo I18N::T('vidmon', '地址'); ?>
                    </td>
                </tr>
                <tr class="double">
                    <td class="nowrap label top">
                        <input name="location" placeholder='楼宇名称' class="text vidcam_input tooltip_position:left"
                            q-tooltip="<?php echo I18N::T('vidmon', '楼宇名称'); ?>" value="<?php echo H($vidcam->location); ?>" />
                    </td>
                    <td class="nowrap label top">
                        <input name="location2" placeholder='房间号' class="text vidcam_input tooltip_position:left"
                            q-tooltip="<?php echo I18N::T('vidmon', '房间号'); ?>" value="<?php echo H($vidcam->location2); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="nowrap label top">
                        <?php
                            $admin_tokens = array_map('Auth::normalize', (array) Config::get('lab.admin'));
                            if (in_array(L('ME')->token, $admin_tokens)):
                        ?>
                        <div class="title">

                            <?php echo $require ?>

                            <?php echo I18N::T('vidmon', '控制地址'); ?>
                            <?php echo V('form_filter', ['error' => $form->errors['control_address'][0]]) ?>
                        </div>
                        <input name="control_address" class="text vidcam_input" value="<?php echo H($vidcam->control_address); ?>" />
                    </td>
                </tr>
                <?php endif;?>
                <?= Event::trigger('vidcam[edit].view.extra', $form, $vidcam); ?>

            </tbody>
        </table>
        <?php $can_delete = L('ME')->is_allowed_to('删除', $vidcam);?>
        <div class="button_container">
            <div class="float_right">
                <?php if ($can_delete) : ?>
                    <input class="font-button-delete rmargin_16" name="delete" type="button" q-static="<?php echo H(['vidcam_id'=>$vidcam->id])?>" q-src="<?php echo H(URI::url('!vidmon/vidcam')) ?>" q-event="click" q-object="delete_vidcam" value="<?php echo H(I18N::T('vidmon', '删除')) ?>" />
                <?php endif;?>
                <input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('vidmon', '取消'); ?>" />
                <input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('vidmon', '更新'); ?>" />
                
            </div>
        </div>
    </form>
</div>
