<div class="hr_1">&#160;</div>
<div class="single_video float_left">
    <div class="single_video_body loading">
		<video muted style="width: 352px; height: 288px;" class="stream" data-id="<?= H($vidcam->id); ?>"></video>
	</div>
</div>
<script type="text/javascript">
$(function() {
    var start = function() {
        Q.trigger({
            object: 'stream_address',
            event: 'click',
            url: '<?= URI::url('!vidmon/vidcam'); ?>',
            global: false,
            data: {
                id: $('.stream').data('id'),
            },
            success: function(res) {
                _preview(res.stream_address);
            }
        });
    }

    function _preview(stream_address) {
        var hls = new Hls();
        var video = document.querySelector('.stream');

        if(Hls.isSupported()) {
            hls.loadSource(stream_address);
            hls.attachMedia(video);
            hls.once(Hls.Events.MANIFEST_PARSED, function() {
                video.play().catch(function(e) {
                    window.location.replace(window.location.href);
                });
            });

            hls.once(Hls.Events.ERROR, function(event, data) {
                if (data.fatal) {
                    switch(data.type) {
                        case Hls.ErrorTypes.NETWORK_ERROR:
                            hls.startLoad();
                            break;
                        case Hls.ErrorTypes.MEDIA_ERROR:
                            hls.recoverMediaError();
                            break;
                        default:
                            hls.destroy();
                            break;
                    }
                }
                start();
            });
        } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
            video.src = stream_address;
            video.addEventListener('loadedmetadata',function() {
                video.play().catch(function(e) {
                    window.location.replace(window.location.href);
                });
            });
        }
    }

    start();
});
</script>
