<?php $form = $form['struct'][$flexform_index]; ?>
<table class="form" style="width: 100%">
	<tbody>
		<tr>
			<td class="nowrap left">
                <?php echo $require; ?><?php echo I18N::T('cers', '机组名称')?>
			</td>
            <td class="nowrap">
                <?php echo I18N::T('cers', '机组类型')?>
            </td>
        </tr>
        <tr><td><div class="interval_16"></div> </td></tr>
        <tr>
			<td class="nowrap">
				<input class="text" size="60" placeholder="请输入机组名称" name="struct[<?php echo $flexform_index?>][name]" value="<?php echo H($no_error ? $name : $form['name']) ?>" size="40" />
			</td>
            <td class="nowrap dropdown_special">
                <?php
                $selectors = [0 => I18N::T('cers', '普通机组'), 1 => I18N::T('cers', '示范机组')];
                echo Form::dropdown("struct[$flexform_index][type]", $selectors , $no_error ? (int)$type : (int)$form['type'], 'class="dropdown" '); ?>
            </td>
		</tr>
        <tr><td><div class="interval_20"></div> </td></tr>
		<tr>
			<td class="nowrap left top">
                <?php echo $require; ?><?php echo I18N::T('cers', '负责人')?>
			</td>
            <td class="nowrap top">
                <?php echo I18N::T('cers', '机组描述')?>
            </td>
		</tr>
        <tr><td><div class="interval_16"></div> </td></tr>
        <tr>
            <td class="nowrap">
                <div style="width: 442px">
                    <?php
                    echo Widget::factory('multi_user_selector',
                        [
                            'name'=>"struct[$flexform_index][contacts]",
                            'autocomplete'=>URI::url('autocomplete/user'),
                            'value'=> $no_error ? $contacts : $form['contacts'],
                            'extra'=>'token_verify',
                            'size' => 40
                        ]);
                    ?>
                </div>
            </td>
            <td>
                <textarea placeholder="请输入机组描述" class="text autogrow" rows="3" cols="63" name="struct[<?php echo $flexform_index?>][description]"><?php echo $no_error ? $description : $form['description']?></textarea>
            </td>
        </tr>
        <tr><td><div class="interval_60"></div> </td></tr>
	</tbody>
</table>
