<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('billing', '财务列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
			.align_right {
				text-align:right;
			}

		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('billing', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('billing', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                	echo I18N::HT('billing', '财务列表');
                ?>

            </caption>
			<thead>
				 <?php
				 		if ($accounts->total_count()) {
                            $statics = Event::trigger('billing.account.statics.row', $accounts, $has_remote_billing, $form);
                            if (isset($statics['tol_amount']) && isset($statics['tol_amount_confirmed']) && isset($statics['tol_use']) && isset($statics['tol_balance'])) {
                                $tol_amount = (double)$statics['tol_amount'];
                                $tol_amount_confirmed = (double)$statics['tol_amount_confirmed'];
                                $tol_use = (double)$statics['tol_use'];
                                $tol_balance = (double)$statics['tol_balance'];
                            } else {
                            //余额
						 	$tol_balance = $accounts->sum('balance');

                            $has_remote_billing = count(Config::get('billing.sources'));

                            //如果有远程billng
                            if ($has_remote_billing) {
                                //总收入
                                //
                                $tol_amount =
                                    $accounts->sum('income_remote')  //远程充值
                                    -
                                    $accounts->sum('outcome_remote') //远程扣费
                                    +
                                    $accounts->sum('income_local')  //本地充值
                                    -
                                    $accounts->sum('outcome_local'); //本地扣费

                                $tol_amount_confirmed =
                                    $accounts->sum('income_remote_confirmed')  //远程充值confirmed
                                    -
                                    $accounts->sum('outcome_remote') //远程扣费
                                    +
                                    $accounts->sum('income_local')  //本地充值
                                    -
                                    $accounts->sum('outcome_local'); //本地扣费

                            }
                            else {
                                //总收入
                                //本地收入 - 本地扣费
                                $tol_amount = $accounts->sum('income_local') - $accounts->sum('outcome_local');
                            }

						 	$tol_use = $accounts->sum('outcome_use');
                            }
						 	$tol_credit_line = $accounts->sum('credit_line');
						}
			 	?>
				<tr>	
					<td colspan="<?php echo count($valid_columns); ?>" class="align_right">

                        <?php if ($object_name == 'billing_department') :?>
                            <p><?php echo I18N::HT('billing', '当前所有实验室的总收入为%tol_amount', ['%tol_amount' => Number::currency($tol_amount)]); ?></p>
                        <?php elseif ($object_name == 'lab') : ?>
                            <p><?php echo I18N::HT('billing', '当前总收入为%tol_amount', ['%tol_amount' => Number::currency($tol_amount)]); ?></p>
                        <?php endif;?>
                        <?php if ($has_remote_billing) :?>
                            <p><?php echo I18N::HT('billing', '当前有效入为%tol_amount_confirmed', ['%tol_amount_confirmed' => Number::currency($tol_amount_confirmed)]); ?></p>
                        <?php endif;?>

                        <p><?php echo I18N::HT('billing', '总费用%tol_use', ['%tol_use' => Number::currency($tol_use)]); ?></p>
                        <p><?php echo I18N::HT('billing', '总余额%tol_balance', ['%tol_balance' => Number::currency($tol_balance)]); ?></p>
                        <p><?php echo I18N::HT('billing', '总信用额度%tol_credit_line', ['%tol_credit_line' => Number::currency($tol_credit_line)]); ?></p>
					</td>			
				</tr>

				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('billing', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($accounts as $account):
                Event::trigger('billing.account.table_list.row', $account, $has_remote_billing, $form);
			?>
				<tr>
					<?php if(array_key_exists('billing_department', $valid_columns)):?>
						<td>
							<?php echo H($account->department->name)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('lab', $valid_columns)):?>
						<td>
							<?php echo H($account->lab->name)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('income_remote', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->income_remote))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('income_remote_confirmed', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->income_remote_confirmed))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('income_local', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->income_local))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('income_transfer', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->income_transfer))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('outcome_remote', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->outcome_remote))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('outcome_local', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->outcome_local))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('outcome_use', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->outcome_use))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('outcome_transfer', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->outcome_transfer))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('balance', $valid_columns)):?>
						<td>
                        <?php echo H(Number::currency($account->balance))?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if(array_key_exists('credit_line', $valid_columns)):?>
						<td>
							<?php echo H(Number::currency($account->credit_line))?:'-'; ?>
						</td>
					<?php endif; ?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</body>
</html>
