<?php
$me = L("ME");
$root = $this->root->id ? $root : Tag_Model::root('group');
$tag = O('tag_group', $form['group']);
/*
NO. TASK#249 (Cheng.Liu@2010.11.18)
billing模块 account列表转换成 table widget
*/
$table = Widget::factory('table');
$table->name = 'billing_accounts';
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;

$table->add_columns($column);
$table->add_sub_columns($sub_column);

$table->empty_message = I18N::T('billing', '没有符合条件的帐号');

if (count($accounts) > 0) foreach ($accounts as $account) {
	if ($me->is_allowed_to('查看', $account)) {

        $row = [
            // 'id' => V('billing:accounts_table/data/id', ['account'=>$account]),
            'lab_name'=>V('billing:accounts_table/data/lab_name', ['account'=>$account]),
            'department'=>V('billing:accounts_table/data/department', ['account'=>$account, 'object'=>$object/*$object->name()==='lab'*/]),
            //'amount'=>V('billing:accounts_table/data/lab_amount', array('account'=> $account)), //旧方案中的 收入
            //'expense'=>V('billing:accounts_table/data/lab_expense', array('account'=> $account)), //旧方案中的 过期支出
            'outcome_local'=> $form['site'] ? V('db_sync:accounts_table/data/outcome/local', ['account'=> $account,'site'=>$form['site']])
                : V('billing:accounts_table/data/outcome/local', ['account'=> $account]), //本地扣费
            'outcome_use'=> $form['site'] ? V('db_sync:accounts_table/data/outcome/use', ['account'=> $account,'site'=>$form['site']])
                : V('billing:accounts_table/data/outcome/use', ['account'=> $account]), //使用收费
            'outcome_transfer'=> $form['site'] ? V('db_sync:accounts_table/data/outcome/transfer', ['account'=> $account,'site'=>$form['site']])
                : V('billing:accounts_table/data/outcome/transfer', ['account'=> $account]), //调账
            'balance'=>V('billing:accounts_table/data/lab_balance', ['account'=>$account]),
            'credit_line'=>H(Number::currency($account->credit_line)),
            'rest' => V('billing:accounts_table/data/rest', ['account'=>$account]),
            'income_local'=> $form['site'] ? V('db_sync:accounts_table/data/income/local', ['account'=> $account,'site'=>$form['site']])
                : V('billing:accounts_table/data/income/local', ['account'=> $account]), //本地充值
            'income_transfer'=> $form['site'] ? V('db_sync:accounts_table/data/income/transfer', ['account'=> $account,'site'=>$form['site']])
                : V('billing:accounts_table/data/income/transfer', ['account'=> $account]), //调账
        ];
        
        if ($has_remote_billing) {
            $row['income_remote'] = V('billing:accounts_table/data/income/remote', ['account'=> $account]); //远程充值
            $row['income_remote_confirmed'] = V('billing:accounts_table/data/income/remote_confirmed', ['account'=> $account]); //有效远程充值
            $row['outcome_remote'] = V('billing:accounts_table/data/outcome/remote', ['account'=> $account]); //远程扣费
        }
        Event::trigger('billing.account.table_list.row', $account, $has_remote_billing, $form);
        $table->add_row($row);
	}
}

echo $table;
?>

<div class="pages"><?= $pagination ?></div>
