<!DOCTYPE html>
<html>
<head>
	<style>
		div {
			font-size: 14px;
		}
		.hr_1 {
			padding-top: 42px;
		}
		.indent {
			font-size: 14px;
			margin-left: 42px;
			padding: 4px;
		}
		.padding-tb {
			padding: 5px 0px;
		}
		table.email {
			font-size: 14px;
			margin:auto;
		}
		table .header {
			font-size: 16px;
			min-width: 120px;
		}
		table .right {
			text-align: right;

		}
		thead{
			border-top:2px solid  #000;
			border-bottom:1px solid #000;
		}

		tbody{
			border-bottom:2px solid #000;
		}

		thead#stat{
			font-size: 10px;
			border:none;
		}

		table.email caption {
			font-size: 150%;
			margin-bottom: 10px;
		}

		table.email tbody td {
			vertical-align: center;
			border-bottom: 1px solid #CCC;
		}
		table.email {
			background-color: #eee;
			border:1px dotted #CCC;
			border-left: none;
			border-right: none;
		}
		table.email > tbody > tr:nth-of-type(odd) {
			background-color: #f9f9f9;
		}
	</style>
</head>
<body>
	<table class="email" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
		<caption><?php echo I18N::T('eq_charge', '财务明细报表'); ?></caption>
		<thead>
			<tr>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '使用者'); ?>
				</td>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '仪器/财务账号'); ?>
                </td>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '转入金额'); ?>
				</td>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '转出金额'); ?>
				</td>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '时间'); ?>
				</td>
				<td class="header padding-rl">
					<?php echo I18N::T('eq_charge', '备注'); ?>
				</td>
			</tr>
		</thead>
		<tbody>
			<?php if ($transactions) foreach ($transactions as $transaction) : ?>
			<tr>
				<td><?php echo strip_tags(new Markup($transaction->description['%user'], true)) ?></td>
				<?php if ($transaction->income > 0) :?>
				<td><?php echo strip_tags(new Markup($transaction->description['%account'], true)) ?></td>
                <td><?php echo Number::currency($transaction->income); ?></td>
                <td><?php echo '--' ?></td>
                <?php else: ?>
                <td><?php echo strip_tags(new Markup($transaction->description['%equipment'], true)) ?></td>
                <td><?php echo '--' ?></td>
                <td><?php echo Number::currency($transaction->outcome) ?></td>
                <?php endif;?>
				<td><?php echo Date::format($transaction->ctime, 'Y/m/d H:i'); ?></td>
				<td><?php echo strip_tags(str_replace('<br>', "\r\n", $transaction->description())) ? : '--' ?></td>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td class="right" colspan="6">
					<?php echo I18N::T('eq_charge', '转入总和');?>:
					&nbsp;
					<?php echo Number::currency($transactions->sum(income));?>
					&nbsp;
				</td>
			</tr>
			<tr>
				<td class="right" colspan="6">
					<?php echo I18N::T('eq_charge', '转出总和');?>:
					&nbsp;
					<?php echo Number::currency($transactions->sum(outcome));?>
					&nbsp;
				</td>
			</tr>
		</tbody>
	</table>
	<div class="hr_1">
		<br />
		如果您想要了解更多信息，请您登录
		<a href="<?php echo Config::get('system.base_url')?>">
			<?php echo Config::get('page.title_default'); ?>
		</a>
	</div>
	<div class="padding-tb">Labscout LIMS Team</div>
</body>
</html>
