<div class="form">
    <?php if ($type == 'csv'): ?>
        <form id="account_form" method="POST" q-object="billing_account_export" q-src="<?= URI::url('!billing/department') ?>" q-static="<?php echo
        H(['form_token'=>$form_token, 'type' => $type, 'object_name' => $object_name])?>" q-event="submit" autocomplete="off" class="prevent_default">
    <?php else: ?>
        <form 
  		    action="<?php echo H(URI::url('!billing/department', ['type' => $type, 
  																  'form_token' => $form_token, 
  																  'object_name'=>$object_name])) ?>" 
  		    target="<?php echo H(($type == 'csv' ? '_self' : '_blank') ) ?>" 
  		    class="prevent_default" method="post">
	<?php endif; ?>
	<div class="interval_20">&nbsp</div>
		<ul class="ep_triple" >
			<?php
			foreach ($columns as $p => $p_name) :?>
				<li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('billing', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>
				</li>
			<?php endforeach;?>
		</ul>	
		<div class="button_container">
		<div class="float_right">
		<input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('billing', '取消');?>" />
		<input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('billing', '提交');?>" />
		</div>
		</div>
  </form>
</div>


