<table class="form" style="width: 50%">
  <tr>
    <td colspan="2">
      <h4><?php echo I18N::T('yiqikong_approval', '不受限用户设置'); ?></h4>
    </td>
  </tr>
  <tr>
    <td class="left nowrap top">
      <?php extract($uncontrolInfo);?>
      <?= Form::checkbox("select_user_mode_user[{$flexform_index}]", !!$uncontroluser,
        I18N::T('yiqikong_approval','个别用户'), 'class="middle monitor" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
    </td>
    <td>
      <?= implode(',', json_decode($uncontroluser, true) ? : []); ?>
    </td>
  </tr>
  <?php if (!$GLOBALS['preload']['people.multi_lab'] && Module::is_installed('labs')): ?>
  <tr>
    <td class="left nowrap top">
      <?= Form::checkbox("select_user_mode_lab[{$flexform_index}]", $uncontrollab,
        I18N::T('yiqikong_approval','课题组'),'class="middle monitor" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
    </td>
    <td>
      <?= implode(',', json_decode($uncontrollab, true) ? : []); ?>
    </td>
  </tr>
  <?php endif ?>
  <tr>
    <td class="left nowrap top">
      <?= Form::checkbox("select_user_mode_group[{$flexform_index}]", $uncontrolgroup,
        I18N::T('yiqikong_approval','组织机构'),'class="middle monitor" disabled="disabled"', 'class="middle monitor" disabled="disabled"') ?>
    </td>
    <td>
      <?= implode(',', json_decode($uncontrolgroup, true) ? : []); ?>
    </td>
  </tr>
</table>
