<?php
$tip = Config::get('eq_evaluate')['rate.tip'];
$baseline = Config::get('eq_evaluate')['rate.baseline'];
$default = Config::get('eq_evaluate')['default.rate'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" style="overflow: hidden; margin: 0px;">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

    <title>Glogon退出登录</title>
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />

    <base href="<?php echo H(Config::get('system.base_url') ) ?>" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <?php echo $this->controller->load_css(); ?>
    <link href="<?php echo Config::get('system.base_url') ?>gini-ui/iconfont.css" rel="stylesheet" />
    <?php echo $this->controller->load_js(TRUE); ?>

    <style>
        body {
            background: #f5f7fa;
            position: relative;
            font-size: 14px;
        }

        table.form td {
            padding: 3px;
            font-weight: normal;
        }

        table.form td.right {
            text-align: right;
        }

        input[name="samples"], select, textarea {
            border: 1px solid #E5E5E5;
            height: 30px;
            padding: 0 10px;
            outline: none;
            border-radius: 3px;
            width: 346px;
            box-sizing: border-box;
            font-size: 14px;
        }

        textarea {
            resize: none;
            height: 45px;
        }

        .dropdown_container {
            width: 278px;
        }

        .dropdown_menu {
            max-height: 150px;
            overflow-y: scroll;
        }
        div.form {
            padding: 10px 20px;
            background: none;
            width: 480px;
            box-sizing: border-box;
        }

        .radio {
            vertical-align: unset;
        }
    </style>

</head>
<body>
    <img src="<?php echo H(URI::url('!equipments/images/glogon_banner.bmp')) ?>" />
    <div style="height: 400px; overflow-y: scroll; position: relative;" class="form">
        <form window_width="<?php echo H(Config::get('glogon.logout.window_width', 420)) ?>" window_height="<?php echo H(Config::get('glogon.logout.window_height.with_evaluate', Config::get('glogon.logout.window_height', 420))) ?>" action="glogon_action_submit" method="get" id="form">
            <table class="form">
                <tr>
                    <td class="middle right label nowrap">
                        <?php echo I18N::T('equipments', '仪器状态')?>
                    </td>
                    <td class="middle label">
                        <input id="status_normal" name="status" type="radio" class="radio" value_type="int" value="1" checked="true"> <label for="status_normal"><?= I18N::T('equipments', '正常') ?></label>
                        <input id="status_broken" name="status" type="radio" class="radio" value_type="int" value="-1"> <label for="status_broken"><?= I18N::T('equipments', '故障') ?></label>
                    </td>
                </tr>
                <?php if (Config::get('equipment.feedback_show_samples', 0)): ?>
                <tr>
                    <td class="middle right label nowrap">
                        <?php echo I18N::T('equipments', '样品数')?>
                    </td>
                    <td class="top">
                        <input id="samples" type="text" name="samples" class="text number" value_type="int" number="true" _name="样品数" value="<?= Config::get('eq_record.must_samples') ? 0 : Config::get('eq_record.record_default_samples')?>" id="samples" />
                    </td>
                </tr>
                <?php endif;?>
                <?php echo V('equipments:glogon/logout_projects', [
                    'user' => $user,
                    'projects' => $projects,
                    'lab_id' => $lab_id,
                ]);?>
                <tr>
                    <td class="top right label nowrap">
                        <?php echo I18N::T('equipments', '反馈');?>
                    </td>
                    <td class="top">
                        <textarea name="feedback"></textarea>
                    </td>
                </tr>
                <?php echo V('equipments:glogon/logout_extra', ['user' => $user, 'equipment' => $equipment]);?>
                <style type="text/css">
                td.wrap {
                <?php if (Config::get('system.locale') == 'en_US') :?>
                    line-height: 16px !important;
                    width: 110px !important;
                <?php else :?>
                   width: 100px !important;
                <?php endif;?>
                }
                </style>
                <tr>
                    <td class="top right label wrap">
                        <?php echo Config::get('eq_evaluate')['score.require'] ? I18N::T('equipments', '*') : '';?>
                        <?php echo I18N::T('equipments', '服务态度');?>
                    </td>
                    <td class="middle">
                        <span style="margin-left: -5px; display: inline-block; width: 130px; "><?php echo Widget::factory('rateit_input', ['name' => "score", 'rateit_value' => Config::get('eq_evaluate')['default.rate'], 'rateit_tip' => TRUE, 'tip' => $tip]) ?></span>
                        <br/>
                        <?php // echo I18N::T('equipments', '当评分小于'.$baseline.'星时需填写评价');?>
                    </td>
                </tr>
                <tr>
                    <td class="top right label nowrap">
                        <?php echo I18N::T('equipments', '服务评价');?>
                    </td>
                    <td class="top">
                        <textarea name="content" rows="6" cols="30"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>&#160;</td>
                    <td class="content">
                        <input id="submit" class="font-button-save" type="submit" value="<?php echo H(I18N::T('equipments', '提交')) ?>" />
                        &#160;
                        <input id="reset" class="font-button-default" type="button" value="<?php echo H(I18N::T('equipments', '取消')) ?>" onclick="javascript:window.location.href='glogon_action_cancel'"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>
<script type="text/javascript">
    window.onload = function(){
        var $form = document.getElementById('form');
        var msg = [];

        function get_radio_value(obj_name) {
            var obj = document.getElementsByName(obj_name);
            for(i = 0; i < obj_name.length; i++){
                if(obj[i].checked){
                    return obj[i].value;
                }
            }
        }

        document.getElementById('submit').onclick = function() {
            var $samples_input = document.getElementById('samples');
            var sample_input_val = $samples_input.value;

            if (sample_input_val <= 0) {
                msg.push('<?php echo I18N::T('equipments', '样品数填写有误, 请填写大于0的整数!')?>');
            }

            /* if ('<?php // echo $check_project ?>') {
            var project_val = $form.find(':input[name=project]').val();

            if (project_val == 0) {
                msg.push('<?php // echo I18N::T('equipments', '请选择项目后再进行提交!')?>');
            }
        } */

            if (get_radio_value('status') == <?= EQ_Record_Model::FEEDBACK_PROBLEM ?>) {
                if (!$form.getElementByName('feedback').value) {
                    msg.push("<?= I18N::T('equipments', '请填写故障的反馈备注!')?>");
                }
            }

            if(msg.length){
                if (msg.length) {
                    alert(msg.join('\n'));
                    msg = []
                    return false;
                }
            }

            // $form.getElementBy
            // $form.find(':input[name=project]:disabled').remove();
        }
    }
</script>
</html>
