<div class="float_left list_video">
    <?php $video_img_id = 'video_img'. uniqid();?>
    <div class="list_video_title">
        <div class="list_video_name clearfix">
            <span class="float_left">
                <h4>
                    <a href="<?php echo H($vidcam->url()) ?>"><?php echo H($vidcam->name)?></a>
                </h4>
            </span>
        </div>
            <div class="list_video_address">
            <?php echo V('vidcam_table/data/location', ['vidcam'=>$vidcam])?>
        </div>
    </div>
    <div class="list_video_monitor loading video_monitor_<?php echo $vidcam->id?>" style="width:212px;height:160px">
        <a href="<?php echo H($vidcam->url() ) ?>">
            <video muted style="width: 212px; height: 160px;" class="<?= $vidcam->uuid; ?>" data-id="<?= H($vidcam->id) ?>" data-src="<?php 
                    $scheme = $_SERVER['HTTP_X_FORWARDED_PROTO'] ?: ($_SERVER['HTTPS'] ? 'https' : 'http');
                    $stream_address = str_replace(["http://", "https://"], "$scheme://", $vidcam->stream_address);
                    echo $stream_address = preg_replace('/^(http|https):\/\/([^\/]+)(.*)$/', "$1://".$_SERVER['HTTP_HOST']."$3", $stream_address); 
            ?>"></video>
        </a>
    </div>
</div>
