<?php
	$auth_backends = Config::get('auth.backends');
	$is_hide = FALSE;
	if (count($auth_backends) > 1) {
		$hidden = [];
		foreach ($auth_backends as $key => $backend) {
			if ($backend['readonly']) {
				$hidden[] = $key;
			}
		}
		if (count($hidden)) $class = "toggle:".$this->name.' hide_on:'.join(' hide_on:', $hidden);
	}
	else {
		$default_backend = $this->default_backend ?: Config::get('auth.default_backend');
		if ($auth_backends[$default_backend]['readonly']) {
			$is_hide = TRUE;
		}
	}

	$rs = Lab_Model::add_require_fields();
?>
<?php if (!$is_hide): ?>
<tr class="<?php echo H($class) ?>">
	<td class="label left nowrap">
	<div class="title"><?php if ($rs['passwd']) : ?><span class="required">*</span><?php endif; ?><span><?php echo I18N::T('people', '密码')?></span></div>
		<input name="password" type="password" autocomplete="new-password" class="text" size="40" />
	</td>

	<td class="label left nowrap">
		<div class="title"><?php if ($rs['confirm_passwd']) : ?><span class="required">*</span><?php endif; ?><?php echo I18N::T('people', '确认密码')?></div>
		<input name="confirm_password" type="password" class="text" size="40" />
	</td>
</tr>
<tr>
	<td colspan="2" style="padding-top: 0;"><div class="interval_6"></div></td>
</tr>
<tr class="top description">
	<td class="red" style="padding-top:0px !important"><?= H(T('8-24个字符，必须包含数字和大小写字母')) ?></td>
	<td style="padding-top:0px !important"><?php echo Form::checkbox('must_change_password', !!(empty($form['must_change_password']) || $form['must_change_password']=='null'?false:true), I18N::T('people', '第一次登录时修改密码'),'class="middle checkbox"','class="middle"'); ?></td>
</tr>

<?php endif; ?>
