<div class="form">
    <form
        method="post"
        q-object="add_lab_member"
        action="<?php echo H(URI::url('!labs/lab')) ?>"
        autocomplete="off">
        <?php echo V('form_error', ['form'=>$form]);?>
        <?php 
	$add_methods = Config::get('labs.add_member_method', TRUE);
?>

        <table class="form flexible">
            <tr class="begin">
                <td class="label left top nowrap ">
                    <h1 class="blue">
                        <?php echo I18N::T('people', '添加来源') ?>
                    </h1>
                </td>
                <td style="padding-left: 0;">
                    <span class="float_right">
                        <span class="require "><span class="required">*</span></span>
                        必填
                    </span>
                </td>
            </tr>

            <tr>
                <td class="label left middle nowrap" width="80px;">
                    <?php 
                    foreach ($add_methods as $method => $name) {
					    echo Form::radio('add_from', $method, array_keys($add_methods)[0] == $method, I18N::T('labs', $name), 'class="radio monitor"', 'class="rmargin_40 middle"');
                    }
                    ?>
                </td>
            </tr>
        </table>
        <?php foreach ($add_methods as $method => $name) {
		$view = V("labs:lab/add_member_table/{$method}", [
				'lab' => $lab,
				'form' => $form,
				'method' => $method
			]);
		echo $view;
	}?>

    <div class="button_container">
        <div class="float_right">
            <input
                name="cancel"
                id="cancel"
                type='reset'
                class="font-button-default sm rmargin_2e4"
                value="<?php echo I18N::HT('people', '取消');?>"/>
            <input
                name="submit"
                type='submit'
                class="font-button-save sm"
                value="<?php echo I18N::HT('people', '添加');?>"/>
        </div>
    </div>

    </form>
</div>