<?php
/* $shortcuts = Config::get('lab.shortcuts');
if (count($shortcuts)>0) {
	$i = 0;
	foreach ($shortcuts as $shortcut) {
		$output = (string)(V($shortcut));
		if ($output) {
			if($i == 0){
				echo '<div class="shortcuts shortcut_title">快捷方式</div>';
			}
			$odd = $i % 2 ? 'even':'odd';
			// if ($i > 0 && $output) // echo '<div class="hr_1">&#160;</div><hr /><div class="hr_1">&#160;</div>';
			echo '<div class="shortcut shortcut_'.$odd.'">'.$output.'</div>';
			$i++;
		}
	}
} */
