<?php
$me = L('ME');
$val = json_encode([$incharges->id => $incharges->name]);

if (($me->access('管理所有内容')
    ||$me->access('管理组织机构')) 
    || (($me->access('添加/修改所有机构的仪器')
    || $me->access('添加/修改下属机构的仪器'))
    && !$me->access('添加负责的仪器'))) {
    echo Widget::factory('multi_user_selector', [
        'name' => 'incharges',
        'autocomplete' => URI::url('autocomplete/user'), 
        'value' => $form['incharges'],
        'extra' => 'token_verify'
    ]);
} else {
    echo $incharges->name;
    echo '<input type="hidden" name="incharges" value=\''.$val.'\' />';
}

?>
