<?php
$me = L('ME');
$val = json_encode([$contacts->id => $contacts->name]);

if (($me->access('管理所有内容')
    ||$me->access('管理组织机构')) 
    || (($me->access('添加/修改所有机构的仪器')
    || $me->access('添加/修改下属机构的仪器'))
    && !$me->access('添加负责的仪器'))) {
    echo Widget::factory('multi_user_selector', [
        'name' => 'contacts',
        'autocomplete' => URI::url('autocomplete/user'),
        'value' => $form['contacts'],
        'extra' => 'token_verify'
    ]);
} else {
    echo $contacts->name;
    echo '<input type="hidden" name="contacts" value=\''.$val.'\' />';
}

?>
