<script type="text/javascript">
    var var_name = null;
</script>
<table>
    <tbody>
    <tr>
        <td class="nowrap middle">
            <span class="label"><?php echo I18N::T('equipments', 'name值')?></span>
            <input class="text" id="var_name" />
            <input class="font-button-save" onclick="javascript:addElement();return false;" type="button" value="<?php echo H(I18N::T('equipments', '确定')) ?>" name="submit" />
        </td>
    </tr>
    <tr><td class="interval_80"></td></tr>
    </tbody>
</table>
