<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('equipments', '仪器列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('equipments', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('equipments', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                	echo I18N::HT('equipments', '仪器列表');			
                ?>
              
            </caption>
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('equipments', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php

			foreach($equipments as $equipment): ?>
				<tr>
				<?php if (array_key_exists('name', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->name) ? H($equipment->name).Event::trigger('extra.equipment.name', $equipment) : '-'; ?></td>
				<?php endif; ?>
				<?php if (array_key_exists('ref_no', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->ref_no) ?: '-'; ?></td>
				<?php endif; ?>
                <?php if (array_key_exists('price', $valid_columns)) : ?>
                    <td class="left nowrap"><?php echo $equipment->price ? Number::currency($equipment->price) : '-'; ?></td>
                <?php endif; ?>

				<?php
				//自定义的输出项
				$data_custom = Event::trigger('equipments.export_list_csv', $equipment, $data, $valid_columns);
				if(is_array($data_custom)) foreach ($data_custom as $key => $value) :?>
					<td class="left nowrap">
						<?php echo $value;?>
					</td>
				<?php endforeach;?>

				<?php if (array_key_exists('eq_cf_id', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->id)?:'-'; ?></td>
				<?php endif; ?>
				<?php if (array_key_exists('cat', $valid_columns)) : ?>
					<td class="left nowrap">
						<?php 
							$root = Tag_Model::root('equipment');
							$tags = Q("$equipment tag_equipment[root=$root]");
							$cats = [];
							foreach ($tags as $cat) {	
								$cats[] = $cat->name; 
							}
							echo H(implode(', ',$cats))?:'-';
						 ?>
					</td>
				<?php endif; ?>
				<?php if (array_key_exists('control_mode', $valid_columns)) : ?>
					<td class="left nowrap">
						<?php 
							$control_modes = Config::get('equipment.control_modes');
							echo $control_modes[H($equipment->control_mode)]?:'-';
						 ?>
					</td>
				<?php endif; ?>
				<?php if (array_key_exists('location', $valid_columns)) : ?>
                    <?php if (Config::get('equipment.location_type_select')):?>
                        <td class="left nowrap">
                            <?php
                                $location = [];
                                $ls = Q("{$equipment} tag_location")->to_assoc('id', 'name');
                                if (count($ls)) {
                                    $location[] = join(' ', $ls);
                                }else{
                                    $location[] = '';
                                }
                                echo ($location[0]=='' && $location[1]=='') ? '-': implode(' &#187; ',$location);
                            ?>
                        </td>
                    <?php else:?>
                        <td class="left nowrap">
                            <?php
                            $location = [
                                H($equipment->location)
                            ];
                            echo  ($location[0]=='' && $location[1]=='')?'-':H(implode(', ',$location));
                            ?>
                        </td>
                    <?php endif;?>
				<?php endif; ?>
				<?php if (array_key_exists('contacts', $valid_columns)) : ?>
					<td class="left nowrap">
						<?php 
							$users = Q("$equipment<contact user");
							$contacts = [];
							foreach ($users as $contact) {	
								$contacts[] = $contact->name; 
							}
							echo H(implode(', ',$contacts))?:'-';
						 ?>
					</td>
				<?php endif; ?>
				<?php if (array_key_exists('phone', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->phone)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('group', $valid_columns)) : ?>
					<td class="left nowrap">
						<?php 
							$anchors = [];
							if ( Config::get('tag.group_limit')>=0 && $equipment->group->id ) {
								
								$tag = $equipment->group;
								$tag_root = $equipment->group->root;
								
								if (!$tag || !$tag->id) return;

								if (!isset($tag_root)) $tag_root = $tag->root;
								

								if ($tag->id == Tag_Model::root('group')->id) return;

								$found_root =  ($tag_root->id == $tag->root->id);
								foreach ((array) $tag->path as $unit) {
									list($tag_id, $tag_name) = $unit;
									if (!$found_root) {
										if ($tag_id != $tag_root->id) continue;
										$found_root = TRUE;
									}
									$anchors[] =  HT($tag_name);
								}
								
								echo implode(' &#187; ', $anchors);

							}
							if ( !$anchors ) {
								echo '-';
							}
						 ?>
					</td>
				<?php endif; ?>
                <?php if (array_key_exists('atime', $valid_columns)) : ?>
                    <td class="left nowrap"><?php echo $equipment->atime ? Date::format($equipment->atime, 'Y/m/d') : '-';?></td>
                <?php endif; ?>
				<?php if (array_key_exists('specification', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->specification)?:'-';?></td>
				<?php endif; ?>
                <?php if (array_key_exists('brand', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->brand)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('model_no', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->model_no)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('manufacturer', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->manufacturer)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('manu_at', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->manu_at)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('purchased_date', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo $equipment->purchased_date?(H(date('Y/m/d',$equipment->purchased_date))?:"-"):'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('manu_date', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo $equipment->manu_date?(H(date('Y/m/d',$equipment->manu_date))?:"-"):'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('cat_no', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->cat_no)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('tech_specs', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->tech_specs)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('features', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->features)?:'-';?></td>
				<?php endif; ?>
				<?php if (array_key_exists('configs', $valid_columns)) : ?>
					<td class="left nowrap"><?php echo H($equipment->configs)?:'-';?></td>
				<?php endif; ?>
			<?php
			endforeach;
			?>
				<tr>
					<td colspan="<?php echo count($valid_columns) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('equipments', '总计:') . $equipments->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
