<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	p {
		margin: 0;
	}
	.quote {
		margin-left: 1em;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('equipments', '打印'); ?></a>
        <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('equipments', '关闭|:print'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></caption>
	<thead id="stat">
		<tr>
		<td colspan="8">
		<?php echo I18N::T('equipments', '时间范围:'); ?>
		&#160;
		<?php
			$dtstart = isset($dtstart) ? H(date('Y/m/d',$dtstart)) : I18N::T('equipments','最初');
			$dtend = isset($dtend) ? H(date('Y/m/d',$dtend)) : I18N::T('equipments','最末');
			echo $dtstart . ' - ' . $dtend;
		?>
		</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<th class="left nowrap"><?php echo I18N::T('equipments', '仪器'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '使用者'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '实验室'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '时段'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '时长'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '时间总计 (小时)'); ?></th>
			<th class="left nowrap"><?php echo I18N::T('equipments', '样品数'); ?></th>
			<th class="center nowrap"><?php echo I18N::T('equipments', '代开'); ?></th>
			<th class="center nowrap"><?php echo I18N::T('equipments', '反馈'); ?></th>
			<th class="center nowrap"><?php echo I18N::T('equipments', '备注'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php
        $sum_dtstart = 0;
        $sum_dtend = 0;
		foreach($records as $record): ?>
		<tr>
		<td class="left nowrap"><?php echo H($record->equipment->name); ?></td>
		<td class="left nowrap"><?php echo H($record->user->name); ?></td>
		<td class="left nowrap">
		<?php 
			if ($GLOBALS['preload']['people.multi_lab']) {
				$lab = $record->project->lab;
			}
			else {
				$lab = Q("$record->user lab")->current();
			}
			echo H($lab->name); ?>
		</td>
		<td class="left nowrap">
			<small class="description">
			<?php echo Date::format($record->dtstart); ?> - <?php echo !$record->dtend ? I18N::T('equipments', '使用中') : Date::format($record->dtend); ?>
			</small>
		</td>
		<td class="left nowrap">
			<small class="description">
			<?php
			$duration = !$record->dtend ? I18N::T('equipments', '使用中') : Date::format_duration($record->dtstart, $record->dtend, 'i');
			echo $duration; 
            if ($record->dtend) {
                $sum_dtend += $record->dtend;
                $sum_dtstart += $record->dtstart;
            }
            ?>
			</small>
		</td>
		<td class="right nowrap">
			<?php echo  $record->dtend ? (float) round(($record->dtend - $record->dtstart) / 3600, 4) : I18N::T('equipments', '使用中'); ?>
		</td>
		<td class="right nowrap">
			<?php echo $record->samples; ?>
		</td>
		<td class="right nowrap">
			<?php echo $record->agent->id ? 'Y':'&#160;' ?>
		</td>
		<td class="right nowrap">
			<?php 
			if ($record->status == EQ_Record_Model::FEEDBACK_NORMAL) {
				echo I18N::T('equipments', '正常');
			}
			elseif ($record->status == EQ_Record_Model::FEEDBACK_PROBLEM) {
				echo I18N::T('equipments', '故障');
			}
			else {
				echo I18N::T('equipments', '-');
			}
		
			$feedback = $record->feedback;
			if ($feedback) {
				echo '<br/>'.H($feedback);
			}
			?>
		</td>
		<td class="left nowrap">
		<?php
		$views = Event::trigger('eq_record.description', $record);
		if(is_array($views)){
			echo implode('<div class="interval_12"></div>', $views);
		}else{
			echo '&#160;';
		}
		?>
		</td>
		</tr>
		<?php endforeach; ?>
		<tr>
		<td colspan="10" class="right nowrap">
			<?php echo I18N::T('equipments', '总计使用: %count 次', ['%count'=>$records->total_count()]); ?>
            &nbsp;
            <?php echo I18N::T('equipments', '总计时长: %count_time (小时)', ['%count_time'=>round(($sum_dtend - $sum_dtstart) / 3600, 4)])?>
		</td>
		</tr>
	</tbody>
	</table>
</body>
</html>
