<div class="form ">
    <?php if ($type == 'csv'): ?>
        <form id="people_form" method="POST" q-object="people_export" q-src="<?= URI::url('!people/list/export') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" q-event="submit" autocomplete="off" class="prevent_default">
    <?php else: ?>
        <form action="<?php echo H(URI::url('!people/list/export', ['type'=> $type ,'form_token'=>$form_token])) ?>" target="<?php echo H(($type == 'csv') ? '_self' : '_blank' ) ?>" class="prevent_default" method="post">
    <?php endif; ?>
    <div class="interval_24"></div>
	<ul class="ep_triple">
	  <?php
	 		foreach ($columns as $p => $p_name) :?>
	  <li class="nowrap">
		<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('people', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>
	  </li>
	  <?php endforeach;?>
	</ul>
	<div class="button_container">
            <div class="float_right">
                <input name="cancel" id="cancel" type='reset' class="font-button-default rmargin_2e4" value="<?php echo I18N::HT('eq_sample', '取消');?>" />
                <input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('equipment', '保存');?>" />
            </div>
     </div>
  </form>
</div>
