<?php
$upload_form_uniqid = 'upload_form_'.uniqid();
$error_msg = I18N::T('nfs', '异常原因: 文件上传中止!');
?>
<div class="form padding_2" class="prevent_default">
    <div style="text-align: center; margin-bottom: 15px;">
        <div>请先下载导入模板, 确保数据格式正确！</div>
        <a class="prevent_default" style="text-decoration: underline; padding-top: 5px; display: inline-block;" href="<?php echo H(URI::url('!people/list/download_template')) ?>">人员信息导入模板.xlsx</a>
    </div>
    <form id="<?php echo H($upload_form_uniqid) ?>" method="post" action="<?php echo H(URI::url('!people/list/import')) ?>" class="nowrap" style="padding: 1px">
        <input name="Filedata" type="file" class="middle" />
        <input name="single" type="hidden" value="1" />
        <a name="upload" href="#" class="button button_import middle prevent_default"><?php echo I18N::HT('nfs', '上传')?></a>
    </form>
</div>
<script>
jQuery(function($){
    var $form = $('#<?php echo $upload_form_uniqid?>');
    $form.find('a[name=upload]').bind('click', function(){
        $form.ajaxSubmit({
            dataType: 'json',
            success : function(data) {
                if (data.status == true) {
                    var content = data.content;
                    var text = '共处理'+content.total+'名用户, '+"\n";
                    text += '新导入'+content.new+'名用户, '+"\n";
                    text += '系统中已存在'+content.existed.count+'名用户';
                    if (content.existed.count) {
                        text += ':'+"\n"
                        $.each(content.existed.users, function(index, user) {
                            text += '    第'+user.row+'行, 姓名: '+user.name+','+"\n";
                        })       
                    } else {
                        text += ','+"\n";    
                    }
                    text += '尝试导入, 但失败'+content.failed.count+'名用户';
                    if (content.failed.count) {
                        text += ':'+"\n"
                        $.each(content.failed.users, function(index, user) {
                            text += '    第'+user.row+'行, 姓名: '+user.name+','+"\n";
                        })       
                    } else {
                        text += ','+"\n";    
                    }
                    alert(text);
                } else {
                    alert(data.content);
                }
                Dialog.close();
                location.reload();
            },
            error : function (data){
                alert('导入失败');
                Dialog.close();
            }
        });
        return false;
    });
});
