<div class="form padding_2">
<table class="form">
	<tbody>
	<tr>
		<td class="top icon">
			<img src="images/icons/signup_big.png" />
		</td>
		<td class="top" style="padding-left:20px">
		<h1 style="font-size:22px;">
			<span class="red">
				<?php echo I18N::T('people', '请重置您的登录密码, 否则将无法使用系统!') ?>
			</span>
		</h1>

		<form method="post" autocomplete="off" action="<?php echo H(URI::url()) ?>">
		<?php echo V('form_error', ['form'=>$form]);?>
			<table>
				<tbody>
					<tr><td><div class="interval_20"></div></td></tr>
					<tr><td colspan="2"><?php echo V('form_filter', ['error'=>$form->errors["new_pass"][0]]); ?></td></tr>
					<tr>
						<td class="left nowrap middle"><?php echo I18N::T('people', '新密码')?></td>
						<td class="middle"><input type="password" name="new_pass" class="text"  /></td>
					</tr>
					<tr><td><div class="interval_20"></div></td></tr>
					<tr><td colspan="2"><?php echo V('form_filter', ['error'=>$form->errors["confirm_pass"][0]]); ?></td></tr>
					<tr>
						<td class="left nowrap middle"><?php echo I18N::T('people', '确认密码')?></td>
						<td class="middle"><input type="password" name="confirm_pass" class="text" /></td>
					</tr>
                    <tr class="description">
                        <td></td>
                        <td colspan="3"><?= H(I18N::T('people','8-24个字符，必须包含数字和大小写字母')) ?></td>
					</tr>
					<tr><td><div class="interval_30"></div></td></tr>
					<tr>
						<td></td>
						<td>
							<input type="submit" name="submit" class="float_right font-button-save" value="<?php echo H(I18N::T('people', '保存')) ?>" />
						</td>
					</tr>
				</tbody>
			</table>
		</form>
		</td>
	</tr>
	</tbody>
</table>
</div>
<?php  
	$me = L('ME'); 
	$hideSidebar = $me->id && $me->hideSidebar();
?>
<script>
jQuery(function($){
	var $center = $('#center')
	    , $sidebar = $('#sidebar')
	    , hideSidebar = '<?= $hideSidebar; ?>'
	$center
		.css('vertical-align', 'middle')
		.find('.center_content').css({width: '600px', margin: 'auto'});
	if ( hideSidebar ) $sidebar.remove()
});
</script>
