<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('people', '成员列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('people', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('people', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                    if ($role_name) {
                        echo I18N::HT('people', '"%role_name"的成员列表', ['%role_name'=>I18N::T('people', $role_name)]);
                    }
                    else {
                        echo I18N::HT('people', '成员列表');
                    }
                ?>
            </caption>
			<thead>
				<tr>
					<th class="left nowrap"><?php echo I18N::T('people', '姓名'); ?></th>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('people', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
			$roles = L('ROLES');
			$group_root = Tag_Model::root('group');
			$role_names = [];
			foreach ($roles as $id => $role) {
				$role_names[$id] = $role->name;
			}

			$backends = Config::get('auth.backends');
			foreach($users as $user): ?>
				<tr>
					<td class="left nowrap">	
						<?php echo H($user->name); ?>
					</td>
					<?php foreach ($valid_columns as $p => $p_name) : ?>
						<td class="left nowrap">
						<?php
							switch ($p) {
							case 'gender':
								echo I18N::T('people', User_Model::$genders[$user->gender]) ?: '--';
								break;
							case 'member_type':
								echo User_Model::get_member_label($user->member_type) ?: '--';
								break;
							case 'group':
								$anchors = [];
								$found_root = ($group_root->id == $user->group->root->id);
								foreach ((array) $user->group->path as $unit) {
									list($tag_id, $tag_name) = $unit;
									if (!$found_root) {
										if ($tag_id != $group_root->id) continue;
										$found_root = TRUE;
									}
									$anchors[] = HT($tag_name);
								}
								echo implode(' >> ', $anchors);
								break;
							case 'lab':
								$labs = Q("$user lab")->to_assoc('id', 'name');
								echo H(join(',', $labs));
								break;
							case 'roles':
								$user_roles = $user->roles();
								$user_role_names = [];
	
								foreach ($user_roles as $role) {
									$user_role_names[] = I18N::HT('people', $role_names[$role]);
								}
								echo join(', ', $user_role_names);
								break;
                            case 'lab_contact' :
								$labs_contact = Q("$user lab")->to_assoc('id', 'contact');
								echo H(join(',', $labs_contact));
                                break;
							case 'token':
								echo People::print_token($user->token, $backends);
                                break;
                            case 'ctime':
                                echo Date::format($user->ctime, 'Y/m/d');
                                break;
                            case 'creator':
                                echo H($user->creator->name);
                                break;
                            case 'auditor':
                                echo H($user->auditor->name);
                                break;
							default:
								echo H($user->{$p});
							}
						?>
					</td>
					<?php
					endforeach;
			endforeach;
			?>
				<tr>
					<td colspan="<?php echo count($valid_columns) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('people', '总计:') . $users->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
