<?php
// 初始化变量
$me = L('ME');
$no_error = ($form->no_error !== FALSE);
$div_uniqid = 'div_refresh_'.uniqid();
$form_token = Session::temp_token('note',3600);
$_SESSION[$form_token] = '#'.$div_uniqid;
?>
<div class="hr_1">&#160;</div>
<div class="padding_2 form">
	<form action="<?php echo H(URI::url()) ?>" method="post" autocomplete="off">
	<?php echo V('form_error', ['form'=>$form]);?>
	<?php $require = (string) V('form_require'); ?>
		<table class="form add_task">
			<tbody>
				<tr>
					<td class="label left nowrap"><?php echo I18N::T('treenote', '标题')?></td>
					<td class="flexible"><input class="text" size="60" name="title" value="<?php echo H($form['title']) ?>"/><?php echo $require?></td>
				</tr>
				<tr>
					<td class="label left nowrap"><?php echo I18N::T('treenote', '任务')?></td>
					<td><?php echo Widget::factory('treenote:task_selector', ['name' => 'task', 'task' => $form['task'] ? O('tn_task', $form['task']) : $note->task, 'must_set_task' => TRUE, 'size'=>60]) ?><?php echo $require?></td>
				</tr>
				<tr>
					<td class="label left nowrap top">
						<?php echo I18N::T('treenote', '内容')?>
					</td>
					<td class="top relative">
						<textarea name="content" class="text autogrow" cols="60" rows="10"><?php echo $form['content']?></textarea>
					</td>
				</tr>
				<?php if (Module::is_installed('nfs')) : ?>
				<tr>
					<td class="label left nowrap top">
						<?php echo I18N::HT('treenote', '附件')?>
					</td>
					<td class="top relative">
					<div class="text_like relative" style="display:block">
					<?php
						echo V('nfs:nfs_lite/view', [
							'object'=>O('tn_note'),
							'path_type'=>'attachments'
						]);
?>
					</div>
					</td>
				</tr>
				<?php endif;?>
				<tr>
					<td>&#160;</td>
					<td class="nowrap">
						<input class="button button_save" type="submit" name="submit" value="<?php echo H(I18N::T('treenote', '添加')) ?>" />
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>
