<div class="hr_1">&#160;</div>
<?php if (isset($task) && L('ME')->is_allowed_to('添加记录', $task)):?>
<div class="group_prevent_default panel padding_1 clearfix">
	<a class="button button_add" href="#" q-object="new_note" q-event="click" q-src="<?php echo H(URI::url('!treenote/note') ) ?>" q-static="<?php echo H(['task'=>$task->id])?>"><?php echo I18N::HT('treenote', '添加记录')?></a>
</div>
<?php endif;?>
<?php echo $pagination;?>
<?php

$table = Widget::factory('table');

$table->name = 'treenote_notes';
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;

if($form['dtstart_check'] && $form['dtend_check']) {
	$form['date'] = H(date('Y/m/d',$form['dtstart'])).'~'.H(date('Y/m/d',$form['dtend']));
}
elseif($form['dtstart_check']) {
	$form['date'] = H(date('Y/m/d',$form['dtstart'])).'~'.I18N::T('treenote','最末');
}
elseif($form['dtend_check']) {
	$form['date'] = I18N::T('treenote','最初').'~'.H(date('Y/m/d',$form['dtend']));
}

$table->add_columns([
	'@' => [
		'extra_class' => 'tight',
	],
	'note'=>[
		'title'=>I18N::T('treenote', '记录'),
	],
	'mtime'=>[
		'title'=>I18N::T('treenote', '时间'),
		'filter' => [
			'form' => V('treenote:general/table/filters/date', [
				'dtstart_check'=>$form['dtstart_check'],
				'dtstart'=>$form['dtstart'],
				'dtend_check'=>$form['dtend_check'],
				'dtend'=>$form['dtend']
			]),
			'value' => $form['date'] ? H($form['date']) : NULL,
            'field' =>'dtstart_check,dtend_check,dtstart,dtend'
		],
		'sortable' => TRUE,
		'nowrap'=>TRUE,
		'invisible' => TRUE,
	],
]);

$table->empty_message = I18N::T('treenote', '无相关记录');
$me = L('ME');
foreach ($notes as $note) {
	if (!$me->is_allowed_to('列表', $note)) continue;

	$table->add_row(
		[
			'@' => [
				'view'=> $note->user->icon('32', 'style="display:block"'),
				'extra'=>'style="padding:4px" align="right" align="right"',
				'align'=>'top',
			],
			'note'=> V('treenote:note/table/data/note', ['note'=>$note]),
			]);
}

echo $table;
