<?php
foreach ($component_form['#categories'] as $category => $fields) :
    if (!count($fields) || !$category) continue;

    // 启用之前从来没有过作用的weight属性
    $items = $fields['items'];
    usort($items, function ($a, $b) use ($component_form) {
        $weight_a = $component_form[$a]['weight'] ?? PHP_INT_MAX;
        $weight_b = $component_form[$b]['weight'] ?? PHP_INT_MAX;
        return $weight_a <=> $weight_b;
    });
?>
<tr class="begin">
    <td class="label left  nowrap blue" >
        <h1><?= $fields['title'];?></h1>
    </td>
    <td class="right description middle red" >*&nbsp;<?php echo I18N::T('calendar', '必填项');?></td>
</tr>
<tr >
<?php
    $v_count=1;
    foreach ($fields['items'] as $name) {
        $properties = $component_form[$name];
        $path = isset($properties['path']['form']) ? $properties['path']['form'] : 'calendars:calendar/component_form/';
        $path_view = (string) V($path, [
            'component'=>$component,
            'name'=> $name,
            'properties'=> $properties,
            'calendar'=> $calendar,
            'files'=> $files,
            'form'=> $form
        ])?:V($path.$name, [
            'component'=>$component,
            'name'=>$name,
            'properties'=>$properties,
            'calendar'=>$calendar,
            'files'=>$files,
            'form'=>$form
        ]);
        echo $path_view;
        if($v_count%2==0&&$v_count>2)
        {
            echo "</tr><tr>";
        }
        $v_count++;
      
    }
endforeach;
?>
</tr>