<table class="form margin_2" style="min-width: 600px;margin-bottom:24px;line-height: 25px;">
    <thead style="display: table-caption;background: #fafafa;border: 1px solid #f3f3f3;border-radius:4px 4px 0 0;">
        <tr>
            <th style="font-weight:400; width: 150px;padding:10px;"><?= I18N::T('calendars', '检查项目')?></th>
            <th style="font-weight:400; width: 60px;padding:10px;"><?= I18N::T('calendars', '结果')?></th>
            <th style="font-weight:400; width: 390px;padding:10px;"><?= I18N::T('calendars', '项目值')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($check_list as $list) : ?>
            <tr style="border-bottom: 1px solid #eee;">
                <td style="font-weight:800;width: 150px;padding:10px;"><?= $list['title']?></td>
                <td style="font-weight:900;width: 60px;padding:10px;"><?= $list['result'] ? "✔️": "❌"?></td>
                <td style="padding:10px; width: 390px;"><?= $list['description']?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php 
$me = L('ME');
if($me->access('为负责仪器添加预约') && Equipments::user_is_eq_incharge($me, $calendar->parent) || $me->access('为所有仪器添加预约') || $me->access('为下属机构仪器添加预约')):?>
<div style="padding:0 10px 10px 10px" class="margin_2 description">注：具备仪器管理权限的用户可预约，无论检查项目结果如何。</div>
<?php endif;?>
