<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View blocked users for equipment usage.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Add blocked users.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit blocked user list.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>