<div class="dashboard"></div>
<?php
    $host = $_SERVER["HTTP_HOST"];
    $src = strtr($src, ['172.17.42.1' => $host]);
?>
<script>
    $(function() {
        var height = document.body.scrollHeight;

        var src = "<?= $src; ?>";

        var iframe = document.createElement('iframe');
        iframe.setAttribute('src', src);
        iframe.setAttribute('width', '100%');
        iframe.setAttribute('frameborder', '0');
        iframe.setAttribute('height', height);

        $('.dashboard').append(iframe);
    })
</script>
