<div class="message message_normal">
	<p><?php echo I18N::T('eq_vidcam', '您可以在仪器设置中关联摄像头')?></p>
</div>
<?php
	$table = Widget::factory('table');

	$table->name = 'vidcam_equipments';

	$table->add_columns([
		'img'=>NULL,
		'name'=>[
			'title'=>I18N::T('eq_vidcam', '仪器名称'),
			'align'=>'left',
			'filter'=> [
				'form' => V('equipments:equipments_table/filters/name', ['name'=>'name', 'value'=>$form['name']]),
				'value' => $form['name'] ? H($form['name']) : NULL
			],
			'nowrap'=>TRUE,
		],
		'control'=>[
			'title'=>I18N::T('eq_vidcam', '控制'),
			'align'=>'center',
			'filter'=> [
				'form' => V('equipments:equipments_table/filters/control', [
					'mode_name'=>'control_mode', 'mode_value'=>$form['control_mode'],
					'status_name'=>'control_status', 'status_value'=>$form['control_status'],
				]),
				'value' => V('equipments:equipments_table/filters/control.value', [
					'mode'=>$form['control_mode'],
					'status'=>$form['control_status'],
				])
			],
			'nowrap'=>TRUE,
		],
		'current_user'=>[
			'title'=> I18N::T('eq_vidcam', '当前使用者'),
			'align'=>'center',
			'filter'=> [
				'form' => V('equipments:equipments_table/filters/current_user', ['name'=>'current_user', 'value'=>$form['current_user']]),
				'value' => $form['current_user'] ? H($form['current_user']) : NULL
			],
			'nowrap'=>TRUE,
		],
		'location'=>[
			'title'=>I18N::T('eq_vidcam', '放置地点'),
			'align'=>'left',
			'filter'=> [
				'form' => V('equipments:equipments_table/filters/location', [
					'location_name'=>'location', 'location_value'=>$form['location'],
					'location2_name'=>'location2', 'location2_value'=>$form['location2'],
				]),
				'value' => V('equipments:equipments_table/filters/location.value', [
					'location' => $form['location'],
					'location2' => $form['location2'],
				])
			],
			'nowrap'=>TRUE,
		],
		'contact'=>[
			'title'=> I18N::T('eq_vidcam', '联系人'),
			'align'=>'left',
			'filter'=> [
				'form' => V('equipments:equipments_table/filters/contact', ['name'=>'contact', 'value'=>$form['contact']]),
				'value' => $form['contact'] ? H($form['contact']) : NULL
			],
			'nowrap'=>TRUE,
			'extra_class'=>'filter_right',
		],
		'rest'=>[
			'align'=>'right',
			'nowrap'=>TRUE,
		],
	]);

	$table->empty_message = I18N::T('eq_vidcam', '无关联仪器');

	foreach ($equipments as $equipment) {
		$table->add_row([
			'img' => [
				'view'=> URI::anchor($equipment->url(), $equipment->icon('32', 'style="display:block"')),
				'extra'=>'style="padding:4px" align="right"',
			],
			'name' => V('equipments:equipments_table/data/name', ['equipment'=>$equipment]),
			'control' => V('equipments:equipments_table/data/control', ['equipment'=>$equipment]),
			'current_user' => V('equipments:equipments_table/data/current_user', ['equipment'=>$equipment]),
			'location' => V('equipments:equipments_table/data/location', ['equipment'=>$equipment]),
			'contact' => V('equipments:equipments_table/data/contacts', ['equipment'=>$equipment]),
			'rest'=> V('eq_vidcam:equipments_table/data/link', ['equipment'=>$equipment]),
		]);
	}

	echo $table;
