<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('inventory', '存货列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style type="text/css">
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('inventory', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('inventory', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                	echo I18N::HT('inventory', '存货列表');			
                ?>
              
            </caption>
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('inventory', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach($stocks as $stock): ?>
				<tr>
					<?php if (array_key_exists('product_name', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->product_name)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('ref_no', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->ref_no) ?: '-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('catalog_no', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->catalog_no)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('vendor', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->vendor)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('manufacturer', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->manufacturer)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('barcode', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->barcode)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('model', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->model)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('spec', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->spec)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('unit_price', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->unit_price)?:'-'; ?>
						</td>
					<?php endif; ?>
                    <?php if (array_key_exists('type', $valid_columns)) :?>
                        <td class="left nowrap">
                            <?php echo H($stock->type) ? : '-'?>
                        </td>
                    <?php endif;?>
					<?php if (array_key_exists('quantity', $valid_columns)) : ?>
						<td class="left nowrap">
						<?php echo H($stock->quantity)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('location', $valid_columns)) :?>
						<td class="left nowrap">
					<?php echo H($stock->location)?:'-'; ?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('status', $valid_columns)) : ?>
						<td class="left nowrap">
					<?php	
						$status = [
							'1' => '不详',
							'2' => '充足',
							'3' => '紧张',
							'4' => '用罄',
						];
						echo I18N::HT('inventory', $status[$stock->status]) ? : '-';
					?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('tags', $valid_columns)) : ?>
						<td class="left nowrap">
					<?php	
						$root = Tag_Model::root('inventory');
						$tags = (array) Q("$stock tag[root=$root]")->to_assoc('name','name');
						echo H(implode(',',$tags))?:'-';
					?>
						</td>
					<?php endif; ?>
					<?php if (array_key_exists('note', $valid_columns)) :?>
						<td class="left">
						<?php echo H($stock->note)?:'-'; ?>
						</td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
				<tr>
					<td colspan="<?php echo count($valid_columns) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('inventory', '总计: ') . $stocks->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
