<div class="description">
	<p>您正在查看所有实验室的基本信息。</p>
	<p>点击实验室名称可以查看该实验室的详细信息及成员名单。</p>
	<p>您可以按照实验室和组织机构进行搜索。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以添加新的实验室。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以设置或删除实验室的相关信息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>