<div class="category_container">
    <?php
        $show = false;
        foreach ($subMods as $subMod) {
            if (in_array($subMod, $moreMods)) {
                $show = strpos($subMod, MODULE_ID . '_') !== false;
            } else {
                $show = in_array(MODULE_ID, $subMods);
            }
            if ($show) break;
        }
    ?>
    <div class="category category_color <?= ($show ? 'active' : '') ?>">
        <span><?= H($name) ?></span>&#160;<span class="angle icon-down" style="font-size: 10px;"></span>
    </div>
    <div class="items clearfix" style="display: none;"><?php echo $content; ?></div>
</div>
