<?php echo CSS::load_async('inventory:common');?>
<?php $columns = Config::get('inventory.export_columns.stock'); ?>
<div class="form">
  <?php if ($type == 'csv'): ?>
    <form action="<?php echo H(URI::url('!inventory/use', ['type' => $type, 'form_token' => $form_token])) ?>" q-object="export" q-src="<?= URI::url('!inventory/use') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type])?>" target="<?=$type == 'csv' ? '_self' : '_blank'?>" q-event="submit" class="prevent_default" method="post">
  <?php else: ?>
	<form action="<?php echo H(URI::url('!inventory/use/export', ['type'=>$type, 'form_token'=>$form_token])) ?>" target="<?=$type == 'csv' ? '_self' : '_blank' ?>" class="prevent_default" method="POST">
  <?php endif; ?>
		<ul class="ep_triple">
			<?php
			foreach ($columns as $p => $p_name) :?>
				<li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('inventory', $p_name), 'class="middle monitor"', 'class="middle"');?>
				</li>
			<?php endforeach;?>
		</ul>
		<div class="button_container">
		<div class="float_right">
		<input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('inventory', '取消');?>" />
		<input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('inventory', '提交');?>" />
		</div>
		</div>
	</form>
</div>
