<div class="form padding_2">
	<form class="view" method="post" q-object="stock_use_return_add" q-event="submit" q-src="<?php echo URI::url('!inventory/use'); ?>" autocomplete="off">
		<?php echo V('form_error', ['form'=>$form])?>
		<input name="stock_id" type="hidden" value="<?php echo $stock->id; ?>"/>
		<table class="form">
		<?php if( L('ME')->is_allowed_to('代人领用/归还',$stock) ): ?>
			<tr>
				<td class="label nowrap"><?php echo I18N::HT('inventory', '用户'); ?></td>
				<td class="top" >
				<?php
					echo Widget::factory('application:user_selector', [
						'autocomplete'=>'autocomplete/user',
						'name'=>'user',
						'user'=> $no_error ? $form['user'] : (O('user',$form['user'])),
						'cardread'=>URI::url('cardread/user'),
						'size'=>36,
					]);
				?>
				</td>
			</tr>
		<?php endif; ?>
		<tr>
			<td></td>
			<td>
				<?php 
					echo Form::radio('operate_type', 'use', $form['operate_type'] ?: 'use', I18N::T('inventory', '领用'), 'class="monitor middle"', 'class="middle"');
					echo '&#160;&#160;';
					echo Form::radio('operate_type', 'return', $form['operate_type'], I18N::T('inventory', '归还'), 'class="monitor middle"', 'class="middle"');

				?>
			</td>
		</tr>
		<tr>
		<td class="label nowrap"><?php echo I18N::T('inventory', '数量'); ?></td>
		<td><input name="quantity" size="40" class="text number" value="<?php echo $form['quantity'] ? : 1; ?>"/></td>
		</tr>
        <tr>
		<td class="label top nowrap"><?php echo I18N::T('inventory', '备注'); ?></td>
		<td class="top"><textarea class="text" name="note" cols="40" rows="3"><?php echo $form['note'];?></textarea></td>
		</tr>
		<tr>
			<td>&#160;</td>
			<td>
				<input name="submit" class="button button_edit" type="submit" value="<?php echo H(I18N::T('inventory', '确定')) ?>" />
			</td>
		</tr>
		</table>
	</form>
</div>
