<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('inventory', '存货领用 / 归还记录列表'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo T('关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption><?php echo I18N::T('inventory', '存货领用 / 归还记录列表'); ?></caption>
			<thead>
				<tr>
					<?php foreach($columns as $p => $p_name) : ?>
							<th class="left nowrap"><?php echo I18N::T('inventory', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach($stock_uses as $stock_use): ?>
				<tr>
					<?php if (array_key_exists('ctime', $columns)): ?>
					<td class="left nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/ctime', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('stock', $columns)): ?>
					<td class="left nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/stock', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('user', $columns)): ?>
					<td class="left nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/user', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('use_quantity', $columns)): ?>
					<td class="center nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/use_quantity', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('return_quantity', $columns)): ?>
					<td class="cneter nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/return_quantity', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
                    <?php if (array_key_exists('unit_price', $columns)) :?>
                    <td class="right nowrap">
                    <?php
                        echo V('inventory:print_stocks_table/data/unit_price', ['stock_use'=> $stock_use]);
                    ?>
                    </td>
                    <?php endif?>
                    <?php if (array_key_exists('total_price', $columns)) :?>
                    <td class="right nowrap">
                    <?php
                        echo V('inventory:print_stocks_table/data/total_price', ['stock_use'=> $stock_use]);
                    ?>
                    </td>
                    <?php endif;?>
					<?php if (array_key_exists('status', $columns)): ?>
					<td class="right nowrap">
					<?php
						echo V('inventory:print_stocks_table/data/status', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
					<?php if (array_key_exists('note', $columns)): ?>
					<td class="left nowrap">
					<?php 
						echo V('inventory:print_stocks_table/data/note', ['stock_use' => $stock_use]);
					?>
					</td>
					<?php endif; ?>
				</tr>
			<?php endforeach;?>
			<tr>
					<td class="right nowrap" colspan="<?php echo H(count($columns)) ?>">
						<?php echo I18N::T('inventory', '领用总量:');?>
						&#160;
						<?php echo $stock_uses->sum('quantity');?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
