<?php 
if (!$backend_titles) {
	$backends = Config::get('auth.backends');
	$backend_titles = [];
	foreach ($backends as $key=>$values) {
		if ((!$values['remote_auth'] || $this->show_remote_auth)
                &&
                (count($skip_backends) ?
                     !in_array($key, $skip_backends)
                     :
                     TRUE
                 )
                ) {
			$backend_titles[$key] = $values['title'];
		}
	}
}

//bugfix，当default_backend存在于skip_backends中，取第一个backend_titles
$default_backend = $this->default_backend ?:
( in_array(Config::get('auth.default_backend'), $skip_backends) ? array_keys($backend_titles)[0] : Config::get('auth.default_backend'));

$name = $backend_name =  $this->name ?: 'token';
$size = $this->size ?: 40;
$size = count($backends) > 1 ? $size : $size + 15;

$backend_name = preg_replace('/token/', 'token_backend', $backend_name);
?>
<input placeholder="登录账号" name="<?php echo H($name) ?>"
class="text <?php echo $extra_class?> user_token"
size="<?php echo H($size) ?>" 
value="<?php echo H($this->token) ?>" 
<?php echo $extra?> />
<?php if (count($backends) > 1 && $name == 'pi_token'): ?>
<span class="separator middle">@</span>
<?php echo Form::dropdown($backend_name, T($backend_titles), $this->backend ?: $default_backend, 'class="dropdown middle '. $backend_extra_class. '"'); ?>
<?php else: ?>
<input class="hidden" name="<?php echo H($backend_name) ?>" value="<?php echo H($this->backend ?: $default_backend)?>" q-hint="<?php echo H(I18N::T('labs', '请输入关键字并选择') ) ?>" />
<?php endif; ?><?php echo $require; ?>
