<div class="form">
	<form method="post" class="blue view object:refill_deduction event:submit static:type=deduct">
	<input name="account_id" value="<?php echo H($account->id) ?>" class="hidden" />
	<input name="department_id" value="<?php echo H($account->department->id ) ?>" class="hidden" />
	<input name="lab_id" value="<?php echo H($lab->id ) ?>" class="hidden" />
	<?php 
	$require = (string) V('form_require', ['extra_class' => 'top']);
    $requires = Config::get('form.billing_deduction')['requires']; 
	?>
	<table class="form">
		<tbody>
			<tr>
				<td class="left nowrap middle"><?php echo I18N::T('billing', '目前可用余额')?></td>
                <td class="left nowrap middle"><?php echo I18N::T('billing', '扣除金额')?></td>
			</tr>
			<tr>
                <td class="top"><input class="text currency readonly" size="20" sign="<?php echo H(Config::get('lab.currency_sign') ) ?>" value="<?php echo H((float)$account->balance ) ?>" readonly="true" /></td>
				<td class="top"><input name="amount" class="text currency" sign="<?php echo H(Config::get('lab.currency_sign') ) ?>" size="20" value="<?php echo H($form['amount']) ?>" /></td>
				<?= array_key_exists('amount', $requires) ? $require : ''; ?>
			</tr>
			<tr>
				<td class="left nowrap middle">
					<?= array_key_exists('certificate', $requires) ? $require : ''; ?>
					<?php echo I18N::T('billing', '凭证号')?>
					<?php echo V('form_filter',['error'=>$form->errors['certificate'][0]])?>
				</td>
                <?php if (L('ME')->is_allowed_to('修改扣费人员', $account)): ?>
                    <td class="left nowrap middle"><?php echo I18N::T('billing', '扣费人员')?></td>
                <?php endif; ?>
			</tr>

			<tr>
                <td class="top"><input name="certificate" class="text right"  size="20" value="<?php echo H($form['certificate']) ?>" /></td>
                <?php if (L('ME')->is_allowed_to('修改扣费人员', $account)): ?>
				<td class="top">
					<?php
						/*
						NO.BUG#315(guoping.zhang@2010.12.28)
						充值人员默认为是：当前用户
						*/
			   			echo Widget::factory('user_selector', [
			   					'autocomplete'=>URI::url('!billing/autocomplete/users'), 
			   					'name'=>'user_id',
			   					'user'=>L('ME'), 
			   			]); 
				   	?>
				</td>
                <?php endif; ?>
			</tr>
			<tr>
				<td colspan="2" class="left nowrap top"><?php echo I18N::T('billing', '备注')?></td>
			</tr>
            <tr>
                <td colspan="2" class="top">
                    <textarea name="description" type="text" cols="82" rows="4" class="text autogrow"><?php echo H($form['description'])?></textarea>
                </td>
            </tr>
		</tbody>
	</table>
        <div class="button_container">
            <div class="float_right">
                <input name="cancel" id="cancel" type="reset" class="font-button-default sm rmargin_2e4" value="<?php echo H(I18N::T('billing', '取消') ) ?>">
                <input name="submit" type="submit" class="font-button-save sm" value="<?php echo H(I18N::T('billing', '扣费')) ?>">
            </div>
        </div>
	</form>
</div>
