<?php if ( Module::is_installed('labs') ) : ?>
<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View usage logs of all equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Search usage logs.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit usage logs.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Fill out feedback forms.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Print or export usage history.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
<?php else : ?>
<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You are viewing the operation record of all equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Search by equipment names or violation types.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Click "Edit" to reset status.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
<?php endif; ?>