<?php
$message_uniqid = uniqid();
$me = L('ME');
$form_id = 'credit_classification_form_'. uniqid();
?>
<div class="relate_view">
    <form method="post" autocomplete="off" id="<?php echo H($form_id) ?>">
        <div class="form tpadding_2 rpadding_4 bpadding_5">
            <input type="text" name="key" value="<?php echo H($key) ?>" class="hidden" />
            <div id="<?php echo H($message_uniqid) ?>"></div>
            <input type="text" name="message_uniqid" value="<?php echo H($message_uniqid) ?>" class="hidden" />
            <div class="user_box">
            <div class="main_title clearfix">
            <h2 class="section_title">
                <div>
                    <a class="float_right view blue pointer event:click object:credit_edit src:!credit/credit_rule" title="<?= I18N::T('credit','添加')?>">
                        <span class="icon-add vertical_middle"></span>
                        <span class="vertical_middle" style="font-size: 14px;font-family: PingFangSC-Regular, PingFang SC;font-weight: 400;">
                            <?= I18N::T('credit','添加')?>
                        </span>
                    </a>
<!--                    <a class="button button_add view event:click object:credit_edit src:!credit/credit_rule">--><?//= I18N::T('credit','添加')?><!--</a>-->
                </div>
                <span class="middle"><?php echo $key ? T('减分规则') : T('加分规则');?></span>
            </h2>
            </div>
            <div class="interval_20"></div>
            <ul class="margin-left-1-half">
                <?php
                $credits = Q("credit_rule[type={$key}][hidden=" . Credit_Rule_Model::NOT_HIDE_ITEMS . "]");
                foreach($credits as $v):
                    if ($v->ref_no == Credit_Rule_Model::CUSTOM_ADD || $v->ref_no == Credit_Rule_Model::CUSTOM_CUT) continue;
                ?>
                <li class="tpadding_2">
                <?php
                $input_extra_attr = 'class="middle checkbox"';
                $label_extra_attr = 'class="middle"';
                echo Form::checkbox("id_".$v->id, !$v->is_disabled, HT($v->name), $input_extra_attr, $label_extra_attr);
                ?>
                <?= I18N::T('credit', $key ? '减' : '加')?>
                <input class="text number" size="5" name="score_<?=$v->id?>" value="<?php echo H($v->score) ?>" />
                <?= I18N::T('credit', '分')?>
                <?php if($v->is_custom == Credit_Rule_Model::STATUS_CUSTOM): ?>
                    <div class="trash_area lpadding_3" style="display: inline-block;">
                        <a confirm="<?php echo I18N::T('credit', '你确定要删除吗？请谨慎操作！'); ?>"
                            href="<?php echo URI::url('!credit/credit_rule/delete.').$v->id; ?>"
                            class="pointer flexform_button_delete"
                            style="color: #F5222D"
                        >
                            <span style="position: relative;top: 1.5px;" class=" icon-trash"></span>
                            <?php echo HT('删除');?>
                        </a>
                    </div>
                <?php endif; ?>
                </li>
                <?php endforeach;?>
            </ul>
            </div>
            <div class="submit_button">
                <input name="submit" type="submit" class="font-button-save float_right" value="<?php echo H(T('更新')) ?>" />
            </div>
        </div>
    </form>
</div>

<script>
$('#<?php echo $form_id;?>').submit(function () {
        Q.trigger({
            object: 'modify_credit',
            event: 'submit',
            url: '<?php echo URI::url('!credit/credit_rule')?>',
            data: {
                form: $(this).serialize()
            }
        });
        $('body,html').animate({scrollTop:0},200);
        return false;
    });
</script>

