<?php
echo CSS::load_async('notification_list');
$container_id = 'container_'.uniqid();
?>
<div class="notification_list clearfix">
    <div class="notification_types">
        <?php
            foreach($types as $key => $value) {
                if (!isset($selected_key)) {
                    $selected_key = $key;
                }
                echo V('credit:admin/credit/type', ['key'=>$key, 'value'=>$value, 'container_id'=>$container_id, 'selected_key'=>$selected_key]);

            }
        ?>
    </div>
    <div class="classification_container" id="<?php echo H($container_id) ?>">
        <?php echo V('credit:admin/credit/relate_view', ['key'=>$selected_key]);?>
    </div>
</div>
