<div class="tab_pagination_border">
    <?= $secondary_tabs; ?>
</div>
<?php if($secondary_tabs->panel_buttons || $secondary_tabs->search_box): ?>
    <div class='search_panel no_padding_secondary_search'>
        <?php
        echo $secondary_tabs->panel_buttons;
        echo $secondary_tabs->search_box;
        ?>
    </div>
<?php else: ?>
    <div class="interval_16"></div>
<?php endif ?>

<?= $secondary_tabs->content; ?>

