<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('research', '科研服务'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('research', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('research', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<thead>
				<tr>
					<?php foreach($valid_columns as $p => $p_name) : ?>
						<th class="left nowrap"><?php echo I18N::T('research', $p_name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
			foreach($researchs as $research): ?>
				<tr>
					<?php foreach ($valid_columns as $p => $p_name) : ?>
						<td class="left nowrap">
						<?php
							switch ($p) {
							case 'group':
                                $group = $research->group;
                                $groups = [];
                                $root = Tag_Model::root('group');
                                while ($group->id != $root->id) {
                                    array_unshift($groups, $group->name);
                                    $group = $group->parent;
                                }
                                echo H(join(' » ', $groups));
								break;
							case 'contacts':
							    $contacts = [];
                                foreach (Q("{$research} user.contact") as $user) {
                                    $contacts[] = H($user->name);
                                }
                                echo join(',', $contacts);
								break;
							default:
								echo H($research->{$p});
							}
						?>
					</td>
					<?php
					endforeach;
			endforeach;
			?>
				<tr>
					<td colspan="<?php echo count($valid_columns) + 1; ?>" class="right nowrap">
						<?php echo I18N::T('research', '总计:') . $users->total_count(); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
