<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<Platform xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Platform.xsd">
	<SchoolCode><?php echo $config['SchoolCode']?></SchoolCode>
	<SchoolName><?php echo $config['SchoolName']?></SchoolName>
	<SchoolTypeCode><?php echo $config['SchoolTypeCode']?></SchoolTypeCode>
	<SchoolPropertyCode><?php echo $config['SchoolPropertyCode']?></SchoolPropertyCode>
	<SchoolHolderCode><?php echo $config['SchoolHolderCode']?></SchoolHolderCode>
	<WebSite><?php echo $config['WebSite']?></WebSite>
	<Address><?php echo $config['Address']?></Address>
	<ZIPCode><?php echo $config['ZIPCode']?></ZIPCode>
	<Telephone><?php echo $config['Telephone']?></Telephone>
	<Fax><?php echo $config['Fax']?></Fax>
	<Email><?php echo $config['Email']?></Email>
	<ImageURL><?php echo $config['ImageURL']?></ImageURL>
	<Introduction><?php echo $config['Introduction']?></Introduction>
	<OtherInfo><?php echo $config['OtherInfo']?></OtherInfo>
	<PlatformDescXmlURL><?php echo $config['PlatformDescXmlURL']?></PlatformDescXmlURL>
	<InstrusShareXmlURL><?php echo $config['InstrusShareXmlURL']?></InstrusShareXmlURL>
	<InstrusShareEffectXmlURL><?php echo $config['InstrusShareEffectXmlURL']?></InstrusShareEffectXmlURL>
</Platform>