<?php if (!$hide_category_title): ?>
    <div class="category category_color">
        <span class="middle"><?php echo H($name) ?></span>
        <!-- <span class='category_image'><img src="images/point_down.png" with="20" height="20" /></span> -->
        <span class="category_image icon-up"></span>
    </div>
<?php endif ?>
<?php
$show = false;
foreach ($subMods as $subMod) {
    if (in_array($subMod, $moreMods)) {
        $show = strpos($subMod, MODULE_ID . '_') !== false;
    } else {
        $show = in_array(MODULE_ID, $subMods);
    }
    if ($show) break;
}
?>
<div class="items clearfix" style="display: <?= ($show ? 'block' : 'none') ?>"><?php echo $content; ?></div>
