<div class="item icon_item <?php echo $class?> icon_item_<?php echo H($id)?>">
	<?php $tooltip = H(I18N::T($item['i18n'], $item['title'])); ?>
	<div class="item_content" q-tooltip="<?php echo H($tooltip) ?>" q-tooltip_offsetY="8" q-tooltip_class="sidebar_tooltip">
		<a href="<?php echo H(URI::url($item['url']) ) ?>" class="icon center clearfix" <?php echo $item['target'] ? 'target="'. $item['target']. '"' : NULL;?>>
			<img width="32px" height="32px" src="<?php echo H(_C($item['icon']) ) ?>" class="icon pngfix"/>
		<?php 
		if ($item['notif_callback']) :
			$number = call_user_func($item['notif_callback'], $item);
			if ($number): $len = strlen($number); ?>
		<span class="sidebar_notif num_notif num_notif_<?php echo $len;?> middle"><?php echo $number; ?></span>
		<?php endif;
		endif;
		?>
		</a>
	</div>
</div>