<?php
$k = false;
if ($item['key'] && is_array($item['key'])) {
    foreach ($item['key'] as $key) {
        if(count(explode($key, $_SERVER['REQUEST_URI']))>1){
            $k = true;
            break;
        }
    }
}
?>
<div class="item list_item <?php echo $class?> list_item_<?php echo H($id)?> <?= $k ? 'active' : ''?>">
	<a class="item_content clearfix" href="<?php echo H(URI::url($item['url']) ) ?>" <?php echo $item['target'] ? 'target="'. $item['target'].'"' : NULL;?>>
		<!-- <img src="<?php // echo $item['icon'] ? H(_C($item['icon'])) : '' ?>" width="16px" height="16px" class="pngfix middle"/> -->
		<span class="<?= $item['class'] ?> rmargin_2"></span><span class="middle menu_font"><?php echo I18N::HT($item['i18n'], $item['title']); ?></span>
        <?php
        if ($item['notif_callback']) :
            $number = call_user_func($item['notif_callback'], $item);
            if ($number): 
                $len = strlen($number); 
        ?>
            <span class="sidebar_notif num_notif num_notif_<?php echo $len; ?> middle"><?php echo $number; ?></span>
            <?php endif; ?>
        <?php endif;?>
	</a>
</div>
