<?php
echo CSS::load_async('eq_sample:common');
echo JS::load('eq_sample:dropdown_links');
?>
<div class="pages"><?= $pagination ?></div>
<?php

	$table = Widget::factory('table');
	$table->name = 'eq_sample';
	$table->sort_asc = $sort_asc;
	$table->sort_by = $sort_by;

	$table->add_columns((array)$columns);

	$table->empty_message = I18N::T('eq_sample', '没有送样信息');
	if (count($samples)) {
//		$sort_by_time = in_array($sort_by, ['dtsubmit', 'dtrial', 'dtpickup']); // 或按时间排序
		$sort_by_time = in_array($sort_by, ['dtsubmit', 'dtpickup']); // 或按时间排序

		if ($sort_asc) {
			$flag_time = -1;
		}
		else {
			$flag_time = 2147483647;
		}

		// 将$sample存放到table对象中
		$table->samples = $samples;

		foreach ($samples as $sample) {
//		    error_log(print_r($sample),1);
			if ($sort_by_time) {
				$sample_time = $sort_by == 'dtsubmit' ? $sample->dtsubmit : $sample->dtpickup;
                $sample_trunk_time = $sample_time ? Date::get_day_start($sample_time) : 0;

				if ($sample_trunk_time != $flag_time) {
					if ($sample_trunk_time == 0 && $sort_by == 'dtpickup') {
						$separator = I18N::T('eq_sample', '未设取样');
					}
					elseif ($sample_trunk_time == 0 && $sort_by == 'dtsubmit') {
						$separator = I18N::T('eq_sample', '未设送样');
					}
					else {
						$separator = H(Date::fuzzy($sample_trunk_time));
					}
					$flag_time = $sample_trunk_time;
				}
			}

            $key = 'sample_' . $sample->id;
			$row = [
                'serial_number'=> V('eq_sample:samples_table/data/serial_number', ['sample' => $sample]),
				'equipment_name'=>V('eq_sample:samples_table/data/equipment_name', ['sample'=>$sample]),
				'count' => V('eq_sample:samples_table/data/count', ['sample'=>$sample]),
				'dtsubmit' => V('eq_sample:samples_table/data/dtsubmit', ['sample'=>$sample]),
				// 'dtrial' => V('eq_sample:samples_table/data/dtrial', array('sample'=>$sample)),
				'dtpickup' => ($sample->status != EQ_Sample_Model::STATUS_APPLIED && $sample->dtpickup) ? V('eq_sample:samples_table/data/dtpickup', ['sample'=>$sample]) : '--',
				'status' => V('eq_sample:samples_table/data/status', ['sample'=>$sample, '_type'=> 'lab', '_object'=> $lab]),
				'fee' => V('eq_sample:samples_table/data/fee', ['sample'=>$sample]),
				'sender' => '<div>' . $sample->sender->render(NULL, TRUE) . '</div>',
				'operator' => V('eq_sample:samples_table/data/operator', ['sample'=>$sample]),
				'description' => V('eq_sample:samples_table/data/description', ['sample'=>$sample]),
				'rest'=> Widget::factory('application:links', ['links'=>$sample->links('check')]),
			];
			$row = new ArrayIterator($row);
			Event::trigger('eq_sample.table_list.row', $row, $sample);
			$table->add_row_withkey($row, $key);
		}
	}

	echo $table;
    ?>
<div class="pages"><?= $pagination ?></div>
