<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('eq_sample', '仪器送样记录信息单')?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
            div.holder {
                display: inline-block;
                width: 24px;
            }
			a {
				color:blue;
				text-decoration:underline;
			}
			table {
				font-size: 14px;
				margin:auto;
                margin-bottom: 100px
			}
            
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				border-top: 1px solid #CCC;
			}
            table.report tbody td:nth-child(even){
                border-left: 2px solid #CCC;
            }
            table.report tbody td.category{
                padding-top:15px;
                border-top: 2px solid #CCC;
                border-bottom: 2px solid #CCC;
            }
			table.report .referred_sample {
				background-color: #eee;
				border:1px solid #CCC;
			}

            table.attachments .topborder{
                border-top: 1px solid #CCC;
            }
            table.report tbody tr.category{
                border-top: 2px solid #CCC;
                border-bottom: 2px solid #CCC;
            }
            table.report .description {
                word-break: break-word;
            }

		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>

	<body>
		<div class="buttons">
            <a href="<?php echo H($sample->url(NULL, NULL, NULL,'pdf')) ?>" target="_blank"><?php echo I18N::T('eq_sample', '导出PDF');?></a>			
            <a href="#" onclick="window.print(); return false;" class="lpadding_2"><?php echo I18N::T('eq_sample', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;" class="lpadding_2"><?php echo I18N::T('eq_sample', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
        <?php $equipment = $sample->equipment;?>
			<caption><?php echo I18N::T('eq_sample', '仪器送样记录信息单'); ?></caption>
			<tbody>
                <?php $print = $sample->eq_sample_view_print($sample);
                    $first = TRUE;
                    foreach ($print as $category => $fields):?>
                <tr>
                    <td colspan="2" class="left nowrap category" <?php echo $first ? 'style="border-top: 2px solid #CCCCCC;"' && $first = FALSE : '';?>>
                        <b><?php echo $category;?></b>
                    </td>
                </tr>
                    <?php foreach ($fields as $title => $v) :?>
                    <tr>
                        <td class="left nowrap">
                            <div class="holder">&#160;</div>
                            <?php echo $title;?>
                        </td>
                        <td class="left nowrap">
                            <?php echo $v?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                <?php endforeach;?>

                <?php $other_values = Event::trigger('eq_sample.view.print', $sample);
                ?>
                <?php foreach ($other_values as $category => $fields):?>
                <tr>
                    <td colspan="2" class="left nowrap category">
                        <b><?php echo $category;?></b>
                    </td>
                </tr>
                    <?php foreach ($fields as $title => $v) :?>
                    <tr>
                        <td class="left nowrap">
                            <div class="holder">&#160;</div>
                            <?php echo $title;?>
                        </td>
                        <td class="left nowrap">
                            <?php echo $v?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                <?php endforeach;?>

                <?php $extra = Extra_Model::fetch($sample->equipment, 'eq_sample');?>
                <?php foreach($extra->get_categories() as $category) :?>
                <?php 
                    $c_fields = $extra->get_fields($category);
                    if (count($c_fields) == 0) continue; 
                ?>
                <tr>
                    <td colspan="2" class="category">
                        <b><?php echo I18N::T('eq_sample', $category);?></b>
                    </td>
                </tr>
                    <?php foreach($c_fields as $uniqid=>$field) :?>
                    <tr>
                        <td class="left nowrap">
                            <div class="holder">&#160;</div>
                            <?php echo I18N::T('eq_sample', $field['title']);?>
                        </td>
                        <?php
                            $wrap = ($field[adopted] && $uniqid == 'description') || (
                                    !$field[adopted] && $field[type] == Extra_Model::TYPE_TEXTAREA
                                );
                            $class = !$wrap ? 'nowrap' : '';
                        ?>
                        <td class="left <?= $uniqid.' '.$class ?>">
                            <?php
                            $values = '';
                            if (!$field['adopted']) {
                                $extra_value =  O('extra_value', ['object'=> $sample]);
                                $values = $extra_value->values;
                                $values =  $values[$uniqid];

                                //过滤多选保存的值
                                if($field['type'] == Extra_Model::TYPE_CHECKBOX){
                                    $values = array_filter($values, function($value){return ($value == 'on');});
                                    $values = array_keys($values);
                                } 
                                //过滤下拉表单未选的值
                                else if($field['type'] == Extra_Model::TYPE_SELECT & $values == -1){
                                    $values = '--';
                                }else if($field['type'] == Extra_Model::TYPE_DATETIME){
                                    $values = date('Y-m-d',$values);
                                }
                                if(is_array($values)) $values =  join(',', $values);
                                echo H($values);
                            }
                            else {
                                if($field['type'] == Extra_Model::TYPE_CHECKBOX) {
                                    $checkbox_value = array_values(json_decode($sample->$uniqid, TRUE));
                                    $res = in_array('on', $checkbox_value);
                                    if (!$res) {
                                        echo T('无');
                                    } else {
                                        echo Event::trigger('sample.print.' . $uniqid, $sample, $uniqid) ? : H($sample->$uniqid);
                                    }
                                } else {
                                    echo Event::trigger('sample.print.' . $uniqid, $sample, $uniqid) ? : H($sample->$uniqid);
                                }
                            }
                            ?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                <?php endforeach;?>
                <?php echo Event::trigger('sample.extra.print', $sample); ?>
                <tr><td colspan="2" style="border-top: 2px solid #CCC"></td></tr>
			</tbody>
		</table>
        <?php 
            $full_path = NFS::get_path($sample, null, 'attachments', TRUE);
            if (
            L('ME')->is_allowed_to('下载文件', $sample, ['type' => 'attachments']) &&
            is_dir( $full_path ) && NFS::count_attachments($sample)):
                $files = NFS::file_list($full_path);
        ?>
            <table class="attachments" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
                <caption><?php echo I18N::T('eq_sample', '送样检测附件'); ?></caption>
                <tbody>
                    <tr style="border-bottom: 2px solid #CCC">
                        <th class="category" style="text-align:left"><?php echo I18N::T('eq_sample', '文件名称')?></th>
                        <th class="category"><?php echo I18N::T('eq_sample', '更新时间')?></th>
                        <th class="category"><?php echo I18N::T('eq_sample', '大小')?></th>
                    </tr>
                    <?php foreach ($files as $file) :?>
                    <tr class="topborder">
                        <td style="text-align:left">
                            <?php if($file['file'] && NFS::user_access(L('ME'), '下载文件', $sample, ['type'=>'attachments','path'=>$file['path']])):
                            ?>
                            <a href="<?php echo H(URI::url('!nfs/nfs_lite/index.'.$sample->name().'.'.$sample->id.'.attachments', ['path'=>$file['path'], 'form_token'=>$form_token])) ?>" class='prevent_default'>
                                <?php echo H($file['name']); ?> 
                            </a>
                            <?php else: ?>
                                <?php echo H($file['name']); ?> 
                            <?php endif;?>
                        </td>
                        <td><?php echo Date::format($file['mtime']);?></td>
                        <td><?php echo File::bytes($file['size']);?></td>
                    </tr>
                    <?php endforeach?>
                    <tr><td colspan="3" style="border-top: 2px solid #CCC"></td></tr>
                </tbody>
            </table>
        <?php endif?>
	</body>
</html>
