<?php $root_id = 'flexform_'.uniqid(); ?>
<div id="<?php echo H($root_id) ?>" class="flexform">
    <?php if ($this->title): ?>
        <h2 class="section_title">
            <span class="border"></span>
            <span class="black_title"><?php echo H($this->title) ?></span>
        </h2>
    	<!-- <h4><span class="middle"><?php // echo H($this->title) ?></span></h4> -->
    <?php endif; ?>
    <?php if($this->description): ?>&#160;<span class="description middle"><?php echo H($this->description) ?></span><?php endif;?>
    <?php /* if($this->description || $this->title): ?><div class="interval_24"></div><?php endif; */ ?>
    <div class="padding_1 panel clearfix">
    	<a class="button button_add flexform_button_add middle"><?php echo isset($this->add_button_text) ? $this->add_button_text : HT('添加项目'); ?></a>
    	<a class="button button_add middle"
           q-object="test_project_cat"
           q-event="click"
           q-src="<?php echo URI::url('!test_project/test_project'); ?>"
           q-static="equipment_id=<?php echo $equipment->id;?>" >
            <?php echo HT('添加分类'); ?>
        </a>
    </div>
    <div class="interval_12"></div>
    <div class="flexform_container">
	<?php
		$index = 0;
		if(is_array($this->existing_data)) foreach($this->existing_data as $data) {
            $index ++; 
			echo V('widgets/flexform_item', [
				'data'=> $data, 
				'index'=>$index, 
				'view'=>$this->item_view,
				'extra_vars'=> $this->extra_vars, 
				'no_delete_confirm'=>$this->no_delete_confirm,
			]); 
		}
	?>
    </div>
	<script class="flexform_template" type="text/html">
	<?php echo V('widgets/flexform_item', [
		'data'=> $this->template_data, 
		'view'=>$this->item_view, 
		'extra_vars'=> $this->extra_vars, 
		'index'=>'@INDEX',
		'no_delete_confirm'=>$this->no_delete_confirm,
	]); ?>
	</script>
</div>
<?php echo JS::load('widgets/flexform', ['index'=>$index, 'index_token'=>'@INDEX', 'root_id'=>$root_id, 'delete_message'=> $this->delete_message ?: T("你确定要删除吗？请谨慎操作！")]);

