<?php
	$me = L('ME');
?>
<div class="form padding_2">
	<form method="post" action="<?php echo H(URI::url('')) ?>">
	<?php echo Form::checkbox('no_labs_active_info', $me->no_labs_active_info, I18N::T('labs','实验室人员被激活时不接收提醒')); ?>
	<br />
	<?php echo Form::checkbox('labs_active_info_self', $me->labs_active_info_self, I18N::T('labs','自己激活人员时收到提醒')); ?>
	<div class="hr_2">&#160;</div>
	<input type="submit" name="submit" class="button button_save" value="<?php echo HT('更新')?>" />
	</form>
</div>

