<table>
	<tbody>
<?php 
	$datas = array_intersect_key((array)json_decode($update->new_data, TRUE), (array) $properties);
	foreach((array)$datas as $key=>$data):
		if (!$data)
			continue;
	?>
		<tr>
			<td class="left top nowrap">
				<strong class="description"><?php echo I18N::HT('eq_charge', $properties[$key]);?></strong>
			</td>
			<td class="left top">
				<div class="content_wrap lpadding_2">
				<?php echo H(I18N::T('eq_charge', $data), TRUE); ?>
				</div>
			</td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
