<div class="hr_1">&#160;</div>
<div class="clearfix">
	<table class="account_grid form">
		<tr>
			<td class="top icon">
				<?php 
					$user = O('user');
					echo $user->icon('64'); 
				?>
			</td>
			<td class="top nowrap">
				<h2>
					<?php echo H($account->lab_name)?>
					<small class="description normal">
						(<?php echo H($account->lab_id)?>)
					</small>
				</h2>
				<div class="hr_1">&#160;</div>
				<p>
					<?php
						echo I18N::T('accounts', 'PI：');
						echo H($account->pi_name);
					?>
				</p>
				<p>
					<?php
						echo I18N::T('accounts', 'PI Email：');
						echo H($account->pi_email);
					?>
				</p>
				<p>
					<?php
						echo I18N::T('accounts', '开通模块：');
						echo join(', ', $account->mod_enable);
						if ($account->mod_changed): ?>
							<span class="red">
							<?php echo I18N::T('accounts', '开通模块更新过, 但尚未同步'); ?>
							</span>
					<?php endif; ?>
				</p>
				<?php if ($account->etime):?>
				<p>
					<?php

						echo I18N::T('accounts', '到期时间：');
						echo Date::format($account->etime);


						if (time() > $account->etime && $account->is_open()):
					?>
							<span class="red"><?php echo I18N::T('accounts', '(未关闭)');?></span>
						<?php endif; ?>
				</p>
				<?php endif; ?>
				<div class="hr_3">&#160;</div>
				<?php echo V('application:widgets/links', ['links'=>$account->links('view'), 'separator'=>'&#160;&#160;']);?>
			</td>
		</tr>
	</table>
</div>
<div class="hr_3">&#160;</div>
<?php 
	echo $secondary_tabs;
	echo $secondary_tabs->content;
?>
	<?php echo Widget::factory('application:comments', ['object'=>$account]) ?>