<?php
$uniqid = uniqid();
$select_all_id = 'select_all_' . $uniqid;
$batch_form_id = 'batch_form_' . $uniqid;
$delete_selected = 'delete_selected_' . $uniqid;
$form_token = 'form_token_' . $uniqid;
$me = L('ME');
?>
<?php
$table = Widget::factory('table');

$table->name = 'distribution_billing';
$table->form = $form;


$table->add_columns([
    'checkbox' => [
        'type' => 'checkbox',
        'id' => $select_all_id,
        'align' => 'center'
    ],
    'distribution_serial_number'=> [
        'title' => I18N::T('billing_standard', '报销单号'),
        'nowrap'=>TRUE,
        'filter' => [
            'form' => V('billing_standard:charges_table/filters/distribution_serial_number', ['form' => $form])
        ],
        'weight'=> 10,
    ],
	'distribution_ctime'=>[
		'title'=>I18N::T('billing_standard', '报销单生成时间'),
		'nowrap'=>TRUE,
        'input_type' => 'date',
        'filter' => [
            'form' => V('billing_standard:charges_table/filters/distribution_ctime', ['form' => $form])
        ],
		'weight'=> 20,
    ],
    'group'=>[
        'title'=>I18N::T('billing_standard', '仪器单位'),
        'nowrap'=>TRUE,
        'filter' => [
            'form' => V('billing_standard:charges_table/filters/distribution_group', ['form' => $form])
        ],
        'weight'=> 40,
    ],
    'fund_no'=> [
        'title' => I18N::T('billing_standard', '经费卡号'),
        'nowrap'=> TRUE,
        'weight'=> 90,
    ],
    'balance'=> [
        'title' => I18N::T('billing_standard', '金额'),
        'nowrap'=> TRUE,
        'weight'=> 90,
    ]
]);


$table->add_column('rest', ['title'=>I18N::T('billing_standard', '操作'), 'align'=>'left', 'nowrap'=>TRUE, 'weight'=> 120,]);

$table->empty_message = I18N::T('billing_standard', '无符合条件的报销单');

$table->distributions = $distributions;

foreach ($distributions as $distribution) {
    $links = [];
    $links[] = [
        'text' => I18N::T('billing_standard', '撤回'),
        'extra' => 'class="blue" q-event="click" q-object="cancel_distribution"' .
                    ' q-static="' . H(['distribution_id' => $distribution['id']]) .
                    '" q-src="' . URI::url("!billing_standard/index") . '"',
    ];

    $links[] = [
        'text' => I18N::T('billing_standard', '修改经费卡号'),
        'extra' => 'class="blue" q-event="click" q-object="edit_distribution"' .
                     ' q-static="' . H(['distribution_id' => $distribution['id'], 'fund_id' => $distribution['fund_id']]) .
                     '" q-src="' . URI::url("!billing_standard/index") . '"',
     ];

     $links[] = [
         'text' => I18N::T('billing_standard', '提交'),
         'extra' => 'class="blue" q-event="click" q-object="submit_distribution"' .
                      ' q-static="' . H(['distribution_id' => $distribution['id']]) .
                      '" q-src="' . URI::url("!billing_standard/index") . '"',
      ];

	$add_row_arr = [
		'checkbox'=>V('billing_standard:charges_table/data/selector', ['id'=>$distribution['id'], 'select_all_id' => $select_all_id]),
		'distribution_serial_number'=>$distribution['distribution_serial_number'],
        'distribution_ctime'=>$distribution['distribution_ctime'],
		'group'=>$distribution['group'],
		'fund_no'=>$distribution['fund_no'],
		'balance'=>$distribution['balance'],
		'rest'=>Widget::factory('application:links', ['links'=>$links])
	];

	$table->add_row($add_row_arr);
}

$columns = (array)$table->columns;

$param = [
    'top_input_arr' => ['distribution_serial_number', 'group', 'distribution_ctime'],
    'columns'       => $columns,
];

echo V('application:search_box', $param);

?>


<form
    q-object="batch_edit_distribution"
    q-event="submit"
    q-src="<?= H(URI::url("!billing_standard/index")); ?>"
    id="<?= H($batch_form_id) ?>"
    method="post"
    autocomplete="off"
>
<div class="panel clearfix">
<div class="float_left" style="padding-top: 10px; color: #000;">
        未报销（个）：<span style="color: var(--basiccolor);"><?php echo $total_distributions; ?></span>，合计金额（元）：<span style="color: var(--basiccolor);"><?php echo $total_amount; ?></span>
    </div>
    <div class="float_right">
        <input class="font-button-save" type="submit" name="cancel" value="<?= I18N::T('application', '批量撤回') ?>">
        <input class="font-button-save" type="submit" name="edit" value="<?= I18N::T('application', '批量修改经费卡号') ?>">
        <input class="font-button-save" type="submit" name="submit" value="<?= I18N::T('application', '批量提交') ?>">
    </div>
</div>
<div class="interval_16"></div>
<?php 
    echo $table;
?>
</form>
<div style="text-align: right"><?php echo $pagination; ?></div>
<div class="interval_10"></div>
<?php
echo JS::load('people:index_operate', ['select_all_id'=>$select_all_id, 'batch_form_id' => $batch_form_id]);
?>
