<?= CSS::load_async('calendars:common') ?>

    <script>
        Q.globals.cal_week_rel = 'edit_week';
        Q.globals.mode = 'list';
    </script>
<?php
$uniqid = uniqid();
$select_all_id = 'select_all_' . $uniqid;
$batch_form_id = 'batch_form_' . $uniqid;
$delete_selected = 'delete_selected_' . $uniqid;
$form_token = 'form_token_' . $uniqid;
$table = Widget::factory('table');
$table->name = 'approval';
$table->form = $form;

if($form['dtstart_check'] && $form['dtend_check']) {
    $form['date'] = H(date('Y/m/d', $form['dtstart'])).'~'.H(date('Y/m/d', $form['dtend']));
} elseif($form['dtstart_check']) {
    $form['date'] = H(date('Y/m/d', $form['dtstart'])).'~'.I18N::T('approval_flow', '最末');
} elseif($form['dtend_check']) {
    $form['date'] = I18N::T('approval_flow', '最初').'~'.H(date('Y/m/d', $form['dtend']));
}

$columns = [
    //'@' => NULL,
    'checkbox' => [
        'type' => 'checkbox',
        'id' => $select_all_id,
        'align' => 'center'
    ],
    'equipment'=> [
        'title' => I18N::T('approval_flow', '仪器名称'),
        'filter' => [
            'form' => V('approval_flow:flow_table/filters/equipment', ['equipment' => $form['equipment']]),
            'value' => $form['equipment'] ? H($form['equipment']) : NULL
        ],
        'align' => 'left',
        'nowrap' => TRUE
    ],
    'user'=> [
        'title' => I18N::T('approval_flow', '申请人'),
        'filter' => [
            'form' => V('approval_flow:flow_table/filters/user', ['user' => $form['user']]),
            'value' => $form['user'] ? O('user', H($form['user']))->name : NULL
        ],
        'align' => 'left',
        'nowrap' => TRUE
    ],
    'date' => [
        'title' => I18N::T('approval_flow', '预约起止时间'),
        'input_type' => 'date',
        'align' => 'left',
        'nowrap' =>TRUE,
        'filter' => [
            'form'  => V('approval_flow:flow_table/filters/date_range', [
                'dtstart' => $form['dtstart'],
                'dtend' => $form['dtend']
            ])
        ]
    ],
    'ctime' => [
        'title' => I18N::T('approval_flow', '申请时间'),
        'input_type' => 'date',
        'align' => 'left',
        'nowrap' =>TRUE,
        'filter'    => [
            'form'  => V('approval_flow:flow_table/filters/date_range', [
                'dtstart' => $form['ctime_dtstart'],
                'dtend' => $form['ctime_dtend'],
                'name_prefix' => 'ctime_',
            ])
        ],
    ],
    /*'description'=> [
        'title' => I18N::T('approval_flow', '备注'),
        'align' => 'left',
        'nowrap' => TRUE
    ],*/
    'rest'=>[
        'title'  => I18N::T('eq_reserv', '操作'),
        'align'=>'left',
        'nowrap'=>TRUE,
    ]
];

if ($type == 'equipment') {
    unset($columns['equipment']);
}

$incharge = Q("{$me} equipment.incharge");
if (!$incharge->total_count()) {
    if ($type == 'people') {
        unset($columns['user']);
    }
}

$table->add_columns($columns);

$table->empty_message = I18N::T('approval_flow', '没有查询到相应的项目!');

if (count($approval) > 0) {

    foreach($approval as $ap) {
        $rows = [
            '@' => [
                'view'=>$ap->equipment->icon('32', 'style="display:block"'),
                'extra'=>'style="padding:4px" align="right" align="right" align="right"'
            ],
            'checkbox'=>V('approval_flow:flow_table/data/selector', ['ap'=>$ap, 'select_all_id' => $select_all_id]),
            'equipment' => V('approval_flow:flow_table/data/equipment', ['ap' => $ap]),
            'user' => V('approval_flow:flow_table/data/user', ['ap' => $ap]),
            'date' => V('approval_flow:flow_table/data/date', ['ap' => $ap]),
            'ctime' => V('approval_flow:flow_table/data/ctime', ['ap' => $ap]),
            'rest' => Widget::factory('application:links', ['links' => $ap->links()])
        ];

        if ($type == 'equipment') {
            $rows['@'] = [
                'view'=>$ap->user->icon('32', 'style="display:block"'),
                'extra'=>'style="padding:4px" align="right" align="right" align="right"'
            ];
            unset($columns['equipment']);
        }

        $table->add_row($rows);
    }
}

$param = [
    'top_input_arr' => ['equipment', 'user', 'date', 'ctime'],
    'columns'       => (array)$table->columns,
];

echo V('application:search_box', $param);
?>

<form
    q-object="batch_action"
    q-event="submit"
    q-src="<?= H(URI::url("!approval_flow/index")); ?>"
    id="<?= H($batch_form_id) ?>"
    method="post"
    autocomplete="off"
>
<div class="panel clearfix">
    <div class="float_right">
        <input class="font-button-delete" type="submit" name="reject" value="<?= I18N::T('application', '批量驳回') ?>">
        <input class="font-button-save" type="submit" name="pass" value="<?= I18N::T('application', '批量通过') ?>">
    </div>
</div>
<div class="interval_16"></div>
<?php 
    echo $table;
?>
</form>

<div style="text-align: right"><?php echo $pagination; ?></div>
<div class="interval_10"></div>
<?php
echo JS::load('people:index_operate', ['select_all_id'=>$select_all_id, 'batch_form_id' => $batch_form_id]);
?>