<?php
$grantSelect = ($sample->fund_card_no ? $sample->fund_card_no : $form['fund_card_no']) ?: 0;
$user = $user->id ? $user : ($form['sender'] ? O('user', $form['sender']) : $sample->sender);
$grants = (array)Billing_Standard::get_grants($user);
$tr_authorized_id = 'user_authorized';
?>

<td id="<?php echo $tr_authorized_id; ?>" class="label left nowrap">
    <div class="title">
        <?php 
          $must_select_fund = Config::get('billing_standard.must_select_fund', 0) && 
          !Event::trigger('billing_standard.not_must_select_fund', $user);
          if ($must_select_fund) echo "*";
         ?>
         <?php echo I18N::T('billing_standard', '经费卡号'); ?>
    </div>
    <div class="middle nowrap">
      <?php echo Form::dropdown('fund_card_no', ['--'] + $grants, $grantSelect,
            'style="width: 280px;"'
        ); ?>
    </div>
</td>

<script type="text/javascript">
  $(document).ready(function () {
    var $user_selector = $("input:hidden[name=<?php echo $user_selector ?: 'sender'; ?>]")
      , $tr_authorized_id = "<?php echo $tr_authorized_id; ?>"
      , $url = "<?php echo $url ?: URI::url('!billing_standard/index'); ?>"
      , $sam_id = "<?php echo H($sample->id) ?>"

    $user_selector.change(function () {
      var $user_id = $(this).val();
      replace_grant_items($url, $user_id, $tr_authorized_id);
    });

    function replace_grant_items(rq_url, u_id, tr_id, sam_id) {
      Q.trigger({
        object: 'edit_eq_sample_grants',
        event: 'change',
        data: {
          'user_id': u_id,
          'tr_authorized_id': $tr_authorized_id,
          'sample_id': $sam_id
        },
        url: rq_url
      });
    }
  });
</script>