<div style="width: 100px;height: 100px;bottom:0;right:0;position:absolute;overflow:hidden;">
	<div class="qrcode_mask"></div>
</div>
<div class="qrcode">
	<p>
	    <img width="100" src="<?php echo URI::url('!wechat/qrcode/equipment.'.$equipment->yiqikong_id); ?>" />
	</p>
	<!-- <p class="center">
	    <?php // echo Widget::factory('application:links', array('links' => $equipment->links('wechat'))) ?>
	</p> -->
</div>
