<?php if(!is_array($month)) $month = []; ?>
<div class="interval_6"></div>
<div>
<table class="month">
<tr>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][1]', in_array(1, $month) ? TRUE : FALSE, I18N::T('application','一月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][2]', in_array(2, $month) ? TRUE : FALSE, I18N::T('application','二月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][3]', in_array(3, $month) ? TRUE : FALSE, I18N::T('application','三月'), 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][4]', in_array(4, $month) ? TRUE : FALSE, I18N::T('application','四月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][5]', in_array(5, $month) ? TRUE : FALSE, I18N::T('application','五月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][6]', in_array(6, $month) ? TRUE : FALSE, I18N::T('application','六月'), 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][7]', in_array(7, $month) ? TRUE : FALSE, I18N::T('application','七月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][8]', in_array(8, $month) ? TRUE : FALSE, I18N::T('application','八月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][9]', in_array(9, $month) ? TRUE : FALSE, I18N::T('application','九月'), 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][10]', in_array(10, $month) ? TRUE : FALSE, I18N::T('application','十月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][11]', in_array(11, $month) ? TRUE : FALSE, I18N::T('application','十一月'), 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('month['.$flexform_index.'][12]', in_array(12, $month) ? TRUE : FALSE, I18N::T('application','十二月'), 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>
</table>
</div>
