<?php if(!is_array($month_week)) $month_week = []; ?>
<div><div class="month_week">
<table class="form">
<tr>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('month_week['.$flexform_index.'][1]', in_array(1, $month_week) ? TRUE : FALSE, I18N::T('application','第一周'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('month_week['.$flexform_index.'][2]', in_array(2, $month_week) ? TRUE : FALSE, I18N::T('application','第二周'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('month_week['.$flexform_index.'][3]', in_array(3, $month_week) ? TRUE : FALSE, I18N::T('application','第三周'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('month_week['.$flexform_index.'][4]', in_array(4, $month_week) ? TRUE : FALSE, I18N::T('application','第四周'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('month_week['.$flexform_index.'][5]', in_array(5, $month_week) ? TRUE : FALSE, I18N::T('application','最后一周'), 'class="middle checkbox"', 'class="middle"') ?></td>
</tr>
</table>
</div></div>
