<?php if(!is_array($week_day)) $week_day = []; ?>
<div class="interval_6"></div>
<div><div class="week_day">
<table class="form">
<tr>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][0]', in_array(0, $week_day) ? TRUE : FALSE , I18N::T('application','周日'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][1]', in_array(1, $week_day) ? TRUE : FALSE, I18N::T('application','周一'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][2]', in_array(2, $week_day) ? TRUE : FALSE, I18N::T('application','周二'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][3]', in_array(3, $week_day) ? TRUE : FALSE, I18N::T('application','周三'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][4]', in_array(4, $week_day) ? TRUE : FALSE, I18N::T('application','周四'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][5]', in_array(5, $week_day) ? TRUE : FALSE, I18N::T('application','周五'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap" width="126"><?php echo Form::checkbox('week_day['.$flexform_index.'][6]', in_array(6, $week_day) ? TRUE : FALSE, I18N::T('application','周六'), 'class="middle checkbox"', 'class="middle"') ?></td>
</tr>
<tr><td class="interval_20"></td></tr>
<tr>
	<td class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][-1]', in_array(-1, $week_day) ? TRUE : FALSE, I18N::T('application','每天'), 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][-2]', in_array(-2, $week_day) ? TRUE : FALSE, I18N::T('application','工作日'), 'class="middle checkbox"', 'class="middle tooltip:'.H(rawurlencode('周一至周五')).'"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][-3]', in_array(-3, $week_day) ? TRUE : FALSE, I18N::T('application','周末'), 'class="middle checkbox"', 'class="middle tooltip:'.H(rawurlencode('周六、周日')).'"') ?></td>
</tr>
</table>
</div></div>
