<?php if(!is_array($week_day)) $week_day = []; ?>

<div class="interval_6">&nbsp</div>
<div>
<ul class="weekday" >
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][0]', in_array(0, $week_day) ? TRUE : FALSE , I18N::T('application','周日'), 'class="middle checkbox" disabled checked', 'class="middle" disabled checked') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][1]', in_array(1, $week_day) ? TRUE : FALSE, I18N::T('application','周一'), 'class="middle checkbox" disabled ', 'class="middle" disabled') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][2]', in_array(2, $week_day) ? TRUE : FALSE, I18N::T('application','周二'), 'class="middle checkbox" disabled', 'class="middle" disabled') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][3]', in_array(3, $week_day) ? TRUE : FALSE, I18N::T('application','周三'), 'class="middle checkbox" disabled', 'class="middle" disabled') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][4]', in_array(4, $week_day) ? TRUE : FALSE, I18N::T('application','周四'), 'class="middle checkbox" disabled', 'class="middle" disabled') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][5]', in_array(5, $week_day) ? TRUE : FALSE, I18N::T('application','周五'), 'class="middle checkbox" disabled', 'class="middle" disabled') ?></li>
	<li class="left nowrap"><?php echo Form::checkbox('week_day['.$flexform_index.'][6]', in_array(6, $week_day) ? TRUE : FALSE, I18N::T('application','周六'), 'class="middle checkbox" disabled checked', 'class="middle" disabled checked') ?></li>
</ul>
</div>
