<?php 
if(!is_array($month_day)) $month_day = []; 
if(!is_array($year_month)) $year_month = [];
?>
<div class="interval_6">&nbsp</div>
<table class="month_day">
<tr>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][1]', in_array(1, $year_month) ? TRUE : FALSE, '一月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][2]', in_array(2, $year_month) ? TRUE : FALSE, '二月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][3]', in_array(3, $year_month) ? TRUE : FALSE, '三月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][4]', in_array(4, $year_month) ? TRUE : FALSE, '四月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][5]', in_array(5, $year_month) ? TRUE : FALSE, '五月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][6]', in_array(6, $year_month) ? TRUE : FALSE, '六月', 'class="middle checkbox"', 'class="middle"') ?></td>
</tr>
<tr>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][7]', in_array(7, $year_month) ? TRUE : FALSE, '七月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][8]', in_array(8, $year_month) ? TRUE : FALSE, '八月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][9]', in_array(9, $year_month) ? TRUE : FALSE, '九月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][10]', in_array(10, $year_month) ? TRUE : FALSE, '十月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][11]', in_array(11, $year_month) ? TRUE : FALSE, '十一月', 'class="middle checkbox"', 'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('year_month['.$flexform_index.'][12]', in_array(12, $year_month) ? TRUE : FALSE, '十二月', 'class="middle checkbox"', 'class="middle"') ?></td>
</tr>
</table>
