<?php 
$uniqid = uniqid();
$plot_id = 'plot_'.$uniqid;
$left_container_id = 'left_container_'.$uniqid;
$legend_id = 'legend_'.$uniqid;

?>
<div class="bucket_vis clearfix">
<div class="intaval_24">&nbsp</div>
<table class="flexible">
<tr>
	<td class="top tight ">
	    <div id="<?php echo H($left_container_id ) ?>" class="clearfix" style="width:200px;">
			<fieldset>
				<legend><?php echo I18N::HT('envmon', '曲线坐标') ?></legend>
				<?php echo V('envmon:bucket/curve_axis', ['node'=>$node, 'axes' => $options['axes']]);?>
			</fieldset>
			<?php 
				echo V('envmon:bucket/axis_parameters', [
					'legend' => I18N::T('envmon', 'X轴'),
					'axis' => 'xaxis',
					'nolog' => TRUE,
					'data' => $options['xaxis'],
				]); 
			?>
			<?php 
				echo V('envmon:bucket/axis_parameters', [
					'legend' => I18N::T('envmon', 'Y1轴'),
					'axis' => 'yaxis',
					'data' => $options['yaxis'],
				]); 
			?>
			<?php 
				echo V('envmon:bucket/axis_parameters', [
					'legend' => I18N::T('envmon', 'Y2轴'),
					'axis' => 'y2axis',
					'data' => $options['y2axis'],
				]); 
			?>
			<fieldset>
				<legend><?php echo I18N::HT('envmon', '其他') ?></legend>
				<div class="lpadding_1">
					<p>
						<a class="button icon-lg icon-history" title="<?php echo I18N::T('envmon', '重置视图') ?>" onclick="jQuery('#<?php echo $plot_id ?>').trigger('envplotResetZoom'); return false;"><?php echo I18N::T('envmon', '重置视图') ?></a>
						<a class="button icon-lg icon-refresh" title="<?php echo I18N::T('envmon', '刷新')?>" onclick="jQuery('#<?php echo $plot_id ?>').trigger('envplotChange'); return false;"><?php echo I18N::T('envmon', '刷新') ?></a>
					</p>
				</div>
			</fieldset>
		</div>
	</td>

	<td class="top">
		<div class="padding_1">
			<div id="<?php echo H($plot_id); ?>" class="loading" style="position:relative"></div>
		</div>
	</td>
</tr>
</table>
</div>
<?php 
echo JS::load('envmon:envplot', [
				'node_id' => $node->id,
				'plot_id' => $plot_id,
				'left_container_id' => $left_container_id,
				'bottom_container_id' => $bottom_container_id,
				'legend_id' => $legend_id,
				'options' => $options,
				'xlabel' => I18N::HT('envmon', '时间'),
				'from' => I18N::HT('envmon', '从'),
				'to' => I18N::HT('envmon', '到'),
				'xaxisMax' => $options['xaxis']['max'] ?: Date::time(),
				'xaxisMin' => $options['xaxis']['min'] ?: Date::time() - 3600
			]);
			?>