<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Please add laboratory project for statistic purposes. Users need to choose projects when filling out feedback forms.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">For campus users, please choose between research projects and teaching projects. For off-campus users, please choose public service.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>