<div class="hr_1">&#160;</div>
<div class="panel padding_1 clearfix">
	<?php if (L('ME')->is_allowed_to('添加仪器黑名单', $equipment?:'equipment') ): ?>
		<a class="button button_add"
		q-event="click"
		q-object='add_banned_user'
		q-static="<?php echo H(['e_id'=>$equipment->id])?>"
		q-src="<?php echo H(URI::url('!eq_ban/blacklist')) ?>" ><?php echo I18N::T('eq_ban', '添加封禁用户')?></a>
	<?php endif;?>
</div>
<?php echo $pagination; ?>
<?php

	/*
		NO. TASK#256 (Cheng.Liu@2010.11.19)
		equipments blacklist 转换成table widget
	*/
	$table = Widget::factory('table');
	$table->name = 'equipments_blacklist';
	$table->add_columns([
		'@'=>[
			'align'=>'center',
			'nowrap'=>TRUE,
		],
		'name'=>[
			'title'=>I18N::T('eq_ban', '姓名'),
			'filter'=>[
				'form'=>V('eq_ban:users_table/filters/name', ['name'=>$form['name']]),
				'value'=>$form['name'] ? H($form['name']) : NULL
			],
			'nowrap'=>TRUE
		],
		'reason'=>[
			'title'=>I18N::T('eq_ban', '封禁原因'),
			'extra_class'=>'flexible',
			'nowrap'=>TRUE
		],
		'date'=>[
			'title'=>I18N::T('eq_ban', '封禁时间'),
			'nowrap'=>TRUE
		],
		'atime'=>[
			'title'=>I18N::T('eq_ban', '到期时间'),
			'nowrap'=>TRUE,
            'align'=> 'center'
		],
		'rest'=>[
			'nowrap'=>TRUE,
			'align'=>'right'
		]
	]);

	$table->empty_message = I18N::T('eq_ban', '没有符合条件的用户');
	if ($banned->total_count()) {
		foreach($banned as $banned_item) {
			$user = $banned_item->user;
			$lab = $user->lab;
			$links = $banned_item->links();
			$table->add_row([
				'@' => [
					'view'=>$user->icon('32', 'style="display:block"'),
					'extra'=>'style="padding:4px" align="right"',
				],
				'name'=>V('eq_ban:users_table/data/name', ['user'=>$user]),
				//'lab'=>V('eq_ban:users_table/data/lab', array('lab'=>$lab)),
				'reason'=>H($banned_item->reason),
				'date'=>Date::format($banned_item->ctime, 'Y/m/d'),
				'atime'=>$banned_item->atime ? Date::format($banned_item->atime, 'Y/m/d') : I18N::T('eq_ban', '不过期'),
				'rest'=> Widget::factory('application:links', ['links'=>$links]),
			]);
		}
	}

	echo $table;
?>

