<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('entrance', '门禁系统进出记录'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>
<body>
	<?php 
	$max_print_count = Config::get('print.max.print_count', 500);

	if ($records->total_count() > $max_print_count) :
		$form_token = Session::temp_token('dc_record_',300);
		$door_link = $records->current()->door->url(NULL, NULL, NULL, 'view');
		$csv_link = I18N::T('entrance', '导出Excel');
		$return_link = I18N::T('entrance', '搜索条件');
			
	?>
	<div class="center">
		<h2><?php echo I18N::T('entrance', '门禁系统进出记录'); ?></h2>
		<strong><?php echo I18N::T('entrance', '您选择数据超过%print_limit条, 不适合打印, 请选择%csv_link或调整您的%return_url', [
		'%print_limit' => $max_print_count,
		'%csv_link' => $csv_link, 
		'%return_url' => $return_link]);?>
		</strong>
	</div>
	<?php else: ;?>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
		<a href="#" onclick="window.close(); return false;"><?php echo T('关闭'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('entrance', '门禁系统进出记录'); ?></caption>
	<thead id="stat">
		<tr>
		<td colspan="8">
		<?php echo I18N::T('entrance', '时间范围:'); ?>
		&#160;
		<?php 
            $dtstart = $form['dtstart'];
            $dtend = $form['dtend'];
			$dtstart = isset($dtstart) ? date('Y/m/d', $dtstart) : I18N::T('entrance' ,'最初');
			$dtend = isset($dtend) ? date('Y/m/d', $dtend) : I18N::T('entrance' ,'最末');
			echo $dtstart . ' ～ ' . $dtend;
		 ?>
		</td>
		</tr>
	</thead>
	<thead>
		<tr>
		<?php foreach($valid_columns as $key=>$value) :?>	
		<td class="left nowrap"><?php echo I18N::T('entrance',$value); ?></td>
		<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($records as $record): ?>
		<tr>
		<?php 
			$data = [];
			foreach ($valid_columns as $key => $value) {
				switch ($key) {
				case 'name':
					$data[] = H($record->door->name);
					break;
				case 'location':
					$tags = [];
					$tag_root = Tag_Model::root('location');
					foreach (Q("{$record->door} tag_location") as $tag) {
						$repeated = false;
						if ($tag->id == $tag_root->id) {
							continue;
						}
						$tags[$tag->id] = $tag;
						$tag = $tag->parent;
						while ($tag->id && $tag->id != $tag_root->id) {
							if (array_key_exists($tag->id, $tags)) {
								unset($tags[$tag->id]);
							}
							$tag = $tag->parent;
						}
					}

					$locations = [];
					foreach ($tags as $id => $tag) {
						$locations[] = H(strip_tags(V('application:tag/path', ['tag' => $tag, 'tag_root' => Tag_Model::root('location'), 'url_template' => URI::url('', 'location_id=%tag_id')])));
					}
					$data[] = join("<br />", $locations);
					break;
				case 'user':
					$data[] = H($record->user->name); 
					break;
				case 'lab':
					$labs = Q("{$record->user} lab")->to_assoc('id', 'name');
                    $data[] = H(join(',', $labs));
					break;
				case 'date':
					$data[] = H(date('Y/m/d H:i:s',$record->time));
					break;
				case 'direction':
					$data[] = H(DC_Record_Model::$direction[$record->direction]);
					break;
				case 'site':
					$data[] = H(Config::get('site.map')[$record->door->site]);
					break;
				} 
			}
		?>
		<?php foreach ($data as $key => $value) : ?>
		<td class="left nowrap"><?php echo $value ?></td>
		<?php endforeach; ?>
		</tr>
		<?php endforeach;?>
	</tbody>
	</table>
<?php endif;?>
</body>
</html>
