<div class="dashboard"></div>
<script>
    $(function() {
        var height = document.body.scrollHeight;

        var src = "<?= $src; ?>";

        var iframe = document.createElement('iframe');
        iframe.setAttribute('src', src);
        iframe.setAttribute('width', '100%');
        iframe.setAttribute('frameborder', '0');
        iframe.setAttribute('height', height);

        $('.dashboard').append(iframe);
    })
</script>