<div id="dashboard" style="margin: 10px"></div>
<?php
    $src = "http://" . $_SERVER["HTTP_HOST"] . '/dashboard/';
?>

<script>
    $(function() {
        var src = "<?= $src; ?>";
        var iframe = document.createElement('iframe');
        iframe.setAttribute('src', src);
        iframe.setAttribute('width', '100%');
        iframe.setAttribute('frameborder', '0');
        iframe.setAttribute('scrolling', 'no');
        iframe.height=document.getElementById('dashboard').offsetWidth / 16 * 9;
        $('#dashboard').append(iframe);
        $('.center_content').remove();
    })
</script>
