<div class="form">
<form class="view object:create_form event:submit">
	<?php echo Form::hidden('path', $path); ?>
	<?php echo Form::hidden('old_name', $name); ?>
	<?php echo Form::hidden('form_token', $form_token)?>
	<?php echo V('form_error', ['form'=>$form]);?>
	<table class="form">
		<tbody>
			<tr>
				<td class="left nowrap middle">
                    <?php echo T('名称')?><br>
                    <?php echo V('form_filter',['error'=>$form->errors['name'][0]]); ?>
                </td>
				<td class="middle">
					<input type="text" class="text" name="name" value="<?php echo H($name ?: 'untitled') ?>" />
				</td>
			</tr>
		</tbody>
	</table>
    <div class="button_container">
        <div class="float_right">
            <input type="submit" name="submit" class="font-button-save" value="提交">
        </div>
    </div>
</form>
</div>
