<div class="padding_1">
    <h3 class="center"><?= T('温馨提示') ?></h3>
    <div class="lmargin_2 left">
        <strong>
            <?= $me->name .
            T('文件 ' . $file_name . ' 已上传，正在排队等待病毒检测，结束后会发消息至您的信息中心，请注意查收！您也可以在右侧查看正在上传的文件列表') ?>
        </strong>
    </div>
    <div class="right">
        <a class="blue income_know"><?= T('我知道了') ?></a>
    </div>
</div>
<script>
    $(function () {
        $('.fixed-menu').show();
        $('.income_know').click(function (){
            $('div.prop_box').remove();
        });
    })
</script>