<div class="interval_16"></div>
<?= CSS::load_async('eq_approval:common') ?>

<?php

	$table = Widget::factory('table');
	$table->name = 'eq_approval_user_voucher';
	$field = [
		'equipment_name' => [
			'title' => I18N::T('eq_approval', '仪器名称'),
			'align' => 'left',
			'nowrap' => TRUE,
			'filter' => [
				'form' => V('eq_approval:voucher_tables/filters/equipment_name', ['equipment_name' => $form['equipment_name']]),
				'value' => $form['equipment_name'] ? H($form['equipment_name']) : NULL
			]
		],
		'used_time' => [
			'title' => I18N::T('eq_approval', '预计使用时长'),
			'align' => 'center',

			/*
			'filter' => [
				'form' => V('eq_approval:voucher_tables/filters/used_time', ['used_time' => $form['used_time']]),
				'value' => $form['used_time'] ? H($form['used_time']) : NULL
			],
			*/
			'nowrap' => TRUE
		],
		'samples' => [
			'title' => I18N::T('eq_approval', '送样数'),
			'align' => 'center',
			'nowrap' => TRUE,
			// 'filter' => [
			// 	'form' => V('eq_approval:voucher_tables/filters/samples', ['samples' => $form['samples']]),
			// 	'value' => $form['samples'] ? H($form['samples']) : NULL
			// ],
		],
		'auto_amount' => [
			'title' => I18N::T('eq_approval', '预计价格'),
			'align' => 'center',
			'nowrap' => TRUE
		],
		'type' => [
			'title' => I18N::T('eq_approval', '预约类型'),
			'align' => 'center',
			'nowrap' => TRUE
		],
		'status' => [
			'title' => I18N::T('eq_approval', '申请状态'),
			'align' => 'center',
			'nowrap' => TRUE
		],
		'use_status' => [
			'title' => I18N::T('eq_approval', '使用状态'),
			'align' => 'center',
			'nowrap' => TRUE
		],
		'ctime' => [
			'title' => I18N::T('eq_approval', '申请时间'),
			'align' => 'center',
			'nowrap' => TRUE
		],
		'rest' => [
			'align' => 'right',
			'extra_class' => 'flexible',
			'nowrap' => TRUE
		],
	];
	$table->add_columns($field);

	$table->empty_message = I18N::T('eq_approval', '没有相关预约凭证!');

    $param = [
        'panel_buttons' => $panel_buttons,
        'top_input_arr'=> ['equipment_name'],
        'columns'=> $table->columns,
    ];
    echo V('application:search_box', $param);

	foreach ($vouchers as $voucher) {
		$equipment = $voucher->equipment;
		$links = $voucher->links('index');
		$table->add_row([
			'equipment_name' => V('eq_approval:voucher_tables/data/equipment_name', ['equipment' => $equipment]),
			'used_time' => V('eq_approval:voucher_tables/data/used_time', ['voucher' => $voucher]),
			'samples' => V('eq_approval:voucher_tables/data/sample', ['voucher' => $voucher]),
			'auto_amount' => V('eq_approval:voucher_tables/data/auto_amount', ['voucher' => $voucher]),
			'type' => V('eq_approval:voucher_tables/data/type', ['voucher' => $voucher]),
			'status' => V('eq_approval:voucher_tables/data/status', ['voucher' => $voucher]),
			'use_status' => V('eq_approval:voucher_tables/data/use_status', ['voucher' => $voucher]),
			'ctime' => V('eq_approval:voucher_tables/data/ctime', ['voucher' => $voucher]),
			'rest' => Widget::factory('application:links', ['links' => $links]),
		]);
	}
?>
<div class="pages" ><?php echo $pagination; ?></div>
<?php
echo $table;
?>
<div class="pages" ><?php echo $pagination; ?></div>
