<div class="description">
	<p>You are viewing the equipment information and the status of current user.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit or delete equipment information.</span>
	</p>
	<?php if ( Module::is_installed('labs') ) : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may turn on/off the instrument power supply or login/logout of system in a remote mode for users under special circumstances.</span>
	</p>
	<?php else : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may turn on/off the instrument power supply in a remote mode for users under special circumstances.</span>
	</p>
	<?php endif; ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
