<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View blocked user list of this equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Search blocked users.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Add/Edit/Delete blocked users.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
