<div class="description">
	<p>View your own charge records from this equipment.</p>
	<p>Search your own records.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View all charge records of this equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Print and export charge records.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Search records.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>