<div class="description">
	<p>View the usage history of this equipment.</p>
	<p>Search usage logs.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Fill out feedback forms.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit or delete equipment information.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may turn on/off the instrument power supply or login/logout of system in a remote mode for users under special circumstances.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Click "Edit" to reset status.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>