<div class="description">
	<p>View sign-up schedule for this instrument in a calendar or list view.</p>
	<p>Double click existing schedule blocks to view detailed information.</p>
	<p>Click and drag from the desired starting time to the ending time to sign up. Please fill out the form in the pop-up window.</p>
	<p>You may change or cancel you appointment in advance.</p>
	<p>Drag existing schedule blocks to other dates or drag to change block size when a change of schedule is needed.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit or delete equipment information.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">You may turn on/off the instrument power supply in a remote mode for users under special circumstances.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Double click and edit appointment in the pop-up window.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>