<div class="description">
	<p>View testing service requests for this instrument.</p>
	<p>Send testing service requests.</p>
	<p>Edit testing service requests.</p>
	<p>Sort and search requests.</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Send message to request senders.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Edit all testing service request.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>