<div class="form padding_1">
	<form method="post" autocomplete="off" q-event="submit" q-object="add_banned_user" q-static="<?php echo H(['eid'=>$eid])?>">
		<?php echo V('form_error', ['form'=>$form]);?>
		<?php $require = (string) V('form_require'); ?>
		<table class="form flexible">
			<tbody>
			<?php
				if (Module::is_installed('labs') ):
			?>
					<tr>
						<td class="top label right nowrap">
						<?php
							$selected = $form['type'] ? : 'user';
							echo Form::radio('type', 'user', $selected, I18N::T('eq_ban', '用户'), 'class="monitor middle"', 'class="middle"');
						?>
						</td>
						<td class="top toggle_status:type enable_on:user">
							<?php
								echo Widget::factory('user_selector', [
										'autocomplete'=>URI::url('!eq_ban/autocomplete/user.'.$eid),
										'name'=> 'user_id',
										'user'=> O('user', $form['user_id']),
								]);
							?>
						</td>
					</tr>
					<tr>
						<td class="top label right nowrap">
						<?php
							echo Form::radio('type', 'lab', $selected, I18N::T('eq_ban', '实验室'), 'class="monitor middle"', 'class="middle"');
						?></td>
						<td class="top toggle_status:type enable_on:lab">
						<?php
							echo Widget::factory('labs:lab_selector', [
											'name'=>'lab_id',
											'selected_lab'=> $form['lab_id'] ? : 0,
											'all_labs'=>TRUE,
											]);
						?>
						</td>
					</tr>
			<?php
				else:
			?>
					<tr>
						<td class="top label right nowrap">
							<?php echo I18N::T('eq_ban', '封禁用户');?>
						</td>
						<td class="top toggle_status:type enable_on:user">
							<input class="hidden" name="type" value="user" />
							<?php
								echo Widget::factory('user_selector', [
										'autocomplete'=>URI::url('!eq_ban/autocomplete/user.'.$eid),
										'name'=> 'user_id',
										'user'=> O('user', $form['user_id']),
								]);
							?>
						</td>
					</tr>
			<?php
				endif;
			?>
			<tr>
				<td class="top label right nowrap"><?php echo I18N::T('eq_ban', '封禁原因')?></td>
				<td class="top nowrap">
					<textarea class="top" name="reason" rows="3" cols="37" class="autogrow"><?php echo $form['reason'] ?></textarea>
					<?php echo $require; ?>
				</td>
			</tr>
			<tr>
				<td class="top label right nowrap"><?php echo I18N::T('eq_ban', '到期时间')?></td>
				<td class="top nowrap">
                    <input name="atime" class="text date" value="<?php echo H($form['atime']) ?>" q-date_format="<?php echo HT('$year/$month/$day')?>" />
                    <?php echo $require;?>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" name="submit" class="button button_add" value="<?php echo H(I18N::T('eq_ban', '添加封禁')) ?>" />
				</td>
			</tr>
		</table>
	</form>
</div>
