<?php $me = L('ME');?>
<?php


$table = Widget::factory('table');

$table->name = 'eq_ban_eq';
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;
$table->form_url = URI::url('!eq_ban/index.eqs?unsealing=1');
if($form['dtstart'] && $form['dtend']) {
	$form['time'] = H(date('Y/m/d',$form['dtstart'])).'~'.H(date('Y/m/d',$form['dtend']));
}
elseif($form['dtstart']) {
	$form['time'] = H(date('Y/m/d',$form['dtstart'])).'~'.I18N::T('eq_ban','最末');
}
elseif($form['dtend']) {
	$form['time'] = I18N::T('eq_ban','最初').'~'.H(date('Y/m/d',$form['dtend']));
}

$columns = new ArrayIterator($columns);

Event::trigger('eq_ban.list.columns', $form, $columns);

$table->add_columns((array)$columns);

$table->empty_message = I18N::T('eq_ban', '找不到相关的黑名单！');

if ($bans->total_count()) foreach ($bans as $ban) {
	$links = $ban->links('eq');
	$table->add_row([
		'name' => V('eq_ban:eq_ban_table/data/name', ['ban'=>$ban]),
        'unsealing_user' => V('eq_ban:eq_ban_table/data/unsealing_user', ['ban' => $ban]),
        'unsealing_ctime' => V('eq_ban:eq_ban_table/data/unsealing_ctime', ['ban' => $ban]),
        'eq_name' => V('eq_ban:eq_ban_table/data/eq', ['ban'=>$ban]),
		'reason' => V('eq_ban:eq_ban_table/data/reason', ['ban' => $ban]),
		'ctime' => V('eq_ban:eq_ban_table/data/ctime', ['ban' => $ban]),
		'atime' => V('eq_ban:eq_ban_table/data/atime', ['ban' => $ban]),
//		'rest'=> Widget::factory('application:links', ['links'=>$links]),
	]);
}
?>

<?php echo V('eq_ban:banstatus_pannel', ['form'=>$form]); ?>

<?php echo $table; ?>
<div class="pages"><?= $pagination ?></div>