<div class="hr_1">&#160;</div>
<div class="form padding_1">
	<table class="form">
		<tr>
			<td class="top icon">
				<?php echo $food->icon('64'); ?>
			</td>
			<td class="top">
				<form action="<?php echo H(URI::url()) ?>" method="post" enctype="multipart/form-data">
					<p>
						<input name="file" type="file" class="file" />
						<input type="submit" class="button button_import" name="submit" value="<?php echo H(I18N::T('food', '上传图片')) ?>"/>
					</p>
					<div class="hr_1">&#160;</div>
					<p>
						<a class="font-button-delete" href="<?php echo H(URI::url('!food/food/delete_photo.'.$food->id)) ?>"><?php echo I18N::T('food', '删除图片')?></a>
					</p>
				</form>
			</td>
		</tr>
	</table>
</div>
