<div class="hr_1">&#160;</div>
<div class="form padding_1">
<table class="form">
	<tbody>
		<tr>
			<td class="icon top">
				<a href="<?php echo H($food->url('photo',NULL,NULL,'edit') ) ?>"><img class="icon" src="<?php echo H($food->icon_url('64')) ?>" /></a>
			</td>
			<td class="top">
				<form method="post" autocomplete="off" action="<?php echo URI::url(); ?>">
				<?php echo V('form_error', ['form'=>$form]); ?>
					<table class="form food_edit_form">
						<tbody>
							<tr>
								<td class="label right nowrap top"><?php echo I18N::T('food', '供应商名称'); ?></td>
								<td>
									<input name="supplier" class="text" value="<?php echo H($food->supplier); ?>"/>
								</td>
							</tr>
							<tr>
								<td class="label right nowrap top"><?php echo I18N::T('food', '菜谱名称'); ?></td>
								<td>
									<input name="name" class="text" value="<?php echo H($food->name); ?>"/>
								</td>
							</tr>
							<tr>
								<td class="label right nowrap"><?php echo I18N::T('food', '菜谱价格'); ?></td>
								<td>
									<input name="price" class="text currency" sign="<?php echo H(Config::get('lab.currency_sign')) ?>" value="<?php echo H($food->price); ?>"/><?php echo I18N::T('food', '元'); ?>
								</td>
							</tr>
							<tr>
								<td class="label right nowrap"><?php echo I18N::T('food', '可预订日期'); ?></td>
								<td>
									<?php echo Form::checkbox('reserve[1]', strstr($food->reserve, '1') ? TRUE : FALSE , I18N::T('food','周一'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[2]', strstr($food->reserve, '2') ? TRUE : FALSE , I18N::T('food','周二'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[3]', strstr($food->reserve, '3') ? TRUE : FALSE , I18N::T('food','周三'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[4]', strstr($food->reserve, '4') ? TRUE : FALSE , I18N::T('food','周四'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[5]', strstr($food->reserve, '5') ? TRUE : FALSE , I18N::T('food','周五'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[6]', strstr($food->reserve, '6') ? TRUE : FALSE , I18N::T('food','周六'), 'class="middle"', 'class="middle"'); ?>
									<?php echo Form::checkbox('reserve[7]', strstr($food->reserve, '7') ? TRUE : FALSE , I18N::T('food','周日'), 'class="middle"', 'class="middle"'); ?>
								</td>
							</tr>
							<tr>
								<td class="label right nowrap"><?php echo I18N::T('food', '菜式说明');?></td>
								<td>
									<textarea name="description"><?php echo $food->description;?></textarea>				
								</td>
							</tr>
							<tr>
								<td></td>
								<td>
									<input name="submit" type="submit" class="button button_add" value="<?php echo I18N::T('food', '修改'); ?>" />
									<input type="reset" class="button button_cancel" value="<?php echo I18N::T('food', '重置'); ?>" />
								</td>
							</tr>
						</tbody>
					</table>
				</form>
			</td>
		</tr>
	</tbody>
</table>
</div>
