<?php $name_prefix = $this->name_prefix; ?>
<?php
    $this->dtstart = $this->dtstart ? date('Y-m-d', $this->dtstart) : '';
    $this->dtend = $this->dtend ? date('Y-m-d', $this->dtend) : '';
?>
<input autocomplete="off"  id="<?php echo $name_prefix?>dtstart" name="<?php echo $name_prefix?>dtstart" date_type="date" class="text date small_search_text" value="<?php echo H($this->dtstart) ?>" /><span class="middle description date_interval">-</span><input id="<?php echo $name_prefix?>dtend" name="<?php echo $name_prefix?>dtend" date_type="date" class="text date small_search_text" value="<?php echo H($this->dtend); ?>" />
