<?php
	$require = (string)V('form_require');
	$me = L("ME");
	$ac_authors = Q("ac_author[achievement=$patent]");
	$authors = [];
	foreach ($ac_authors as $ac_author) {
		if($ac_author->user->id) {
			$authors[$ac_author->name] = [
				'user_id'=>$ac_author->user->id,
				'text'=>$ac_author->name,
				'em'=>TRUE,
			];
		}
		elseif($ac_author->name) {
			$authors[$ac_author->name]=$ac_author->name;
		}
	}
    echo $edit_title;

?>
<div class="interval_24"></div>
<form method="post" action="" class="edit" style="padding-left: 48px;">
<div class="form">
	<?php echo V('form_error', ['form'=>$form]);?>
	<table class="form" style="margin: 0 auto;">
		<tbody>
			<tr>
				<td class="label left nowrap middle label_width">
                    <?php echo $require;?><?php echo I18N::T('achievements', '专利名称'); ?>
                    <br>
                    <?php echo V('form_filter',['error'=>$form->errors['name'][0]]); ?>
                </td>
				<td class="middle" width="300">
					<input name="name" class="text"  value="<?php echo H(!$form->no_error ? $form['name'] : $patent->name); ?>" />
				</td>
                <td class="table_interval"></td>
                <td class="label left nowrap middle label_width">
                    <?php echo $require;?><?php echo I18N::T('achievements', '专利号')?>
                    <br>
                    <?php echo V('form_filter',['error'=>$form->errors['ref_no'][0]]); ?>
                </td>
                <td class="middle" width="300">
                    <input name="ref_no" class="text" value="<?php
                    echo H($patent->ref_no)?>" />
                </td>
			</tr>

            <tr><td><div class="interval_20"></div></td> </tr>

            <tr>
                <td class="label left nowrap middle lpadding_21"><?php echo I18N::T('achievements', '日期'); ?></td>
                <td >
                    <input name="date" class="text date" date_type="date" value="<?php echo $patent->date ?: ''; ?>" />
                </td>
                <td colspan="3"></td>
            </tr>

            <tr><td><div class="interval_20"></div></td></tr>

            <?php
            echo $GLOBALS['preload']['people.multi_lab'] ?
                V("patents/edit.mlab.info", ['form' => $form, 'patent' => $patent]) :
                V("patents/edit.lab.info", ['form' => $form, 'patent' => $patent]);
            ?>

            <tr><td><div class="interval_20"></div></td> </tr>

			<tr>
				<td class="label left nowrap top label_width lpadding_21"><?php echo I18N::T('achievements', '专利类型')?></td>
				<?php
				   	$root = Tag_Model::root('achievements_patent');
					$tags = (array) Q("$patent tag_achievements_patent[root=$root]")->to_assoc('id', 'name');
					if(count($tags)) {
						$tags = json_encode($tags,TRUE);
					}
					else{
						$tags = '';
					}
				?>
				<td class="middle" colspan="4">
				<?php
					echo Widget::factory('achievements:tag_selector', [
							'autocomplete'=> URI::url('!achievements/patents/autocomplete/tags'),
							'name'=>'tags',
							'value'=> $form->no_error ? $tags : $form['tags']
					]);
				?>
				</td>
			</tr>
            <tr><td><div class="interval_20"></div></td> </tr>
			<tr>
				<td class="label left nowrap top lpadding_21">
                    <?php echo I18N::T('achievements', '人员表'); ?>
                    <br>
                    <br>
                    <?php
                    $lab = $patent->id ? $patent->lab : 'lab';
                    if($me->is_allowed_to('添加成果', 'lab') && count($authors) > 0):?>
                        <input type="button" value="<?php echo H(I18N::T('achievements','对应作者')) ?>" class="font-button-save middle button view object:select_author event:click static:object=<?php echo $patent->id?>&type=patent  src:<?php echo URI::url('!achievements/index')?>" />
                    <?php endif;?>
                </td>
				<td class="middle" colspan="4">
					<div class="nowrap middle">
						<input name="people" class="middle text token" value="<?php echo !$form->no_error ? H($form['people']) : H(@json_encode($authors, TRUE))?>" q-token_tip='<?php echo I18N::T('achievements', '您可选择标签或按回车键输入专利人员')?>' />
					</div>
				</td>

			</tr>
			<?php if (Module::is_installed('nfs')) :?>
            <tr><td><div class="interval_20"></div></td> </tr>
			<tr>
				<td class="left nowrap top label lpadding_21">
					<?php echo I18N::T('things', '附件'); ?>
				</td>
				<td class="left nowrap" colspan="4">
					<?php echo V('achievements:attachments', ['achievement'=> $patent->id ? $patent : O('patent')]);?>
				</td>
			</tr>
            <tr><td><div class="interval_12"></div></td> </tr>
            <tr>
                <td></td>
                <td colspan="4"><?php echo $view; ?></td>
            </tr>
			<?php endif;?>

            <tr>
                <td colspan="5">
                    <div class="interval_60"></div>
                    <div class="float_right">
                        <input type="reset" name="reset" class="font-button-default rmargin_16" value="取消">
                        <input type="submit" name="submit" class="font-button-save" value="<?php echo H(I18N::T('achievements','提交')) ?>">
                    </div>
                </td>
            </tr>
		</tbody>
	</table>
</div>

</form>
