<div class="clearfix">
	<?php echo CSS::load_async('achievements:publication'); ?>
	<h2 class="general_title">
		<span class="middle"><?php echo I18N::T('achievements', '专利信息') ?></span>
	</h2>
	<div class="publication_template">
		<ol class='publications'>
			<?php foreach ($patents as $patent): ?>
			<li class="publication">
				<?php echo V('achievements:author_name', ['achievement'=>$patent]);?>
				<span class="title">
					<?php if(L('ME')->is_allowed_to('查看成果', $patent->lab)):?>
					<a href="<?php echo $patent->url(); ?>"><?php echo H($patent->name)?></a>
					<?php else:?>
					<?php echo H($patent->name); ?>
					<?php endif;?>.
				</span>
				<span class="year">
					<?php echo Date::format($patent->date, H('Y')); ?>
				</span>
			</li>
			<?php endforeach; ?>
		</ol>
	</div>
	<div class="hr_3">&#160;</div>
</div>
