<div class="tab_pagination_border bmargin_4">
    <?php echo $secondary_tabs; ?>
</div>
<?php if($secondary_tabs->panel_buttons || $secondary_tabs->search_box): ?>
    <div class='search_panel no_padding_tertiary_search'>
        <?php
        echo $secondary_tabs->panel_buttons;
        echo $secondary_tabs->search_box;
        ?>
    </div>
<?php endif ?>
<?php echo $secondary_tabs->content; ?>

