<?php 
	$calendar = O('calendar', $form['calendar_id']);
	$title = '';
    if ($calendar->parent->name() == 'user') {
        $title = I18N::HT('eq_reserv', '%name负责的仪器预约列表', [
            '%name'=> $calendar->parent->name
        ]);
    }
    elseif ($calendar->parent->name() == 'equipment') {
        $title = I18N::HT('eq_reserv', '%name预约记录列表', [
            '%name'=> $calendar->parent->name
        ]);
    }
?>
<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('eq_reserv', '预约记录打印') . $title; ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('eq_reserv', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('eq_reserv', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php echo $title;?>
            </caption>
			<thead id="stat">
                <tr>
                    <td colspan="<?php echo H(count($columns)) ?>" class="small">
                        <?php echo I18N::HT('eq_reserv', '时间: %dtstart - %dtend', [
                            '%dtstart' => $form['dtstart'] ? Date::format($form['dtstart']) : I18N::T('eq_reserv', '最初'),
                            '%dtend'=> $form['dtend'] ? Date::format($form['dtend']) : I18N::T('eq_reserv', '最末')
                        ])?>
                    </td>
                </tr>
            </thead>
            <thead>
				<tr>
					<?php foreach($columns as $name) : ?>
						<th class="left nowrap"><?php echo I18N::T('eq_reserv', $name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($components as $component): 

					$calendar = $component->calendar;
					
					$equipment = NULL;
					if ($calendar->parent->name() == 'equipment') {
						$equipment = $calendar->parent;
					}
			?>
					<tr>
						<?php  if (array_key_exists('equipment', $columns)): ?>
							<td class="left nowrap">
								<?php echo H($equipment->name) ?: '--';?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('eq_ref_no', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($equipment->ref_no) ?: '--'; ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('eq_cf_id', $columns)) :?>
							<td class="left nowrap">
								<?php echo $equipment->id ?: '--'; ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('eq_group', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($equipment->group->name) ?: ''; ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('organizer', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($component->organizer->name); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('email', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($component->organizer->email); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('phone', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($component->organizer->phone); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('group', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($component->organizer->group->name); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('lab', $columns)) :?>
							<td class="left nowrap">
								<?php 
								$eq_reserv = O('eq_reserv', ['component' => $component]);
								$lab = $eq_reserv->project->lab->id ?
										$eq_reserv->project->lab :
										Q("{$component->organizer} lab")->current();
								echo H($lab->name);?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('time', $columns)) :?>
							<td class="left nowrap">
								<?php echo Date::format($component->dtstart, 'Y/m/d H:i:s'). ' - '. Date::format($component->dtend, 'Y/m/d H:i:s'); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('duration', $columns)) :?>
							<td class="left nowrap">
								<?php echo I18N::T('eq_reserv', '%duration小时', [
	                                '%duration'=> round(($component->dtend - $component->dtstart) / 3600, 2)]); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('name', $columns)) :?>
							<td class="left nowrap">
								<?php echo H($component->name); ?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('reserv_type', $columns)) :?>
							<td class="left nowrap">
								<?php 
				                    $ctype = $component->type;
				                    if ($ctype == Cal_Component_Model::TYPE_VEVENT) {
										echo I18N::T('eq_reserv', '预约');
				                    }
				                    elseif ($ctype == Cal_Component_Model::TYPE_VFREEBUSY) {
										echo I18N::T('eq_reserv', '非预约时段');
				                    }
								?>
							</td>
						<?php endif; ?>
						<?php if (array_key_exists('description', $columns)): ?>
							<td class="left nowrap">
								<?php 
									echo H($component->description);
								?>
							</td>
						<?php endif; ?>
					</tr>
			<?php
				endforeach;
			?>
			</tbody>
		</table>
	</body>
</html>
