<div class="interval_24"></div>
<form class="form" q-object="create_tag" q-event="submit"
q-src="<?= H(URI::url('!meeting/meeting')) ?>">
	<?= V('form_error', ['form' => $form]);?>
	<table>
		<tbody>
			<tr>
				<td class="nowrap middle">
					<input class="hidden text" value="<?= H($id) ?>" name="id" />
					<span class="label"><?= I18N::T('meetting', '名称')?></span>
					<input class="text" name="name" />
				</td>
                <td><?php echo V('form_filter',['error'=>$form->errors['name'][0]])?></td>
			</tr>
		</tbody>
	</table>
    <div class="button_container">
        <div class="float_right">
            <input type="submit" name="submit" class="font-button-save" value="<?php echo H(I18N::T('equipments', '更新')) ?>">
        </div>
    </div>
</form>
