<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('grants', '%name支出明细', ['%name'=>$grant->project]); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#grant{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>
<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('grants', '打印'); ?></a>
		<a href="#" onclick="window.close(); return false;"><?php echo I18N::T('grants', '关闭'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('grants', '%name 支出明细', ['%name'=>H($grant->project)]); ?></caption>
	<thead id="grant">
		<tr>
		<td colspan="8">
		<?php echo I18N::T('grants', '时间范围:'); ?>
		&#160;
		<?php
			$dtstart = isset($dtstart) ? H(date('Y/m/d',$dtstart)) : I18N::T('grants','最初');
			$dtend = isset($dtend) ? H(date('Y/m/d',$dtend)) : I18N::T('grants','最末');
			echo $dtstart . ' - ' . $dtend;
		?>
		</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<?php foreach ($valid_columns as $key => $value) : ?>
			<th class="left nowrap"><?php echo I18N::T('grants', $value);?></th>	
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php $valid_columns = array_flip($valid_columns); ?>
		<?php foreach($expenses as $expense):?>
		<tr>
			<?php if (in_array('ref_no', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo str_pad($expense->id,6,'0',STR_PAD_LEFT); ?>
			</td>
			<?php endif ?>
			<?php if (in_array('date', $valid_columns)): ?>
			<td class="left nowrap">
				<span class="description"><?php echo Date::format($expense->ctime)?></span>
			</td>
			<?php endif; ?>
			<?php if (in_array('portion', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo V('grants:portion_name',['portion'=>$expense->portion]); ?>
			</td>
			<?php endif; ?>
			<?php if (in_array('amount', $valid_columns)): ?>
			<td class="right nowrap"><?php echo H(Number::currency($expense->amount))?></td>
			<?php endif; ?>
			<?php if (in_array('summary', $valid_columns)): ?>
			<td class="left nowrap">
			<?php
				if ($expense->pre_summary) {
					echo new Markup($expense->pre_summary);
					echo '&#160;&#160;&#160;&#160;';
				}
				echo H($expense->summary)
			?>
			</td>
			<?php endif; ?>
			<?php if (in_array('invoice_no', $valid_columns)): ?>
			<td>
				<?php echo H($expense->invoice_no); ?>
			</td>
			<?php endif; ?>
		</tr>
		<?php endforeach;?>
		<tr>
			<td colspan="<?php echo H(count($valid_columns) ) ?>" class="right nowrap">
				<?php echo I18N::T('grants', '总支出: ').H(Number::currency($expenses->sum(amount)))?>
			</td>
		</tr>
	</tbody>
	</table>
</body>
</html>
