<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('grants', '%name概况', ['%name'=>$grant->project]); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#grant{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>
<?php 
$max_width = 500;	
?>
<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
		<a href="#" onclick="window.close(); return false;"><?php echo T('关闭'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;" class="grant_summary">
	<caption class="nowrap"><?php echo I18N::T('grants', '%name 概况', ['%name'=>H($grant->project)]); ?></caption>
	<thead id="grant">
		<tr>
			<td colspan="4">
				<?php echo I18N::T('grants', '负责人: ').H($grant->user->name)?>
			</td>	
		</tr>
	</thead>
	<thead>
		<tr>
			<?php foreach ($valid_columns as $key => $value) : ?>
			<td class="nowrap"><?php echo I18N::T('grants', $value)?></td>
			<?php endforeach;?>
		</tr>
	</thead>
	<tbody>
		<?php 
		$valid_columns = array_flip($valid_columns);
		foreach ($gp_form as $gp):
			$portion = $gp['portion'];
			$indent = $gp['indent'] + 1;
		?>
		<tr>
			<?php if (in_array('name', $valid_columns)):?>
			<td class="nowrap">
				<div class="inline_block" style="width:<?php echo $indent * 16 ?>px">&#160;</div>
				<?php echo H($portion->name); ?>
			</td>
			<?php endif; ?>
			<?php if (in_array('amount', $valid_columns)) :?>
			<td class="right nowrap">
				<?php echo H(Number::currency($portion->amount)); ?>
			</td>
			<?php endif; ?>
			<?php if (in_array('utilization', $valid_columns)): ?>
			<td class="right nowrap">
				<?php echo H(Number::currency($portion->amount - $portion->balance)); ?>
			</td>
			<?php endif;?>
			<?php if (in_array('balance', $valid_columns)): ?>
			<td class="right nowrap">
				<?php echo H(Number::currency($portion->balance)); ?>
			</td>
			<?php endif; ?>
		</tr>
		<?php endforeach;?>
	</tbody>
	</table>
</body>
</html>
