<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('grants', '经费列表'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#grant{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>
<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('grants', '打印'); ?></a>
		<a href="#" onclick="window.close(); return false;"><?php echo I18N::T('grants', '关闭'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('grants', '经费列表'); ?></caption>
	<thead>
		<?php 
	 		$tamount = $grants->sum('amount');//保存所有项目总额
 		    $tbalance = $grants->sum('balance'); //保存所有项目总余额
	 	?>
	 	<tr>
			<td colspan="<?php echo H(count($valid_columns) ) ?>" class="right nowrap">
				<?php echo I18N::T('grants', '当前实验室所有课题的经费总额为%tamount, 余额总计为%tbalance',
				[
					'%tamount' => H(Number::currency($tamount)),
					'%tbalance' => H(Number::currency($tbalance)),
				])?>
			</td>
		</tr>
		<tr>
			<?php foreach ($valid_columns as $key => $value) : ?>
			<th class="left nowrap"><?php echo I18N::T('grants', $value);?></th>	
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($grants as $grant):?>
		<tr>
			<?php if (array_key_exists('project', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo H($grant->project)?:'-'; ?>
			</td>
			<?php endif; ?>
			
			<?php if (array_key_exists('source', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo H($grant->source)?:'-'; ?>
			</td>
			<?php endif; ?>
			
			<?php if (array_key_exists('ref', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo H($grant->ref)?:'-'; ?>
			</td>
			<?php endif; ?>
			<?php if (array_key_exists('amount', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo H(Number::currency($grant->amount))?:'-'; ?>
			</td>
			<?php endif; ?>
			
			<?php if (array_key_exists('balance', $valid_columns)): ?>
			<td class="left nowrap">
				<?php echo H(Number::currency($grant->balance))?:'-'; ?>
			</td>
			<?php endif; ?>
			<?php if (array_key_exists('incharge', $valid_columns)): ?>
			<td class="left nowrap">
				<?php 
					$incharge = Q("$grant<user user");
					echo $incharge->name?:'-';  
				?>
			</td>
			<?php endif; ?>
		</tr>
		<?php endforeach;?>
	</tbody>
	</table>
</body>
</html>
