<style>
span div.dropdown_container{
    min-width:revert !important;
    width:4.3rem !important;
    vertical-align: top;
}
.dialog_content tr td div.dropdown_container div.dropdown_text{
    min-width:revert !important;
    width:2rem !important;
}
</style>
<?php $me = L('ME'); ?>
<div class="form">
    <form method="post" action="<?php echo H(URI::url()) ?>">
        <table class="form" style="width: 100%;">
            <tbody>
                <tr>
                    <td class="top equipments_icon" width="130" rowspan="2">
                        <div class="short_container">
                            <div class="img_icon" style="position: relative;">
                                <?php echo $service->icon('104'); ?>
                                <div class="icon_cover" style="display: none;">
                                    <div class="modify_icon">+</div>
                                    <div class="interval_8"></div>
                                    <div class="modify_font">修改图标</div>
                                </div>
                            </div>
                            <input class="upload_icon" name="file" type="file" class="file" style="display: none;" />
                        </div>

                        <script>
                        $.upload_icon(<?php echo '"' . URI::url() . '"'; ?>);
                        </script>

                        <div class="short_info short_container">
                            <a style="padding: 0 9px;" class="font-button-delete"
                                href="<?php echo H(URI::url('!technical_service/service/delete_photo.' . $service->id)) ?>"
                                confirm="<?php echo H(I18N::T('technical_service', '确定要删除图标吗?')) ?>"><?php echo I18N::T('technical_service', '删除服务图标') ?></a>
                        </div>

                        <div class="interval_24"></div>

                    </td>

                    <td class="top">
                        <?= V('form_error', ['form' => $form]); ?>
                        <?php
                    $no_error = ($form->no_error !== FALSE);
                    $require = trim((string)V('form_require', ['extra_class' => 'top']));
                    ?>
                    </td>
                </tr>

                <tr>
                    <td class="top">
                        <h2 class="section_title">
                            <span class="border"></span>
                            <span class="black_title"><?= I18N::T('technical_service', '基本信息') ?></span>
                            <span class="float_right red"
                                style="font-size: 14px;font-weight: normal;color: #666;margin-right: 140px;">*必填</span>
                        </h2>
                        <div class="interval_24"></div>
                        <table class="form lmargin_40r">
                            <tbody>
                                <tr>
                                    <td class="right nowrap label">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?= I18N::T('technical_service', '服务名称') ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_2">
                                        <input name="name" placeholder="请输入服务名称" class="text"
                                            value="<?php echo H($form['name'] ?? $service->name) ?>" />
                                        <div><?php echo V('form_filter', ['error' => $form->errors['name'][0]]) ?></div>
                                    </td>
                                    <td class="lpadding_4 right">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?php echo I18N::T('technical_service', '收费平台') ?>
                                        </div>
                                    </td>
                                    <td class="left nowrap label">
                                        <?php
                                $billing_departments = Q('billing_department')->to_assoc('id', 'name');
                                echo Form::dropdown('billing_department', $billing_departments, $form['billing_department'] ?? $service->billing_department->id, 'class="lmargin_2"')
                                ?>
                                        <div>
                                            <?php echo V('form_filter', ['error' => $form->errors['billing_department'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="right nowrap label">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?= I18N::T('technical_service', '服务编号') ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_2">
                                        <input name="ref_no" placeholder="请输入服务编号" class="text"
                                            value="<?php echo H($form['ref_no'] ?? $service->ref_no) ?>" />
                                        <div><?php echo V('form_filter', ['error' => $form->errors['ref_no'][0]]) ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_4 right">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?= I18N::T('technical_service', '服务分类') ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_2">
                                        <?php
                                echo Widget::factory('technical_service:service_type_selector', [
                                    'autocomplete' => URI::url('!technical_service/autocomplete/service_type'),
                                    'name' => 'service_type',
                                    'tag' => $form['service_type'] ? O('tag_service_type', $form['service_type']) : $service->service_type,
                                    'root' => Tag_Model::root('service_type'),
                                    'ajax' => true,
                                ]);
                                ?>
                                        <div>
                                            <?php echo V('form_filter', ['error' => $form->errors['service_type'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="right nowrap label">
                                        <div class="title">
                                            <?php echo I18N::T('technical_service', '服务周期') ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_2">
                                        <input type="text" name="intervals" size="26" class="text number"
                                            value="<?php echo H(isset($form['intervals']) ?  $form['intervals'] : $service->intervals) ?>" />&#160;
                                        <span>
                                            <?php echo Form::dropdown('intervals_format', Date::units('hd'), isset($form['intervals_format']) ?  $form['intervals_format'] :  $service->intervals_format ? : Config::get('technical_service.intervals_format', 'h'),'class="middle swid"');?>
                                        </span>
                                        <div><?php echo V('form_filter', ['error' => $form->errors['intervals'][0]]) ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_4 right">
                                        <div class="title">
                                            <?= I18N::T('technical_service', '所属单位') ?>
                                        </div>
                                    </td>
                                    <td class="lpadding_2">
                                        <?php
                                $group_root = Tag_Model::root('group');
                                if (!L('ME')->access('管理所有服务') && !Q("{$service}<incharge {$me}")->total_count()) {
                                    $group_root = L('ME')->group;
                                }
                                echo Widget::factory('application:tag_selector', [
                                    'tag' => $form['group_id'] ? O('tag_group', $form['group_id']) : $service->group,
                                    'root' => $group_root,
                                    'name' => 'group_id',
                                    'ajax' => true,
                                ]);
                                ?>
                                        <div><?php echo V('form_filter', ['error' => $form->errors['group'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label right top">
                                        <span><?php echo I18N::T('technical_service', '服务简介') ?></span>
                                    </td>
                                    <td class="label lpadding_2" colspan="3">
                                        <textarea name="description" class="text autogrow"
                                            style="width: 100%;height: 70px;"><?= $form['description'] ?? $service->description ?></textarea>
                                        <div>
                                            <?php echo V('form_filter', ['error' => $form->errors['description'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label right top">
                                        <span><?php echo I18N::T('technical_service', '样本要求') ?></span>
                                    </td>
                                    <td class="label lpadding_2" colspan="3">
                                        <textarea name="sample_requires" class="text autogrow"
                                            style="width: 100%;height: 70px;"
                                            cols="80"><?= $form['sample_requires'] ?? $service->sample_requires ?></textarea>
                                        <div>
                                            <?php echo V('form_filter', ['error' => $form->errors['sample_requires'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label right top">
                                        <span><?php echo I18N::T('technical_service', '收费标准') ?></span>
                                    </td>
                                    <td class="label lpadding_2" colspan="3">
                                        <textarea name="charge_settings" class="text autogrow"
                                            style="width: 100%;height: 70px;"
                                            cols="80"><?= $form['charge_settings'] ?? $service->charge_settings ?></textarea>
                                        <div>
                                            <?php echo V('form_filter', ['error' => $form->errors['charge_settings'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label right top">
                                        <span><?php echo I18N::T('technical_service', '注意事项') ?></span>
                                    </td>
                                    <td class="label lpadding_2" colspan="3">
                                        <textarea name="attentions" class="text autogrow"
                                            style="width: 100%;height: 70px;"
                                            cols="80"><?= $form['attentions'] ?? $service->attentions ?></textarea>
                                        <div><?php echo V('form_filter', ['error' => $form->errors['attentions'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <?php
                            if ($me->is_allowed_to('修改负责人',$service)):
                        ?>
                                <tr>
                                    <td class="label right top tpadding_2">
                                        <?= $require; ?>
                                        <span><?php echo I18N::T('technical_service', '负责人') ?></span>
                                    </td>
                                    <td class="nowrap label lpadding_2" colspan="3">
                                        <div class="tmargin_2">
                                            <?= V('service/incharges', ['service' => $service, 'form' => $form]) ?>
                                        </div>
                                        <div><?php echo V('form_filter', ['error' => $form->errors['incharges'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <?php endif;?>
                                <tr>
                                    <td class="right nowrap label">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?= I18N::T('technical_service', '联系电话') ?>
                                        </div>
                                    </td>
                                    <td class=" lpadding_2">
                                        <input name="phones" placeholder="请输入联系电话" class="text"
                                            value="<?php echo H($form['phones'] ?? $service->phones) ?>" />
                                        <div><?php echo V('form_filter', ['error' => $form->errors['phones'][0]]) ?>
                                        </div>
                                    </td>
                                    <td class="nowrap lpadding_4 right label">
                                        <div class="title">
                                            <?= $require; ?>
                                            <?php echo I18N::T('technical_service', '联系邮箱') ?>
                                        </div>
                                    </td>
                                    <td class="left nowrap label lpadding_2">
                                        <input name="emails" placeholder="请输入联系邮箱" class="text"
                                            value="<?php echo H($form['emails'] ?? $service->emails) ?>" />
                                        <div><?php echo V('form_filter', ['error' => $form->errors['emails'][0]]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <div class="interval_16"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td colspan="3" class="left nowrap label lpadding_2">
                                        <?php if (L('ME')->is_allowed_to('删除', $service)): ?>
                                        <a class="font-button-delete lmargin_10"
                                            confirm="<?php echo H(I18N::T('equipments', '您确定删除该服务吗?')) ?>"
                                            href="<?php echo H($service->url(NULL, NULL, NULL, 'delete')) ?>"><?php echo I18N::T('technical_service', '删除服务') ?></a>
                                        <?php endif; ?>
                                        <input type="submit" name="submit" class="font-button-save"
                                            value="<?php echo H(I18N::T('technical_service', '保存修改')) ?>" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>