<?php
if ($service->id) {
    $users = Q("$service<incharge user");
    $incharges = [];

    foreach ($users as $incharge) {
        if ($GLOBALS['preload']['people.multi_lab']) {
            $incharges[$incharge->id] = $incharge->name;
        } else {
            $incharges[$incharge->id] = $incharge->name . '(' . Q("{$incharge} lab")->current()->name . ')';
        }
    }
}


if (!$disabled) {
    echo Widget::factory('multi_user_selector', [
        'name' => 'incharges',
        'autocomplete' => URI::url('autocomplete/user'),
        'value' => !$form['incharges'] ? json_encode($incharges) : $form['incharges'],
        'extra' => 'token_verify'
    ]);
} else {
    ?>
    <div style="padding-top: 3px;">
        <?= implode(',', $incharges); ?>
    </div>
    <?php
}
echo $require;
?>
