<div class="padding_1 clearfix">
	<table class="form" align="center" width="100%">
		<tbody>
			<tr>
				<td align="right"><span class="description"><?php echo I18N::T('schedule', '主题'); ?></span></td>
				<td> <?php echo H($component->name); ?></td>		
			</tr>
			
			<tr>
				<td align="right"><span class="description"><?php echo I18N::T('schedule', '开始时间'); ?></span></td>
				<td><?php echo Date::format($component->dtstart, T('Y/m/d H:i:s')); ?></td>
			</tr>
			
			<tr>
				<td align="right"><span class="description"><?php echo I18N::T('schedule', '结束时间'); ?></span></td>
				<td><?php echo Date::format($component->dtend, T('Y/m/d H:i:s')); ?></td>
			</tr>
		</tbody>
	</table>
</div>