<?php 

if ($record->status == EQ_Record_Model::FEEDBACK_NORMAL) {
	$output .= '<strong>'.I18N::T('equipments', '正常').'</strong>';
}
elseif ($record->status == EQ_Record_Model::FEEDBACK_PROBLEM) {
	$output .= '<strong style="color:red">'.I18N::T('equipments', '故障').'</strong>';
}
else {
	$output .= '<span class="description">'.I18N::T('equipments', '未反馈').'</span>';
}

if ($record->feedback) {
	$output .= ' <span style="word-break: break-word;white-space: normal;" class="description">'.H($record->feedback, TRUE).'</span>';
}

$views = [];
if ($output) {
	$views['status'] = '<div>'.$output.'</div>';
}

$views += (array) Event::trigger('eq_record.description', $record);
echo implode('', $views);

