<?php
    $this->dtstart_check = $form['dtstart_check'];
    $this->dtstart = $form['dtstart'];
    $this->dtend_check = $form['dtend_check'];
    $this->dtend = $form['dtend'];
?>
<?php echo Form::checkbox('dtstart_check', $this->dtstart_check, '', 'class="middle monitor"'); ?>&#160;<input name="dtstart" class="text date middle toggle_status:dtstart_check enable_on:on" value="<?php echo H($this->dtstart ) ?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>

<span class="middle description">-</span>

<?php echo Form::checkbox('dtend_check', $this->dtend_check, '', 'class="middle monitor"'); ?>&#160;<input name="dtend" class="text date middle toggle_status:dtend_check enable_on:on" value="<?php echo H($this->dtend ) ?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>
<input class="hidden" name="date_filter" value="1" />
