<div class="hr_1">&#160;</div>
<?php if (count($panel_buttons)) :?>
    <div class="panel padding_1 clearfix">
        <span><input type="checkbox" name="select_all" class="button button_edit" data-item="all">&#160;<?= I18N::T('nrii', '全选')?></span>
        <span><?= Widget::factory('application:links', ['links'=>$panel_buttons, 'separator'=>'&#160;']);?></span>
    </div>
<?php endif;?>
<?= $pagination ?>
<?php

$me = L('ME');

if($form['worthmin'] && $form['worthmax']){
    $worthValue = H($form['worthmin'] . '~' .$form['worthmax'] . '(元)');
}elseif ($form['worthmin']) {
    $worthValue = H($form['worthmin'] . '~ * (元)');
}elseif ($form['worthmax']) {
    $worthValue = H(' * ~' .$form['worthmax'] . '(元)');
}

$table = Widget::factory('table');
$table->name = 'nirr_record';
$table->form = $form;
$columns = [
    '@'=>NULL,

    'eq_name'=> [
        'title' => I18N::T('nrii', '仪器名称'),
        'filter'=> [
            'form'=> V('nrii:device/filters/text', ['form'=> $form, 'name' => 'eq_name']),
            'value'=> H($form['eq_name']),
        ],
        'weight' => 10,
        'nowrap'=>TRUE
    ],
    'innerId'=> [
        'title' => I18N::T('nrii', '所属单位科学内部编号'),
        'filter'=> [
            'form'=> V('nrii:equipment/filters/text', ['form'=> $form, 'name' => 'innerId']),
            'value'=> I18N::T('nrii', $form['innerId']),
        ],
        'invisible' => TRUE,
        'weight' => 20,
        'nowrap'=>TRUE
    ],
    'amounts'=> [
        'title' => I18N::T('nrii', '服务金额'),
        'filter'=> [
            'form'=> V('nrii:device/filters/worth', ['form'=> $form]),
            'value'=> $worthValue,
            'field' => 'worthmin,worthmax'
        ],
        'weight' => 30,
        'nowrap'=>TRUE
    ],
    'subject'=> [
        'title' => I18N::T('nrii', '课题名称'),
        'filter'=> [
            'form'=> V('nrii:device/filters/text', ['form'=> $form, 'name' => 'subject']),
            'value'=> H($form['subject']),
        ],
        'weight' => 40,
        'nowrap'=>TRUE
    ],
    'applicant'=> [
        'title' => I18N::T('nrii', '申请人'),
        'filter'=> [
            'form'=> V('nrii:device/filters/text', ['form'=> $form, 'name' => 'applicant']),
            'value'=> H($form['applicant']),
        ],
        'weight' => 50,
        'nowrap'=>TRUE
    ],
    'nrii_status'=> [
        'title' => I18N::T('nrii', '上报状态'),
        'filter'=> [
            'form'=> V('nrii:record/filters/status', ['form'=> $form]),
            'value'=> H(Nrii_Record_Model::$nrii_status[$form['nrii_status']]),
        ],
        'weight' => 60,
        'nowrap'=>TRUE
    ],
    'rest'=> [
        'title' => I18N::T('nrii', '操作'),
        'weight' => 70,
        'nowrap'=>TRUE
    ]
];


$extraColumns = Event::trigger('extra.nrii.record.column', $form, $columns);
if($extraColumns) {
    $columns = $extraColumns;
}

$table->add_columns($columns);

$table->empty_message = I18N::T('nrii', '没有查询到相应的服务记录!');

if (count($records) > 0) {
    foreach($records as $record) {
        $links = $record->links('index');
        $row = [
            '@'=>V('nrii:record/table/select', ['record'=>$record]),
            'eq_name'=>HT($record->eq_name),
            'amounts'=>HT($record->amounts),
            'subject'=>HT($record->subject_name),
            'applicant'=>HT($record->applicant),
            'nrii_status'=>HT(Nrii_Record_Model::$nrii_status[$record->nrii_status]),
            'rest'=>Widget::factory('application:links', ['links' => $links]),
        ];
        $extraRow = Event::trigger('extra.nrii.record.row', $record, $row);
        if($extraRow) {
            $row = $extraRow;
        }
        $table->add_row($row);
    }
}
echo $table;
?>
<?= $pagination ?>
