<div class="form padding_1 clearfix">
    <div class="float_right">
        <a class="font-button-delete middle"><?php echo I18N::T('labs', '删除');?></a>
        <a class="button button_edit middle"><?php echo I18N::T('labs', '编辑');?></a>
    </div>
    <span class="toggle_button toggle_expand middle"></span> <span class="middle"><?php echo I18N::T('labs', '目录2');?></span>
</div>
<div class="tag_container">
</div>
