<div class="description">
	<?php if (Module::is_installed('labs')) : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">请您填写新添加成员的基本信息。</span>
	</p>
	<?php else : ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">请按照提示添加新用户的基本信息。</span>
	</p>
	<?php endif; ?>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>
