<div class="form padding_2">
  <?php if ($type == 'csv'): ?>
    <form action="<?php echo H(URI::url('!eq_comment/user/export', ['type' => $type, 'form_token' => $form_token, 'tab' => $tab])) ?>" q-object="export" q-src="<?= URI::url('!eq_comment/user/export') ?>" q-static="<?php echo H(['form_token'=>$form_token, 'type' => $type, 'tab' => $tab])?>" target="<?=$type == 'csv' ? '_self' : '_blank'?>" q-event="submit" class="prevent_default" method="post">
  <?php else: ?>
    <form action="<?php echo H(URI::url('!eq_comment/user/print', ['type' => $type, 'form_token' => $form_token, 'tab' => $tab])) ?>" target="<?= $type == 'csv' ? '_self' : '_blank'?>" class="prevent_default" method="post">
  <?php endif; ?>
		<ul class="ep_triple">
			<?php
			foreach ($columns as $p => $p_name) :?>
			<?php if ($p < 0): ?>
			<div class="clear">&#160;</div>
            <h4 class="ep_title"><?php echo I18N::HT('eq_comment', $p_name) ?></h4>
			<?php  else:?>
				<li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('eq_comment', $p_name), 'class="middle monitor checkbox"', 'class="middle"');?>
				</li>
			<?php endif; ?>
			<?php endforeach;?>
		</ul>
        <div class="button_container">
            <div class="float_right">
                <input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('eq_comment', '取消');?>" />
                <input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('eq_comment', '提交');?>" />
            </div>
        </div>
  </form>
</div>