<?php
$real_root = $root->root->id ? $root->root : $root;

if ($root->id) {
	$children = Q("{$root->name()}[root=$real_root][parent=$tag]");
	$has_children = $children->length() > 0;
}

?>
<?php echo Form::hidden('root_id', $root->id); ?>
<?php echo Form::hidden($name, $tag->id); ?>
<div class="nowrap">
	<?php if ($tag->id == $root->id && !$has_children) {
		$root_class = 'tag_selector_last';
	}
	else {
		$root_class = 'tag_selector_first';
	}?>

    <?php if (!$has_children):
        if ($tag->id != Tag_Model::root('group')->id) : ?>
            <div class="tag_selector_link tag_selector_last">
                <?php echo (string)Widget::factory('tag_selector/link', [
                    'name' => $i18n ? I18N::T($i18n, $tag->name) : $tag->name,
                    'id' => $tag->id,
                    'is_next' => false,
                    'field_title' => $field_title,
                ]); ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="tag_selector_link tag_selector_first">
            <?php
            if ($tag->id != $real_root->id) {
                echo (string) Widget::factory('tag_selector/link', [
                    'name' => $i18n ? I18N::T($i18n, $tag->name) : $tag->name,
                    'id' => $tag->id,
                    'field_title' => $field_title,
                ]);
            }
            ?>
        </div>
    <?php endif; ?>


<div class="tag_selector_more tooltip:<?php echo HT('请点击');?> tooltip_position:left">
    <span class="icon-drop_down"></span>
</div>
</div>
