<?php /* NO.STORY#38(xiaopei.li@2011.03.07) */?>
<?php echo $pagination; ?>
<?php
	$sort_fields = Config::get('equipments.training.sortable_columns');

	$table = Widget::factory('table');
	$table->name = 'equipments_approved_training';
	$table->sort_asc = $sort_asc;
	$table->sort_by = $sort_by;
    $table->add_columns($field);

	$table->empty_message = I18N::T('equipments', '没有已通过培训 / 授权记录!');

	if (count($trainings) > 0) {
		foreach($trainings as $training) {
			$user = $training->user;
			$table->add_row([
				'@'=>[
					'view' => $user->icon('32', 'style="display: block"'),
					'extra' => 'style="padding: 4px" align="right"',
				],
				'approved_name'=>V('equipments:users_table/data/name', ['user'=>$user]),
				'contact_info'=>V('equipments:users_table/data/contact_info', ['user'=>$user, 'training'=>$training]),
				'address'=>V('equipments:users_table/data/address', ['user'=>$user]),
				'mtime'=>$training->mtime ? date('Y/m/d', $training->mtime) : T('--'),
				'atime'=>$training->atime?date('Y/m/d', $training->atime):I18N::T('equipments', '不过期'),
				'rest'=>Widget::factory('application:links', ['links' => $training->links('approved')]),
			]);
		}
	}

	echo $table;
?>
