
<div class="tab_pagination">
    <?php echo $tertiary_tabs; ?>
</div>
<?php if($tertiary_tabs->panel_buttons || $tertiary_tabs->search_box): ?>
    <div class='search_panel no_padding_tertiary_search'>
        <?php
        echo $tertiary_tabs->panel_buttons;
        echo $tertiary_tabs->search_box;
        ?>
    </div>
<?php endif ?>

<?php echo $tertiary_tabs->content; ?>

<script>
    jQuery(function($){
        $(".no_padding_tertiary_search").next(".tab_content")
            .css('margin', '0px 16px 66px 16px')
            .css('padding', '0px 16px 16px 16px');
        $(".no_padding_tertiary_search")
            .css('margin', '0px')
            .css('padding', '16px 0 0 0');

    })
</script>

