<div class="form padding_1"><form method="post" action="" autocomplete="off">
<?php
$error = FALSE;
if($form['type']==$type){
	$error = ($form->no_error===FALSE);
	if($error) echo V('form_error', ['form'=>$form]);
}
?>
	<table class="form">
		<tr><td colspan="2"><strong>
			<?php echo I18N::T($module_name, $description); ?>
		</strong></td></tr>
		<?php if (isset($title)):?>
		<tr>
			<td class="top nowrap left"><?php echo I18N::T('equipments', '消息标题'); ?></td>
			<td><input type="text" name="title" size="40" class="text" value="<?php echo H($error ? $form['title'] : $title) ; ?>" /></td>
		</tr>
		<?php endif;?>
		<tr>
			<td class="top nowrap left"><?php echo I18N::T('equipments', '消息内容'); ?></td>
			<td><textarea name="body" cols="50" rows="5" class="autogrow"><?php echo H($error ? $form['body'] : $body); ?></textarea></td>
		</tr>
		<tr><td></td><td>
        <?php
            $handlers = Config::get('notification.handlers');
            if(is_array($send_by)) foreach($send_by as $k=>$v){
                $i18n_name = $handlers[$k]['module_name'] ?: $module_name;
				echo Form::checkbox('send_by_'.$k, ($error ? $form['send_by_'.$k] : $v[1]), I18N::T($i18n_name, $v[0]), 'class="middle"', 'class="middle"');
				echo '&#160;&#160;';
			}
		?>
		</td></tr>
		<tr><td></td>
		<td class="description">
		    <?php 
		        $descriptions = $strtr; 
		        if(is_array($descriptions)):
		    ?>
		    	<ul>
		    <?php
					foreach($descriptions as $k=>$v):
		    ?>
		    		<li><?php echo $k; ?>: <?php echo I18N::T($module_name, $v); ?></li>
		    <?php			            
		        	endforeach;
		    ?>
		    	</li></ul>
		    <?php
		        endif;
		    ?>
		</td></tr>
		<tr><td></td><td>
			<input type="hidden" name="type" value="<?php echo $type; ?>" />
			<input type="submit" name="submit" class="button button_save" value="<?php echo I18N::HT('equipments', '保存'); ?>" />
			<input type="reset" class="button button_cancel" value="<?php echo I18N::HT('equipments', '取消'); ?>" />
		</td></tr>
	</table>
</form></div>
