<?php
    echo JS::load_async('preview');
    echo CSS::load_async('preview');
	$now = time();
	if (!$form['dtstart']) {
		$dtstart = $now;
		$date=getdate($dtstart);
		$dtstart = mktime(0,0,0,$date['mon'], $date['mday'], $date['year']);
	} else {
		$dtstart = $form['dtstart'];
	}
	$dtend = $form['dtend'] ?: $dtstart + 604800;
	$browser_id = 'browser_' . uniqid();
    $search_date = $form['date']?:'';

?>
<script type="text/javascript">
Q.Calendar = Q.Calendar || {};
Q.Calendar.left_nav_area = <?php echo JS::quote((string) V('meeting:calendar/left_nav', ['calendar_id'=> $calendar->id]))?>
</script>
<div id="<?php echo H($browser_id) ?>" src="<?php echo H($calendar->url($type, ['browser_id'=>$browser_id, 'st'=>$dtstart, 'ed'=>$dtend, 'dtstart'=>$dtstart, 'dtend'=>$dtend, 'calendar_id'=>$calendar->id,'date'=>$search_date]) ) ?>"></div>
