<?php
	$form_errors = $form->errors;
?>
<div class="gapper_upgrade">
<div class="process">
	<div>
		<div class="proce proce_ed proce_first float_left">&#160;</div>
		<div class="node node_ing float_left">&#160;</div>
		<div class="proce proce_ed proce_normal float_left">&#160;</div>
		<div class="node node_ing float_left">&#160;</div>
		<div class="proce proce_will proce_normal float_left">&#160;</div>
		<div class="node node_will float_left">&#160;</div>
		<div class="proce proce_will proce_normal float_left">&#160;</div>
		<div class="node node_will float_left">&#160;</div>
		<div class="proce proce_will proce_last float_left">&#160;</div>
	</div>
	<div class="clearfix"></div>
	<div class="announce">
		<div class="float_left center announce-slim"><b><?= I18N::T('gapper','关联商城')?></b></div>
		<div class="float_left center announce-fat"><b><?= I18N::T('gapper','分组设置')?></b></div>
		<div class="float_left center announce-slim"><b><?= I18N::T('gapper','负责人开通')?></b></div>
		<div class="float_left center announce-fat text-grey"><?= I18N::T('gapper','完成')?></div>
	</div>
</div>
<div class="clearfix"></div>

<div class="gapper_content">
	<div class="float_left gapper_img">
		<div>
			<img src="!gapper/images/gapper.png">
		</div>
	</div>
    <p class="title">
		<?php echo I18N::T('gapper','分组设置')?>
	</p>
	<p class="notes">
		<?php echo I18N::T('gapper','您绑定的商城买方账户已升级为Gapper账户, 请选择并进行确认:') ?>&#160;
	</p>

	<div style="margin:40px 120px">
		<?php foreach ((array)$mall_gapper_groups as $group) {
			$rpc = Gapper::get_RPC();
			$group_info = $rpc->gapper->group->getInfo((int)$group['id']);
			if(!$group_info) continue;
			?>
			<div class="float_left center group_img gapper_img">
				<div class="icon_location" >
					<a class="app_bind" q-object="choose_mall_group" q-event="click" q-static="<?= H(['gid'=>$group_info['id'], 'source'=>$group['source']])?>">
					<?php if($group_info['icon']) {?>
					<img class="app_icon" src="<?= $group_info['icon']?>">
					<?php }else{?>

					<div class="gapper_icon">
						<div class="icon_text">
							<p class="icon_font"><b><?php echo $group_info['name'] ?></b></p>
						</div>
					</div>
					<?php }?>
					</a>
				</div>
				<p><?= $group_info['title']?></p>
			</div>
		<?php }?>
	</div>
</div>
</div>
