<form method="post">
    <div id="labs_columns">
        <?php foreach ($columns as $key => $column):?>
            <div class="column-item">
                <?= Form::hidden('sort[]',$key)?>
                <?= Form::checkbox($key, $column['show'], I18N::T('labs', $column['title']), ' class="middle checkbox monitor"', 'class="middle"'); ?>
            </div>
        <?php endforeach;?>
    </div>
    <div class="form" style="margin-top: 10px">
        <input type="submit" class="font-button-save" value="<?php echo H(T('保存修改'))?>" name="submit" />
    </div>
</form>
<script>
    var el = document.getElementById('labs_columns');
    new Sortable(el, {
        animation: 150,
        ghostClass: 'blue-background-class'
    });
</script>