<input name="check_time_s" class="text small_search_text date" date_type="date" value="<?php echo H($form['check_time_s']) ?>" q-date_format="<?php echo HT('$year/$month/$day') ?>" />
&#160;<span class="middle description">-</span>&#160;
<input name="check_time_e" class="text small_search_text date" date_type="date" value="<?php echo H($form['check_time_e']) ?>" q-date_format="<?php echo HT('$year/$month/$day') ?>" />
<input class="hidden" name="date_filter" value="1" />
