<input name="ctime_s" class="text small_search_text date" date_type="date" value="<?php echo H($form['ctime_s']) ?>" q-date_format="<?php echo HT('$year/$month/$day') ?>" />
&#160;<span class="middle description">-</span>&#160;
<input name="ctime_e" class="text small_search_text date" date_type="date" value="<?php echo H($form['ctime_e']) ?>" q-date_format="<?php echo HT('$year/$month/$day') ?>" />
<input class="hidden" name="date_filter" value="1" />
