<?php 
	$me = L('ME');
?>
<div class="hr_1">&#160;</div>

<form method="post" action="<?php URI::url();?>">
	<div class="form padding_2">
		<?php echo V('form_error', ['form'=>$form]);?>
		<table class="form">
			<tbody>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '消费人员'); ?></td>
					<td class="middle" colspan="2">
						<?php
							echo Widget::factory('user_selector', [
												'name'=>'user', 
												'autocomplete'=>URI::url('autocomplete/user'), 
												'user'=> $order->user,
							]);
						?>
					</td>
				</tr>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '消费时间'); ?></td>
					<td class="middle" colspan="2">
						<input name="time" id="time" class="text date" value="<?php echo $time; ?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>
					</td>
				</tr>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '消费金额')?></td>
					<td class="middle" colspan="2">
						<input name="price" class="text currency" sign="<?php echo H(Config::get('lab.currency_sign')) ?>" value="<?php echo H($order->price); ?>" size="40" />
					</td>
				</tr>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '食品名称'); ?></td>
					<td class="middle" colspan="2">
						<?php
							$fd_id = json_decode($order->foods, TRUE);
							echo Widget::factory('multi_user_selector', [
										'name'=>'fd_id', 
										'autocomplete'=>URI::url('!food/autocomplete/food'),
										'value'=>json_encode($fd_id),
							]);
						?>
					</td>
				</tr>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '食品供应商'); ?></td>
					<td class="middle" colspan="2">
						<input name="supplier" class="text" value="<?php echo H($order->supplier);?>" size="40" />
					</td>
				</tr>
				<tr>
					<td class="label right nowrap middle"><?php echo I18N::T('food', '备注信息'); ?></td>
					<td class="middle" colspan="2">
						<textarea name="remarks" cols="40" rows="3" style="height:60px;"><?php echo H($order->remarks); ?></textarea>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="form padding_2">
		<div class="nowrap">
			<input name="submit" type="submit" class="button button_add" value="<?php echo I18N::T('food', '修改'); ?>" />
			<input type="reset" class="button button_cancel" value="<?php echo I18N::T('food', '重置'); ?>" />
		</div>
	</div>
</form>
