<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View all accounts of this financial department.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Add, edit or delete accounts.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">View financial transaction details. </span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>