<?php foreach ($disabled_materials as $disabled_id => $disabled_number):
    $disabled_material = O('material', $disabled_id);
    ?>
    <tr>
        <td class="label left top nowrap">
            <div class="lpadding_3">
            <?php
            echo Form::checkbox("material[$disabled_material->id]", true, I18N::T('material', $disabled_material->name), 'class="middle"', 'class="middle"')?>
            </div>
        </td>
        <td class="nowrap">
            <input name="material_number[<?= $disabled_material->id?>]" type="text" class="text number" size="36" value="<?= $disabled_number?>">
            <?php echo $disabled_material->material_unit->name?>
        </td>
        <?php
        //echo Form::hidden("material[$disabled_material->id]", 'on');
        //echo Form::hidden("material_number[$disabled_material->id]", $disabled_number);
        ?>
    </tr>
<?php endforeach;?>