<?php

$tr_class = [];
$tr_class['extra'] = $row['#extra_class'];
$tr_extra = $row['#extra'];

if ($row['#special_view']) {
	$tr_class['type'] = 'special';
}
else {
	$tr_class['type'] = 'row';
}

$sort_by = (string) $table->sort_by;
if ($row['#special_view']) {
	echo '</tbody><tbody><tr '.$tr_extra . ' class="'. implode(' ', $tr_class) . '">';
	echo '<td colspan="'.H($table->visible_count).'">'.$row['#special_view'].'</td>';
	echo '</tr></tbody><tbody>';
}
elseif ($row['#special_row']) {
	echo '<tr '.$tr_extra . ' class="'. implode(' ', $tr_class) . '">';
	echo '<td colspan="'.H($table->visible_count).'">'.$row['#special_row'].'</td>';
	echo '</tr>';	
}
elseif ($row['#custom_row']) {
	echo $row['#custom_row'];
}
else {	
	echo '<tr '.$tr_extra . ' class="'. implode(' ', $tr_class) . '">';
	foreach ($table->columns as $key => $column) {
		if ($column['invisible']) continue; 

	
		if (is_array($row[$key])) {

			$extra = $row[$key]['extra']?:'';
			$view = $row[$key]['view'];
			unset($row[$key]['view']);
			$column = $row[$key] + $column;
		}
		else {
			$view = $row[$key];
		}

		$class = [];
		if ($column['align']) $class['align'] = $column['align'];
		if ($column['nowrap']) $class['nowrap'] = 'nowrap';
		/*
		* @Date:2018-09-06 09:43:43
		* @Author: LiuHongbo
		* @Email: hongbo.liu@geneegroup.com
		* @Description:该处用来添加自定义class
		*/
		if($column['extra_class'])$class['exstra_class']=$column['extra_class'];
		if ($column['sortable'] && $sort_by == $key) {
			$class['sort_column'] = 'sort_column';
		}

		if ($key == "rest") {
            $class['test'] = 'last';
        }
		$str_view = (string) $view;
		echo '<td class="'.implode(' ', $class).'" '.$extra.'>'
			. ($str_view != '' ? $str_view : '&#160;')
			. '</td>';
	}

}

