<?php //echo Form::checkbox('dtstart_check', $this->dtstart_check, '', 'class="middle monitor"'); ?><!--&#160;<input name="dtstart" class="text date middle toggle_status:dtstart_check enable_on:on" value="--><?php //echo H($this->dtstart);?><!--" q-date_format="--><?php //echo HT('$year/$month/$day')?><!--"/>-->
<!--			-->
<!--&#160;<span class="middle description">-</span>-->
<!---->
<?php //echo Form::checkbox('dtend_check', $this->dtend_check, '', 'class="middle monitor"'); ?><!--&#160;<input name="dtend" class="text date middle toggle_status:dtend_check enable_on:on" value="--><?php //echo H($this->dtend);?><!--" q-date_format="--><?php //echo HT('$year/$month/$day')?><!--"/>-->
<!--<input class="hidden" name="date_filter" value=1 />-->

<?php
$this->dtstart = $this->dtstart ? date('Y-m-d', $this->dtstart) : '';
$this->dtend = $this->dtend ? date('Y-m-d', $this->dtend) : '';
?>

<input id="dtstart" autocomplete="off" name="dtstart" class="text small_search_text date" date_type="date" value="<?php echo H($this->dtstart); ?>" /><span class="middle description date_interval">-</span><input autocomplete="off" id="dtend" name="dtend" class="text small_search_text date" date_type="date" value="<?php echo H($this->dtend); ?>" />

