<style>
    .tag_selector {
        min-width: 400px;
    }
    .dropdown_container {
        min-width: 378px;
    }
</style>
<?php
    $me = L('ME');
?>
<div class="form">
<table class="flexible form">
	<tbody>
	<tr>
		<td class="top icon" style="width: 100px">
			<?php echo V('people:profile/short_info', ['user'=>$user]);?>
            <div class="interval_12"></div>
            <div class="short_info short_container">
                <a class="font-button-delete" confirm="<?php echo H(I18N::T('people', '您确定删除头像吗?')) ?>" href="<?php echo H(URI::url('!people/profile/delete_photo.'.$user->id)) ?>"><?php echo I18N::T('people', '删除头像')?></a>
            </div>
        </td>
		<td class="top lpadding_30">
			<form class="edit" method="post" autocomplete="off" action="<?php echo H(URI::url() ) ?>">
            <input type="password" class="hidden" />
			<?php
				echo V('form_error', ['form'=>$form]);
				$form_no_error = ($form->no_error!==FALSE);

				$requires = Lab_Model::edit_require_fields();
				$data = Event::trigger("user_signup_requires", $requires, $user);
				$requires = is_null($data) ? $requires : $data;
			
				$_requires = function($key) use ($requires) {
					// echo $requires[$key] ? (string) V('form_require') : '';
					echo $requires[$key] ? '<span class="required">*</span>' : '<span class="lpadding_18"></span>';
				}
			?>
			<?php
				$form_token = 'people.admin_edit_info'. uniqid();
				$_SESSION['people.admin_edit_info'] = $form_token;
			?>
			<input type="hidden" name="token" value="<?= $form_token?>">
			<table class="form">
				<tbody>
					<tr>
						<td colspan="4">
							<h2 class="section_title">
                                <span class="border"></span>
                                <span class="black_title"><?php echo I18N::T('people', '个人信息') ?></span>
                                <span class="float_right" style="font-size: 14px;font-weight: normal;color: #F5222D;"><span class="required">*</span>必填</span>
                            </h2>
						</td>
					</tr>
                    <tr><td colspan="4"><div class="interval_16"></div> </td></tr>
                    <tr>
                        <td class="padding_2  rpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '姓名')?></span><?php echo $_requires('name')?>
                                <br>
                                <?php echo V('form_filter',['error'=>$form->errors['name'][0]])?>
                            </div>
                            <div>
                                <input placeholder="请输入姓名" name="name" class="text" size="54" value="<?php echo H($form_no_error?$user->name:$form['name'])?>" />
                            </div>
                        </td>
                        <td  class="padding_2  lpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '性别')?></span><?php echo $_requires('gender')?>
                                <br>
                                <?php echo V('form_filter',['error'=>$form->errors['lab_contact'][0]]);?>
                            </div>
                            <div>
                                <?php echo Form::dropdown('gender', I18N::T('people', User_Model::$genders), $form_no_error ? ($user->gender >= 0 ? $user->gender : -1) : $form['gender'], 'class="dropdown"'); ?>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="padding_2  rpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '人员类型')?></span><?php echo $_requires('member_type')?>
                                <br>
                                <?php echo V('form_filter',['error'=>$form->errors['member_type'][0]])?>
                            </div>
                            <?php
                                $members_type = [];
                                foreach(User_Model::get_members() as $key => $value){
                                    $members_type[I18N::T('people', $key)] = $value;
                                }
                            ?>
                            <div>
                                <?php echo Form::dropdown('member_type', ['-1'=>'--'] + I18N::T('people', $members_type), $form_no_error ? ($user->member_type >= 0 ? $user->member_type : -1) :(isset($form['member_type']) ? $form['member_type'] : -1), 'class="dropdown"'); ?>
                            </div>
                        </td>
                        <?php
                        if ($GLOBALS['preload']['tag.group_limit'] >= 0 && $me->is_allowed_to('修改组织机构', $user)): ?>
                            <td  class="padding_2  lpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '组织机构')?></span><?php echo $_requires('group_id')?>
                                    <br>
                                    <?php echo V('form_filter',['error'=>$form->errors['lab_contact'][0]]);?>
                                </div>
                                <div>
                                    <div class="gray_tag_container">
                                        <?php
                                        if (!$me->is_allowed_to('修改组织机构', $user, ['@ignore'=>'修改下属机构成员'])) {
                                            $group_root = $me->group;
                                        }
                                        echo Widget::factory('application:tag_selector', [
                                            'tag'=>$form['group_id'] ? O('tag_group', $form['group_id']) : $user->group,
                                            'root'=>$group_root,
                                            'name'=>'group_id',
                                            'ajax'=>true,
                                        ]);
                                        ?>

                                    </div>
                                </div>
                            </td>
                        <?php endif;?>
                    </tr>
					<?php if ( Config::get('people.show_ref_no', true) ) : ?>
                        <tr>
                            <td class="padding_2  rpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '学号/工号')?></span><?php echo $_requires('ref_no')?>
                                </div>
                                <div>
                                    <input placeholder="请输入学号/工号" name="ref_no" class="text" size="54" value="<?php echo H($form_no_error?$user->ref_no:$form['ref_no'])?>" />
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
					<?php if (Config::get('people.show_mentor_name', false) ) : ?>
                        <tr>
                            <td class="padding_2" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '导师姓名');  ?></span><?php echo $_requires('mentor_name')?>
                                </div>
                                <div>
                                    <input placeholder="导师姓名" name="mentor_name" size="54" class="text" value="<?php echo H( $form_no_error ? $user->mentor_name : $form['mentor_name']); ?>" />
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
                    <tr>
                        <td class="padding_2  rpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '专业')?></span><?php echo $_requires('major')?>
                            </div>
                            <div>
                                <input placeholder="请输入专业" name="major" class="text" size="54" value="<?php echo H($form_no_error?$user->major:$form['major'])?>" />
                            </div>
                        </td>
                        <td  class="padding_2  lpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '单位名称')?></span><?php echo $_requires('organization')?>
                            </div>
                            <div>
                                <input placeholder="请输入单位名称" name="organization" class="text"  size="54" value="<?php echo H($form_no_error?$user->organization:$form['organization'])?>" />
                            </div>
                        </td>
                    </tr>
                    <?php if (Module::is_installed('equipments')) :?>
						<?php $default_lab = Equipments::default_lab();?>
                        <?php if (Q("$user $default_lab")->total_count()) :?>
                        <?php echo Event::trigger('equipments.record.edit_user_view', $user, $form);?>
                        <tr>
                            <td class="padding_2  rpadding_4" colspan="2">
                                <?php if (Config::get('people.temp_user.tax_no.required', FALSE)) :?>
                                    <?php echo V('form_require');?>
                                <?php endif;?>
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '税务登记号')?></span>
                                </div>
                                <div>
                                    <input name="tax_no" class="text"  size="54" value="<?php echo H($form_no_error ? $user->tax_no : $form['tax_no']);?>" />
                                </div>
                            </td>
                            <td class="padding_2  lpadding_4" colspan="2">
                            </td>
						</tr>
						<tr><td colspan="4"><div class="interval_16"></div> </td></tr>
						<?php else:?>
							<?php $is_auth = Event::trigger('extra.is_auth', $user);
								if ($is_auth == 'outsider') :
							?>
                                    <?= V('labs:signup/signup_extra_field', ['form' => $form, 'user' => $user, 'form_no_error' => $form_no_error, 'type' => 'profile']);?>
							<?php endif;?>
						<?php endif;?>
                    <?php endif;?>
					<?php if ($GLOBALS['preload']['people.enable_member_date']): ?>
                        <tr>
                            <td class="padding_2 rpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '所在时间(开始)')?></span>
                                    <?php if ($requires['time']) :?>
                                        <?php echo V('form_require');?>
                                    <?php endif;?>
                                </div>
                                <div>
                                    <?php //echo Form::checkbox('has_dfrom', $form->no_error ? ($user->dfrom > 0) : $form['has_dfrom'], NULL, 'class="middle monitor"'); ?>
                                    <?php
                                    $dfrom = $form_no_error ? ($user->dfrom) : $form['dfrom'];
                                    $dfrom = $dfrom ? date('Y-m-d', $dfrom) : '';
                                    ?>
                                    <input id="dfrom" placeholder="请输入开始时间" date_type="date" name="dfrom"  size="54" class="text date" value="<?php echo H($dfrom); ?>" />
                                </div>
                            </td>
                            <td  class="padding_2 lpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '所在时间(结束)')?></span>
                                </div>
                                <div>
                                    <?php //echo Form::checkbox('has_dto', $form->no_error ? ($user->dto > 0) : $form['has_dto'], NULL, 'class="middle monitor"'); ?>
                                    <?php
                                    $dto = $form_no_error ? ($user->dto) : $form['dto'];
                                    $dto = $dto ? date('Y-m-d', $dto) : '';
                                    ?>
                                    <input id="dto" placeholder="请输入结束时间" date_type="date" name="dto"  size="54" class="text date" value="<?php echo H($dto); ?>" />
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
                    <tr><td colspan="4"><div class="interval_16"></div> </td></tr>
					<tr>
						<td>
							<h2 class="section_title">
                                <span class="border"></span>
                                <span class="black_title"><?php echo I18N::T('people', '联系方式') ?></span>
                            </h2>
						</td>
					</tr>
                    <tr><td colspan="4"><div class="interval_16"></div> </td></tr>
                    <tr>
                        <td class="padding_2  rpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '电子邮箱')?></span>
                                <?php echo $_requires('email')?>
                                <br>
                                <?php echo V('form_filter',['error'=>$form->errors['email'][0]])?>
                            </div>
                            <div>
                                <?php if ($yiqikong_lab_name = Config::get('people.yiqikong_lab_name')
                                    && Q("$user lab[name={$yiqikong_lab_name}]")->total_count()): ?>
                                <input placeholder="请输入电子邮箱" name="email" class="text"  size="54" value="<?php echo H($user->email)?>" disabled="disabled" /><?php echo $_requires('email')?>
                                <?php else : ?>
                                <input placeholder="请输入电子邮箱" name="email" class="text"  size="54" value="<?php echo H($form_no_error?$user->email:$form['email'])?>" /><?php echo $_requires('email')?>
                                <?php endif; ?>
                            </div>
                        </td>
                        <td  class="padding_2 lpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '联系电话')?></span>
                                <?php echo $_requires('phone')?>
                                <br>
                                <?php echo V('form_filter',['error'=>$form->errors['phone'][0]])?>
                            </div>
                            <div>
                                <input placeholder="请输入联系电话" name="phone" class="text"  size="54" value="<?php echo H($form_no_error?$user->phone:$form['phone'])?>" />
                            </div>
                        </td>
                    </tr>
                    <?php if (Config::get('people.show_personal_phone', false) ) : ?>
                        <tr>
                            <td class="padding_2" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '个人手机'); ?></span>
                                    <?php echo $_requires('personal_phone')?>
                                </div>
                                <div>
                                    <input placeholder="请输入个人手机" name="personal_phone" class="text"  size="54" value="<?php echo H($form_no_error ? $user->personal_phone : $form['personal_phone']); ?>" />
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
                    <tr>
                        <td class="padding_2  rpadding_4" colspan="2">
                            <div class="bpadding_2">
                                <span class="rpadding_1"><?php echo I18N::T('people', '地址')?></span>
                                <?php echo $_requires('address')?>
                            </div>
                            <div>
                                <input placeholder="请输入地址" name="address" class="text"  size="54" value="<?php echo H($form_no_error?$user->address:$form['address'])?>" />
                                <!-- 防止360浏览器自动将账号密码填充到ic卡号。。 -->
                                <input type="text" autocomplete="off"  style="display: none;"/>
                                <input type="password" autocomplete="off" style="display: none;"/>
                            </div>
                        </td>
                    </tr>
                    <?php echo V('profile/admin/user_card', ['user' => $user, 'form' => $form, 'form_no_error' => $form_no_error, '_requires' => $_requires]);?>
					<?php if ($me->is_allowed_to('激活', $user)): ?>
                        <tr><td colspan="4"><div class="interval_16"></div> </td></tr>
                        <tr>
                            <td colspan="4">
                                <h2 class="section_title">
                                    <span class="border"></span>
                                    <span class="black_title"><?php echo I18N::T('people', '状态信息') ?></span>
                                </h2>
                            </td>
                        </tr>
                        <tr><td colspan="4"><div class="interval_16"></div> </td></tr>
                        <tr>
                            <td class="padding_2" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '是否激活')?></span>
                                </div>
                                <div>
                                    <?php echo Form::radio('activate', '1', $form_no_error?($user->atime>0):($form['activate']>0), I18N::T('people', '是'), 'class="middle radio"', 'class="middle rmargin_152_i"'); ?>
                                    <?php echo Form::radio('activate', '0', $form_no_error?($user->atime>0):($form['activate']>0), I18N::T('people', '否'), 'class="middle radio"', 'class="middle"'); ?>
                                </div>
                            </td>
                        </tr>
					<?php elseif (Q('user[atime>0]')->total_count() >= $GLOBALS['preload']['lab.max_active_members']): ?>
                        <tr>
                            <td class="padding_2" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '立即激活')?></span>
                                </div>
                                <div>
                                    <?php echo Form::radio('activate', 1, $form['activate'], I18N::T('people', '是'), ' class="middle" disabled radio', 'class="middle rmargin_152_i"'); ?>
                                    <?php echo Form::radio('activate', 0, $form['activate'], I18N::T('people', '否'), ' class="middle" disabled radio', 'class="middle"'); ?>
                                    <span class="red lpadding_1">*<?php echo I18N::T('people', '激活用户数量已达上限')?></span>
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
					<?php if($user->id != $me->id): ?>
                        <tr>
                            <td class="padding_2  rpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"> <?php echo I18N::T('people', '不可删除')?></span>
                                </div>
                                <div>
                                    <?php echo Form::radio('undeletable', 1, $form_no_error?$user->undeletable:$form['undeletable'], I18N::T('people', '是'), ' class="middle radio"', 'class="middle rmargin_152_i"'); ?>
                                    <?php echo Form::radio('undeletable', 0, $form_no_error?$user->undeletable:$form['undeletable'], I18N::T('people', '否'), ' class="middle radio"', 'class="middle"'); ?>
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
					<?php if ($me->is_allowed_to('隐藏', $user)): ?>
                        <tr>
                            <td class="padding_2  rpadding_4" colspan="2">
                                <div class="bpadding_2">
                                    <span class="rpadding_1"><?php echo I18N::T('people', '是否隐藏')?></span>
                                </div>
                                <div>
                                    <?php echo Form::radio('hidden', 1, $form_no_error?$user->hidden:$form['hidden'], I18N::T('people', '是'), ' class="middle radio"', 'class="middle rmargin_152_i"'); ?>
                                    <?php echo Form::radio('hidden', 0, $form_no_error?$user->hidden:$form['hidden'], I18N::T('people', '否'), ' class="middle radio"', 'class="middle"'); ?>
                                </div>
                            </td>
                        </tr>
					<?php endif; ?>
					<tr>
						<td colspan="4"><div class="interval_36"></div> </td>
					</tr>
                    <tr>
                        <td  colspan="4">
                            <div class="float_right">
                                <input type="submit" name="submit" class="font-button-save middle rmargin_16  float_right" value="<?php echo H(I18N::T('people', '保存修改')) ?>" />
                                <?php if($me->is_allowed_to('删除', $user) && !Module::is_installed('uno')): ?>
                                    <a
                                            class="font-button-delete middle   rmargin_16 float_right"
                                            confirm="<?php echo I18N::T('people', '你确定要删除吗? 删除后不可恢复!'); ?>"
                                            href="<?php echo $user->url(NULL, 'referer_url='.$_SESSION['system.last_layout_url'], NULL, 'delete'); ?>"><?php echo I18N::T('people', '删除用户')?></a>
                                <?php endif;?>
                            </div>
                        </td>
                    </tr>
				</tbody>
			</table>

			</form>
		</td>
	</tr>
	</tbody>
</table>
</div>
