<div class="form">
    <table class="form" style="width: 100%">
        <tbody>
            <tr>
                <td class="icon top" width="130">
                    <div class="short_container">
                        <div class="icon-radius img_icon" style="position: relative;">
                                <?php echo $meeting->icon('104'); ?>
                        </div>
                    </div>
                </td>
                <td>
                    <form method="post" class="edit" autocomplete="off" action="<?php echo H(URI::url()) ?>">
                    <?php echo V('form_error', ['form'=>$form]);?>
                    <?php $require = (string) V('form_require', ['extra_class' => 'top']); ?>
                    <div class="interval_30"></div>
                        <h2 class="section_title">
                            <span class="border"></span>
                            <span class="black_title"><?php echo I18N::HT('eq_reserv', '预约审核'); ?></span>
                        </h2>
                    <div class="interval_12"></div>
                    <div class="lmaigin_1e5">
                        <?php echo Form::checkbox('need_approval', $meeting->need_approval, I18N::T('meeting', '需要审核'), 'class="middle checkbox monitor"', 'class="middle"'); ?>
                    </div>

                    <div class="interval_30"></div>
                        <h2 class="section_title">
                            <span class="border"></span>
                            <span class="black_title"><?php echo I18N::HT('eq_reserv', '预约规则'); ?></span>
                        </h2>
                    <div class="interval_12"></div>
                    <table class="lmaigin_1e5">
                            <tbody>
                                 <tr>
                                    <td class="left nowrap middle"><?php echo I18N::T('eq_reserv', '添加预约最早可提前')?></td>
                                    <td class="nowrap middle">
                                        <?php
                                            echo Form::radio('default_add_earliest', 'customize',
                                                is_null($add_reserv_earliest_time) && !isset($form['add_reserv_earliest_time']) ?
                                                'default' : 'customize','','class="middle monitor"' . $disabled); ?>
                                        <span class="middle toggle_status:default_add_earliest enable_on:customize">
                                        <input class="text number middle set_time_value" name="add_reserv_earliest_time" value="<?php echo H(isset($add_reserv_earliest_time) ?  $add_reserv_earliest_time : $default_add_reserv_earliest_time) ?>" <?php echo $disabled?>/>&#160;
                                        <?php echo Form::dropdown('add_reserv_earliest_format', Date::units('ihd'), $add_reserv_earliest_format ? :
                                        $default_add_reserv_earliest_format ? : Config::get('eq_reserv.default_add_reserv_limit_format', 'i'),'class="middle set_time_format"' . $disabled);?>
                                        </span>
                                        &#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
                                        <?php
                                            echo Form::radio('default_add_earliest', 'default',
                                                is_null($add_reserv_earliest_time) && !isset($form['add_reserv_earliest_time']) ?
                                                    'default' : 'customize',
                                                    I18N::T('eq_reserv', '系统默认值'),'class="middle monitor"' . $disabled,'class="middle"');
                                        ?>
                                    </td>
                                </tr>
                                <tr><td colspan="2"><div class="interval_6"></div></td></tr>
                                <tr>
                                    <td class="left nowrap middle"><?php echo I18N::T('eq_reserv', '添加预约最晚可提前')?></td>
                                    <td class="nowrap middle">
                                        <?php echo Form::radio('default_add_latest','customize', is_null($add_reserv_latest_time) && !isset($form['add_reserv_latest_time']) ? 'default' : 'customize','','class="middle monitor"' . $disabled); ?>
                                        <span class="middle toggle_status:default_add_latest enable_on:customize">
                                        <input class="text number middle set_time_value" name="add_reserv_latest_time" value="<?php echo H(isset($add_reserv_latest_time) ?  $add_reserv_latest_time : $default_add_reserv_latest_time) ?>" <?php echo $disabled?>/>&#160;
                                        <?php echo Form::dropdown('add_reserv_latest_format', Date::units('ihd'), $add_reserv_latest_format ? : $default_add_reserv_latest_format ? : Config::get('eq_reserv.default_add_reserv_limit_format', 'i'),'class="middle set_time_format"' . $disabled);?>
                                        </span>
                                        &#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
                                        <?php echo Form::radio('default_add_latest','default', is_null($add_reserv_latest_time) && !isset($form['add_reserv_latest_time']) ? 'default' : 'customize',I18N::T('eq_reserv', '系统默认值'),'class="middle monitor"' . $disabled,'class="middle"'); ?>
                                    </td>
                                </tr>
                                <tr><td colspan="2"><div class="interval_6"></div></td></tr>
                                <tr>
                                    <td class="left nowrap middle"><?php echo I18N::T('eq_reserv', '修改 / 删除预约最晚可提前')?>&#160;&#160;</td>
                                    <td class="nowrap middle">
                                        <?php echo Form::radio('default_modify_latest', 'customize', is_null($modify_reserv_latest_time) && !isset($form['modify_reserv_latest_time']) ? 'default' : 'customize','','class="middle monitor"' . $disabled); ?>
                                        <span class="middle toggle_status:default_modify_latest enable_on:customize">
                                        <input class="text number middle set_time_value" name="modify_reserv_latest_time" value="<?php echo H(isset($modify_reserv_latest_time) ?  $modify_reserv_latest_time : $default_modify_reserv_latest_time) ?>" <?php echo $disabled?>/>&#160;
                                        <?php echo Form::dropdown('modify_reserv_latest_format', Date::units('ihd'), $modify_reserv_latest_format ? : $default_modify_reserv_latest_format ? : Config::get('eq_reserv.default_modify_reserv_limit_format','i'),'class="middle set_time_format"' . $disabled);?>
                                        </span>
                                        &#160;&#160;<?php echo I18N::T('eq_reserv', '或'); ?>&#160;&#160;
                                        <?php echo Form::radio('default_modify_latest', 'default', is_null($modify_reserv_latest_time) && !isset($form['modify_reserv_latest_time']) ? 'default' : 'customize',I18N::T('eq_reserv', '系统默认值'),'class="middle monitor"' . $disabled,'class="middle"'); ?>
                                    </td>
                                </tr>
                                <tr>

                                    <td class="middle description nowrap" colspan="3" style="color: #E02020;">
                                        <div class="interval_6"></div>
                                        <?php echo I18N::HT('eq_reserv', '* 设置为0, 表示不限制添加 / 修改 / 删除的提前时间')?>
                                    </td>
                                </tr>
                                <tr>

                                    <td class="middle description nowrap" colspan="3" style="color: #E02020;">
                                        <div class="interval_6"></div>
                                        <?php echo I18N::HT('eq_reserv', '* 建议 “修改 / 删除预约最晚可提前” 时间小于 “添加预约最晚可提前” 时间, 否则会出现添加预约后用户不可编辑的情况');?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <div class="interval_30"></div>
                        <h2 class="section_title">
                            <span class="border"></span>
                            <span class="black_title"><?php echo I18N::T('meeting', '时间对齐设置') ?></span>
                        </h2>
                        <div class="interval_12"></div>
                        <div class="lmaigin_1e5">
                            <?php echo Form::checkbox('accept_block_time', $meeting->accept_block_time, I18N::T('meeting', '需要时间对齐'), 'class="middle checkbox monitor"', 'class="middle"'); ?>
                            <div class="hidden toggle:accept_block_time show_on:on">
                                <table class="form">
                                    <tbody>
                                    <tr>
                                        <td class="nowrap middle">
                                            <div class="interval_6"></div>
                                            <?php list($interval_time, $interval_time_format) = Date::format_interval($meeting->reserv_interval_time, 'ih') ?>
                                            <span class="middle rpadding_12"><?php echo I18N::T('eq_reserv', '时间长度对齐间距') ?></span>
                                            <input class="text number middle set_time_value" name="interval_time"
                                                   value="<?php echo $interval_time ?: 1; ?>"/>
                                            <?php echo Form::dropdown('interval_time_format', Date::units('ih'), $interval_time_format, 'class="middle  set_time_format"'); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="interval_6"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="nowrap middle">
                                            <?php list($align_time, $align_time_format) = Date::format_interval($meeting->reserv_align_time, 'ih') ?>
                                            <span class="middle rpadding_12"><?php echo I18N::T('eq_reserv', '时间起始对齐间距') ?></span>
                                            <input class="text number middle set_time_value" name="align_time"
                                                   value="<?php echo H($align_time ?: 1) ?>"/>
                                            <?php echo Form::dropdown('align_time_format', Date::units('ih'), $align_time_format, 'class="middle  set_time_format"'); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="interval_6"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="nowrap middle">
                                        <span class="description" style="color: #E02020;">
                                        <?php echo I18N::T('meeting', '<span class="required">*</span> 时间段不允许跨天设置'); ?>
                                        </span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="interval_30"></div>
                        <div class="hidden toggle:accept_block_time show_on:on">
                            <?php
                            echo Widget::factory('flexform', [
                                'title' => I18N::T('meeting', '个别时间段时间对齐设置'),
                                'description' => '(' . I18N::T('meeting', '个别时间段之间的预约不能合并') . ')',
                                'template_data' => ['disabled' => TRUE],
                                'existing_data' => $meeting->reserv_block_data,
                                'item_view' => 'meeting:meeting/meeting_block_item',
                                'extra_vars' => [
                                    'meeting' => $meeting,
                                ],
                            ]);
                            ?>
                        </div>
                        <div class="button_container">
                            <div class="float_right">
                                <input type="submit" name="submit" class="font-button-save rmargin_16" value="保存修改">
                            </div>
                        </div>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
</div>