<div class="padding_3 clearfix">
  <table class="form" align="center" width="100%">
    <tbody>
      <tr>
        <td class="description" align="left" style="min-width: 80px;"><?php echo I18N::T('meeting', '主题'); ?></td>
        <td> <?php echo H($component->name); ?></td>
      </tr>
      <tr>
        <td class="description" align="left"><?php echo I18N::T('meeting', '预约者'); ?></td>
        <td>
          <?php
          $has_lab = Module::is_installed('labs');
          if ($has_lab && !$GLOBALS['preload']['people.multi_lab']) {
            echo H($component->organizer->name) . ' (' . H(Q("{$component->organizer} lab")->current()->name) . ')';
          } else {
            echo H($component->organizer->name);
          }
          ?>
        </td>
      </tr>
      <tr>
        <td class="description" align="left"><?php echo I18N::T('meeting', '会议室'); ?></td>
        <td>
          <?php
          if ($component->calendar->parent_name == 'meeting') {
            $parent = $component->calendar->parent;
            echo H($parent->name);
          }
          ?>
        </td>
      </tr>
      <tr>
        <td class="description" align="left"><?php echo I18N::T('meeting', '起始时间'); ?></td>
        <td><?php echo Date::format($component->dtstart, T('Y/m/d H:i:s')); ?></td>
      </tr>

      <tr>
        <td class="description" align="left"><span class="description"><?php echo I18N::T('meeting', '结束时间'); ?></span></td>
        <td><?php echo Date::format($component->dtend, T('Y/m/d H:i:s')); ?></td>
      </tr>
      <?php
      $me = L('ME');
      if ($me->is_allowed_to('修改', $component) || $me->is_allowed_to('删除', $component)) : ?>
        <tr class="padding_3">
          <td>&nbsp;<div style="margin-top: 10px;"></div></td>
          <td>
            <div class="lmaigin_1e5">
              <?php if ($me->is_allowed_to('修改', $component)) : ?>
                <a title="修改" class="button icon-edit" q-src="<?php echo URI::url('!calendars/calendar'); ?>" q-event="click" q-static="<?php echo H([
                  'id' => $component->id,
                  'calendar_id' => $component->calendar->id,
                  'dtstart' => $component->dtstart,
                  'dtend' => $component->dtend,
                  'mode' => 'week',
                ]); ?>" q-object="edit_component">
                  <?php echo I18N::T('meeting', '修改'); ?>
                </a>
              <?php endif; ?>

              <?php if ($me->is_allowed_to('删除', $component)) : ?>
                <a title="删除" class="button icon-trash" q-src="<?php echo URI::url('!calendars/calendar'); ?>" q-event="click" q-object="delete_component" q-static="<?php echo H(['component_id' => $component->id,]); ?>">
                  <?php echo I18N::T('meeting', '删除'); ?>
                </a>
              <?php endif; ?>

              <?php 
                $reserv = O('me_reserv', ['component' => $component]);
                $workflow = O('workflow', ['source' => $reserv]);
                if ($workflow->id && $workflow->flag != 'done' && $me->is_allowed_to('审核', $reserv)) : ?>
                <a title="审核" class="button icon-approving" q-src="<?php echo URI::url('!workflow/index'); ?>" q-event="click" q-object="workflow_approval" q-static="<?php echo H([
                  'source_name' => 'me_reserv',
                  'source_id' => $reserv->id
                ]); ?>">
                  <?php echo I18N::T('meeting', '审核'); ?>
                </a>
              <?php endif; ?>
            </div>
          </td>
        </tr>
      <?php endif; ?>
    </tbody>
  </table>
</div>