<div class="description">
	<p>您正在查看此台仪器的基本信息和当前使用者。</p>
	<p>您可以关注此台仪器，您将在您的主页面直接看到该仪器。</p>
	<p>当仪器出现问题时您向负责人报告仪器故障。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以修改或删除此台仪器的相关信息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以代用户打开此台仪器的控制开关。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">如果此台仪器为电脑控制，您可以实时监控控制此台仪器的电脑显示桌面。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>