<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您正在查看该台仪器的封禁用户列表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以按照成员姓名进行搜索。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以在这里手动添加该台仪器的封禁用户。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以为用户解除封禁。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>
