<div class="description">
	<p>你可以看到您使用此台仪器的使用收费记录。</p>
	<p>您可以按照使用者、实验室、时间等查找收费记录。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以看到该台仪器的所有使用收费记录。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以直接打印出仪器使用收费记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以以CSV格式导出仪器使用收费记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>

