<div class="description">
	<p>您正在您使用此台仪器的使用记录。</p>
	<p>您可以按照使用者、实验室、时间、状态等查找使用记录。</p>
	<p>您可以在这里填写反馈记录。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以看到该台仪器的所有使用记录。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以手动添加仪器使用记录。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以点击“编辑”设定代开成员、爽约和超时状态。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以直接打印出仪器使用记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以以CSV格式导出仪器使用记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>

