<div class="description">
	<p>您可以按周历或列表查看此台仪器的预约情况。</p>
	<p>双击已经建立的预约时间段,可以查看预约信息。</p>
	<p>您可以点击开始时间并拖到终止时间来确定您需要的预约时间段,并填写弹出窗口中的内容。</p>
	<p>您可以在规定时间内修改/取消预约时间。</p>
	<p>您可以把预约色块拖拽到任意可预订时段,改变预约色块长度可以更改预约时间。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以修改或删除此台仪器的相关信息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以代用户打开此台仪器的控制开关。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以在弹出窗口修改预约类型和预约人员姓名。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>