<div class="description">
	<p>您可以看到该台仪器的送样预约申请记录。</p>
	<p>您可以在这里进行送样预约。</p>
	<p>您可以编辑您的送样申请信息。</p>
	<p>您可以按照样品数、时间、状态进行排序。</p>
	<p>您可以按照申请人、样品数、时间、状态、操作者姓名进行搜索。</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以向申请人发送消息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以点击“编辑”修改送样预约的相关记录信息。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>