<div class="hr_1">&#160;</div>
<div class="padding_1 nowrap">
	<form autocomplete="off" q-object="edit_approve_tag" q-event="submit" q-static="<?php echo H(['tid'=>$tid]) ?>">
		<table class="form">
			<tr>
				<td class="left middle nowrap"><?php echo I18N::T('meeting', '过期时间') ?></td>
				<td class="left middle padding_1">
					<?php
						$selected = $atime ? 1 : 0;
						echo Form::radio('atime', 0, $selected, I18N::T('meeting', '不过期'), 'class="monitor middle"', 'class="middle"');
						echo '&#160;&#160;';
						echo Form::radio('atime', 1, $selected, NULL, 'class="monitor middle"', 'class="middle"'); 
					?>
				<span class="toggle_status:atime enable_on:1">
					<input name="deadline" class="text date" value="<?php echo H($atime ) ?>" q-date_format="<?php echo HT('$year/$month/$day')?>"/>
				</span>
				</td>
			</tr>
		<tr>
			<td>&#160;</td>
			<td class="left middle">
				<input type="submit" class="button button_add" value="<?php echo H(I18N::T('meeting', '添加') ) ?>" />
			</td>
		</tr>
		</table>
	</form>
</div>
