<div class="form">
	<form action="<?php echo H(URI::url('!equipments/export', ['type'=>'csv', 'form_token'=>$form_token])) ?>" class="prevent_default" method="post">
	<div class="interval_20">&nbsp</div>
		<ul class="ep_triple">
			<?php
			foreach ($columns as $p => $p_name) :?>
				<li class="nowrap">
					<?php echo Form::checkbox("columns[{$p}]", TRUE, I18N::T('equipments', $p_name), 'class="middle monitor"', 'class="middle"');?>
				</li>
			<?php endforeach;?>
		</ul>
		<div class="button_container">
            <div class="float_right">
                <input name="cancel" id="cancel" type='reset' class="font-button-default sm rmargin_2e4" value="<?php echo I18N::HT('equipments', '取消');?>" />
                <input name="submit" type='submit' class="font-button-save sm" value="<?php echo I18N::HT('equipments', '提交');?>" />
            </div>
     </div>
	 </form>
</div>
