<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {
		
		font-size: 14px;
		margin:auto;
	}
	
	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}
	
	tbody{
		border-bottom:2px solid #000;
	}
	
	thead#stat{
		font-size: 10px;
		border:none;
	}
	
	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		border-bottom: 1px dotted #CCC;
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	p {
		margin: 0;
	}
	.quote {
		margin-left: 1em;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo I18N::T('equipments', '打印'); ?></a>
        <a href="#" onclick="window.close(); return false;"><?php echo I18N::T('equipments', '关闭|:print'); ?></a>
	</div>
	<?php
	$form['@columns'] = $valid_columns;
	$form['selector'] = $selector;
	
	$_SESSION[$form_token] = $form;

    $print_limit = Config::get('equipment.record.print_max', 500);
    if ($records->total_count() >= $print_limit) :

	$csv_link = I18N::T('equipments', '导出Excel');
	
	$return_url = I18N::T('equipments', '搜索条件');
	?>
	<div class="center">
		<strong>
			<?php echo I18N::T( 'equipments', '您选择数据超过%print_limit条, 不适合打印, 请选择%csv_link或调整您的%return_url',
			['%print_limit' => $print_limit,
				'%csv_link' => $csv_link,
				'%return_url' => $return_url,
			 ] ); ?> 
		</strong>
	</div>
	<?php else : ?>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
	<caption><?php echo I18N::T('equipments', '仪器使用记录报表'); ?></caption>
	<thead id="stat">
		<tr>
		<td colspan="8">
		<?php echo I18N::T('equipments', '时间范围:'); ?>
		&#160;
		<?php
			$dtstart = isset($form_submit['dtstart_check']) ? H(date('Y/m/d',$form_submit['dtstart'])) : I18N::T('equipments','最初');
			$dtend = isset($form_submit['dtend_check']) ? H(date('Y/m/d',$form_submit['dtend'])) : I18N::T('equipments','最末');
			echo $dtstart . ' - ' . $dtend;
		?>
		</td>
		</tr>
	</thead>
	<thead>
		<tr>
			<?php foreach ($valid_columns as $key => $value) :?>
				<th class="left nowrap"><?php echo I18N::T('equipments',$value); ?></th>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php
        $sum_dtstart = 0;
        $sum_dtend = 0;
		foreach($records as $record): ?>
		<tr>
		<?php if(array_key_exists('equipment', $valid_columns)) : ?>
		<td class="left nowrap"><?php echo H($record->equipment->name.Event::trigger('extra.equipment.name', $record->equipment)); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('eq_ref_no', $valid_columns)) : ?>
		<td class="left nowrap"><?php echo H($record->equipment->ref_no); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('eq_cf_id', $valid_columns)) : ?>
		<td class="left nowrap"><?php echo H($record->equipment->id); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('eq_group', $valid_columns)) : ?>
		<td class="left nowrap"><?php echo H($record->equipment->group->name); ?></td>
		<?php endif; ?>
        <?php if(array_key_exists('eq_cat', $valid_columns)) : ?>
        <?php
            $cate_root = Tag_Model::root('equipment');
            $cate = Q($record->equipment. " tag_equipment[id!=".$cate_root->id."]")->to_assoc('id','name');
            $cate_str = implode(',',$cate);
        ?>
        <td class="left nowrap"><?php echo H($cate_str); ?></td>
        <?php endif; ?>
        <?php if(array_key_exists('eq_incharge', $valid_columns)) : ?>
        <?php
            $incharges = Q($record->equipment . " user.incharge")->to_assoc('id','name');
            $incharge_str = implode(',',$incharges);
        ?>
        <td class="left nowrap"><?php echo H($incharge_str); ?></td>
        <?php endif; ?>
		<?php if(array_key_exists('user', $valid_columns)): ?>
		<td class="left nowrap"><?php echo H($record->user->name); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('lab', $valid_columns)): ?>
			<?php if ($GLOBALS['preload']['people.multi_lab']) {
				$lab = $record->project->lab;
			}
			else {
				$lab = Q("$record->user lab")->current();
			}?>
		<td class="left nowrap"><?php echo H($lab->name); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('user_group', $valid_columns)): ?>
		<td class="left nowrap"><?php echo H($record->user->group->name); ?></td>
		<?php endif; ?>
		<?php if(array_key_exists('record_ref_no', $valid_columns)): ?>
		<td class="left nowrap"><?php echo Number::fill(H($record->id), 6); ?></td>
		<?php endif;?>
		<?php if(array_key_exists('date', $valid_columns)): ?>
		<td class="left nowrap">
            <?php echo $record->get_date();?>
		</td>
		<?php endif; ?>
		<?php if(array_key_exists('total_time', $valid_columns)): ?>
		<td class="right nowrap">
			<?php
            echo $record->get_total_time();
            if ($record->get_total_time() && $record->dtend) {
                $sum_dtend += $record->dtend;
                $sum_dtstart += $record->dtstart;
            }
			?>
		</td>
		<?php endif; ?>
		<?php if(array_key_exists('total_time_hour', $valid_columns)): ?>
		<td class="right nowrap">
			<?php
            echo $record->get_total_time_hour();
			?>
		</td>
		<?php endif; ?>
		<?php
		//自定义的输出项
        $data_custom = Event::trigger('eq_record_lab_use.export_list_csv', $record, $data, $valid_columns);
        if(is_array($data_custom)) foreach ($data_custom as $key => $value) :?>
    		<td class="left nowrap">
				<?php echo $value;?>
			</td>
        <?php endforeach;?>

		<?php if(array_key_exists('samples', $valid_columns)) : ?>
		<td class="right nowrap">
			<?php echo $record->samples?>
		</td>
		<?php endif; ?>
		<?php if (Module::is_installed('eq_charge')): ?>
            <?php if(array_key_exists('charge_amount', $valid_columns)) :
                $charge = O("eq_charge", ['source' => $record]);
                $amount = $charge->amount;
                $reserv_charge = O('eq_charge', ['source' => $record->reserv]);
                if ($reserv_charge->id) {
                    $amount += $reserv_charge->amount;
                }
			?>
				<td class="right nowrap">
					<?= $amount ? : 0 ?>
				</td>
			<?php endif; ?>
		<?php endif; ?>
            <?php if(array_key_exists('material_amount', $valid_columns)) :
                if ($record->reserv->id) {
                    $charge = O("eq_charge", ['source' => $record->reserv]);
                }else {
                    $charge = O("eq_charge", ['source' => $record]);
                }
                $amount = $charge->material_amount;
                ?>
                <td class="right nowrap">
                    <?= $amount ? : 0 ?>
                </td>
            <?php endif; ?>
		<?php if(array_key_exists('agent', $valid_columns)) : ?>
		<td class="right nowrap">
			<?php echo $record->agent->id ? H($record->agent->name):'&#160;' ?>
		</td>
		<?php endif; ?>
        <?php if(array_key_exists('status', $valid_columns)): ?>
        <td class="left" style="word-break: break-word;min-width: 150px">
            <?php 
            if ($record->status == EQ_Record_Model::FEEDBACK_NORMAL) {
                echo I18N::T('equipments', '正常');
            }
            elseif ($record->status == EQ_Record_Model::FEEDBACK_PROBLEM) {
                echo I18N::T('equipments', '故障');
            }
            else {
                echo I18N::T('equipments', '-');
            }
        
            $feedback = $record->feedback;
            if ($feedback) {
                echo '<br/>'.H($feedback);
            }
            ?>
        </td>
        <?php endif;?>
		<?php if(array_key_exists('description', $valid_columns)) : ?>
		<td class="left nowrap">
		    <?php
            $views = Event::trigger('eq_record.description', $record);
            echo is_array($views) ? implode('<div class="hr_1">&#160;</div>', $views) : '&#160;';
		    ?>
		</td>
		<?php endif; ?>
		<?php if (Config::get('equipment.enable_use_type')): ?>
            <?php if(array_key_exists('use_type', $valid_columns)): ?>
            <td class="left nowrap"><?php echo H(EQ_Record_Model::$use_type[$record->use_type]); ?></td>
            <?php endif; ?>
            <?php if(array_key_exists('use_type_desc', $valid_columns)): ?>
            <td class="left" style="word-break: break-word;min-width: 150px"><?php echo H($record->use_type_desc); ?></td>
            <?php endif; ?>
		<?php endif; ?>
		<?php if (Config::get('eq_record.duty_teacher') && $record->equipment->require_dteacher): ?>
			<?php if(array_key_exists('duty_teacher', $valid_columns)) : ?>
			<td class="right nowrap">
				<?php echo $record->duty_teacher->name; ?>
			</td>
			<?php endif; ?>
		<?php endif; ?>
        <?php if (Module::is_installed('eq_evaluate_user')): ?>
            <?php if(array_key_exists('attitude', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo Config::get('eq_evaluate_user')['rate.tip'][$record->evaluate_user->attitude - 1]; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('attitude_feedback', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo $record->evaluate_user->attitude_feedback; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('proficiency', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo Config::get('eq_evaluate_user')['rate.tip'][$record->evaluate_user->proficiency - 1]; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('proficiency_feedback', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo $record->evaluate_user->proficiency_feedback; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('cleanliness', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo Config::get('eq_evaluate_user')['rate.tip'][$record->evaluate_user->cleanliness - 1]; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('cleanliness_feedback', $valid_columns)) : ?>
            <td class="right nowrap">
                <?php echo $record->evaluate_user->cleanliness_feedback; ?>
            </td>
            <?php endif; ?>
            <?php if(array_key_exists('use_type_desc', $valid_columns)): ?>
            <td class="left nowrap"><?php echo H($record->use_type_desc); ?>
			</td>
            <?php endif; ?>
		<?php endif; ?>
        <?php if(array_key_exists('university', $valid_columns)): ?>
		<td class="right nowrap">
			<?php echo Config::get('university.list')[$record->source_name];?>
		</td>
        <?php endif; ?>
        <?php if(array_key_exists('site', $valid_columns)): ?>
            <td class="left nowrap"><?php echo H(Config::get('site.map')[$record->equipment->site]); ?></td>
        <?php endif; ?>
         <?php   //自定义的输出项
            $data_custom = Event::trigger('eq_record.export_list_csv', $record, $data, $valid_columns);
            if(is_array($data_custom)) foreach ($data_custom as $key => $value) :?>
            <td class="left nowrap">
                <?php echo $value;?>
            </td>
            <?php endforeach;?>
        </tr>
		<?php endforeach; ?>
		<tr>
		<td colspan="<?php echo H(count($valid_columns)) ?>" class="right nowrap">
			<?php echo I18N::T('equipments', '总计使用: %count 次', ['%count'=>$records->total_count()]); ?>
            &nbsp;
            <?php echo I18N::T('equipments', '总计时长: %count_time (小时)', ['%count_time'=>round(($sum_dtend - $sum_dtstart) / 3600, 4)])?>
		</td>
		</tr>
	</tbody>
	</table>
	<?php endif; ?>
</body>
</html>
