<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Please set the sign-up rules for this equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Default setting: this instrument will charge all labs with the same standard. If different fees apply to specific labs, please add tags of these labs to the exception list.
</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
