<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Set the current status of this equipment.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Detailed description is required when changed to "Our of Order" or "Scrapped".</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Warning: Once the status is set to be "Scrapped", it can no longer be reversed.</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">Administrators only.</span>
	</p>
	<br />
</div>
