<div class="form-group">
  <label class="col-sm-2 control-label">
    <?= I18N::T('equipments', '展现方式') ?>
  </label>
  <div class="col-md-3">
    <label class="radio-inline">
      <input type="radio" name="type" value="bar" style="position: inherit;" 
      <?= $query['type'] == 'bar' ? 'checked' : '' ?>>
      <?= I18N::T('equipments', '柱状图') ?>
    </label>
  </div>
  <div class="col-md-3">
    <label class="radio-inline">
      <input type="radio" name="type" value="line" style="position: inherit;" 
      <?= $query['type'] == 'line' ? 'checked' : '' ?>>
      <?= I18N::T('equipments', '折线图') ?>
    </label>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <?= I18N::T('equipments', '仪器分类') ?>
  </label>
  <div class="col-sm-10">
    <select class="form-control" name="tag">
      <option value="0" <?= $query['tag'] == 0 ? 'checked' : '' ?>><?= H('全部') ?></option>
    <?php foreach ($tags as $tag) : ?>
      <option value="<?= H($tag->id) ?>" <?= $query['tag'] == $tag->id ? 'checked' : '' ?>><?= H($tag->name) ?></option>
    <?php endforeach ?>
    </select>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <?= I18N::T('equipments', '组织机构') ?>
  </label>
  <div class="col-sm-10">
    <select class="form-control" name="group">
      <option value="0" <?= $query['group'] == 0 ? 'checked' : '' ?>><?= H('全部') ?></option>
    <?php foreach ($groups as $group) : ?>
      <option value="<?= H($group->id) ?>" <?= $query['group'] == $group->id ? 'checked' : '' ?>><?= H($group->name) ?></option>
    <?php endforeach ?>
    </select>
  </div>
</div>
