<div class="description">
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以查看所有仪器的使用记录。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以按照仪器名称、使用者姓名、实验室名称、时间等方式查找使用记录。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以点击“编辑”设定代开成员、爽约和超时状态。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以点击“反馈”填写使用反馈。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以直接打印出仪器使用记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">您可以以CSV格式导出仪器使用记录报表。</span>
	</p>
	<p>
		<span class="tip_star">*</span>
		<span class="tip_content">管理员权限。</span>
	</p>
	<br />
</div>

