<?php
$me = L('ME');
if ($me->is_allowed_to('查看', $vidcam) && $me->is_allowed_to('列表', $vidcam)) :
	
?>

<?php  echo $vidcam->icon('32', 'style="display:inline;margin-right:24px;vertical-align:middle"'); ?>
<div style="width:250px;height:91px;line-height:91px;display:inline-block" >

<a href="<?php echo $vidcam->url(); ?>"><?php  echo H($vidcam->name); ?></a>
<span class="description lmargin_3" ><?php echo H($vidcam->location); ?></span>
</div>
<?php else :?>
	<p><?php echo H($vidcam->name); ?></p>
<?php endif; ?>
