<?php $me = L('ME');?>
<div class="form">
	<h3><?php echo I18N::HT('achievements', '从公共数据库导入')?></h3>
	<div class="lpadding_3">
		<?php
			$basic_info_tbody_id = 'tbody_' . uniqid();
			$q_static = [
				'basic_info_tbody_id'=>$basic_info_tbody_id
			];
			$sites = (array) Config::get('achievements.publication.collect.sites');
			foreach ($sites as $site_name=>$site_info) :
				$q_static['type'] = $site_name;
		?>
		<a q-object="site_logo" q-event="click" q-static="<?php echo H($q_static);?>" href="#"><img src="<?php echo H($site_info['logo']) ?>" /></a>
		<?php endforeach;?>
	</div>
</div>

<div class="form">
    <form method="post" autocomplete="off" q-object="add_publication" action="<?php echo H(URI::url('!achievements/publications/publication')) ?>">
    <table class="form">
    <tr>
    <td>
    	<h3><?php echo I18N::HT('achievements', '或直接录入') ?></h3>
    	<?php echo V('form_error', ['form'=>$form]);?>
    	<table class="form">
    		<tbody id="<?php echo H($basic_info_tbody_id) ?>">
    			<?php echo V('publications/edit.basic.info', ['form'=>$form, 'publication'=>$publication]);?>
                <?php echo '<br>'.V('form_filter',['error'=>$form->errors['name'][0]])?>
    		</tbody>
    		<tbody>
    			<?php
    				echo $GLOBALS['preload']['people.multi_lab'] ?
    					V("publications/edit.mlab.info", ['form' => $form, 'publication' => $publication]) :
    					V("publications/edit.lab.info", ['form' => $form, 'publication' => $publication]);
    			?>
    			<tr>
    				<td class="label right nowrap top"><?php echo I18N::T('achievements', '标签')?></td>
    				<?php
    					$root = Tag_Model::root('achievements_publication');
    					$tags = (array) Q("$publication tag[root=$root]")->to_assoc('id','name');
    					if(count($tags)) {
    						$tags = json_encode($tags, TRUE);
    					}
    					else{
    						$tags = '';
    					}
    				?>
    				<td class="middle" colspan="2">
    				<?php
    					echo Widget::factory('achievements:tag_selector', [
    							'autocomplete'=> URI::url('!achievements/publications/autocomplete/tags'),
    							'name'=>'tags',
    							'value'=> $form->no_error ? $tags : $form['tags']
    					]);
    				?>
    				</td>
    			</tr>

    			<tr>
    				<td class="label right nowrap top">
    					<?php echo I18N::T('achievements', '影响因子') ?>
    				</td>
    				<td class="middle" colspan="2">
    					 <input type="text" name="impact" style="width:100px;" class="text" value="<?php echo H($form->no_error ? $publication->impact : $form['impact'] ) ?>" />
    				</td>
    			</tr>

    			<tr>
    				<td class="label right nowrap top">
    					<?php echo I18N::T('achievements', '备注') ?>
    				</td>
    				<td  class="middle" colspan="2">
    					<textarea name="notes" class="text autogrow" cols="60" rows="3"  style="height:60px;"><?php echo $form->no_error ? $publication->notes : $form['notes'] ?></textarea>
    				</td>
    			</tr>

    			<?php if (Module::is_installed('nfs')) : ?>
    			<tr>
    				<td class="right nowrap top label">
    					<?php echo I18N::T('achievements', '附件'); ?>
    				</td>
    				<td class="left nowrap">
    					<?php echo V('achievements:attachments', ['achievement'=> $publication->id ? $publication : O('publication')]);?>
    				</td>
    			</tr>
    			<?php endif;?>
    		</tbody>
    	</table>
    </td>
    </tr>
    </table>
    <?php echo $view; ?>
    <div class="form padding_2">
        <input name="submit" type="submit" class="button button_save" value="<?php echo I18N::T('achievements', '提交'); ?>" />
    </div>
    </form>

    <div class="button_container">
        <div class="float_right">
            <input type="button" name="cancel" id="cancel" class="font-button-default rmargin_16" value="取消">
            <input type="submit" name="submit" class="font-button-save" value="<?php echo H(I18N::T('equipments', '添加')) ?>">
        </div>
    </div>
</div>
