<?php 
$me = L('ME');
$require = (string)V('form_require');
if (Module::is_installed('labs')):
  if ($me->access('添加/修改所有实验室成果')) $autocomplete = '';
  elseif ($me->access('添加/修改负责实验室成果')) $autocomplete =  URI::url("!labs/autocomplete/lab.{$me->id}.pi");
  else $autocomplete = URI::url("!labs/autocomplete/lab.{$me->id}");
?>
  <tr>
    <td class="label left nowrap top">
        <?php echo $require;?><?php echo I18N::T('achievements', '实验室'); ?>
        <br>
        <?php echo V('form_filter',['error'=>$form->errors['lab'][0]]); ?>
    </td>
    <td class="middle" colspan="2">
      <?php
        if ($form->no_error) {
          $selected_lab = $publication->id ? Q("{$publication} lab")->to_assoc('id', 'name') : [];
        } else {
          $selected_lab = json_decode($form['lab'],true);
        }
        echo Widget::factory('labs:multi_lab_selector', [
          'name'=>'lab',
          'form'=>$form,
          'labs'=>$selected_lab,
          'size'=>'50',
          'autocomplete' => $autocomplete
        ]);
      ?>
    </td>
  </tr>
<?php endif;?>
