<?php
$charge_setting = EQ_Charge::get_charge_setting($equipment);
$material_setting = $charge_setting['material'];
$disabled = L('ME')->is_allowed_to('修改计费设置', $equipment) ? '' : 'disabled="disabled"';
?>
<div class="interval_24"></div>
<form method="POST" autocomplete="off" action="<?php echo H(URI::url() ) ?>">
    <div class="form padding_1">
        <table class="form flexible">
            <tbody>
            <tr>
                <td class="top lpadding_30">
                <h2 class="section_title"><?php echo I18N::T('material', '计费参数设置')?> (<?php echo $charge_title?>)</h2>
                <div class="padding_2">
                    <div class="interval_20"></div>
                    <div style="color: #ff9800;font-size: 12px;">
                        <?= I18N::T('material', '注：如需增加耗材，点击上方 “耗材设置” 标签页进行设置')?>
                    </div>
                    <div class="interval_20"></div>
                    <table class="form">
                        <tbody>
                            <?php if (!count($materials)): ?>
                            <tr>
                                <td class="left nowrap middle"><?= I18N::T('material', '请到耗材设置中添加耗材'); ?></td>
                            </tr>
                            <?php else: ?>
                                <?php foreach ($materials as $id => $material):?>
                                <tr>
                                    <td class="middle right nowrap"><?= $material->name; ?></td>
                                    <td class="middle lpadding_8">
                                        <input name="<?= 'price['.$id.']'?>" class="text currency" size="10" sign="<?php echo H(Config::get('lab.currency_sign') ) ?>" value="<?= H($material->price) ?>" <?= $disabled?>/>&nbsp;/&nbsp;<?= $material->material_unit->name?>
                                    </td>
                                </tr>
                                <tr><td><div class="interval_20">&#160;</div></td></tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <?php
    unset($material_setting['*']);
    $tags = $material_setting;
    if ($tags) foreach ($tags as $k => $tag) {
        if ($tag) {
            $key = serialize($tag);
            if (!isset($specific[$key])) {
                $specific[$key] = $tag;
            }
            $specific[$key]['special_tags'][] = $k;
        }
    }
    $specific = (array)$specific;
    if ($specific || !$disabled) :?>
        <div class="form lpadding_30">
            <?php
            echo Widget::factory('flexform', [
                'title' => I18N::T('material', '个别收费标准'),
                'template_data' => ['disabled'=>TRUE],
                'existing_data' => array_values($specific),
                'item_view' => 'material:charge/item',
                'title_class' => 'middle',
                'extra_vars' => [
                    'equipment' => $equipment,
                    'materials' => $materials,
                ],
            ]);
            ?>
        </div>
    <?php endif;?>

    <div class="interval_60">&#160;</div>
    <?php if (!$disabled): ?>
        <div class="form float_right">
            <input type="reset" name="cancel" class="font-button-default rmargin_16" value="<?php echo H(T('取消')) ?>" />
            <input type="submit" name="submit" class="font-button-save" value="<?php echo H(T('保存修改')) ?>" />
        </div>
    <?php endif;?>
</form>
