<?php
    $disabled = L('ME')->is_allowed_to('修改计费设置', $equipment) ? '' : 'disabled="disabled"';
    $charge_template = $equipment->charge_template;
    $charge_material = $charge_template['material'];
?>

<tr>
    <td class="lpadding_30">
        <div class="interval_60"></div>
        <h2 class="section_title"><?php echo I18N::T('material', '耗材计费设置')?></h2>
        <div class="interval_30"></div>
        <div class="charge_setting">
            <div class="">
                <div class="charge_dis lmaigin_1e5">
                    <?= Form::radio('material', 'no_charge_material' , (!$charge_material || !$form['material']) ? TRUE : FALSE, I18N::T('material', '免费选用'), 'class="monitor" data="" ' . $disabled); ?>
				</div>
                <div class="charge_dis lpadding_10">
                    <?= Form::radio('material', 'material_count' , ($charge_material == 'material_count') ? TRUE : FALSE, I18N::T('material', '按耗材个数'), 'class="monitor material_count" data="material" ' . $disabled); ?>
				</div>
            </div>
            <div class="interval_6"></div>
            <div class="lmaigin_1e5" style="color: #ff9800"><?= I18N::T('material', '注：与上述预约/使用计费、送样计费叠加使用')?></div>
        </div>
        <div class="interval_60"></div>
    </td>
</tr>