<style>
#body .tbar span{
	margin: 0px;
	padding: 0 0 0 5px;
	line-height: 25px;
}
#body .tbar a {
	float: right;
	line-height: 25px;
	margin: 0 5px;
	font-size: 10px;
}
@media screen and (min-width: 1280px){
	.gis_left {
		float:left;
		width:900px;
		padding-left:4px;
	}
	.gis_right {
		float: left;
		margin-left:40px;
		width:240px;
	}
	.gis_right .padding_1 {
		overflow-x: scroll;
	}
	.square {
		display:block;
		float:left;
		overflow:hidden;
		height:10px;
		width:10px;
		background:black;
		margin-right:10px;
		margin-top:5px;
	}
	.top {
		padding: 40px;
	}
}
@media screen and (max-width: 1280px){
	.gis_left {
		float:left;
		width:800px;
		padding-left:4px;
	}
	.gis_right {
		float: left;
		margin-left:40px;
		width:240px;
	}
	.gis_right .padding_1 {
		overflow-x: scroll;
	}
	.square {
		display:block;
		float:left;
		overflow:hidden;
		height:10px;
		width:10px;
		background:black;
		margin-right:10px;
		margin-top:5px;
	}
	.top {
		padding: 10px;
	}
}
</style>
<?php 
	$equipment_uniqid = 'equipments_'.uniqid();
?>

<table class="clearfix">
	<tr>
		<td class="top">
			<div class="gis_left">
				<div class="tbar clearfix">
					<span><?php echo I18N::T('gismon', '仪器地图');?></span>
				</div>
				<?php $map_id = 'gismon_'.uniqid(); ?>
				<div class="padding_1 clearfix">
					<div id="<?php echo H($map_id) ?>" class="gismon_map_front"></div>
				</div>
				<?php echo JS::load('gismon:map_front', ['map_id' => $map_id, 'latitude'=> (float) $latitude, 'longitude'=> (float) $longitude, 'building_url'=>URI::url('!gismon/building.%id.2d'), 'equipment_uniqid'=>$equipment_uniqid]);?>
			</div>
		</td>
		<td class="top nowrap">
			<div class="gis_right">
				<div class="location">
					<div class="tbar clearfix">
						<span><?php echo I18N::T('gismon', '仪器列表');?></span>
					</div>
					<div id="<?php echo H($equipment_uniqid) ?>" class="padding_1">
						<?php echo V('front/equipment_list', ['equipments'=>$equipments])?>
					</div>
				</div>
			</div>
		</td>
	</tr>
</table>
<script>
$().ready(function(){
	$("#<?php echo H($equipment_uniqid) ?>").height($(".gis_left .padding_1").height());
})
</script>

