<div class="subtask_item group_prevent_default" >
	<table width="100%">
	<tr>
	<td class="indicator indicator_p<?php echo $task->priority?>"><div>&#160;</div></td>
	<td class="brief" width="100%">
		<div class="deadline"><?php echo Date::format($task->deadline, T('Y/m/d'))?></div>
		<a class="task_title" href="<?php echo H($task->url()) ?>"><?php echo H($task->title) ?></a>
	</td>
	<td class="right tight nowrap" style="padding-right:4px">
		<?php echo V('treenote:task/table/data/status', ['task'=>$task]) ?>
	</td>
	<td class="right tight nowrap">
		<div class="child_count"><?php echo $task->child_tasks()->total_count() ?></div>
	</td>
	</table>
</div>

