<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="renderer" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<title><?php echo I18N::T('treenote', '我的任务'); ?></title>
	<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
	<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
	<style>
	a {
		color:blue;
		text-decoration:underline;
	}
	table.report {

		font-size: 14px;
		margin:auto;
	}

	thead{
		border-top:2px solid  #000;
		border-bottom:1px solid #000;
	}

	tbody{
		border-bottom:2px solid #000;
	}

	thead#stat{
		font-size: 10px;
		border:none;
	}

	table.report caption {
		font-size: 150%;
		margin-bottom: 10px;
	}

	table.report tbody td {
		vertical-align: top;
		/* border-bottom: 1px dotted #CCC; */
	}
	table.report .referred_charge {
		background-color: #eee;
		border:1px dotted #CCC;
	}
	tr.description {
		font-size: 80%;
		border-bottom: 1px dotted #CCC;
	}
	</style>
	<style media="print">
	.buttons{
		display:none;
	}
	</style>
</head>

<body>
	<div class="buttons">
		<a href="#" onclick="window.print(); return false;"><?php echo T('打印'); ?></a>
	</div>
	<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse; width: 500px;">
	<caption><?php echo I18N::T('treenote', '我的任务'); ?></caption>
	<thead id="stat">
		<tr>
		<td colspan="4">
		<?php echo I18N::T('treenote', '时间范围:'); ?>
		&#160;
		<?php
			$dtstart = isset($dtstart) ? H(date('Y/m/d',$dtstart)) : I18N::T('treenote','最初');
			$dtend = isset($dtend) ? H(date('Y/m/d',$dtend)) : I18N::T('treenote','最末');
			echo $dtstart . ' - ' . $dtend;
		?>
		</td>
		</tr>
	</thead>
	<thead>
		<tr>
		<th class="left nowrap"></th>
		<th class="left nowrap"><?php echo I18N::T('treenote', '任务'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('treenote', '优先级'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('treenote', '截止日期'); ?></th>
		<th class="left nowrap"><?php echo I18N::T('treenote', '项目'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach($tasks as $task): ?>
		<tr>
			<td class="left nowrap"><input type="checkbox" /></td>
			<td class="left nowrap"><?php echo H($task->title); ?></td>
			<td class="left nowrap"><?php echo I18N::T('treenote', Tn_Task_Model::$priority_labels[$task->priority]); ?></td>
			<td class="left nowrap"><?php echo Date::format($task->deadline); ?></td>
			<td class="left nowrap"><?php echo H($task->project->title); ?></td>
		</tr>
		<tr class="description">
			<td></td>
			<td></td>
			<td></td>
			<td colspan="2"><?php echo H($task->description); ?></td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td colspan="5" class="right nowrap">
			<?php echo I18N::T('treenote', '总计:') . $tasks->total_count(); ?>
			</td>
		</tr>
	</tbody>
	</table>
</body>
</html>
