<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="renderer" content="webkit" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
		<title><?php echo I18N::T('meeting', '会议室预约记录打印'); ?></title>
		<base href="<?php echo H(Config::get('system.base_url') ) ?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo H(URI::url('css', ['f'=>'core'])) ?>" />
		<style>
			a {
				color:blue;
				text-decoration:underline;
			}
			table.report {
				font-size: 14px;
				margin:auto;
			}
			thead{
				border-top:2px solid	#000;
				border-bottom:1px solid #000;
			}
			tbody{
				border-bottom:2px solid #000;
			}
			thead#stat{
				font-size: 10px;
				border:none;
			}
			table.report caption {
				font-size: 150%;
				margin-bottom: 10px;
			}
			table.report tbody td {
				vertical-align: top;
				border-bottom: 1px dotted #CCC;
			}
			table.report .referred_charge {
				background-color: #eee;
				border:1px dotted #CCC;
			}
		</style>
		<style media="print">
			.buttons{
				display:none;
			}
		</style>
	</head>
	
	<body>
		<div class="buttons">
			<a href="#" onclick="window.print(); return false;"><?php echo I18N::HT('meeting', '打印'); ?></a>
			<a href="#" onclick="window.close(); return false;"><?php echo I18N::HT('meeting', '关闭'); ?></a>
		</div>
		<table class="report" cellpadding="5" cellspacing="5" style="border-collapse:collapse;">
			<caption class="nowrap">
                <?php
                    $calendar = O('calendar', $form['calendar_id']);

                    if ($calendar->parent->name() == 'meeting') {

                            echo I18N::HT('meeting', '%meeting预约记录列表', [
                                '%meeting'=> $calendar->parent->name
                            ]);
                    }
                    elseif ($calendar->parent->name() == 'user') {
                        echo I18N::HT('meeting', '%name负责的会议室预约记录列表', [
                            '%name'=> $calendar->parent->name
                        ]);
                    }
                    elseif ($calendar->type == 'all_meetings')  {
                        echo I18N::HT('meeting', '所有会议室的预约记录列表');
                    }
                ?>
            </caption>
			<thead id="stat">
                <tr>
                    <td colspan="<?php echo H(count($columns)) ?>" class="small">
                        <?php echo I18N::HT('meeting', '时间: %dtstart - %dtend', [
                            '%dtstart' => $form['dtstart'] ? Date::format($form['dtstart']) : I18N::T('meeting', '最初'),
                            '%dtend'=> $form['dtend'] ? Date::format($form['dtend']) : I18N::T('meeting', '最末')
                        ])?>
                    </td>
                </tr>
            </thead>
            <thead>
				<tr>
					<?php foreach($columns as $name) : ?>
						<th class="left nowrap"><?php echo I18N::T('meeting', $name); ?></th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach($components as $c): ?>
			<tr>
                <?php foreach($columns as $key => $value) :?>
                    <?php switch($key) :  //PHP的BUG ? switch和第一个case不能分开?
                        case 'name' :?>
                            <td>
                                <?php echo H($c->name) ?: '-';?>
                            </td>
                        <?php break;?>
                        <?php case 'organizer' : ?>
                            <td>
                                <?php echo H($c->organizer->name) ?: '-';?>
                            </td>
                        <?php break;?>
                        <?php case 'meeting' : ?>
                            <td>
                                <?php echo H($c->calendar->parent->name) ?: '-';?>
                            </td>
                        <?php break;?>
                        <?php case 'time' : ?>
                            <td>
                                <?php echo Date::format($c->dtstart, 'Y/m/d H:i:s'). ' - '. Date::format($c->dtend, 'Y/m/d H:i:s');?>
                            </td>
                        <?php break;?>
                        <?php case 'duration' : ?>
                            <td>
                                <?php echo I18N::T('meeting', '%duration小时', ['%duration'=> round(($c->dtend - $c->dtstart) / 3600, 2)]);?>
                            </td>
                        <?php break;?>
                        <?php case 'description' : ?>
                            <td>
                                <?php echo H($c->description) ?: '-';?>
                            </td>
                        <?php break;?>
                        <?php default : ?>
                            <td>
                                <?php echo Event::trigger('meeting.export_columns.print', $c, $key)?>
                            </td>
                        <?php break;?>
                    <?php endswitch;?>
                <?php endforeach;?>
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</body>
</html>
