<table class="form">
<tr>
	<td>
		<h4><?php echo I18N::T('eq_empower', '设置工作时间'); ?></h4>
	</td>
	<td></td>
</tr>
<tr>
	<td class="left nowrap middle"><?php echo I18N::T('eq_empower','规则起止日期') ?></td>
	<td name="<?php echo H('working_date['.$flexform_index.']') ?>" class="left nowrap middle" colspan="3">
		<input name="startdate[<?php echo $flexform_index ?>]" class="text date"  value="<?php echo H($startdate ) ?>"  disabled="disabled"/>
		-
		<input name="enddate[<?php echo $flexform_index ?>]" class="text date" value="<?php echo H($enddate ) ?>"  disabled="disabled"/>
	</td>
</tr>
<tr>
	<td class="left nowrap middle"><?php echo I18N::T('eq_empower','起止时间') ?></td>
	<td name="<?php echo H('working_time['.$flexform_index.']') ?>" class="left nowrap middle" colspan="3">
		<input name="starttime[<?php echo $flexform_index ?>]" class="text date"  value="<?php echo H(is_null($starttime)?mktime(8,0,0,1,1,1971):$starttime ) ?>" q-date_format="<?php echo HT('$hour:$min:$sec')?>" disabled="disabled"/>
		-
		<input name="endtime[<?php echo $flexform_index ?>]" class="text date" value="<?php echo H(is_null($endtime)?mktime(17,0,0,1,1,1971):$endtime ) ?>"  q-date_format="<?php echo HT('$hour:$min:$sec')?>" disabled="disabled"/>
	</td>
</tr>
</table>
