<?php
    $tag_name = $tag_name ?: 'tag';
	$tag = O($tag_name, $tid);
	$message_uniqid = 'message_'.uniqid();
?>
<div class="relate_view ">
<form method="post" autocomplete="off"
	q-object="tag_relate_data"
	q-event="submit"
	q-static="<?php echo H(['uniqid'=>$message_uniqid, 'eid'=>$eid, 'tag_name'=>$tag_name])?>"
	q-src="<?php URI::url('!equipments/equipment')?>">
	<div id="<?php echo H($message_uniqid) ?>"></div>
	<input class="hidden text" value="<?php echo H($tag->id) ?>" name="tid" />
	<div class="interval_30"></div>
	<h2 class="section_title"><?php echo $tag->name;?></h2>
    <div class="interval_30"></div>

	<!--用户-->
	<div class="form"  style="min-height: 85px">
		<?php $users = Q("{$tag} user")->to_assoc('id', 'name');?>
		<span class='float_left tip_name'><?php echo I18N::T('equipments', '用户')?></span>
		<div class="user_box float_right" style="width: 83%">
			<?php
                $tooltip = I18N::T('equipments', '请输入关键字并选择');
				echo Widget::factory('multi_user_selector', [
	   					'autocomplete'=> URI::url('!equipments/autocomplete/user'),
						'name'=>'users',
						'size'=>'60',
	   					'value'=>@json_encode($users),
                        'tooltip'=>$tooltip,
                        'extra'=>'token_verify'
	   			]);
			?>
		</div>
	</div>

	<?php if (!$GLOBALS['preload']['people.multi_lab'] && Module::is_installed('labs')): ?>
	<!--课题组-->

    <div class="interval_20"></div>
	<div class="form" style="min-height: 85px">
		<?php $labs = Q("{$tag} lab")->to_assoc('id', 'name');?>
		<span  class="float_left  tip_name"><?php echo I18N::T('equipments', '实验室')?></span>
		<div class="lab_box float_right" style="width: 83%">
			<?php
				echo Widget::factory('equipments:tag_selector', [
	   					'autocomplete'=> URI::url('!equipments/autocomplete/labs'),
	   					'name'=>'labs',
	   					'value'=>@json_encode($labs),
	   			]);
			?>
		</div>
	</div>
	<?php endif ?>
	<?php
	#ifdef (equipment.enable_group_specs)
	if (Config::get('equipment.enable_group_specs')):
	?>


	<!--组织机构-->
    <div class="interval_20"></div>
	<div class="form" style="min-height: 85px">
		<?php
			$root = Tag_Model::root('group'); 
			$groups = Q("{$tag} tag_group[root={$root}]")->to_assoc('id', 'name');
		?>
		<span class="float_left tip_name"><?php echo I18N::T('equipments', '组织机构')?></span>
		<div class="group_box float_right" style="width: 83%">
			<?php
				echo Widget::factory('equipments:tag_selector', [
	   					'autocomplete'=> URI::url('!equipments/autocomplete/groups'),
	   					'name'=>'groups',
	   					'value'=>@json_encode($groups),
	   			]);
			?>
		</div>
	</div>
	<?php
	endif;
	#endif
	?>
    <div class="interval_60"></div>
	<div class="form float_right">
		<?php $uniqid = uniqid();?>
		<input  type="button" id="<?= $uniqid;?>" class="font-button-default  rmargin_16" value="<?php echo H(I18N::T('equipments', '撤回')) ?>" />
		<input name="submit" type="submit" class="font-button-save  " value="<?php echo H(I18N::T('equipments', '保存修改')) ?>" />
	</div>

</form>
<script>
var token=[]

setTimeout(() => {
	$(".token_box").each(function(){
		token.push($(this).children());
	})
}, 1000);

    $("#<?php echo $uniqid?>").bind('click', function(e){
        Q.trigger({
            object:'replace_tag',
            event:'click',
            data:{
                tid:<?php echo $tid?>,
                tag_name:'tag',
                uniqid:'<?php echo $relate_uniqid?>'
            },
            url:'<?php echo URI::url("!equipments/equipment")?>',
            complete:function(){
            }
        });
        return false;
    });
</script>
</div>
