<?php
	echo CSS::load_async('equipments:relate_list');
	$uniqid = 'relate_tags_'.uniqid();
	$keys = array_keys($tags);
	$tid = $this->tid ?: $keys[0];
?>

<div >
    <table width="100%">
        <tbody>
        <tr>
            <td class="top icon left" width="130">
                <div>
                    <?= V('equipment/view/icon', ['equipment' => $equipment, 'id' => $uniqid]); ?>
                </div>
            </td>
            <td class="top">
                <h2 class="section_title">
                    <span class="border"></span>
                    <span class="black_title"><?= I18N::HT('equipments', '标签设置') ?></span>
                </h2>
                <div class='interval_30'></div>
                <div class="lmaigin_1e5">
                    <div class="relate_list" id="<?php echo H($uniqid) ?>">
                        <!--左边-->
                        <div class="relate_left ">
                            <div class="padding_1 panel clearfix add_tags center tmargin_3 bmargin_3">
                                <a  class="font-button-default border_gray gray"
                                    q-object="create_tag"
                                    q-event="click"
                                    q-static="<?php echo H(['eid'=>$equipment->id])?>"
                                    q-src="<?php echo H(URI::url('!equipments/equipment')) ?>">
                                    <span class='icon-add rmargin_1'></span><?php echo T('添加标签')?></a>
                            </div>
                            <div class="equipment_tags">
                                <?php
                                foreach($tags as $key => $tag) {
                                    echo V('equipments:equipment_tags/tag', ['id'=>$key, 'tid'=>$tid, 'relate_uniqid'=>$uniqid]);
                                }
                                ?>
                            </div>
                        </div>


                        <!---右边-->
                        <div class="relate_right" id="<?php echo H($uniqid) ?>">

                            <?php
                            if ($tid) {
                                echo V('equipment_tags/relate_view',['tid'=>$tid, 'eid'=>$equipment->id, 'relate_uniqid'=>$uniqid]);
                            }
                            ?>

                        </div>
                    </div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>


<script type="text/javascript">
jQuery(function($) {
	Q.equipment_tag_sortable("<?php echo $uniqid; ?>", "<?php echo URI::url('!equipments/equipment/'); ?>", "tag");
});
</script>
