<div class="hr_1">&#160;</div>
<div class="form padding_1">
<form method="post" autocomplete="off">
    <?php 
    echo V('form_error', ['form' => $form]);
    $no_error = ($form->no_error !== FALSE);
    $require = (string)V('form_require');
    ?>
    <table class="form flexible">
        <tr>
            <th colspan="2" class="legend">
                <span class="lpadding_2">
                    <?= I18N::T('servant', '机构信息') ?>
                </span>
            </th>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '机构名称')?>
            </td>
            <td class="middle">
                <input name="name" class="text" size="40" 
                value="<?= $no_error ? $pf->name : H($form['name']) ?>" disabled/>
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '机构代码')?>
            </td>
            <td class="middle">
                <input class="text" size="40" 
                value="<?= $no_error ? $pf->code : H($form['code']) ?>" disabled/>
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '联系方式')?>
            </td>
            <td class="middle">
                <input name="contact" class="text" size="40" 
                value="<?= $no_error ? $pf->contact : H($form['contact']) ?>" />
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '地址')?>
            </td>
            <td class="middle">
                <input name="address" class="text" size="40" 
                value="<?= $no_error ? $pf->address : H($form['address']) ?>" />
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '描述')?>
            </td>
            <td class="middle">
                <textarea name="description" class="text" rows="4"
                cols="40"><?= $no_error ? $pf->description : H($form['description']) ?></textarea>
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '负责人')?>
            </td>
            <td class="top">
            <?php
            $users = [];
            if (count($owners)) foreach ($owners as $user) {
                $users[$user->id] = "{$user->name}({$user->lab->name})";
            }
            echo Widget::factory('multi_user_selector', [
                'name' => 'owner',
                'autocomplete' => URI::url('autocomplete/user'),
                'value' => $no_error ? json_encode($users) : $form['owner'],
                'extra' => 'token_verify'
            ]);
            echo $require; 
            ?>
            </td>
        </tr>
        <tr>
            <td class="label right nowrap" width="80px;">
                <?= I18N::T('servant', '是否激活')?>
            </td>
            <td class="top middle">
                <?php 
                $active = $pf->atime > 0 ? 1 : 0;
                echo Form::radio('active', 1, $no_error ? $active : $form['active'], 
                I18N::T('servant', '是'), ' class="middle"', 'class="middle"'); 
                ?>
                &#160;
                <?php echo Form::radio('active', 0, $no_error ? $active : $form['active'], 
                I18N::T('servant', '否'), ' class="middle"', 'class="middle"'); 
                ?>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="hr_1">&#160;</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="submit" class="button button_save" 
                value="<?= H(I18N::T('servant', '保存')) ?>" />
                <?php if ($pf->id) : ?>
                <a class="font-button-delete" q-object="pf_delete" q-static="<?= H(['id' => $pf->id]) ?>"
                q-event="click" q-src="<?= URI::url(); ?>">
                <?= H(I18N::T('servant', '删除')) ?>
                </a>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</form>
</div>
