<?php if(!is_array($month_day)) $month_day = []; ?>
<div class="interval_6"></div>
<table class="form month">
<tr>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][1]', in_array(1, $month_day) ? TRUE : FALSE, 1, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][2]', in_array(2, $month_day) ? TRUE : FALSE, 2, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][3]', in_array(3, $month_day) ? TRUE : FALSE, 3, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][4]', in_array(4, $month_day) ? TRUE : FALSE, 4, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][5]', in_array(5, $month_day) ? TRUE : FALSE, 5, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][6]', in_array(6, $month_day) ? TRUE : FALSE, 6, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][7]', in_array(7, $month_day) ? TRUE : FALSE, 7, 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][8]', in_array(8, $month_day) ? TRUE : FALSE, 8, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][9]', in_array(9, $month_day) ? TRUE : FALSE, 9, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][10]', in_array(10, $month_day) ? TRUE : FALSE, 10, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][11]', in_array(11, $month_day) ? TRUE : FALSE, 11, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][12]', in_array(12, $month_day) ? TRUE : FALSE, 12, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][13]', in_array(13, $month_day) ? TRUE : FALSE, 13, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][14]', in_array(14, $month_day) ? TRUE : FALSE, 14, 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][15]', in_array(15, $month_day) ? TRUE : FALSE, 15, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][16]', in_array(16, $month_day) ? TRUE : FALSE, 16, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][17]', in_array(17, $month_day) ? TRUE : FALSE, 17, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][18]', in_array(18, $month_day) ? TRUE : FALSE, 18, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][19]', in_array(19, $month_day) ? TRUE : FALSE, 19, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][20]', in_array(20, $month_day) ? TRUE : FALSE, 20, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][21]', in_array(21, $month_day) ? TRUE : FALSE, 21, 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][22]', in_array(22, $month_day) ? TRUE : FALSE, 22, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][23]', in_array(23, $month_day) ? TRUE : FALSE, 23, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][24]', in_array(24, $month_day) ? TRUE : FALSE, 24, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][25]', in_array(25, $month_day) ? TRUE : FALSE, 25, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][26]', in_array(26, $month_day) ? TRUE : FALSE, 26, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][27]', in_array(27, $month_day) ? TRUE : FALSE, 27, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][28]', in_array(28, $month_day) ? TRUE : FALSE, 28, 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

<tr>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][29]', in_array(29, $month_day) ? TRUE : FALSE, 29, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][30]', in_array(30, $month_day) ? TRUE : FALSE, 30, 'class="middle checkbox"',  'class="middle"') ?></td>
	<td class="left nowrap"><?php echo Form::checkbox('time_counts_month_day['.$flexform_index.'][31]', in_array(31, $month_day) ? TRUE : FALSE, 31, 'class="middle checkbox"',  'class="middle"') ?></td>
</tr>

</table>
